{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.684.0 (23.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Calendar - FY13+\",\"Key Measures\",\"Prospect Measures\",\"Proposal Measures\",\"Pledge Measures\",\"Prospects and Scores\",\"Primary Managers\",\"Proposals\",\"Proposal Solictors\",\"Contact Reports\",\"Entities w/Locations\",\"Household Giving\",\"Pledge Pymts Due\",\"Current FY\",\"Household Keys\",\"Max Proposal Date\",\"Plg DD Cats\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "512e84a8-ab9e-4f07-ac88-5a75219c2f9d",
        "fromColumn": "Granted Dt",
        "fromTable": "Proposals",
        "toColumn": "Date",
        "toTable": "Calendar - FY13+"
      },
      {
        "name": "7436fec3-3ee7-474f-b2a8-b2f4a16921bc",
        "fromColumn": "Planned Dt",
        "fromTable": "Proposals",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar - FY13+"
      },
      {
        "name": "ee92e69d-c315-4ec0-b162-c510598dd83f",
        "fromColumn": "Ask Date",
        "fromTable": "Proposals",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar - FY13+"
      },
      {
        "name": "139adeb2-cb4b-4aa1-a6b9-d95faa733f92",
        "fromColumn": "Expected Date",
        "fromTable": "Proposals",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar - FY13+"
      },
      {
        "name": "d92668eb-7b4e-4ffa-b08a-7048d8f26333",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Household Key",
        "fromTable": "Household Giving",
        "toColumn": "Household Key",
        "toTable": "Entities w/Locations"
      },
      {
        "name": "8ef4f6a4-fd61-44fa-9e5c-bfb6c592a108",
        "fromColumn": "Entity ID",
        "fromTable": "Prospects and Scores",
        "toColumn": "Primary Ent ID",
        "toTable": "Entities w/Locations"
      },
      {
        "name": "41cc68ee-e7b5-465b-acb6-ac5427e509bf",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Pledge Nbr",
        "fromTable": "Pledge Pymts Due",
        "toCardinality": "many",
        "toColumn": "Pledge Nbr",
        "toTable": "Plg DD Cats"
      },
      {
        "name": "b60b49a3-3b22-40f8-9e21-393233999c19",
        "fromColumn": "HH Key",
        "fromTable": "Proposals",
        "toColumn": "HH Key",
        "toTable": "Household Keys"
      },
      {
        "name": "aef44824-2ebe-4718-a986-28851653a35b",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Proposal ID",
        "fromTable": "Proposal Solictors",
        "toColumn": "Proposal ID",
        "toTable": "Proposals"
      },
      {
        "name": "e5d7f336-5808-4802-84b0-d35051d31a82",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Prospect ID",
        "fromTable": "Proposals",
        "toColumn": "Prospect ID",
        "toTable": "Prospects and Scores"
      },
      {
        "name": "1986d646-07f8-456c-8158-530df35124a1",
        "fromColumn": "Contacted ID",
        "fromTable": "Contact Reports",
        "toColumn": "Primary Ent ID",
        "toTable": "Entities w/Locations"
      },
      {
        "name": "93b91549-3089-4d86-bd58-527b189ee1f5",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Prospect ID",
        "fromTable": "Prospects and Scores",
        "toColumn": "Pros ID",
        "toTable": "Primary Managers"
      },
      {
        "name": "6affad7b-7d36-4fea-87e2-556ef2f58d63",
        "fromColumn": "GO Unique Key",
        "fromTable": "Contact Reports",
        "isActive": false,
        "toColumn": "GO Unique Key",
        "toTable": "Primary Managers"
      },
      {
        "name": "facaa29d-0e92-4d04-a37c-27109a740d39",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Solicitor Key",
        "fromTable": "Pledge Pymts Due",
        "toCardinality": "many",
        "toColumn": "Solicitor Key",
        "toTable": "Proposal Solictors"
      },
      {
        "name": "15a578ca-609f-4d0d-b840-e7feae055a5f",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "HH Key",
        "fromTable": "Prospects and Scores",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "Household Key",
        "toTable": "Household Giving"
      },
      {
        "name": "4570fd01-4907-451d-9dfa-de50218edc4f",
        "fromColumn": "Contact Dt",
        "fromTable": "Contact Reports",
        "toColumn": "Date",
        "toTable": "Calendar - FY13+"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Calendar - FY13+",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isKey": true,
            "lineageTag": "68d8f5c7-ab22-4052-996d-3241a6c99cdb",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e65911be-d6e7-4271-8569-d5928790f781",
            "sourceColumn": "MonthNum",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71f9ee07-b564-4baf-b537-44339d62ca97",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "MonthLong",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11406ef8-8058-4f58-8496-d240d37dc42a",
            "sourceColumn": "MonthLong",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31eb46dc-1952-4a5e-80af-a7b2bb0ff8ff",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3d7d0a84-f1fe-4a04-a814-a84f00dad89f",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "SortFiscalMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "aa065a51-5a68-4157-8bde-6aa71448de8c",
            "sourceColumn": "SortFiscalMonth",
            "summarizeBy": "sum"
          },
          {
            "name": "FiscalMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "9cfeae54-8cc6-407a-8b31-60627e9e328a",
            "sortByColumn": "SortFiscalMonth",
            "sourceColumn": "FiscalMonth",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalMonthLong",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c23d30f4-c23a-45e1-a22c-25750c4ee0c9",
            "sourceColumn": "FiscalMonthLong",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a685ff7e-a5f5-43bd-91ba-6a3c7d70c1e4",
            "sourceColumn": "FiscalQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9d85795-120a-4663-a12c-be3ef2fa51f2",
            "sourceColumn": "FiscalYear",
            "summarizeBy": "none"
          },
          {
            "name": "CurMonthOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3c084556-532b-46ac-a0f3-3daf03608360",
            "sourceColumn": "CurMonthOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "CurQuarterOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "30b1d6f0-26ed-42b4-9f81-8729955c473d",
            "sourceColumn": "CurQuarterOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "CurYearOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1932fe75-9760-41ad-a10b-d1b67fa8d10f",
            "sourceColumn": "CurYearOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "FutureDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a16aaae2-ccee-4bfe-b429-bd1beab7c1b8",
            "sourceColumn": "FutureDate",
            "summarizeBy": "none"
          },
          {
            "name": "CurFiscalYearOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "896d4f27-c515-4f46-9bc6-69e2198eb607",
            "sourceColumn": "CurFiscalYearOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "SortMonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3bd544e9-7a60-48d8-8fc5-f9f00091830e",
            "sourceColumn": "SortMonthYear",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1c08b8c-d809-4dd4-b6db-51267d7de4b9",
            "sourceColumn": "MonthYear",
            "summarizeBy": "none"
          },
          {
            "name": "MonthYearLong",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6276fcf-2484-459a-ab05-8138e338cd96",
            "sourceColumn": "MonthYearLong",
            "summarizeBy": "none"
          },
          {
            "name": "SortWeekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "723b6f60-13e8-4733-bb80-c42971e1c454",
            "sourceColumn": "SortWeekday",
            "summarizeBy": "sum"
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bb2794b-7b97-4d08-af24-003b245d23ca",
            "sourceColumn": "Weekday",
            "summarizeBy": "none"
          },
          {
            "name": "WeekdayWeekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0296d510-c937-4e94-b6c9-be06b7932849",
            "sourceColumn": "WeekdayWeekend",
            "summarizeBy": "none"
          },
          {
            "name": "SortWeekSequence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "08fe2d8b-d111-4de5-860c-3f79e8feb232",
            "sourceColumn": "SortWeekSequence",
            "summarizeBy": "sum"
          },
          {
            "name": "CurWeekOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b3dd28a8-d1c4-4a10-9fb1-755dc12d00bf",
            "sourceColumn": "CurWeekOffset",
            "summarizeBy": "sum"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "e8cbd443-0f44-4ec7-b9d6-00ff12416f61",
        "partitions": [
          {
            "name": "Calendar - FY13+-c6cf55bb-a47a-4eaa-9b3c-4d2c11f75ce3",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    /*",
                "    ****This Calendar was created and provided by Avi Singh****",
                "    ****This can be freely shared as long as this text comment is retained.****",
                "    http://www.youtube.com/PowerBIPro",
                "    www.LearnPowerBI.com by Avi Singh",
                "    */",
                "    #\"LearnPowerBI.com by Avi Singh\" = 1,",
                "    StartDate = #date(2012, 7, 1),",
                "    EndDate = Date.AddMonths( Date.EndOfYear( #\"Max Proposal Date\" ), FiscalYearEndMonth ) /*was \"#date(2017, 1, 1)\" Updated on 201802027: hard Coded End of Year caused some formulas to break, switching to dynamic date*/,",
                "    //Used for 'Offset' Column calculations, you may Hard code CurrentDate for testing e.g. #date(2017,9,1)",
                "    CurrentDate = DateTime.Date(DateTime.FixedLocalNow()),",
                "    // Specify the last month in your Fiscal Year, e.g. if June is the last month of your Fiscal Year, specify 6",
                "    FiscalYearEndMonth = 6,",
                "    #\"==SET PARAMETERS ABOVE==\" = 1,",
                "    #\"==Build Date Column==\" = #\"==SET PARAMETERS ABOVE==\",",
                "    ListDates = List.Dates(StartDate, Number.From(EndDate - StartDate)+1, #duration(1,0,0,0)),",
                "    #\"Converted to Table\" = Table.FromList(ListDates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Renamed Columns as Date\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Date\"}}),",
                "    // As far as Power BI is concerned, the 'Date' column is all that is needed :-) But we will continue and add a few Human-Friendly Columns",
                "    #\"Changed Type to Date\" = Table.TransformColumnTypes(#\"Renamed Columns as Date\",{{\"Date\", type date}}),",
                "    #\"==Add Calendar Columns==\" = #\"Changed Type to Date\",",
                "    #\"Added Calendar MonthNum\" = Table.AddColumn(#\"==Add Calendar Columns==\", \"MonthNum\", each Date.Month([Date]), Int64.Type),",
                "    #\"Added Month Name\" = Table.AddColumn(#\"Added Calendar MonthNum\", \"Month\", each Text.Start(Date.MonthName([Date]),3), type text),",
                "    #\"Added Month Name Long\" = Table.AddColumn(#\"Added Month Name\", \"MonthLong\", each Date.MonthName([Date]), type text),",
                "    #\"Added Calendar Quarter\" = Table.AddColumn(#\"Added Month Name Long\", \"Quarter\", each \"Q\" & Text.From(Date.QuarterOfYear([Date]))),",
                "    #\"Added Calendar Year\" = Table.AddColumn(#\"Added Calendar Quarter\", \"Year\", each Date.Year([Date]), Int64.Type),",
                "    #\"==Add Fiscal Calendar Columns==\" = #\"Added Calendar Year\",",
                "    #\"Added FiscalMonthNum\" = Table.AddColumn(#\"==Add Fiscal Calendar Columns==\", \"FiscalMonthNum\", each if [MonthNum] > FiscalYearEndMonth",
                "then [MonthNum] - FiscalYearEndMonth",
                "else [MonthNum] + (12 - FiscalYearEndMonth), type number),",
                "    #\"Added FiscalMonth Name\" = Table.AddColumn(#\"Added FiscalMonthNum\", \"FiscalMonth\", each [Month]),",
                "    #\"Added FiscalMonth Name Long\" = Table.AddColumn(#\"Added FiscalMonth Name\", \"FiscalMonthLong\", each [MonthLong]),",
                "    #\"Added FiscalQuarter\" = Table.AddColumn(#\"Added FiscalMonth Name Long\", \"FiscalQuarter\", each \"FQ\" & Text.From(Number.RoundUp([FiscalMonthNum] / 3,0))),",
                "    #\"Added FiscalYear\" = Table.AddColumn(#\"Added FiscalQuarter\", \"FiscalYear\", each \"FY\" & ",
                "Text.End(",
                "  Text.From(",
                "    if [MonthNum] > FiscalYearEndMonth",
                "    then [Year] + 1",
                "    else [Year]",
                "  )",
                "  , 2",
                ")),",
                "",
                "    #\"==Add Calendar Date Offset Columns==\" = #\"Added FiscalYear\",",
                "    // Can be used to for example to show the past 3 months(CurMonthOffset = 0, -1, -2)",
                "    #\"Added CurMonthOffset\" = Table.AddColumn(#\"==Add Calendar Date Offset Columns==\", \"CurMonthOffset\", each ( Date.Year([Date]) - Date.Year(CurrentDate) ) * 12",
                "+ Date.Month([Date]) - Date.Month(CurrentDate), Int64.Type),",
                "    // Can be used to for example to show the past 3 quarters (CurQuarterOffset = 0, -1, -2)",
                "    #\"Added CurQuarterOffset\" = Table.AddColumn(#\"Added CurMonthOffset\", \"CurQuarterOffset\", each /*Year Difference*/",
                "       ( Date.Year([Date]) - Date.Year(CurrentDate) )*4",
                "       /*Quarter Difference*/",
                "      + Number.RoundUp(Date.Month([Date]) / 3) ",
                "      - Number.RoundUp(Date.Month(CurrentDate) / 3),",
                "Int64.Type),",
                "    // Can be used to for example to show the past 3 years (CurYearOffset = 0, -1, -2)",
                "    #\"Added CurYearOffset\" = Table.AddColumn(#\"Added CurQuarterOffset\", \"CurYearOffset\", each Date.Year([Date]) - Date.Year(CurrentDate), Int64.Type),",
                "    // Can be used to for example filter out all future dates",
                "    #\"Added FutureDate Flag\" = Table.AddColumn(#\"Added CurYearOffset\", \"FutureDate\", each if [Date] > CurrentDate then \"Future\" else \"Past\" ),",
                "    // FiscalYearOffset is the only Offset that is different.",
                "    // FiscalQuarterOffset = is same as CurQuarterOffset",
                "    // FiscalMonthOffset = is same as CurMonthOffset",
                "    #\"==Add FiscalYearOffset==\" = #\"Added FutureDate Flag\",",
                "    #\"Filtered Rows to CurrentDate\" = Table.SelectRows(#\"==Add FiscalYearOffset==\", each ([Date] = CurrentDate)),",
                "    CurrentFiscalYear = #\"Filtered Rows to CurrentDate\"{0}[FiscalYear],",
                "    #\"Continue...Orig Table\" = #\"==Add FiscalYearOffset==\",",
                "    #\"Added CurFiscalYearOffset\" = Table.AddColumn(#\"Continue...Orig Table\", \"CurFiscalYearOffset\", each Number.From(Text.Range([FiscalYear],2,2)) - ",
                "Number.From(Text.Range(CurrentFiscalYear,2,2))",
                "/*Extract the numerical portion, e.g. FY18 = 18*/),",
                "    #\"==Add General Columns==\" = #\"Added CurFiscalYearOffset\",",
                "    // Used as 'Sort by Column' for MonthYear columns",
                "    #\"Added MonthYearNum\" = Table.AddColumn(#\"==Add General Columns==\", \"MonthYearNum\", each [Year]*100 + [MonthNum] /*e.g. Sep-2016 would become 201609*/, Int64.Type),",
                "    #\"Added MonthYear\" = Table.AddColumn(#\"Added MonthYearNum\", \"MonthYear\", each [Month] & \"-\" & Text.End(Text.From([Year]),2)),",
                "    #\"Added MonthYearLong\" = Table.AddColumn(#\"Added MonthYear\", \"MonthYearLong\", each [Month] & \"-\" & Text.From([Year])),",
                "    #\"Added WeekdayNum\" = Table.AddColumn(#\"Added MonthYearLong\", \"WeekdayNum\", each Date.DayOfWeek([Date]), Int64.Type),",
                "    #\"Added Weekday Name\" = Table.AddColumn(#\"Added WeekdayNum\", \"Weekday\", each Text.Start(Date.DayOfWeekName([Date]),3), type text),",
                "    #\"Added WeekdayWeekend\" = Table.AddColumn(#\"Added Weekday Name\", \"WeekdayWeekend\", each if [WeekdayNum] = 0 or [WeekdayNum] = 6",
                "then \"Weekend\"",
                "else \"Weekday\"),",
                "    #\"==Improve Ultimate Table\" = #\"Added WeekdayWeekend\",",
                "    #\"----Add WeekSequenceNum----\" = #\"==Improve Ultimate Table\",",
                "    #\"Filtered Rows Sundays Only (Start of Week)\" = Table.SelectRows(#\"----Add WeekSequenceNum----\", each ([WeekdayNum] = 0)),",
                "    #\"Added Index WeekSequenceNum\" = Table.AddIndexColumn(#\"Filtered Rows Sundays Only (Start of Week)\", \"WeekSequenceNum\", 2, 1),",
                "    #\"Merged Queries Ultimate Table to WeekSequenceNum\" = Table.NestedJoin(#\"==Improve Ultimate Table\",{\"Date\"},#\"Added Index WeekSequenceNum\",{\"Date\"},\"Added Index WeekNum\",JoinKind.LeftOuter),",
                "    #\"Expanded Added Index WeekNum\" = Table.ExpandTableColumn(#\"Merged Queries Ultimate Table to WeekSequenceNum\", \"Added Index WeekNum\", {\"WeekSequenceNum\"}, {\"WeekSequenceNum\"}),",
                "    // somehow it ends up being unsorted after Expand Column, should not matter for the end table, but makes it harder to debug and check everything is correct. Thus sorting it.",
                "    #\"ReSorted Rows by Date\" = Table.Sort(#\"Expanded Added Index WeekNum\",{{\"Date\", Order.Ascending}}),",
                "    #\"Filled Down WeekSequenceNum\" = Table.FillDown(#\"ReSorted Rows by Date\",{\"WeekSequenceNum\"}),",
                "    #\"Replaced Value WeekSequenceNum null with 1\" = Table.ReplaceValue(#\"Filled Down WeekSequenceNum\",null,1,Replacer.ReplaceValue,{\"WeekSequenceNum\"}),",
                "    #\"----WeekSequenceNum Complete----\" = #\"Replaced Value WeekSequenceNum null with 1\",",
                "    Current_WeekSequenceNum = #\"----WeekSequenceNum Complete----\"{[Date = CurrentDate]}?[WeekSequenceNum],",
                "    #\"Added Custom CurWeekOffset\" = Table.AddColumn(#\"----WeekSequenceNum Complete----\", \"CurWeekOffset\", each [WeekSequenceNum] - Current_WeekSequenceNum, Int64.Type),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom CurWeekOffset\",{{\"Quarter\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"FiscalMonthNum\", \"SortFiscalMonth\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"FiscalMonth\", type text}, {\"FiscalMonthLong\", type text}, {\"FiscalQuarter\", type text}, {\"FiscalYear\", type text}, {\"FutureDate\", type text}, {\"CurFiscalYearOffset\", Int64.Type}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type1\",{{\"MonthYearNum\", \"SortMonthYear\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"MonthYear\", type text}, {\"MonthYearLong\", type text}}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Changed Type2\",{{\"WeekdayNum\", \"SortWeekday\"}}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"WeekdayWeekend\", type text}}),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Changed Type3\",{{\"WeekSequenceNum\", \"SortWeekSequence\"}})",
                "in",
                "    #\"Renamed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Proposals",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Proposal ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd77ed64-0316-4b9a-a8bc-c777301bb772",
            "sourceColumn": "Proposal ID",
            "summarizeBy": "none"
          },
          {
            "name": "Proposal Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c7b53f1-0182-46ef-bf77-b5184989dca3",
            "sortByColumn": "Sort Status",
            "sourceColumn": "Proposal Status",
            "summarizeBy": "none"
          },
          {
            "name": "Solicitation Details",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99d04cfa-f48f-4637-9d37-e25bdd417389",
            "sourceColumn": "Solicitation Details",
            "summarizeBy": "none"
          },
          {
            "name": "Proposal Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f285414-33b5-4ac8-baa3-e774189513d5",
            "sourceColumn": "Proposal Type",
            "summarizeBy": "none"
          },
          {
            "name": "Proposal Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e5bc528-8ccd-48bb-a33c-7ff70a38fa0b",
            "sourceColumn": "Proposal Title",
            "summarizeBy": "none"
          },
          {
            "name": "PG Indicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6df42719-f284-43c9-bd6c-4f15e1254bd9",
            "sourceColumn": "PG Indicator",
            "summarizeBy": "none"
          },
          {
            "name": "Planned Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "e81d5c35-2e33-4238-8170-3751592cb232",
            "sourceColumn": "Planned Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Planned Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6596dbb0-27e8-4ade-af38-a4767883c9f3",
            "sourceColumn": "Planned Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Planned Amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "2fd68c9c-5610-47d8-a46e-cc1c28c6dda7",
            "sourceColumn": "Planned Amt",
            "summarizeBy": "sum"
          },
          {
            "name": "Ask Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "2bd87597-267c-47aa-905a-db094f72d382",
            "sourceColumn": "Ask Date",
            "summarizeBy": "none"
          },
          {
            "name": "Ask Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "717e6d75-e1b5-4361-830b-ab805ccc5ead",
            "sourceColumn": "Ask Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Ask Amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a6672416-ba4e-433c-88df-f4ad95a9d008",
            "sourceColumn": "Ask Amt",
            "summarizeBy": "sum"
          },
          {
            "name": "Expected Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "77865b89-e855-4a9d-bc53-3e4c0d0882c1",
            "sourceColumn": "Expected Date",
            "summarizeBy": "none"
          },
          {
            "name": "Expected Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c1a253e-6ea9-4fd4-affd-aa4cbad263d0",
            "sourceColumn": "Expected Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Expected Amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c9ccaf30-4266-4365-ac7b-09326b151261",
            "sourceColumn": "Expected Amt",
            "summarizeBy": "sum"
          },
          {
            "name": "Granted Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "06556fe6-0fc9-485a-b34d-c8f2b166eea7",
            "sourceColumn": "Granted Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Granted Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12cf0d6d-ec2d-49a1-b937-0076c55e2782",
            "sourceColumn": "Granted Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Granted Amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "f4995973-a985-4655-ba1f-0a24eea964e9",
            "sourceColumn": "Granted Amt",
            "summarizeBy": "sum"
          },
          {
            "name": "Alloc Cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e159f4e-58f3-4005-bc67-d160131b888c",
            "sourceColumn": "Alloc Cd",
            "summarizeBy": "none"
          },
          {
            "name": "School/College",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "467bd960-64cb-4dd1-9200-f6a1e556d8b1",
            "sourceColumn": "School/College",
            "summarizeBy": "none"
          },
          {
            "name": "Proposal Purpose",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fd7aa94-173e-4294-9c28-e2e757e5e603",
            "sourceColumn": "Proposal Purpose",
            "summarizeBy": "none"
          },
          {
            "name": "Prospect Interest",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e202ae9e-71e0-4f89-852f-964a7ec46c6e",
            "sourceColumn": "Prospect Interest",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee0b1558-103e-4c26-8863-8f52f3ae3ec1",
            "sourceColumn": "Campaign Bucket",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4edb50f7-2009-4aaa-9637-f7207e4f8d33",
            "sourceColumn": "Campaign Priority",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign SubPriority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e940bf4-4a30-4119-83d0-4857e74c55dc",
            "sourceColumn": "Campaign SubPriority",
            "summarizeBy": "none"
          },
          {
            "name": "Current Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c79da9ea-9691-4f2e-b888-92369258780f",
            "sourceColumn": "Current Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Days Until Sol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1fdba241-a901-4976-9c5b-b06ff389e3cd",
            "sourceColumn": "Days Until Sol",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4bc78d4-b4f7-4269-b48e-59d026df3a09",
            "sourceColumn": "Sort Status",
            "summarizeBy": "none"
          },
          {
            "name": "Act?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ec2be1e-b7de-45a7-beb8-418e5575938d",
            "sourceColumn": "Act?",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Action Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "759daf37-a52b-4a47-b955-0e0e12ef9179",
            "sourceColumn": "Sort Action Status",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "031b1e8b-d3cb-494a-bb25-057e29fa5ec5",
            "sourceColumn": "Sort Bucket",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort Priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "22deb9bf-465c-44c5-9dd1-1f52d37f9edb",
            "sourceColumn": "Sort Priority",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort SubPriority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b24ee440-22cb-4392-b6fe-ded63a648036",
            "sourceColumn": "Sort SubPriority",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3950e0da-1515-4c6a-974f-ce42e03925ff",
            "sourceColumn": "Sort Type",
            "summarizeBy": "sum"
          },
          {
            "name": "HH Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e411bca-66e5-41a5-a9cb-5bfdb4d44098",
            "sourceColumn": "HH Key",
            "summarizeBy": "none"
          },
          {
            "name": "Prospect ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6d0339c8-166b-44ca-ba6e-1fba9ff8534b",
            "sourceColumn": "Prospect ID",
            "summarizeBy": "none"
          },
          {
            "name": "Days in Pending",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3c72868c-2a99-45cc-a26d-2014399766d9",
            "sourceColumn": "Days in Pending",
            "summarizeBy": "sum"
          },
          {
            "name": "Days to Wait",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f7e3719-bc36-4dbb-9eaa-dc6cb053c04c",
            "sourceColumn": "Days to Wait",
            "summarizeBy": "sum"
          },
          {
            "name": "Proposal FY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c5ef434-dd68-47cd-a829-fb16988767aa",
            "sourceColumn": "Proposal FY",
            "summarizeBy": "none"
          },
          {
            "name": "DtW Error",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1332a812-605a-4778-b0aa-928402b9399a",
            "sourceColumn": "DtW Error",
            "summarizeBy": "none"
          },
          {
            "name": "Current FY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "655502cd-db9b-4c5d-b174-63ce49cf376f",
            "sourceColumn": "Current FY",
            "summarizeBy": "none"
          },
          {
            "name": "Current Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "94ed7586-1e17-4e1d-b25e-343cfbaaca7a",
            "sourceColumn": "Current Date",
            "summarizeBy": "none"
          },
          {
            "name": "Action Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "303c06ef-a655-47c3-9948-91e31f6a1945",
            "sourceColumn": "Action Status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c7c19d33-04e7-42ff-9dc9-8e9f2675b98f",
        "partitions": [
          {
            "name": "Proposals-073507d7-ead8-486b-bca9-41c1d812a6b0",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(\"PADV\", [HierarchicalNavigation=true, Query=\"-- Query written for Gift Officer Dashboard to get important proposal data.  smk  8/12/2022#(lf)-- Cleaned up some of the logic and created a couple new measures. smk 9/1/2022#(lf)-- Updated to change the \"\"Value\"\" calculation for Asked and Pending proposals... if \"\"Expected Amt\"\" is blank it will return the \"\"Asked Amt\"\". smk 9/12/2022#(lf)-- Separated out the assigned Proposal Solicitors to eliminate duplicates in the dataset; also added a \"\"Current FY\"\". smk 10/17/2023#(lf)#(lf)select distinct prpsl.household_key          \"\"HH Key\"\",#(lf)       prpsl.prospect_id                     \"\"Prospect ID\"\",#(lf)       xp.proposal_id                        \"\"Proposal ID\"\", #(lf)       CASE WHEN xp.proposal_status_code = 'A' THEN 'Planned'#(lf)            WHEN xp.proposal_status_code = 'B' THEN 'Asked, Awaiting Response'#(lf)            WHEN xp.proposal_status_code IN ('U','V') THEN 'Asked, Verbal Response'#(lf)            WHEN xp.proposal_status_code = 'C' THEN 'Granted'#(lf)            WHEN xp.proposal_status_code IN ('D','F') THEN 'Refused'#(lf)          ELSE 'Other Response' END          \"\"Proposal Status\"\",#(lf)       xp.active_ind                         \"\"Act?\"\",#(lf)       xp.description                        \"\"Solicitation Details\"\",#(lf)       xpt.short_desc                        \"\"Proposal Type\"\",#(lf)       xp.proposal_title                     \"\"Proposal Title\"\",#(lf)       xp.plan_gift_ind                      \"\"PG Indicator\"\",#(lf)       trunc(xp.initial_contribution_date)   \"\"Planned Dt\"\",#(lf)       advur.fn_get_fytd_fiscalyear(to_char(xp.initial_contribution_date,'MM/DD/YYYY')) \"\"Planned Yr\"\",#(lf)       xp.original_ask_amt                   \"\"Planned Amt\"\",#(lf)       trunc(xp.start_date)                  \"\"Ask Date\"\",#(lf)       advur.fn_get_fytd_fiscalyear(to_char(xp.start_date,'MM/DD/YYYY')) \"\"Ask Yr\"\",#(lf)       xp.ask_amt                            \"\"Ask Amt\"\",#(lf)       trunc(xp.expected_date)               \"\"Expected Date\"\",#(lf)       advur.fn_get_fytd_fiscalyear(to_char(xp.expected_date,'MM/DD/YYYY')) \"\"Expected Yr\"\",#(lf)       xp.anticipated_amt                    \"\"Expected Amt\"\",#(lf)       trunc(xp.stop_date)                   \"\"Granted Dt\"\",#(lf)       advur.fn_get_fytd_fiscalyear(to_char(xp.stop_date,'MM/DD/YYYY')) \"\"Granted Yr\"\",#(lf)       xp.granted_amt                        \"\"Granted Amt\"\",#(lf)       propdt.statdt                         \"\"Current Date\"\",#(lf)       CASE WHEN xp.proposal_status_code = 'A' THEN advur.fn_get_fytd_fiscalyear(to_char(xp.initial_contribution_date,'MM/DD/YYYY'))#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NOT NULL THEN advur.fn_get_fytd_fiscalyear(to_char(xp.expected_date,'MM/DD/YYYY'))#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NOT NULL THEN advur.fn_get_fytd_fiscalyear(to_char(xp.start_date,'MM/DD/YYYY'))#(lf)            WHEN xp.proposal_status_code = 'C' THEN advur.fn_get_fytd_fiscalyear(to_char(xp.stop_date,'MM/DD/YYYY'))#(lf)            WHEN xp.proposal_status_code IN ('D','F') THEN 0000#(lf)          ELSE 0000 END                      \"\"Current FY\"\",#(lf)       CASE WHEN xp.proposal_status_code = 'A' THEN xp.original_ask_amt#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.anticipated_amt > 0 THEN xp.anticipated_amt#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.anticipated_amt = 0 THEN xp.ask_amt#(lf)            WHEN xp.proposal_status_code = 'C' THEN xp.granted_amt#(lf)            WHEN xp.proposal_status_code IN ('D','F') THEN 0#(lf)          ELSE 0 END                         \"\"Current Value\"\",#(lf)       CASE WHEN xp.proposal_status_code = 'A' AND propdt.statdt < trunc(sysdate) THEN 'Past Due'#(lf)            WHEN xp.proposal_status_code = 'A' AND propdt.statdt BETWEEN trunc(sysdate) AND trunc(sysdate)+90  THEN 'Upcoming'#(lf)            WHEN xp.proposal_status_code = 'A' AND propdt.statdt >= trunc(sysdate)+91  THEN 'Future'#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NOT NULL #(lf)                                                          AND xp.expected_date < trunc(sysdate)-30 THEN 'Past Due'#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NULL #(lf)                                                          AND xp.start_date < trunc(sysdate)-30 THEN 'Past Due'#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NOT NULL #(lf)                                                          AND xp.expected_date BETWEEN trunc(sysdate)-30 AND trunc(sysdate)+30 THEN 'Contact Now'#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NULL #(lf)                                                          AND xp.start_date BETWEEN trunc(sysdate)-30 AND trunc(sysdate)+30 THEN 'Contact Now'#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NULL#(lf)                                                          AND xp.start_date > trunc(sysdate)+31 THEN 'Future'#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NOT NULL #(lf)                                                          AND xp.expected_date > trunc(sysdate)+31 THEN 'Future'#(lf)          ELSE NULL END                      \"\"Action Status\"\",#(lf)       CASE WHEN xp.proposal_status_code = 'A' THEN nvl(propdt.statdt,trunc(sysdate)) - trunc(sysdate)#(lf)          ELSE NULL END                      \"\"Days Until Sol\"\",#(lf)       CASE WHEN xp.proposal_status_code IN ('B','U','V') THEN trunc(sysdate) - trunc(xp.start_date)#(lf)          ELSE NULL END                      \"\"Days in Pending\"\",#(lf)       CASE WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NULL THEN -999#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NOT NULL THEN trunc(xp.expected_date) - trunc(sysdate)#(lf)          ELSE NULL END                      \"\"Days to Wait\"\",#(lf)       CASE WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NULL THEN 'No Expected Date'#(lf)          ELSE NULL END                      \"\"DtW Error\"\",#(lf)       CASE WHEN xp.proposal_status_code = 'A' THEN EXTRACT(YEAR FROM add_months(xp.initial_contribution_date,6))#(lf)            WHEN xp.proposal_status_code = 'B' THEN EXTRACT(YEAR FROM add_months(xp.start_date,6))#(lf)            WHEN xp.proposal_status_code IN ('U','V') THEN EXTRACT(YEAR FROM add_months(xp.expected_date,6))#(lf)            WHEN xp.proposal_status_code = 'C' THEN EXTRACT(YEAR FROM add_months(xp.stop_date,6))#(lf)            WHEN xp.proposal_status_code IN ('D','F') THEN EXTRACT(YEAR FROM add_months(xp.date_modified,6))#(lf)          ELSE NULL END                      \"\"Proposal FY\"\",#(lf)       xpp.allocation                        \"\"Alloc Cd\"\",#(lf)       p.short_desc                          \"\"School/College\"\",#(lf)       pp.short_desc                         \"\"Proposal Purpose\"\",#(lf)       pi.short_desc                         \"\"Prospect Interest\"\",#(lf)       c1.short_desc                         \"\"Campaign Bucket\"\",#(lf)       c2.short_desc                         \"\"Campaign Priority\"\",#(lf)       c3.short_desc                         \"\"Campaign SubPriority\"\",#(lf)       CASE WHEN xp.proposal_status_code = 'A' THEN '1'#(lf)            WHEN xp.proposal_status_code = 'B' THEN '2'#(lf)            WHEN xp.proposal_status_code IN ('U','V') THEN '3'#(lf)            WHEN xp.proposal_status_code = 'C' THEN '4'#(lf)            WHEN xp.proposal_status_code IN ('D','F') THEN '5'#(lf)          ELSE '9' END                       \"\"Sort Status\"\",#(lf)       CASE WHEN xp.proposal_status_code = 'A' AND propdt.statdt < trunc(sysdate) THEN '01'#(lf)            WHEN xp.proposal_status_code = 'A' AND propdt.statdt BETWEEN trunc(sysdate) AND trunc(sysdate)+90  THEN '02'#(lf)            WHEN xp.proposal_status_code = 'A' AND propdt.statdt >= trunc(sysdate)+91  THEN '03'#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NOT NULL #(lf)                                                          AND xp.expected_date < trunc(sysdate)-30 THEN '11'#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NULL #(lf)                                                          AND xp.start_date < trunc(sysdate)-30 THEN '11'#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NOT NULL #(lf)                                                          AND xp.expected_date BETWEEN trunc(sysdate)-30 AND trunc(sysdate)+30 THEN '12'#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NULL #(lf)                                                          AND xp.start_date BETWEEN trunc(sysdate)-30 AND trunc(sysdate)+30 THEN '12'#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NULL#(lf)                                                          AND xp.start_date > trunc(sysdate)+31 THEN '13'#(lf)            WHEN xp.proposal_status_code IN ('B','U','V') AND xp.expected_date IS NOT NULL #(lf)                                                          AND xp.expected_date > trunc(sysdate)+31 THEN '13'#(lf)          ELSE '99' END                      \"\"Sort Action Status\"\",#(lf)       nvl(c1.hierarchy_order,'99')          \"\"Sort Bucket\"\",#(lf)       nvl(c2.hierarchy_order,'999')         \"\"Sort Priority\"\",#(lf)       nvl(c3.hierarchy_order,'999')         \"\"Sort SubPriority\"\",#(lf)       nvl(xpt.hierarchy_order,'999')        \"\"Sort Type\"\"#(lf)       #(lf)from advance.proposal xp#(lf)inner join advur.mvw_proposals prpsl       ON xp.proposal_id = prpsl.proposal_id#(lf)inner join advance.tms_proposal_type xpt   ON xp.proposal_type = xpt.proposal_type#(lf)inner join advance.proposal_purpose xpp    ON xp.proposal_id = xpp.proposal_id#(lf)left join advance.tms_category1 c1         ON xpp.category1_code = c1.category1_code#(lf)left join advance.tms_category2 c2         ON xpp.category2_code = c2.category2_code#(lf)left join advance.tms_category3 c3         ON xpp.category3_code = c3.category3_code#(lf)left join advance.tms_prospect_interest pi ON xpp.prospect_interest_code = pi.prospect_interest_code#(lf)left join advance.tms_prop_purpose pp      ON xpp.prop_purpose_code = pp.prop_purpose_code#(lf)left join advance.tms_program p            ON xpp.program_code = p.program_code#(lf)LEFT JOIN (#(lf)           select xxp.proposal_id pid,#(lf)                  CASE WHEN xxp.proposal_status_code = 'A' THEN xxp.initial_contribution_date#(lf)                       WHEN xxp.proposal_status_code IN ('B','U','V') AND xxp.expected_date IS NULL THEN xxp.start_date#(lf)                       WHEN xxp.proposal_status_code IN ('B','U','V') AND xxp.expected_date IS NOT NULL THEN xxp.expected_date#(lf)                       WHEN xxp.proposal_status_code = 'C' THEN xxp.stop_date#(lf)                       WHEN xxp.proposal_status_code IN ('D','F') THEN trunc(xxp.date_modified)#(lf)                     ELSE NULL END statdt#(lf)             from advance.proposal xxp#(lf)            where xxp.proposal_status_code NOT IN ('G','I')#(lf)            and  ((xxp.proposal_status_code = 'A' AND EXTRACT(YEAR FROM xxp.initial_contribution_date) #(lf)                           >= advur.fn_get_fytd_fiscalyear(to_char(sysdate,'MM/DD/YYYY'))-2)#(lf)              or  (xxp.proposal_status_code IN ('B','U','V') AND EXTRACT(YEAR FROM xxp.start_date) #(lf)                           >= advur.fn_get_fytd_fiscalyear(to_char(sysdate,'MM/DD/YYYY'))-2)#(lf)              or  (xxp.proposal_status_code = 'C' AND EXTRACT(YEAR FROM xxp.stop_date)#(lf)                           >= advur.fn_get_fytd_fiscalyear(to_char(sysdate,'MM/DD/YYYY'))-2)#(lf)              or  (xxp.proposal_status_code IN ('D','F') AND EXTRACT(YEAR FROM xxp.date_modified)#(lf)                           >= advur.fn_get_fytd_fiscalyear(to_char(sysdate,'MM/DD/YYYY'))-2)#(lf)                  )#(lf)           )propdt ON xp.proposal_id = propdt.pid#(lf)where xp.proposal_status_code NOT IN ('G','I')#(lf)and   ((xp.proposal_status_code = 'A' AND EXTRACT(YEAR FROM xp.initial_contribution_date) #(lf)                           >= advur.fn_get_fytd_fiscalyear(to_char(sysdate,'MM/DD/YYYY'))-2)#(lf)   or  (xp.proposal_status_code IN ('B','U','V') AND EXTRACT(YEAR FROM xp.start_date) #(lf)                           >= advur.fn_get_fytd_fiscalyear(to_char(sysdate,'MM/DD/YYYY'))-2)#(lf)   or  (xp.proposal_status_code = 'C' AND EXTRACT(YEAR FROM xp.stop_date)#(lf)                           >= advur.fn_get_fytd_fiscalyear(to_char(sysdate,'MM/DD/YYYY'))-2)#(lf)   or  (xp.proposal_status_code IN ('D','F') AND EXTRACT(YEAR FROM xp.date_modified)#(lf)                           >= advur.fn_get_fytd_fiscalyear(to_char(sysdate,'MM/DD/YYYY'))-2)#(lf)      )#(lf)and   xp.proposal_id NOT IN (select zp1.proposal_id#(lf)                               from advance.proposal zp1#(lf)                              where zp1.proposal_status_code = 'A'#(lf)                              and   zp1.active_ind <> 'Y')#(lf)order by \"\"Sort Status\"\", \"\"Sort Action Status\"\", \"\"Current Value\"\" desc\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Planned Dt\", type date}, {\"Planned Yr\", type text}, {\"Planned Amt\", Currency.Type}, {\"Ask Date\", type date}, {\"Ask Yr\", type text}, {\"Ask Amt\", Currency.Type}, {\"Expected Date\", type date}, {\"Expected Yr\", type text}, {\"Expected Amt\", Currency.Type}, {\"Granted Dt\", type date}, {\"Granted Yr\", type text}, {\"Granted Amt\", Currency.Type}, {\"Current Date\", type date}, {\"Current FY\", type text}, {\"Current Value\", Currency.Type}, {\"Days Until Sol\", Int64.Type}, {\"Days in Pending\", Int64.Type}, {\"Days to Wait\", Int64.Type}, {\"Proposal FY\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Contact Reports",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Report ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fbd84739-7e66-4b03-aa70-8dd236cf12ef",
            "sourceColumn": "Report ID",
            "summarizeBy": "count"
          },
          {
            "name": "Contact Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "a70ba13c-fdce-4be5-9eaf-651db3ecd781",
            "sourceColumn": "Contact Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Contact Purpose",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e094972-47dd-49ec-81d6-015972daf5c2",
            "sortByColumn": "Sort Purpose",
            "sourceColumn": "Contact Purpose",
            "summarizeBy": "none"
          },
          {
            "name": "Contact Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3b36e08-3430-4433-8880-474bf9d42dcd",
            "sortByColumn": "Sort Type",
            "sourceColumn": "Contact Type",
            "summarizeBy": "none"
          },
          {
            "name": "Contact Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebbe1843-f98a-4de8-9d0e-9da4b0728b49",
            "sourceColumn": "Contact Description",
            "summarizeBy": "none"
          },
          {
            "name": "Contacted ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "009175ad-0867-4b4a-a064-7f721fea3b82",
            "sourceColumn": "Contacted ID",
            "summarizeBy": "none"
          },
          {
            "name": "Contacted Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "2237200b-f259-41c8-bdc7-ba39a8536907",
            "sortByColumn": "Sort Contacted",
            "sourceColumn": "Contacted Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fee036a4-190d-48c0-ba88-de1f29a567c3",
            "sourceColumn": "Sort Type",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort Purpose",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c0d763aa-0710-49c3-b6ff-7cb9d0a5980d",
            "sourceColumn": "Sort Purpose",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort Contacted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28ae7159-7831-4b7b-b88f-af699498bf54",
            "sourceColumn": "Sort Contacted",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Officer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "160fc63e-7add-4f6d-bbc6-7af673bb561d",
            "sourceColumn": "Sort Officer",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4abd2a3e-ce33-4ed8-b1ec-0178c0f554a2",
            "sourceColumn": "Sort Team",
            "summarizeBy": "sum"
          },
          {
            "name": "CR Prospect ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c206e8a0-3d26-420c-addc-6513f5d3edfe",
            "sourceColumn": "CR Prospect ID",
            "summarizeBy": "count"
          },
          {
            "name": "Contact FY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f35b089-7170-4a5e-af16-05582f5966f5",
            "sourceColumn": "Contact FY",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Mgr ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d6d5802-1acc-477c-83c1-69d02edd5bf3",
            "sourceColumn": "Primary Mgr ID",
            "summarizeBy": "none"
          },
          {
            "name": "PM Author Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4a90e6d6-ca7e-4d6d-a755-813ddcdc220c",
            "sourceColumn": "PM Author Ind",
            "summarizeBy": "sum"
          },
          {
            "name": "Assgnd Pros Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fbfe8f4b-49f5-4ffc-8752-74f7dad5e3d6",
            "sourceColumn": "Assgnd Pros Ind",
            "summarizeBy": "sum"
          },
          {
            "name": "Author ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2765305-7e29-4e58-b250-bb8038ae938f",
            "sourceColumn": "Author ID",
            "summarizeBy": "none"
          },
          {
            "name": "Author Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8fdf524-3d53-4189-858e-6effd4d38145",
            "sourceColumn": "Author Name",
            "summarizeBy": "none"
          },
          {
            "name": "Author Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbceaf75-1e6a-4438-b275-38613eb8abc6",
            "sourceColumn": "Author Team",
            "summarizeBy": "none"
          },
          {
            "name": "GO Unique Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37fd6ad0-1139-4a17-9db8-021b902ff6a7",
            "sourceColumn": "GO Unique Key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e6c51ac0-b1a0-4056-9a21-60c3378e0a0b",
        "partitions": [
          {
            "name": "Contact Reports-8e6d8b3a-2805-48b1-9785-e9c5ee441d6d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(\"padv\", [HierarchicalNavigation=true, Query=\"-- This query written for the Gift Officer Dashboard, to pull details on Contact Reports from the last and current fiscal year. smk 8/17/2022#(lf)-- Updated to pull in Sort values for Contact Type and Purpose.#(lf)-- Updated to change the \"\"contact year\"\" to a fiscal year value; also filtering to just those entities who are prospects. smk 12/13/2022#(lf)-- Numerous updates made in an effort to filter out as many duplicate rows as possible (mostly in the prospect area). smk 12/14/2022#(lf)-- Reworked to eliminate some duplicates and simplify the logic a little; also added a \"\"GO Unique Key\"\". smk 10/24/2023#(lf)#(lf)select distinct cr1.report_id                             \"\"Report ID\"\",#(lf)       cr1.prospect_id                                    \"\"CR Prospect ID\"\",#(lf)       cr1.id_number                                      \"\"Contacted ID\"\",#(lf)       trunc(cr1.contact_date)                            \"\"Contact Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(cr1.contact_date,6))  \"\"Contact FY\"\",#(lf)       purp.short_desc                                    \"\"Contact Purpose\"\",#(lf)       t.short_desc                                       \"\"Contact Type\"\",#(lf)       cr1.description                                    \"\"Contact Description\"\",#(lf)       e.pref_mail_name                                   \"\"Contacted Name\"\",#(lf)       pm.goid                                            \"\"Primary Mgr ID\"\",#(lf)       CASE WHEN pm.goid = cr1.author_id_number THEN 1#(lf)          ELSE 0 END                                      \"\"PM Author Ind\"\",#(lf)       CASE WHEN pm.goid > 0 THEN 1#(lf)          ELSE 0 END                                      \"\"Assgnd Pros Ind\"\",#(lf)       cr1.author_id_number                               \"\"Author ID\"\",#(lf)       a.pref_mail_name                                   \"\"Author Name\"\",#(lf)       uc.short_desc                                      \"\"Author Team\"\",#(lf)       cr1.prospect_id||cr1.author_id_number              \"\"GO Unique Key\"\",#(lf)       t.hierarchy_order                                  \"\"Sort Type\"\",#(lf)       purp.hierarchy_order                               \"\"Sort Purpose\"\",#(lf)       e.pref_name_sort                                   \"\"Sort Contacted\"\",#(lf)       s.sort                                             \"\"Sort Officer\"\",#(lf)       uc.hierarchy_order                                 \"\"Sort Team\"\"#(lf) from advance.contact_report cr1#(lf)inner join advance.tms_contact_rpt_purpose purp ON cr1.contact_purpose_code = purp.contact_purpose_code#(lf)inner join advance.tms_contact_rpt_type t       ON cr1.contact_type = t.contact_type#(lf)inner join advance.entity e                     ON cr1.id_number = e.id_number#(lf)inner join advance.entity a                     ON cr1.author_id_number = a.id_number#(lf)inner join advance.staff s                      ON a.id_number = s.id_number#(lf)inner join advance.tms_unit_code uc             ON s.unit_code = uc.unit_code#(lf)left join (#(lf)           select asmt.prospect_id pid, pe.id_number eid, s.id_number goid, s.name gonme, #(lf)                  u.short_desc grp, s.sort gosrt, u.hierarchy_order gsrt#(lf)             from advance.staff s#(lf)            inner join advance.assignment asmt    ON s.id_number = asmt.assignment_id_number#(lf)             left join advance.tms_unit_code u    ON s.unit_code = u.unit_code#(lf)             left join advance.prospect_entity pe ON asmt.prospect_id = pe.prospect_id#(lf)            where asmt.assignment_type = 'PM'#(lf)            and   asmt.active_ind = 'Y'#(lf)            )pm ON cr1.id_number = pm.eid#(lf)where cr1.contact_type <> 'DR'#(lf)and   cr1.contact_purpose_code <> 'I'#(lf)and   EXTRACT(YEAR FROM add_months(cr1.contact_date,6)) >= advur.fn_get_fytd_fiscalyear(to_char(sysdate,'MM/DD/YYYY'))-1#(lf)#(lf)order by \"\"Contact Dt\"\"\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Contact Dt\", type date}, {\"Contact FY\", type text}, {\"PM Author Ind\", Int64.Type}, {\"Assgnd Pros Ind\", Int64.Type}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Prospect Discovery\",\"Discovery\",Replacer.ReplaceText,{\"Contact Purpose\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Prospect Cultivation\",\"Cultivation\",Replacer.ReplaceText,{\"Contact Purpose\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"Prospect Solicitation\",\"Solicitation\",Replacer.ReplaceText,{\"Contact Purpose\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"Prospect Qualification\",\"Qualification\",Replacer.ReplaceText,{\"Contact Purpose\"})",
                "in",
                "    #\"Replaced Value3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Prospects and Scores",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Entity ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7f8a171-e9c1-4a5a-8c67-aadd0d2733ce",
            "sourceColumn": "Entity ID",
            "summarizeBy": "none"
          },
          {
            "name": "Prospect ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bf19bd26-b4a5-4f52-90e7-da7595e3cce3",
            "sourceColumn": "Prospect ID",
            "summarizeBy": "none"
          },
          {
            "name": "AF EVI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aa586632-28fd-4333-a8d0-dac8b1fc6b1d",
            "sourceColumn": "AF EVI",
            "summarizeBy": "sum"
          },
          {
            "name": "AF PDI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2a6a129b-718d-400d-87b5-7538ec56bfb6",
            "sourceColumn": "AF PDI",
            "summarizeBy": "sum"
          },
          {
            "name": "MG EVI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ca6710fe-4200-4977-bb4a-71ac7fb92708",
            "sourceColumn": "MG EVI",
            "summarizeBy": "sum"
          },
          {
            "name": "MG Capacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "0",
            "lineageTag": "4803f30e-91a4-4aad-8155-a82da3b1bddd",
            "sourceColumn": "MG Capacity",
            "summarizeBy": "sum"
          },
          {
            "name": "Target Gift Range",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d445178-e749-42ba-92eb-657a906ec584",
            "sourceColumn": "Target Gift Range",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Gift Range",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fcc7ac89-869b-41b5-a902-236ecd0d642c",
            "sourceColumn": "Campaign Gift Range",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Potential",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ec88c90-b917-4e0a-99be-207686690023",
            "sourceColumn": "Campaign Potential",
            "summarizeBy": "none"
          },
          {
            "name": "Affinity Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27b4961f-520c-4de2-8eb0-ce2998c00516",
            "sourceColumn": "Affinity Rating",
            "summarizeBy": "none"
          },
          {
            "name": "FPM Net Worth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36dc0270-7037-4f2f-9045-e88c7529e45c",
            "sourceColumn": "FPM Net Worth",
            "summarizeBy": "none"
          },
          {
            "name": "Six Square Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f98f015d-a9ef-402b-ab7b-1a05bfff01ef",
            "sourceColumn": "Six Square Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Alumni Engagement Score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f9d5212e-92d4-42ae-b56f-523f32b99eb4",
            "sourceColumn": "Alumni Engagement Score",
            "summarizeBy": "none"
          },
          {
            "name": "Sort TGR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "233e316e-e40c-4b64-9f25-4166bcf5f022",
            "sourceColumn": "Sort TGR",
            "summarizeBy": "none"
          },
          {
            "name": "Sort CGR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66bb33fc-2bf9-4df5-a73b-3bce8e6c9468",
            "sourceColumn": "Sort CGR",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Camp Potential",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51aae192-fd8d-4d90-aac5-d2a3c6f41fcd",
            "sourceColumn": "Sort Camp Potential",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Affinity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "180ef9a7-d4a6-4d27-9dae-9d82537ae112",
            "sourceColumn": "Sort Affinity",
            "summarizeBy": "none"
          },
          {
            "name": "Sort RNW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77386fbf-7900-4b68-a1d4-ed68b1fed8df",
            "sourceColumn": "Sort RNW",
            "summarizeBy": "none"
          },
          {
            "name": "CFY Prod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c5233645-3f18-4c76-b91a-570b2ece257e",
            "sourceColumn": "CFY Prod",
            "summarizeBy": "sum"
          },
          {
            "name": "PFY Prod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "49e0ff67-5bb6-4cf3-9567-1df024e968a9",
            "sourceColumn": "PFY Prod",
            "summarizeBy": "sum"
          },
          {
            "name": "Increase?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d7852a5d-76d6-4c49-aa40-81205542d20c",
            "sourceColumn": "Increase?",
            "summarizeBy": "sum"
          },
          {
            "name": "Decrease?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "15ab3e62-a4c7-425d-829d-2833ced53414",
            "sourceColumn": "Decrease?",
            "summarizeBy": "sum"
          },
          {
            "name": "Act Proposal?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "d550202d-8cde-4280-ae23-7835826eb0f6",
            "sourceColumn": "Act Proposal?",
            "summarizeBy": "sum"
          },
          {
            "name": "Proposal?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66a107e6-4cce-4176-990a-83396d20ef92",
            "sourceColumn": "Proposal?",
            "summarizeBy": "none"
          },
          {
            "name": "Prospect Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2f8843a-047f-4493-9fbd-91d724803e23",
            "sourceColumn": "Prospect Name",
            "summarizeBy": "none"
          },
          {
            "name": "CFY Donor?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "52973d20-9013-4f05-b6c1-de30d6d93903",
            "sourceColumn": "CFY Donor?",
            "summarizeBy": "none"
          },
          {
            "name": "Rec Proposal?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "2bfe7d3f-f70b-4227-964f-2f3ad1121b43",
            "sourceColumn": "Rec Proposal?",
            "summarizeBy": "sum"
          },
          {
            "name": "Rec Proposal Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df27f141-9695-4d8d-adec-8712cd143af3",
            "sourceColumn": "Rec Proposal Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Prospect Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30bae1de-3645-41b4-ad17-e081c9449925",
            "sourceColumn": "Primary Prospect Name",
            "summarizeBy": "none"
          },
          {
            "name": "Spouse Prospect Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79608de8-7ce5-414a-8451-a3a64171ccab",
            "sourceColumn": "Spouse Prospect Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prospect Stage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5357d9fb-ca70-4bdd-849a-e33c83f802a4",
            "sourceColumn": "Prospect Stage",
            "summarizeBy": "none"
          },
          {
            "name": "Days In Stage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8540e7f8-bc3b-4cd6-a744-b1e3a38e937b",
            "sourceColumn": "Days In Stage",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort Stage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5d4d01fc-b5fd-4fc7-ad90-e5d83d981b63",
            "sourceColumn": "Sort Stage",
            "summarizeBy": "sum"
          },
          {
            "name": "Days Assgnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5b8dd6ce-100f-4f30-9554-c945ea3d0b21",
            "sourceColumn": "Days Assgnd",
            "summarizeBy": "sum"
          },
          {
            "name": "Act Plg Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "be93f3d6-ccdb-44d3-aa32-e15541a5219c",
            "sourceColumn": "Act Plg Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Act Plg Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "5cc4e0af-06b9-44c8-8ed7-7919a41f70b3",
            "sourceColumn": "Act Plg Total",
            "summarizeBy": "sum"
          },
          {
            "name": "HH Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86b1e2b5-4d26-40f1-a7c2-9660ce31e55f",
            "sourceColumn": "HH Key",
            "summarizeBy": "none"
          },
          {
            "name": "PM ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91b540a8-cb33-40af-b444-4d58fafce4b3",
            "sourceColumn": "PM ID",
            "summarizeBy": "none"
          },
          {
            "name": "PM Start Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "91b5a038-8c23-4b13-8025-ac2b479c3bce",
            "sourceColumn": "PM Start Dt",
            "summarizeBy": "none"
          },
          {
            "name": "PM Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "879a5048-c944-49b0-a6f3-6abc3cfcf989",
            "sourceColumn": "PM Team",
            "summarizeBy": "none"
          },
          {
            "name": "Sort PM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8beda2a5-703b-42d1-b489-30a30da09eb8",
            "sourceColumn": "Sort PM",
            "summarizeBy": "none"
          },
          {
            "name": "Sort PM Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f25e5ac9-5a1f-4c9b-839c-cb7bfb59f089",
            "sourceColumn": "Sort PM Team",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "3eb420af-ead3-4775-9ad7-8e0b155381a3",
        "partitions": [
          {
            "name": "Prospects and Scores-b74859c2-39f4-4e49-8bf3-fe53748432cf",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(\"PADV\", [HierarchicalNavigation=true, Query=\"-- Query written for the Gift Officer Dashboard to pull actively-assigned prospects and their FPM Scores.  smk 8/18/2022#(lf)-- Updated to add sorting columns.  smk 9/14/2022#(lf)-- Updated to add Current and Previous FY Production Totals and \"\"Increase/Decrease\"\" indicators. smk 9/22/2022#(lf)-- Updated to pull all active prospects and not just actively-assigned. smk 9/30/2022#(lf)-- Query developed for the Gift Officer Dashboard intended to pull prospect information and related FPM Scores. smk 10/6/2022#(lf)-- Updated to add a CFY Donor Statement.  smk 10/21/2022#(lf)-- Updated to fix the proposal date error and to add recently completed proposals. smk 11/11/2022#(lf)-- Updated to add fiscal year to current active and recently-completed propsals to add categories to \"\"Proposal?\"\" column. smk 10/16/2023#(lf)-- Updated to add Stage and Days in Stage and the Household Keys. smk 10/20/2023#(lf)#(lf)select distinct pe.id_number                      \"\"Entity ID\"\",#(lf)       hk.household_key                           \"\"HH Key\"\",#(lf)       p.prospect_id                              \"\"Prospect ID\"\",#(lf)       p.prospect_name                            \"\"Prospect Name\"\",#(lf)       e.pref_mail_name                           \"\"Primary Prospect Name\"\",#(lf)       sp.pref_mail_name                          \"\"Spouse Prospect Name\"\",#(lf)       stgdays.Stage                              \"\"Prospect Stage\"\",#(lf)       stgdays.daysin                             \"\"Days In Stage\"\",#(lf)       pm.goid                                    \"\"PM ID\"\",#(lf)       pm.strt                                    \"\"PM Start Dt\"\",#(lf)       pm.grp                                     \"\"PM Team\"\",#(lf)       (trunc(sysdate) - pm.strt)                 \"\"Days Assgnd\"\",#(lf)       nvl(actplg.cnt,0)                          \"\"Act Plg Count\"\",#(lf)       nvl(actplg.ttl,0)                          \"\"Act Plg Total\"\",#(lf)       CASE WHEN r.af_evi = 'N/A' THEN '0'#(lf)          ELSE nvl(r.af_evi,'0') END            \"\"AF EVI\"\",#(lf)       CASE WHEN r.af_pdi_score = 'N/A' THEN '0'#(lf)          ELSE nvl(r.af_pdi_score,'0') END      \"\"AF PDI\"\",#(lf)       CASE WHEN r.af_pdi_score = 'N/A' THEN '0'#(lf)          ELSE nvl(r.mg_evi,'0') END            \"\"MG EVI\"\",#(lf)       r.mg_capacity                            \"\"MG Capacity\"\",#(lf)       r.target_gift_range                      \"\"Target Gift Range\"\",#(lf)       r.campaign_gift_range                    \"\"Campaign Gift Range\"\",#(lf)       r.campaign_potential                     \"\"Campaign Potential\"\",#(lf)       r.affinity_rating                        \"\"Affinity Rating\"\",#(lf)       r.reeher_net_worth                       \"\"FPM Net Worth\"\",#(lf)       r.six_square_segment                     \"\"Six Square Segment\"\",#(lf)       r.alumni_engagement_score                \"\"Alumni Engagement Score\"\",#(lf)       nvl(cfy.ttl,0)                           \"\"CFY Prod\"\",#(lf)       nvl(pfy.ttl,0)                           \"\"PFY Prod\"\",#(lf)       CASE WHEN nvl(cfy.ttl,0) > 0 THEN 'CFY Donor'#(lf)          ELSE 'CFY Non-Donor' END              \"\"CFY Donor?\"\",#(lf)       CASE WHEN nvl(cfy.ttl,0) >= nvl(pfy.ttl,0) THEN 1#(lf)          ELSE 0 END                            \"\"Increase?\"\",#(lf)       CASE WHEN nvl(cfy.ttl,0) < nvl(pfy.ttl,0) THEN 1#(lf)          ELSE 0 END                            \"\"Decrease?\"\",#(lf)       CASE WHEN nvl(actprp.prid,0) > 0 THEN 1        -- AND exstprp.statyr = advur.fn_get_fytd_fiscalyear(TO_CHAR(SYSDATE, 'MM/DD/YYYY'))#(lf)          ELSE 0 END                            \"\"Act Proposal?\"\",#(lf)       CASE WHEN nvl(cprp.prid,0) > 0 THEN 1#(lf)          ELSE 0 END                            \"\"Rec Proposal?\"\",#(lf)       listagg(distinct cprp.statyr,' & ') within group (order by cprp.statyr) \"\"Rec Proposal Yr\"\",#(lf)       CASE WHEN nvl(cprp.prid,0) > 0 THEN 'Recent Completed Proposal'#(lf)            WHEN nvl(actprp.prid,0) > 0 AND actprp.statyr < advur.fn_get_fytd_fiscalyear(TO_CHAR(SYSDATE, 'MM/DD/YYYY')) THEN 'Has Prior Year Proposal'#(lf)            WHEN nvl(actprp.prid,0) > 0 AND actprp.statyr = advur.fn_get_fytd_fiscalyear(TO_CHAR(SYSDATE, 'MM/DD/YYYY')) THEN 'Has Current Year Proposal'#(lf)            WHEN nvl(actprp.prid,0) > 0 AND actprp.statyr > advur.fn_get_fytd_fiscalyear(TO_CHAR(SYSDATE, 'MM/DD/YYYY')) THEN 'Has Future Year Proposal'#(lf)          ELSE 'No Active Proposal' END         \"\"Proposal?\"\",#(lf)       nvl(r.target_gift_range_code,'ZZ999')    \"\"Sort TGR\"\",#(lf)       nvl(r.campaign_gift_range_code,'ZZ999')  \"\"Sort CGR\"\",#(lf)       CASE WHEN r.campaign_potential_code = '0' THEN 'ZZ'#(lf)          ELSE nvl(r.campaign_potential_code,'ZZ') END  \"\"Sort Camp Potential\"\",#(lf)       nvl(r.affinity_rating_code,'Z9')         \"\"Sort Affinity\"\",#(lf)       CASE WHEN r.rnw_code = 'R013' THEN '100'#(lf)            WHEN r.rnw_code = 'R012' THEN '150'#(lf)            WHEN r.rnw_code = 'R011' THEN '200'#(lf)            WHEN r.rnw_code = 'R009' THEN '250'#(lf)            WHEN r.rnw_code = 'R02' THEN '300'#(lf)            WHEN r.rnw_code = 'R03' THEN '350'#(lf)            WHEN r.rnw_code = 'R04' THEN '400'#(lf)            WHEN r.rnw_code = 'R05' THEN '450'#(lf)            WHEN r.rnw_code = 'R06' THEN '500'#(lf)            WHEN r.rnw_code = 'R010' THEN '550'#(lf)            WHEN r.rnw_code = 'UN' THEN '899'#(lf)            WHEN r.rnw_code = 'R12' THEN '900'#(lf)            WHEN r.rnw_code = '0' THEN '905'#(lf)          ELSE nvl(r.rnw_code,'999') END        \"\"Sort RNW\"\",#(lf)       stgdays.srt                              \"\"Sort Stage\"\",#(lf)       pm.gosrt                                 \"\"Sort PM\"\",#(lf)       pm.gsrt                                  \"\"Sort PM Team\"\"#(lf)from advance.prospect p#(lf)inner join advance.prospect_entity pe       ON p.prospect_id = pe.prospect_id#(lf) left join advur.mvw_ent_household_keys hk  ON pe.id_number = hk.id_number#(lf)inner join advance.entity e                 ON pe.id_number = e.id_number AND pe.primary_ind = 'Y' AND e.record_status_code = 'A'#(lf) left join advance.entity sp                ON e.spouse_id_number = sp.id_number AND sp.id_number IN (select xpe.id_number from advance.prospect_entity xpe)#(lf)left join advur.mvw_ent_ratings r           ON pe.id_number = r.id_number#(lf)left join (#(lf)           select distinct xte.donor_id did, sum(xte.trans_amt) ttl  -- Current Fiscal Year production#(lf)             from advur.mvw_total_production xp#(lf)            inner join advur.mvw_trans_entities xte ON xp.trans_nbr = xte.trans_nbr#(lf)            where xp.fiscal_yr = advur.fn_get_fytd_fiscalyear(TO_CHAR(SYSDATE, 'MM/DD/YYYY'))#(lf)            and   xte.trans_amt > 0#(lf)            group by xte.donor_id#(lf)            )cfy ON pe.id_number = cfy.did#(lf)left join (#(lf)           select distinct xte2.donor_id did, sum(xte2.trans_amt) ttl  -- Current Fiscal Year revenue#(lf)             from advur.mvw_total_production xp2#(lf)            inner join advur.mvw_trans_entities xte2 ON xp2.trans_nbr = xte2.trans_nbr#(lf)            where xp2.fiscal_yr = advur.fn_get_fytd_fiscalyear(TO_CHAR(SYSDATE, 'MM/DD/YYYY'))-1#(lf)            and   xte2.trans_amt > 0#(lf)            group by xte2.donor_id#(lf)            )pfy ON pe.id_number = pfy.did#(lf)left join (                                        -- Active proposals#(lf)           select distinct xprp.prospect_id prid,#(lf)                  advur.fn_get_fytd_fiscalyear(TO_CHAR(trunc(xprp.stop_date), 'MM/DD/YYYY')) statyr#(lf)             from advance.proposal xprp#(lf)            where xprp.active_ind = 'Y'#(lf)            and   xprp.proposal_status_code NOT IN ('G','I')#(lf)          )actprp ON p.prospect_id = actprp.prid#(lf)left join (                                        -- Completed proposals in the past year (12 months)#(lf)           select distinct xprp2.prospect_id prid,#(lf)                  advur.fn_get_fytd_fiscalyear(TO_CHAR(trunc(xprp2.stop_date), 'MM/DD/YYYY')) statyr#(lf)             from advance.proposal xprp2#(lf)            where xprp2.active_ind <> 'Y'#(lf)            and   xprp2.proposal_status_code = 'C'#(lf)            and   trunc(xprp2.stop_date) BETWEEN trunc(sysdate)-365 AND trunc(sysdate)#(lf)            )cprp ON p.prospect_id = cprp.prid#(lf)inner join (                                       -- Calculates Days in Current Stage#(lf)            select distinct p.prospect_id prid, ts.short_desc Stage, mxdt.dt Stage_Dt,#(lf)                   (trunc(sysdate) - mxdt.dt) daysin, ts.hierarchy_order srt#(lf)              from advance.prospect p#(lf)             inner join advance.stage s      ON p.prospect_id = s.prospect_id#(lf)              left join advance.tms_stage ts ON p.stage_code = ts.stage_code#(lf)             inner join (#(lf)                         select xs.prospect_id prid, MAX(trunc(xs.stage_date)) dt#(lf)                           from advance.stage xs#(lf)                          group by xs.prospect_id#(lf)                         )mxdt ON p.prospect_id = mxdt.prid#(lf)             where p.active_ind = 'Y'#(lf)            )stgdays ON p.prospect_id = stgdays.prid#(lf)left join (                                        -- Active Pledges#(lf)           select distinct xte3.donor_id did, count(distinct xpp3.prim_pledge_number) cnt, sum(xpp3.prim_pledge_amount) ttl#(lf)             from advance.primary_pledge xpp3#(lf)            inner join advur.mvw_trans_entities xte3 ON xpp3.prim_pledge_number = xte3.trans_nbr#(lf)            where xpp3.prim_pledge_amount > 0#(lf)            and   xpp3.prim_pledge_type NOT IN ('BE','RE')#(lf)            and   xpp3.prim_pledge_status = 'A'#(lf)            group by xte3.donor_id#(lf)            )actplg ON pe.id_number = actplg.did#(lf)left join (                                        -- Primary Managers#(lf)           select asmt.prospect_id pid, pe.id_number eid, s.id_number goid, s.name gonme, #(lf)                  trunc(asmt.start_date) strt, u.short_desc grp, s.sort gosrt, u.hierarchy_order gsrt#(lf)             from advance.staff s#(lf)            inner join advance.assignment asmt    ON s.id_number = asmt.assignment_id_number#(lf)             left join advance.tms_unit_code u    ON s.unit_code = u.unit_code#(lf)             left join advance.prospect_entity pe ON asmt.prospect_id = pe.prospect_id#(lf)            where asmt.assignment_type = 'PM'#(lf)            and   asmt.active_ind = 'Y'#(lf)            and   asmt.stop_date IS NULL#(lf)            )pm ON p.prospect_id = pm.pid#(lf)#(lf)where pe.primary_ind = 'Y' #(lf)and   p.active_ind = 'Y'#(lf)and   p.prospect_id NOT IN (13821,19870,20624)#(lf)#(lf)group by pe.id_number, hk.household_key, p.prospect_id, p.prospect_name, e.pref_mail_name, sp.pref_mail_name, stgdays.Stage, #(lf)         stgdays.daysin, pm.goid, pm.strt, pm.grp, (trunc(sysdate) - pm.strt), nvl(actplg.cnt,0), nvl(actplg.ttl,0),#(lf)         CASE WHEN r.af_evi = 'N/A' THEN '0'#(lf)            ELSE nvl(r.af_evi,'0') END,#(lf)         CASE WHEN r.af_pdi_score = 'N/A' THEN '0'#(lf)            ELSE nvl(r.af_pdi_score,'0') END,#(lf)         CASE WHEN r.af_pdi_score = 'N/A' THEN '0'#(lf)            ELSE nvl(r.mg_evi,'0') END, r.mg_capacity, #(lf)         r.target_gift_range, r.campaign_gift_range, r.campaign_potential, r.affinity_rating,#(lf)         r.reeher_net_worth, r.six_square_segment, r.alumni_engagement_score, nvl(cfy.ttl,0), nvl(pfy.ttl,0),#(lf)         CASE WHEN nvl(cfy.ttl,0) > 0 THEN 'CFY Donor'#(lf)            ELSE 'Non-Donor CFY' END,#(lf)         CASE WHEN nvl(cfy.ttl,0) >= nvl(pfy.ttl,0) THEN 1#(lf)            ELSE 0 END,#(lf)         CASE WHEN nvl(cfy.ttl,0) < nvl(pfy.ttl,0) THEN 1#(lf)            ELSE 0 END,#(lf)         CASE WHEN nvl(actprp.prid,0) > 0 THEN 1        -- AND exstprp.statyr = advur.fn_get_fytd_fiscalyear(TO_CHAR(SYSDATE, 'MM/DD/YYYY'))#(lf)          ELSE 0 END,#(lf)--         CASE WHEN nvl(exstprp.currval,0) > 0 AND exstprp.statyr = advur.fn_get_fytd_fiscalyear(TO_CHAR(SYSDATE, 'MM/DD/YYYY')) THEN 1#(lf)--            ELSE 0 END,#(lf)         CASE WHEN nvl(cprp.prid,0) > 0 THEN 1#(lf)            ELSE 0 END, nvl(r.target_gift_range_code,'ZZ999'), nvl(r.campaign_gift_range_code,'ZZ999'),#(lf)         CASE WHEN r.campaign_potential_code = '0' THEN 'ZZ'#(lf)            ELSE nvl(r.campaign_potential_code,'ZZ') END, nvl(r.affinity_rating_code,'Z9'),#(lf)         CASE WHEN nvl(cprp.prid,0) > 0 THEN 'Recent Completed Proposal'#(lf)              WHEN nvl(actprp.prid,0) > 0 AND actprp.statyr < advur.fn_get_fytd_fiscalyear(TO_CHAR(SYSDATE, 'MM/DD/YYYY')) THEN 'Has Prior Year Proposal'#(lf)              WHEN nvl(actprp.prid,0) > 0 AND actprp.statyr = advur.fn_get_fytd_fiscalyear(TO_CHAR(SYSDATE, 'MM/DD/YYYY')) THEN 'Has Current Year Proposal'#(lf)              WHEN nvl(actprp.prid,0) > 0 AND actprp.statyr > advur.fn_get_fytd_fiscalyear(TO_CHAR(SYSDATE, 'MM/DD/YYYY')) THEN 'Has Future Year Proposal'#(lf)            ELSE 'No Active Proposal' END,#(lf)         CASE WHEN r.rnw_code = 'R013' THEN '100'#(lf)              WHEN r.rnw_code = 'R012' THEN '150'#(lf)              WHEN r.rnw_code = 'R011' THEN '200'#(lf)              WHEN r.rnw_code = 'R009' THEN '250'#(lf)              WHEN r.rnw_code = 'R02' THEN '300'#(lf)              WHEN r.rnw_code = 'R03' THEN '350'#(lf)              WHEN r.rnw_code = 'R04' THEN '400'#(lf)              WHEN r.rnw_code = 'R05' THEN '450'#(lf)              WHEN r.rnw_code = 'R06' THEN '500'#(lf)              WHEN r.rnw_code = 'R010' THEN '550'#(lf)              WHEN r.rnw_code = 'UN' THEN '899'#(lf)              WHEN r.rnw_code = 'R12' THEN '900'#(lf)              WHEN r.rnw_code = '0' THEN '905'#(lf)            ELSE nvl(r.rnw_code,'999') END, stgdays.srt, pm.gosrt, pm.gsrt\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Days In Stage\", Int64.Type}, {\"PM Start Dt\", type date}, {\"Days Assgnd\", Int64.Type}, {\"Act Plg Count\", Int64.Type}, {\"Act Plg Total\", Int64.Type}, {\"MG EVI\", Int64.Type}, {\"AF PDI\", Int64.Type}, {\"AF EVI\", Int64.Type}, {\"MG Capacity\", Currency.Type}, {\"Alumni Engagement Score\", Int64.Type}, {\"CFY Prod\", Currency.Type}, {\"PFY Prod\", Currency.Type}, {\"Increase?\", Int64.Type}, {\"Decrease?\", Int64.Type}, {\"Act Proposal?\", Int64.Type}, {\"Rec Proposal?\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Key Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "5abd78b3-b1bf-413e-bb6b-76611bbb02d2",
        "measures": [
          {
            "name": "Today",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    TODAY()"
            ],
            "formatString": "Short Date",
            "lineageTag": "86984c92-fa23-4751-88d9-7a4b6fb23d78"
          },
          {
            "name": "Today + 30",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    TODAY()+30"
            ],
            "formatString": "Short Date",
            "lineageTag": "6a5ec91b-3476-47b6-9947-3ad7519bf360"
          },
          {
            "name": "Current Year",
            "expression": [
              "",
              "    MAX( 'Current FY'[CFY] )"
            ],
            "lineageTag": "19d16301-2551-4fb1-af40-9d73477347f3"
          },
          {
            "name": "Proposal Page Title",
            "expression": [
              "",
              "    \"Proposals - \" & [Current Year]"
            ],
            "lineageTag": "c070ee73-21f1-449b-9a0d-6d514731286b"
          },
          {
            "name": "Unassigned Prospect Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _UnProsCnt = CALCULATE(",
              "                        DISTINCTCOUNTNOBLANK( 'Prospects and Scores'[Prospect ID] ),",
              "                        ISBLANK('Prospects and Scores'[PM ID] ) )",
              "   return",
              "   IF(ISBLANK(_UnProsCnt),0,_UnProsCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "de2d1fd2-f5bf-4006-b5c0-1f5310fd7ab0"
          },
          {
            "name": "Top 5 CFY Donors",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE( [Prospect CFY Total],",
              "    TOPN(10, ",
              "        'Prospects and Scores', ",
              "        'Prospects and Scores'[Entity ID],",
              "        DESC))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6aff6339-2d41-4747-af34-9e8f49a9bdef"
          },
          {
            "name": "Active Proposal Statement",
            "expression": [
              "",
              "    var _Prop = MAX( 'Prospects and Scores'[Act Proposal?] )",
              "    var _PropIs = CALCULATE( IF( _Prop = 1, \"Active Proposal\", \"No Active Proposal\")",
              "                    )",
              "   return",
              "   IF(ISBLANK(_PropIs), \"No Active Proposal\",_PropIs)"
            ],
            "lineageTag": "9032eb6b-5f9c-4ff8-beea-ad86be730d32"
          },
          {
            "name": "Donor Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    DISTINCTCOUNT( 'Prospects and Scores'[Entity ID] )"
            ],
            "formatString": "#,0",
            "lineageTag": "9bafefd8-7b24-425e-bce9-e0d33cd51140"
          },
          {
            "name": "Unassigned Prospect CFY Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _UnProsTtl = CALCULATE(",
              "                        SUMX( 'Prospects and Scores', 'Prospects and Scores'[CFY Prod] ),",
              "                        ISBLANK( 'Prospects and Scores'[PM ID] )",
              "    )",
              "   return",
              "   IF(ISBLANK(_UnProsTtl),0,_UnProsTtl)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d83efd06-eec8-43cb-b9d1-ad9141ad1707"
          },
          {
            "name": "Household CFY Prod Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _CFY = [Current Year]",
              "    var _HHTtl = CALCULATE(",
              "                    SUMX( 'Household Giving', 'Household Giving'[Trans Amt] ),",
              "                        'Household Giving'[Fiscal Yr] = _CFY,",
              "                        USERELATIONSHIP( 'Household Giving'[Household Key], 'Prospects and Scores'[HH Key] )",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_HHTtl),0,_HHTtl)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "3fa21279-f540-461e-9e90-062917102f59"
          },
          {
            "name": "CFY Donor Statement",
            "expression": [
              "",
              "    var _CFYDnr = CALCULATE( IF( [Prospect CFY Total] > 0, \"CFY Donor\", \"Non-Donor CFY\")",
              "                    )",
              "   return",
              "   IF(ISBLANK(_CFYDnr), \"Non-Donor CFY\",_CFYDnr)"
            ],
            "lineageTag": "11958beb-4f60-4c07-a003-e857f230fd8d"
          },
          {
            "name": "CFY Move CRs Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _CFY = [Current Year]",
              "    var _MvCRCnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Contact Reports'[Report ID] ),",
              "                    'Contact Reports'[Contact FY] = _CFY && ",
              "                    'Contact Reports'[Contact Purpose] IN {\"Qualification\",\"Cultivation\",\"Solicitation\",\"Follow Up on Solicitation\",\"Close Solicitation\"} )",
              "return",
              "IF(ISBLANK(_MvCRCnt),0,_MvCRCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "cb99a814-9f57-4f66-b25d-a91abb555eb6"
          },
          {
            "name": "CFY Move Participation",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    [Prospects w/CFY Move CRs Count] / [Assigned Prospect Count]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "14efae74-9724-4cc4-86a4-902b415d78d9"
          },
          {
            "name": "Proposal Target Penetration",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    [Assigned Prospect Count w/Proposal] / [Prospect Donor Target]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "32d3ad50-7b00-473a-8496-882974a281f5"
          },
          {
            "name": "CFY Target Move Participation",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    [Prospects w/CFY Move CRs Count] / [Prospect Donor Target]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f971f7f7-767b-4b20-87ea-6b3f236d27e6"
          },
          {
            "name": "Current Day",
            "expression": [
              "",
              "    TODAY()"
            ],
            "formatString": "Short Date",
            "lineageTag": "36ad42e7-6cf5-4e76-b0bd-2097766b399c"
          },
          {
            "name": "Unassigned Prospect CFY Donor Count",
            "expression": [
              "",
              "    var _UnProsDnrCnt = CALCULATE(",
              "                        DISTINCTCOUNTNOBLANK( 'Prospects and Scores'[Prospect ID] ),",
              "                        ISBLANK('Prospects and Scores'[PM ID] ),",
              "                        'Prospects and Scores'[CFY Prod] > 0 )",
              "   return",
              "   IF(ISBLANK(_UnProsDnrCnt),0,_UnProsDnrCnt)"
            ],
            "formatString": "0",
            "lineageTag": "c29e8ef4-a5ca-4a6f-8a22-f2f5930c08e7"
          },
          {
            "name": "Unassigned Participation",
            "expression": [
              "",
              "    CALCULATE(",
              "        IF( [Unassigned Prospect Count] = 0,0, [Unassigned Prospect CFY Donor Count] / [Unassigned Prospect Count] )",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "08cbb0a9-44f0-4628-9eb1-03219d9b3b2c"
          },
          {
            "name": "Assigned Participation",
            "expression": [
              "",
              "    [Assigned Prospect CFY Prod Donor Count] / [Assigned Prospect Count]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ab6fb8cf-f26a-47ac-8513-b1fd1638799a"
          },
          {
            "name": "Total Prospects",
            "expression": [
              "",
              "    [Assigned Prospect Count] + [Unassigned Prospect Count]"
            ],
            "formatString": "0",
            "lineageTag": "3bd9719c-a4b1-4e9a-bdcf-66c5be70a54a"
          },
          {
            "name": "Assigned Prospects w-Proposal Count",
            "expression": [
              "",
              "    var _AsnProsPropCnt = CALCULATE(",
              "                    DISTINCTCOUNTNOBLANK( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[PM ID] > \" \",",
              "                    'Prospects and Scores'[Act Proposal?] = 1 )",
              "   return",
              "   IF(ISBLANK(_AsnProsPropCnt),0,_AsnProsPropCnt)"
            ],
            "formatString": "0",
            "lineageTag": "622d17ed-68bb-451f-8a74-97ff754f6a7a"
          },
          {
            "name": "Proposal Count",
            "expression": [
              "",
              "    var _PropCnt = ",
              "    CALCULATE( ",
              "        SUMX( 'Prospects and Scores', 'Prospects and Scores'[Act Proposal?] )",
              "    )",
              "return",
              "IF(ISBLANK( _PropCnt),0,_PropCnt )"
            ],
            "formatString": "0",
            "lineageTag": "5c6fe942-a99d-42e3-90e9-52a4371b5a4b"
          },
          {
            "name": "Previous Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    MAX( 'Current FY'[CFY] )-1"
            ],
            "lineageTag": "8a8d1dd1-e950-438a-8a73-33fa1ed55fbc"
          },
          {
            "name": "CFY CRs Count",
            "expression": [
              "",
              "    var _CFY = [Current Year]",
              "    var _CRCnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Contact Reports'[Report ID] ),",
              "                    'Contact Reports'[Contact FY] = _CFY,",
              "                    USERELATIONSHIP( 'Contact Reports'[GO Unique Key], 'Primary Managers'[GO Unique Key] )",
              "                    )",
              "return",
              "IF(ISBLANK(_CRCnt),0,_CRCnt)"
            ],
            "formatString": "0",
            "lineageTag": "0e5e0f24-047d-4cd6-ab10-f1582f8934aa"
          }
        ],
        "partitions": [
          {
            "name": "Key Measures-e40670d6-b115-4ae9-a826-b6499a57dc3b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Pledge Pymts Due",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Trans Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36c564e0-5840-469c-a2b0-85591fdf82cd",
            "sourceColumn": "Trans Type",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f03e0f2a-9292-4971-be39-21024544018a",
            "sourceColumn": "Trans Category",
            "summarizeBy": "none"
          },
          {
            "name": "Pledge Nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4450186c-ade1-448d-8474-5cfe562bb0f8",
            "sourceColumn": "Pledge Nbr",
            "summarizeBy": "none"
          },
          {
            "name": "Plg Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "f7869d47-5460-4586-be68-b59e0425d319",
            "sourceColumn": "Plg Date",
            "summarizeBy": "none"
          },
          {
            "name": "Plg Camp Cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7c2fd06-cf9f-4213-867a-fc8ffa7b2a0a",
            "sourceColumn": "Plg Camp Cd",
            "summarizeBy": "none"
          },
          {
            "name": "Plg Amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6593c78f-a75f-4e2d-bbad-0241f756071c",
            "sourceColumn": "Plg Amt",
            "summarizeBy": "sum"
          },
          {
            "name": "Plg Amt Pd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "36c67dc5-a0e4-46d6-a7ce-f690bcf29e1e",
            "sourceColumn": "Plg Amt Pd",
            "summarizeBy": "sum"
          },
          {
            "name": "Plg Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "200fba87-5e63-40d7-b651-6f1592fdb678",
            "sourceColumn": "Plg Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "Donor ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d62d8eb-6cb6-465f-9c86-6aa9e1af4b87",
            "sourceColumn": "Donor ID",
            "summarizeBy": "none"
          },
          {
            "name": "Donor Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d381dba8-46ea-4e98-a4c5-b6d70a970d44",
            "sourceColumn": "Donor Name",
            "summarizeBy": "none"
          },
          {
            "name": "School",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e8224f9-2409-46f9-8362-29ce24bdd645",
            "sourceColumn": "School",
            "summarizeBy": "none"
          },
          {
            "name": "Allocation Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77fe5518-d787-462a-b817-3d510779ea51",
            "sourceColumn": "Allocation Code",
            "summarizeBy": "none"
          },
          {
            "name": "Allocation Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c773627-c959-4cfc-adc7-2f68e63c2fee",
            "sourceColumn": "Allocation Name",
            "summarizeBy": "none"
          },
          {
            "name": "Finance Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0c1bfdc-fceb-4a40-ba66-164e03472fb0",
            "sourceColumn": "Finance Category",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83eb93f7-1e6e-4eea-aa37-cb592dde5b25",
            "sourceColumn": "Campaign Bucket",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "788e442d-68e5-4e8d-962c-6cb7f35d7622",
            "sourceColumn": "Campaign Priority",
            "summarizeBy": "none"
          },
          {
            "name": "Camp Sub-Priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf3ff87f-368c-42d6-91ca-5bf074790364",
            "sourceColumn": "Camp Sub-Priority",
            "summarizeBy": "none"
          },
          {
            "name": "Goal Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc977d81-c2b6-4bdc-9a19-512830f9bf6a",
            "sourceColumn": "Goal Category",
            "summarizeBy": "none"
          },
          {
            "name": "Goal SubCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "357d9207-e39f-4c7b-b238-e9df517ba8c4",
            "sourceColumn": "Goal SubCategory",
            "summarizeBy": "none"
          },
          {
            "name": "Proposal Nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "71b381d0-c226-4238-a536-9022f584b40d",
            "sourceColumn": "Proposal Nbr",
            "summarizeBy": "sum"
          },
          {
            "name": "Solicitor ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfbe0ebf-55b8-4912-85d2-19de6025483c",
            "sourceColumn": "Solicitor ID",
            "summarizeBy": "none"
          },
          {
            "name": "Fund",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1232d3f3-63ab-4c4d-88eb-d8243472db45",
            "sourceColumn": "Fund",
            "summarizeBy": "none"
          },
          {
            "name": "Org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d745436a-23ed-4816-b5ab-99e89cfb048e",
            "sourceColumn": "Org",
            "summarizeBy": "none"
          },
          {
            "name": "Donor Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c354b536-437c-4842-804b-c509d70d9d6e",
            "sourceColumn": "Donor Sort",
            "summarizeBy": "none"
          },
          {
            "name": "Last Pymt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "637cd5e4-e748-4a8c-b429-569d5ead6e6f",
            "sourceColumn": "Last Pymt",
            "summarizeBy": "none"
          },
          {
            "name": "Days Since",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "66a72486-bb34-41cd-9c7e-e592bc1d8757",
            "sourceColumn": "Days Since",
            "summarizeBy": "sum"
          },
          {
            "name": "Pymt Cnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "0",
            "lineageTag": "64014753-26f5-448c-ad2d-20edbddc5612",
            "sourceColumn": "Pymt Cnt",
            "summarizeBy": "sum"
          },
          {
            "name": "FYs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ecd6c7a9-36fb-4a31-a723-502fb431d0b2",
            "sourceColumn": "FYs",
            "summarizeBy": "sum"
          },
          {
            "name": "Past Due",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bee0c33f-72a1-4c7d-b91e-d8fb5691faea",
            "sourceColumn": "Past Due",
            "summarizeBy": "sum"
          },
          {
            "name": "Freq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00415582-cb91-413b-8f31-b3ad7952f4a1",
            "sourceColumn": "Freq",
            "summarizeBy": "none"
          },
          {
            "name": "Max Pd Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5f4db1ad-e215-4460-9204-222812fb730c",
            "sourceColumn": "Max Pd Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Min Unpaid Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c6a14efa-b6ec-4c94-88a1-ee64e047f3d4",
            "sourceColumn": "Min Unpaid Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Days 2 Pymt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6c1009a9-c7ca-414e-a9b8-e3e7a723f02a",
            "sourceColumn": "Days 2 Pymt",
            "summarizeBy": "sum"
          },
          {
            "name": "Btwn Due Dts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f8c54f1-c97b-4f6f-91c1-74f07c1d4529",
            "sourceColumn": "Btwn Due Dts",
            "summarizeBy": "sum"
          },
          {
            "name": "Past Due Factor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ac207f8c-7143-4b77-85a9-c6910f4e82c0",
            "sourceColumn": "Past Due Factor",
            "summarizeBy": "sum"
          },
          {
            "name": "Past Due Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "569d085a-8b2a-4afc-a00a-1456366d840b",
            "sourceColumn": "Past Due Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Due 91+ Days Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "43c65086-88f8-4474-ad04-380dd0397d56",
            "sourceColumn": "Due 91+ Days Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Solicitor Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c69d89a-f999-4b13-a335-b30aba312079",
            "sourceColumn": "Solicitor Key",
            "summarizeBy": "none"
          },
          {
            "name": "Due <=30 Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9f677373-3950-425c-ba9a-01644e38b266",
            "sourceColumn": "Due <=30 Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Due <=30 Days Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "597be486-7be9-41d6-b0f9-810a13303155",
            "sourceColumn": "Due <=30 Days Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Due 31 to 60 Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "87a01e2d-834c-4580-b11c-bb3529e79c66",
            "sourceColumn": "Due 31 to 60 Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Due 31 to 60 Days Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "40b39ccc-e76e-4d19-9ef9-3880492920ad",
            "sourceColumn": "Due 31 to 60 Days Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Due 61 to 90 Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c1fa64b0-a8e5-43c3-8db5-356aaa891778",
            "sourceColumn": "Due 61 to 90 Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Due 61 to 90 Days Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "499b9b46-e7c9-4651-8b32-07cbc841b8ac",
            "sourceColumn": "Due 61 to 90 Days Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Due 91+ Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a333f34e-2e3b-4407-adfc-095508e42333",
            "sourceColumn": "Due 91+ Days",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ecdc30c3-6ed5-48bb-bc8e-ebf9e83a4c7a",
        "partitions": [
          {
            "name": "Pledge Pymts Due-21b7579d-de94-4176-ab41-c8143e844276",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(\"PADV\", [HierarchicalNavigation=true, Query=\"-- Query created for the Gift Officer Dashboard to show past due and upcoming pledge payments, with information about those payments. smk 8/22/2022#(lf)-- Updated to pull all pledge payments due instead of breaking out Past Due vs. Currently Due. smk 8/23/2022#(lf)-- Updated to accomodate error situations where a pledge payment is missing a due date.  smk 2/14/2023#(lf)-- Updated to pull counts of payments by due date ranges rather than provide details about each payment due. #(lf)--    This reduces data down to one pledge row per donor, per solicitor. smk 10/13/2023#(lf)-- Added a \"\"Solictor Key\"\" that combines the Proposal ID and the Solicitor's ID. smk 10/24/2023#(lf)#(lf)select distinct pt1.short_desc                         \"\"Trans Type\"\",#(lf)       CASE WHEN pp1.prim_pledge_type IN ('RE','BE') THEN 'Bequest Intentions'#(lf)          ELSE 'Standard Pledge' END                   \"\"Trans Category\"\",#(lf)       pp1.prim_pledge_number                          \"\"Pledge Nbr\"\",#(lf)       pp1.prim_pledge_date_of_record                  \"\"Plg Date\"\",#(lf)       CASE WHEN p1.pledge_campaign LIKE 'C7%' THEN 'Current Campaign'#(lf)          ELSE 'Non-Campaign' END                      \"\"Plg Camp Cd\"\",#(lf)       pp1.prim_pledge_amount                          \"\"Plg Amt\"\",#(lf)       pp1.prim_pledge_amount_paid                     \"\"Plg Amt Pd\"\",#(lf)       CASE WHEN (pp1.prim_pledge_amount - pp1.prim_pledge_amount_paid) < 0 THEN 0#(lf)          ELSE (pp1.prim_pledge_amount - pp1.prim_pledge_amount_paid) END \"\"Plg Balance\"\",#(lf)       cyd.pycnt                                       \"\"Pymt Cnt\"\",#(lf)       cyd.FYs                                         \"\"FYs\"\",#(lf)       nvl(pstdu.cnt,0)                                \"\"Past Due\"\",#(lf)       nvl(pstdu.ttl,0)                                \"\"Past Due Total\"\",#(lf)       nvl(duls30.cnt,0)                               \"\"Due <=30 Days\"\",#(lf)       nvl(duls30.ttl,0)                               \"\"Due <=30 Days Total\"\",#(lf)       nvl(du3160.cnt,0)                               \"\"Due 31 to 60 Days\"\",#(lf)       nvl(du3160.ttl,0)                               \"\"Due 31 to 60 Days Total\"\",#(lf)       nvl(du6190.cnt,0)                               \"\"Due 61 to 90 Days\"\",#(lf)       nvl(du6190.ttl,0)                               \"\"Due 61 to 90 Days Total\"\",#(lf)       nvl(du91pls.cnt,0)                              \"\"Due 91+ Days\"\",#(lf)       nvl(du91pls.ttl,0)                              \"\"91+ Days Total\"\",#(lf)       lst.dt                                          \"\"Last Pymt\"\",#(lf)       pp1.prim_pledge_payment_freq                    \"\"Freq\"\",#(lf)       trunc(sysdate) - lst.dt                         \"\"Days Since\"\",#(lf)       mxpd.dt                                         \"\"Max Pd Dt\"\",#(lf)       mnupd.dt                                        \"\"Min Unpaid Dt\"\",#(lf)       mnupd.dt - trunc(sysdate)                       \"\"Days 2 Pymt\"\",#(lf)       mnupd.dt - mxpd.dt                              \"\"Btwn Due Dts\"\",#(lf)       CASE WHEN pp1.prim_pledge_payment_freq = 'M' THEN round((mnupd.dt - trunc(sysdate))/30,1)#(lf)            WHEN pp1.prim_pledge_payment_freq = 'Q' THEN round((mnupd.dt - trunc(sysdate))/90,1)#(lf)            WHEN pp1.prim_pledge_payment_freq = 'A' THEN round((mnupd.dt - trunc(sysdate))/365,1)#(lf)            WHEN pp1.prim_pledge_payment_freq = 'C' THEN round((mnupd.dt - trunc(sysdate))/(mnupd.dt - mxpd.dt),1)#(lf)          ELSE 0 END                                   \"\"Past Due Factor\"\",#(lf)       dnr.did                                         \"\"Donor ID\"\",#(lf)       dnr.nme                                         \"\"Donor Name\"\",#(lf)       allc.sch                                        \"\"School\"\",#(lf)       allc.cd                                         \"\"Allocation Code\"\",#(lf)       allc.nme                                        \"\"Allocation Name\"\",#(lf)       allc.purp                                       \"\"Finance Category\"\",#(lf)       allc.c1                                         \"\"Campaign Bucket\"\",#(lf)       allc.c2                                         \"\"Campaign Priority\"\",#(lf)       allc.c3                                         \"\"Camp Sub-Priority\"\",#(lf)       allc.gc                                         \"\"Goal Category\"\",#(lf)       allc.gsc                                        \"\"Goal SubCategory\"\",#(lf)       pp1.proposal_id                                 \"\"Proposal Nbr\"\",#(lf)       sol.psid                                        \"\"Solicitor ID\"\",#(lf)       pp1.proposal_id||sol.psid                       \"\"Solicitor Key\"\",#(lf)       substr(allc.acct,1,6)                           \"\"Fund\"\",#(lf)       substr(allc.acct,7,6)                           \"\"Org\"\",#(lf)       dnr.srt                                         \"\"Donor Sort\"\"#(lf)from advance.primary_pledge pp1#(lf)inner join advance.pledge p1           ON pp1.prim_pledge_number = p1.pledge_pledge_number#(lf)inner join advance.tms_pledge_type pt1 ON pp1.prim_pledge_type = pt1.pledge_type_code#(lf)inner join (#(lf)           select xp1.pledge_pledge_number pnbr, xe1.id_number did, xe1.pref_mail_name nme, xe1.pref_name_sort srt#(lf)             from advance.pledge xp1, advance.entity xe1#(lf)            where xp1.pledge_associated_code = 'P'#(lf)            and   xp1.pledge_donor_id = xe1.id_number#(lf)            )dnr ON pp1.prim_pledge_number = dnr.pnbr#(lf)inner join (#(lf)           select xxp1.pledge_pledge_number pnbr, xxsch.short_desc sch, xxa1.long_name nme, cat1.short_desc c1, xxa1.alloc_purpose prp,#(lf)                  cat2.short_desc c2, cat3.short_desc c3, tmsp.short_desc purp, xxa1.allocation_code cd, xxa1.account acct,#(lf)                  ep.short_desc gc, et.short_desc gsc#(lf)             from advance.pledge xxp1#(lf)            inner join advance.allocation xxa1       ON xxp1.pledge_allocation_name = xxa1.allocation_code#(lf)            left join advance.tms_alloc_school xxsch ON xxa1.alloc_school = xxsch.alloc_school_code#(lf)            left join advance.tms_purpose tmsp       ON xxa1.alloc_purpose = tmsp.purpose_code#(lf)            left join advance.tms_category1 cat1     ON xxa1.category1_code = cat1.category1_code#(lf)            left join advance.tms_category2 cat2     ON xxa1.category2_code = cat2.category2_code#(lf)            left join advance.tms_category3 cat3     ON xxa1.category3_code = cat3.category3_code#(lf)            left join advance.tms_endow_pool ep      ON xxa1.endow_pool_code = ep.endow_pool#(lf)            left join advance.tms_endow_type et      ON xxa1.endow_type_code = et.endow_type#(lf)            )allc ON pp1.prim_pledge_number = allc.pnbr#(lf)left join (#(lf)            select xp10.proposal_id prid, xa10.assignment_id_number psid#(lf)              from advance.proposal xp10#(lf)             inner join advance.assignment xa10 ON xp10.proposal_id = xa10.proposal_id#(lf)             inner join advance.staff xs10      ON xa10.assignment_id_number = xs10.id_number#(lf)             inner join advance.tms_unit_code u ON xs10.unit_code = u.unit_code#(lf)             where xa10.assignment_type = 'PS'#(lf)            )sol ON pp1.proposal_id = sol.prid#(lf)left join (#(lf)          select distinct xpp2.prim_pledge_number nbr, nvl(xet2.short_desc,'Missing Goal SubCategory') gsc,#(lf)                 count(distinct xps2.payment_schedule_date) pycnt,#(lf)                 count(distinct substr(xps2.payment_schedule_date,1,4)) FYs,#(lf)                 sum(xps2.payment_schedule_balance) bal#(lf)            from advance.payment_schedule xps2#(lf)           inner join advance.primary_pledge xpp2 ON xps2.payment_schedule_pledge_nbr = xpp2.prim_pledge_number#(lf)           inner join advance.pledge xp2          ON xpp2.prim_pledge_number = xp2.pledge_pledge_number#(lf)           inner join advance.allocation xa2      ON xp2.pledge_allocation_name = xa2.allocation_code --AND xa2.category1_code = 'CST'#(lf)           left join advance.tms_endow_type xet2  ON xa2.endow_type_code = xet2.endow_type#(lf)           where xpp2.prim_pledge_status = 'A'#(lf)           and   xpp2.prim_pledge_type NOT IN ('AO','PO','E1','P1','L2')#(lf)           and   xps2.payment_schedule_status = 'U'#(lf)           group by xpp2.prim_pledge_number, nvl(xet2.short_desc,'Missing Goal SubCategory')#(lf)           )cyd ON pp1.prim_pledge_number = cyd.nbr#(lf)left join (#(lf)           select distinct xpp3.prim_pledge_number nbr,#(lf)                  ' Past Due'  duecat,#(lf)                  count(distinct xps3.payment_schedule_date) cnt,#(lf)                  sum(xps3.payment_schedule_balance) ttl#(lf)             from advance.payment_schedule xps3#(lf)            inner join advance.primary_pledge xpp3 ON xps3.payment_schedule_pledge_nbr = xpp3.prim_pledge_number#(lf)            where xpp3.prim_pledge_status = 'A'#(lf)            and   xpp3.prim_pledge_type NOT IN ('AO','PO','E1','P1','L2')#(lf)            and   xps3.payment_schedule_status = 'U'#(lf)            and   xps3.payment_schedule_date <> '00000000'#(lf)            and   substr(xps3.payment_schedule_date,1,4) <> '0000'#(lf)            and   substr(xps3.payment_schedule_date,5,2) <> '00'#(lf)            and   substr(xps3.payment_schedule_date,7,2) <> '00'#(lf)            and   to_date(xps3.payment_schedule_date,'YYYYMMDD') < trunc(sysdate)#(lf)            group by xpp3.prim_pledge_number, CHR(32)#(lf)            )pstdu ON pp1.prim_pledge_number = pstdu.nbr#(lf)left join (#(lf)           select distinct xpp4.prim_pledge_number nbr,#(lf)                  '30 Days or Less'  duecat,#(lf)                  count(distinct xps4.payment_schedule_date) cnt,#(lf)                  sum(xps4.payment_schedule_balance) ttl#(lf)             from advance.payment_schedule xps4#(lf)            inner join advance.primary_pledge xpp4 ON xps4.payment_schedule_pledge_nbr = xpp4.prim_pledge_number#(lf)            where xpp4.prim_pledge_status = 'A'#(lf)            and   xpp4.prim_pledge_type NOT IN ('AO','PO','E1','P1','L2')#(lf)            and   xps4.payment_schedule_status = 'U'#(lf)            and   xps4.payment_schedule_date <> '00000000'#(lf)            and   substr(xps4.payment_schedule_date,1,4) <> '0000'#(lf)            and   substr(xps4.payment_schedule_date,5,2) <> '00'#(lf)            and   substr(xps4.payment_schedule_date,7,2) <> '00'#(lf)            and   to_date(xps4.payment_schedule_date,'YYYYMMDD') BETWEEN trunc(sysdate) AND trunc(sysdate)+30#(lf)            group by xpp4.prim_pledge_number, CHR(32)#(lf)            )duls30 ON pp1.prim_pledge_number = duls30.nbr#(lf)left join (#(lf)           select distinct xpp5.prim_pledge_number nbr,#(lf)                  '31 to 60 Days'  duecat,#(lf)                  count(distinct xps5.payment_schedule_date) cnt,#(lf)                  sum(xps5.payment_schedule_balance) ttl#(lf)             from advance.payment_schedule xps5#(lf)            inner join advance.primary_pledge xpp5 ON xps5.payment_schedule_pledge_nbr = xpp5.prim_pledge_number#(lf)            where xpp5.prim_pledge_status = 'A'#(lf)            and   xpp5.prim_pledge_type NOT IN ('AO','PO','E1','P1','L2')#(lf)            and   xps5.payment_schedule_status = 'U'#(lf)            and   xps5.payment_schedule_date <> '00000000'#(lf)            and   substr(xps5.payment_schedule_date,1,4) <> '0000'#(lf)            and   substr(xps5.payment_schedule_date,5,2) <> '00'#(lf)            and   substr(xps5.payment_schedule_date,7,2) <> '00'#(lf)            and   to_date(xps5.payment_schedule_date,'YYYYMMDD') BETWEEN trunc(sysdate)+31 AND trunc(sysdate)+60#(lf)            group by xpp5.prim_pledge_number, CHR(32)#(lf)            )du3160 ON pp1.prim_pledge_number = du3160.nbr#(lf)left join (#(lf)           select distinct xpp6.prim_pledge_number nbr,#(lf)                  '61 to 90 Days'  duecat,#(lf)                  count(distinct xps6.payment_schedule_date) cnt,#(lf)                  sum(xps6.payment_schedule_balance) ttl#(lf)             from advance.payment_schedule xps6#(lf)            inner join advance.primary_pledge xpp6 ON xps6.payment_schedule_pledge_nbr = xpp6.prim_pledge_number#(lf)            where xpp6.prim_pledge_status = 'A'#(lf)            and   xpp6.prim_pledge_type NOT IN ('AO','PO','E1','P1','L2')#(lf)            and   xps6.payment_schedule_status = 'U'#(lf)            and   xps6.payment_schedule_date <> '00000000'#(lf)            and   substr(xps6.payment_schedule_date,1,4) <> '0000'#(lf)            and   substr(xps6.payment_schedule_date,5,2) <> '00'#(lf)            and   substr(xps6.payment_schedule_date,7,2) <> '00'#(lf)            and   to_date(xps6.payment_schedule_date,'YYYYMMDD') BETWEEN trunc(sysdate)+61 AND trunc(sysdate)+90#(lf)            group by xpp6.prim_pledge_number, CHR(32)#(lf)            )du6190 ON pp1.prim_pledge_number = du6190.nbr#(lf)left join (#(lf)           select distinct xpp7.prim_pledge_number nbr,#(lf)                  '91+ Days'  duecat,#(lf)                  count(distinct xps7.payment_schedule_date) cnt,#(lf)                  sum(xps7.payment_schedule_balance) ttl#(lf)             from advance.payment_schedule xps7#(lf)            inner join advance.primary_pledge xpp7 ON xps7.payment_schedule_pledge_nbr = xpp7.prim_pledge_number#(lf)            where xpp7.prim_pledge_status = 'A'#(lf)            and   xpp7.prim_pledge_type NOT IN ('AO','PO','E1','P1','L2')#(lf)            and   xps7.payment_schedule_status = 'U'#(lf)            and   xps7.payment_schedule_date <> '00000000'#(lf)            and   substr(xps7.payment_schedule_date,1,4) <> '0000'#(lf)            and   substr(xps7.payment_schedule_date,5,2) <> '00'#(lf)            and   substr(xps7.payment_schedule_date,7,2) <> '00'#(lf)            and   to_date(xps7.payment_schedule_date,'YYYYMMDD') > trunc(sysdate)+90#(lf)            group by xpp7.prim_pledge_number, CHR(32)#(lf)            )du91pls ON pp1.prim_pledge_number = du91pls.nbr#(lf) left join (#(lf)            select xpg.prim_gift_pledge_number pnbr,#(lf)                   max(trunc(xpg.prim_gift_date_of_record)) dt#(lf)              from advance.primary_gift xpg#(lf)             where xpg.prim_gift_pledge_number > ' '#(lf)             group by xpg.prim_gift_pledge_number#(lf)            )lst ON pp1.prim_pledge_number = lst.pnbr#(lf) left join (#(lf)            select xps3.payment_schedule_pledge_nbr pnbr,#(lf)                   max(trunc(to_date(xps3.payment_schedule_date,'YYYYMMDD'))) dt#(lf)              from advance.payment_schedule xps3#(lf)             inner join advance.primary_pledge xpp3 ON xps3.payment_schedule_pledge_nbr = xpp3.prim_pledge_number#(lf)             where xps3.payment_schedule_status = 'P'#(lf)             and   xpp3.prim_pledge_type NOT IN ('AO','E1','L2','P1','PO')#(lf)             and   xpp3.prim_pledge_status = 'A'#(lf)             and   xpp3.prim_pledge_type NOT IN ('AO','E1','L2','P1','PO')#(lf)             and   substr(xps3.payment_schedule_date,1,4) <> '0000'#(lf)             and   substr(xps3.payment_schedule_date,5,2) <> '00'#(lf)             and   substr(xps3.payment_schedule_date,7,2) <> '00'#(lf)             group by xps3.payment_schedule_pledge_nbr#(lf)            )mxpd ON pp1.prim_pledge_number = mxpd.pnbr#(lf) left join (#(lf)            select xps4.payment_schedule_pledge_nbr pnbr,#(lf)                   min(trunc(to_date(xps4.payment_schedule_date,'YYYYMMDD'))) dt#(lf)              from advance.payment_schedule xps4#(lf)             inner join advance.primary_pledge xpp4 ON xps4.payment_schedule_pledge_nbr = xpp4.prim_pledge_number#(lf)             where xps4.payment_schedule_status = 'U'#(lf)             and   xpp4.prim_pledge_status = 'A'#(lf)             and   xpp4.prim_pledge_type NOT IN ('AO','E1','L2','P1','PO')#(lf)             and   substr(xps4.payment_schedule_date,1,4) <> '0000'#(lf)             and   substr(xps4.payment_schedule_date,5,2) <> '00'#(lf)             and   substr(xps4.payment_schedule_date,7,2) <> '00'#(lf)             group by xps4.payment_schedule_pledge_nbr#(lf)            )mnupd ON pp1.prim_pledge_number = mnupd.pnbr#(lf)#(lf)where pp1.prim_pledge_status = 'A'#(lf)and   pp1.prim_pledge_type NOT IN ('AO','E1','P1','L2','PO')#(lf)#(lf)order by \"\"Solicitor ID\"\", \"\"Allocation Name\"\", \"\"Trans Type\"\", \"\"Donor Sort\"\"\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Plg Date\", type date}, {\"Plg Amt\", Currency.Type}, {\"Plg Amt Pd\", Currency.Type}, {\"Plg Balance\", Currency.Type}, {\"Pymt Cnt\", Currency.Type}, {\"FYs\", Int64.Type}, {\"Past Due\", Int64.Type}, {\"Past Due Total\", Currency.Type}, {\"Due <=30 Days\", Int64.Type}, {\"Due <=30 Days Total\", Currency.Type}, {\"Due 31 to 60 Days\", Int64.Type}, {\"Due 31 to 60 Days Total\", Currency.Type}, {\"Due 61 to 90 Days\", Int64.Type}, {\"Due 61 to 90 Days Total\", Currency.Type}, {\"Due 91+ Days\", Int64.Type}, {\"91+ Days Total\", Currency.Type}, {\"Last Pymt\", type date}, {\"Days Since\", Int64.Type}, {\"Max Pd Dt\", type date}, {\"Min Unpaid Dt\", type date}, {\"Days 2 Pymt\", Int64.Type}, {\"Btwn Due Dts\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"91+ Days Total\", \"Due 91+ Days Total\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Proposal Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "90019b5a-2e94-4588-9bb6-215d2e96a8b5",
        "measures": [
          {
            "name": "CFY Asked Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _CFY = MAX( 'Current FY'[CFY] )",
              "    var _AskCnt = CALCULATE(",
              "                    DISTINCTCOUNT( Proposals[Proposal ID] ),",
              "                    Proposals[Ask Yr] = _CFY && Proposals[Proposal Status] IN {\"Asked, Awaiting Response\",\"Response Pending\"}",
              "                        )",
              "   return",
              "   IF(ISBLANK(_AskCnt),0,_AskCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "ac05bc66-cc92-4862-880c-8af0eba276f9"
          },
          {
            "name": "CFY PD Asked Count",
            "expression": [
              "",
              "    var _Today = TODAY()",
              "    var _CFY = MAX( 'Current FY'[CFY] )",
              "    var _AskPDCnt = CALCULATE(",
              "                    DISTINCTCOUNT( Proposals[Proposal ID] ),",
              "                    Proposals[Ask Yr] = _CFY && Proposals[Proposal Status] IN {\"Asked, Awaiting Response\",\"Response Pending\"} && Proposals[Expected Date] < _Today",
              "                        )",
              "   return",
              "   IF(ISBLANK(_AskPDCnt),0,_AskPDCnt)"
            ],
            "formatString": "0",
            "lineageTag": "daf2ad2f-121a-4611-8a59-3407a6909e5a"
          },
          {
            "name": "CFY Asked Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _CFY = MAX( 'Current FY'[CFY] )",
              "    var _AskTtl = CALCULATE(",
              "                    SUMX( Proposals, Proposals[Current Value] ),",
              "                    Proposals[Ask Yr] = _CFY && Proposals[Proposal Status] IN {\"Asked, Awaiting Response\",\"Response Pending\"}",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_AskTtl),0,_AskTtl)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6664573e-f5ea-4425-853b-b8c81f14c4bc"
          },
          {
            "name": "CFY Expected Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _CFY = MAX( 'Current FY'[CFY] )",
              "    var _ExpCnt = CALCULATE(",
              "                    DISTINCTCOUNT( Proposals[Proposal ID] ),",
              "                    Proposals[Expected Yr] = _CFY && Proposals[Proposal Status] = \"Asked, Verbal Response\"",
              "                        )",
              "   return",
              "   IF(ISBLANK(_ExpCnt),0,_ExpCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "34a81b36-75f2-42d2-9752-f5fa0c05bde7"
          },
          {
            "name": "CFY Granted Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _CFY = [Current Year] // MAX( 'Current FY'[CFY] )",
              "    var _GrantCnt = CALCULATE(",
              "                    DISTINCTCOUNTNOBLANK( Proposals[Proposal ID] ),",
              "                    Proposals[Granted Yr] = _CFY,",
              "                    Proposals[Proposal Status] = \"Granted\"",
              "                        )",
              "   return",
              "   IF(ISBLANK(_GrantCnt),0,_GrantCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "1cc5e458-4127-4ddd-bbea-72fdf4c1a1d2"
          },
          {
            "name": "CFY Granted Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _CFY = MAX( 'Current FY'[CFY] )",
              "    var _DnrTtl = CALCULATE(",
              "                    SUMX( Proposals, Proposals[Current Value] ),",
              "                    Proposals[Granted Yr] = _CFY && Proposals[Proposal Status] = \"Granted\"",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_DnrTtl),0,_DnrTtl)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ccc40d5c-4153-4b18-90fa-cdc51ccf2c46"
          },
          {
            "name": "CFY Planned Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _CFY = [Current Year]",
              "    var _PlanCnt = CALCULATE(",
              "                    DISTINCTCOUNT( Proposals[Proposal ID] ),",
              "                    Proposals[Planned Yr] = _CFY,",
              "                    Proposals[Proposal Status] = \"Planned\"",
              "                        )",
              "   return",
              "   IF(ISBLANK(_PlanCnt),0,_PlanCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "64070a25-fc39-4171-9682-681e2785a05b"
          },
          {
            "name": "CFY PD Planned Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _Today = TODAY()",
              "    var _CFY = MAX( 'Current FY'[CFY] )",
              "    var _PlnPDTtl = CALCULATE(",
              "                    SUMX( Proposals, Proposals[Current Value] ),",
              "                    Proposals[Planned Yr] = _CFY && Proposals[Proposal Status] = \"Planned\" && Proposals[Planned Dt] < _Today",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_PlnPDTtl),0,_PlnPDTtl)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "35c86bae-64e0-4e92-98c3-650b03da59d7"
          },
          {
            "name": "CFY Planned Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _CFY = MAX( 'Current FY'[CFY] )",
              "    var _DnrTtl = CALCULATE(",
              "                    SUMX( Proposals, Proposals[Current Value] ),",
              "                    Proposals[Planned Yr] = _CFY && Proposals[Proposal Status] = \"Planned\"",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_DnrTtl),0,_DnrTtl)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f8acd35e-ce2e-4d59-9235-f793fd54478f"
          },
          {
            "name": "CFY PD Planned Count",
            "expression": [
              "",
              "    var _Today = TODAY()",
              "    var _CFY = [Current Year]",
              "    var _PlanCnt = CALCULATE(",
              "                    DISTINCTCOUNTNOBLANK( Proposals[Proposal ID] ),",
              "                    Proposals[Planned Yr] = _CFY,",
              "                    Proposals[Proposal Status] = \"Planned\",",
              "                    Proposals[Planned Dt] < _Today",
              "                        )",
              "   return",
              "   IF(ISBLANK(_PlanCnt),0,_PlanCnt)"
            ],
            "formatString": "0",
            "lineageTag": "b8be09a0-00fa-4df5-9014-c7c584bc2172"
          },
          {
            "name": "CFY PD Asked Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _Today = TODAY()",
              "    var _CFY = MAX( 'Current FY'[CFY] )",
              "    var _AskTtl = CALCULATE(",
              "                    SUMX( Proposals, Proposals[Current Value] ),",
              "                    Proposals[Ask Yr] = _CFY && Proposals[Proposal Status] IN {\"Asked, Awaiting Response\",\"Response Pending\"} && Proposals[Expected Date] < _Today",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_AskTtl),0,_AskTtl)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f9071290-6c32-4f54-bb46-4d48235ad1a8"
          },
          {
            "name": "CFY PD Expected Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _Today = TODAY()",
              "    var _CFY = MAX( 'Current FY'[CFY] )",
              "    var _ExpTtl = CALCULATE(",
              "                    SUMX( Proposals, Proposals[Current Value] ),",
              "                    Proposals[Expected Yr] = _CFY && Proposals[Proposal Status] = \"Asked, Verbal Response\"",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_ExpTtl),0,_ExpTtl)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "0971be50-b248-490e-bed1-ba11cb175213"
          },
          {
            "name": "CFY PD Expected Count",
            "expression": [
              "",
              "    var _Today = TODAY()",
              "    var _CFY = MAX( 'Current FY'[CFY] )",
              "    var _ExpCnt = CALCULATE(",
              "                    DISTINCTCOUNT( Proposals[Proposal ID] ),",
              "                    Proposals[Expected Yr] = _CFY && Proposals[Proposal Status] = \"Asked, Verbal Response\" && Proposals[Expected Date] < _Today",
              "                        )",
              "   return",
              "   IF(ISBLANK(_ExpCnt),0,_ExpCnt)"
            ],
            "formatString": "0",
            "lineageTag": "1b3df1f0-35ba-46dc-a720-5df1d5577587"
          },
          {
            "name": "CFY Expected Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _CFY = MAX( 'Current FY'[CFY] )",
              "    var _ExpTtl = CALCULATE(",
              "                    SUMX( Proposals, Proposals[Current Value] ),",
              "                    Proposals[Expected Yr] = _CFY && Proposals[Proposal Status] = \"Asked, Verbal Response\"",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_ExpTtl),0,_ExpTtl)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "1d16f32b-bf94-460a-987e-7468c4f7c5ef"
          },
          {
            "name": "CFY Refused Count",
            "expression": [
              "",
              "    var _CFY = MAX( 'Current FY'[CFY] )",
              "    var _RefCnt = CALCULATE(",
              "                    DISTINCTCOUNT( Proposals[Proposal ID] ),",
              "                    Proposals[Ask Yr] = _CFY && Proposals[Proposal Status] = \"Refused\"",
              "                        )",
              "   return",
              "   IF(ISBLANK(_RefCnt),0,_RefCnt)"
            ],
            "formatString": "0",
            "lineageTag": "7bd6a17f-885e-4c7d-9333-d106f82a568e"
          },
          {
            "name": "CFY Refused Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _CFY = MAX( 'Current FY'[CFY] )",
              "    var _RefTtl = CALCULATE(",
              "                    SUMX( Proposals, IF( Proposals[Current Value], Proposals[Ask Amt], Proposals[Current Value] ) ),",
              "                    Proposals[Ask Yr] = _CFY && Proposals[Proposal Status] = \"Refused\"",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_RefTtl),0,_RefTtl)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c68e7ade-e3dc-432d-8d78-3407ca3d49d6"
          },
          {
            "name": "Count of CFY Granted Proposals",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _CFY = [Current Year]",
              "    var _PropGrantCnt = CALCULATE(",
              "                    DISTINCTCOUNT( Proposals[Proposal ID] ),",
              "                    Proposals[Current FY] = _CFY &&",
              "                    Proposals[Proposal Status] = \"Granted\"",
              "                    )",
              "return",
              "IF(ISBLANK(_PropGrantCnt),0,_PropGrantCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "c5d83727-1def-4260-93d5-b022e7415002"
          },
          {
            "name": "Sum of CFY Granted Proposals",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _CFY = [Current Year]    //This includes all Proposals that are Active and have a \"Current\" FY equal to the current FY",
              "    var _CFYPGrant = CALCULATE(",
              "                    SUMX( Proposals, Proposals[Granted Amt] ),",
              "                    Proposals[Current FY] = _CFY,",
              "                    Proposals[Proposal Status] = \"Granted\" )",
              "return",
              "IF(ISBLANK(_CFYPGrant),0,_CFYPGrant)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "8fe9c70b-e825-4f18-ba49-fe22a2d72661"
          },
          {
            "name": "Avg Active CFY Proposal",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        IF( [Count of CFY Proposals] = 0,0, [Sum of CFY Proposals] / [Count of CFY Proposals] )",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d1c2a5ab-835f-4677-8cd9-9451c9d2e380"
          },
          {
            "name": "Sum of CFY Pending Proposals",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _CFY = [Current Year]    //This includes all Proposals that are Active and have a \"Current\" FY equal to the current FY",
              "    var _CFYPPend = CALCULATE(",
              "                    SUMX( Proposals, Proposals[Expected Amt] ),",
              "                    Proposals[Current FY] = _CFY )",
              "return",
              "IF(ISBLANK(_CFYPPend),0,_CFYPPend)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ddf74458-30c1-4f68-9c56-931d0143c375"
          },
          {
            "name": "Sum of CFY Planned Proposals",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _CFY = [Current Year]    //This includes all Proposals that are Active and have a \"Current\" FY equal to the current FY",
              "    var _CFYPPlan = CALCULATE(",
              "                    SUMX( Proposals, Proposals[Planned Amt] ),",
              "                    Proposals[Current FY] = _CFY )",
              "return",
              "IF(ISBLANK(_CFYPPlan),0,_CFYPPlan)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "4f04ad5b-9585-4694-8d2f-70feba264c80"
          },
          {
            "name": "Count of CFY Proposals",
            "expression": [
              "",
              "    var _CFY = [Current Year]",
              "    var _PropCnt = CALCULATE(",
              "                    DISTINCTCOUNT( Proposals[Proposal ID] ),",
              "                    Proposals[Current FY] = _CFY &&",
              "                    Proposals[Act?] = \"Y\"",
              "                    )",
              "return",
              "IF(ISBLANK(_PropCnt),0,_PropCnt)"
            ],
            "formatString": "0",
            "lineageTag": "dd1f271a-9c53-4fdb-af58-3ccade1652a0"
          },
          {
            "name": "Count of CFY Pending Proposals",
            "expression": [
              "",
              "    var _CFY = [Current Year]",
              "    var _PropPendCnt = CALCULATE(",
              "                    DISTINCTCOUNT( Proposals[Proposal ID] ),",
              "                    Proposals[Current FY] = _CFY &&",
              "                    Proposals[Proposal Status] IN {\"Asked, Awaiting Response\",\"Response Pending\",\"Asked, Verbal Response\"}",
              "                    )",
              "return",
              "IF(ISBLANK(_PropPendCnt),0,_PropPendCnt)"
            ],
            "formatString": "0",
            "lineageTag": "8067311f-a2d7-45db-97bf-8674c44ece3d"
          },
          {
            "name": "Sum of CFY Proposals",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _CFY = [Current Year]    //This includes all Proposals that are Active and have a \"Current\" FY equal to the current FY",
              "    var _CFYPSum = CALCULATE(",
              "                    SUMX( Proposals, Proposals[Granted Amt] ),",
              "                    Proposals[Current FY] = _CFY,",
              "                    Proposals[Act?] = \"Y\")",
              "return",
              "IF(ISBLANK(_CFYPSum),0,_CFYPSum)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f8f4cb57-dac9-4a71-b2fd-5c371c8c736a"
          },
          {
            "name": "Count of CFY Planned Proposals",
            "expression": [
              "",
              "    var _CFY = [Current Year]",
              "    var _PropPlanCnt = CALCULATE(",
              "                    DISTINCTCOUNT( Proposals[Proposal ID] ),",
              "                    Proposals[Current FY] = _CFY &&",
              "                    Proposals[Proposal Status] = \"Planned\"",
              "                    )",
              "return",
              "IF(ISBLANK(_PropPlanCnt),0,_PropPlanCnt)"
            ],
            "formatString": "0",
            "lineageTag": "5ed2af7e-f387-4c05-9d3e-33a4a7d8137a"
          },
          {
            "name": "Avg Planned CFY Proposal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        IF( [Count of CFY Planned Proposals] = 0,0, [Sum of CFY Planned Proposals] / [Count of CFY Planned Proposals] ))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "e119469e-3dbf-4603-bb3c-1fc25d7239e7"
          },
          {
            "name": "Avg Pending CFY Proposal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        IF( [Count of CFY Pending Proposals] = 0,0, [Sum of CFY Pending Proposals] / [Count of CFY Pending Proposals] )",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "3056199d-49d5-4d48-a446-91e794203f18"
          },
          {
            "name": "Avg Granted CFY Proposal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        IF( [Count of CFY Granted Proposals] = 0,0, [Sum of CFY Granted Proposals] / [Count of CFY Granted Proposals] )",
              "    )"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "39602ff1-2ff3-4e76-8179-48ff4ff5e223"
          }
        ],
        "partitions": [
          {
            "name": "Proposal Measures-957191c2-1a60-4d7b-a3cf-b8b9be61516b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Current FY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CFY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "27beba9d-a307-4367-a304-cd7c3720b6e1",
            "sourceColumn": "CFY",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "be889103-60b3-4e1b-a38e-7656255a5fd4",
        "partitions": [
          {
            "name": "Current FY-136f006a-e5bf-4465-949b-d656317f0539",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(\"PADV\", [HierarchicalNavigation=true, Query=\"select advur.fn_get_fytd_fiscalyear(to_char(sysdate,'MM/DD/YYYY')) CFY#(lf)from dual\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Pledge Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "368fe7cb-731a-4590-ba0b-b5e7ad6eb1b0",
        "measures": [
          {
            "name": "Due 31-60 Plg Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _D3160Cnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Pledge Pymts Due'[Pledge Nbr] ),",
              "                    'Pledge Pymts Due'[Due 31 to 60 Days] > 0",
              "                        )",
              "   return",
              "   IF(ISBLANK(_D3160Cnt),0,_D3160Cnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "df648843-d93f-494c-86c7-e30054102e7d"
          },
          {
            "name": "Due 31-60 Pymt Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _D3160Cnt = CALCULATE(",
              "                    SUMX( 'Pledge Pymts Due', 'Pledge Pymts Due'[Due 31 to 60 Days] ),",
              "                    'Pledge Pymts Due'[Due 31 to 60 Days] > 0",
              "                        )",
              "   return",
              "   IF(ISBLANK(_D3160Cnt),0,_D3160Cnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "f3878679-ee08-4d02-a501-ac8137084acf"
          },
          {
            "name": "Due 31-60 Total",
            "expression": [
              "",
              "    var _D3160Ttl = CALCULATE(",
              "                    SUMX( 'Pledge Pymts Due', 'Pledge Pymts Due'[Due 31 to 60 Days Total] ),",
              "                    'Pledge Pymts Due'[Due 31 to 60 Days] > 0",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_D3160Ttl),0,_D3160Ttl)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "458b8538-7adf-4b59-a3da-04953a642f5f"
          },
          {
            "name": "Due 61-90 Plg Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _D6190Cnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Pledge Pymts Due'[Pledge Nbr] ),",
              "                    'Pledge Pymts Due'[Due 61 to 90 Days] > 0",
              "                        )",
              "   return",
              "   IF(ISBLANK(_D6190Cnt),0,_D6190Cnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "3b6732d2-8f5c-45fb-bf34-f35652a823dd"
          },
          {
            "name": "Due 61-90 Pymt Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _D6190Cnt = CALCULATE(",
              "                    SUMX( 'Pledge Pymts Due', 'Pledge Pymts Due'[Due 61 to 90 Days] ),",
              "                    'Pledge Pymts Due'[Due 61 to 90 Days] > 0",
              "                        )",
              "   return",
              "   IF(ISBLANK(_D6190Cnt),0,_D6190Cnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "415dfde9-d7b4-4f7a-a35a-36a4bdf09c18"
          },
          {
            "name": "Due 61-90 Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _D6190Ttl = CALCULATE(",
              "                    SUMX( 'Pledge Pymts Due', 'Pledge Pymts Due'[Due 61 to 90 Days Total] ),",
              "                    'Pledge Pymts Due'[Due 61 to 90 Days] > 0",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_D6190Ttl),0,_D6190Ttl)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b474c50c-9825-4d2c-b576-4449e6b92b49"
          },
          {
            "name": "Due 91-Plus Plg Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _D91Cnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Pledge Pymts Due'[Pledge Nbr] ),",
              "                    'Pledge Pymts Due'[Due 91+ Days] > 0",
              "                        )",
              "   return",
              "   IF(ISBLANK(_D91Cnt),0,_D91Cnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "bae9202b-d7e0-4068-b28b-4803dc3c09fe"
          },
          {
            "name": "Due 91-Plus Pymt Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _D91Cnt = CALCULATE(",
              "                    SUMX( 'Pledge Pymts Due', 'Pledge Pymts Due'[Due 91+ Days] ),",
              "                    'Pledge Pymts Due'[Due 91+ Days] > 0",
              "                        )",
              "   return",
              "   IF(ISBLANK(_D91Cnt),0,_D91Cnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "11b998b3-1140-4333-bdd9-16e29cae902d"
          },
          {
            "name": "Due 91-Plus Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _D91Ttl = CALCULATE(",
              "                    SUMX( 'Pledge Pymts Due', 'Pledge Pymts Due'[Due 91+ Days Total] ),",
              "                    'Pledge Pymts Due'[Due 91+ Days] > 0",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_D91Ttl),0,_D91Ttl)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "46e30f75-fd84-4f5f-bf58-0ad61a76a71d"
          },
          {
            "name": "Due in 30 Plg Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _D30Cnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Pledge Pymts Due'[Pledge Nbr] ),",
              "                    'Pledge Pymts Due'[Due <=30 Days] > 0",
              "                        )",
              "   return",
              "   IF(ISBLANK(_D30Cnt),0,_D30Cnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "47b82cee-1be7-4278-96f7-fb00157f59e0"
          },
          {
            "name": "Due in 30 Pymt Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _D30Cnt = CALCULATE(",
              "                    SUMX( 'Pledge Pymts Due', 'Pledge Pymts Due'[Due <=30 Days] ),",
              "                    'Pledge Pymts Due'[Due <=30 Days] > 0",
              "                        )",
              "   return",
              "   IF(ISBLANK(_D30Cnt),0,_D30Cnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "f2db56a0-30a9-40da-8f34-eccdd0e14cb2"
          },
          {
            "name": "Due in 30 Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _D30Ttl = CALCULATE(",
              "                    SUMX( 'Pledge Pymts Due', 'Pledge Pymts Due'[Due <=30 Days Total] ),",
              "                    'Pledge Pymts Due'[Due <=30 Days] > 0",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_D30Ttl),0,_D30Ttl)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "109ae2da-ea28-42ea-9fba-36652209edaa"
          },
          {
            "name": "Past Due Plg Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _PDCnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Pledge Pymts Due'[Pledge Nbr] ),",
              "                    'Pledge Pymts Due'[Past Due] > 0",
              "                        )",
              "   return",
              "   IF(ISBLANK(_PDCnt),0,_PDCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "f88ee24d-fcf6-4b11-bfbc-703bb5f09c18"
          },
          {
            "name": "Past Due Pymt Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _Today = TODAY()",
              "    var _PDCnt = CALCULATE(",
              "                    SUMX( 'Pledge Pymts Due', 'Pledge Pymts Due'[Past Due] ),",
              "                    'Pledge Pymts Due'[Past Due] > 0",
              "                        )",
              "   return",
              "   IF(ISBLANK(_PDCnt),0,_PDCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "4a47add1-161d-4569-a662-b83d074b1c3e"
          },
          {
            "name": "Past Due Pymt Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _PDTtl = CALCULATE(",
              "                    SUMX( 'Pledge Pymts Due', 'Pledge Pymts Due'[Past Due Total] ),",
              "                    'Pledge Pymts Due'[Past Due] > 0",
              "                        )",
              "   return",
              "   IF(ISBLANK(_PDTtl),0,_PDTtl)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "2e4b67cb-0e01-4914-ab19-dea4c0298a59"
          },
          {
            "name": "Total Due",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    [Past Due Pymt Total] + [Due in 30 Total] + [Due 31-60 Total] + [Due 61-90 Total] + [Due 91-Plus Total]"
            ],
            "lineageTag": "1b6c5df1-1b17-48ef-81db-d49e232fee3f"
          }
        ],
        "partitions": [
          {
            "name": "Pledge Measures-715343a5-5244-45ee-8f2c-3d286de14592",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Entities w/Locations",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Household Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aed3328f-73dc-4080-bfe9-45a5d202892e",
            "sourceColumn": "Household Key",
            "summarizeBy": "none"
          },
          {
            "name": "Market Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c15a0e6-05ce-4bab-bde7-50d7b5c9cdd1",
            "sourceColumn": "Market Area",
            "summarizeBy": "none"
          },
          {
            "name": "Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8293449b-90cd-4436-b5dc-ea4db0e2cdd9",
            "sourceColumn": "Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f4f4616-58d9-431f-a5c6-e5db2f77d0fe",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "ST",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9dc2951f-faec-49e4-884b-632762bf5585",
            "sourceColumn": "ST",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b90a692b-d2a2-417d-81db-e7e3a4811780",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64f8c4b4-52b4-4ed9-8f87-4b944cecde03",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "HH Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7c6d9d64-48db-4b34-8469-168b2bce897b",
            "sourceColumn": "HH Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Donor Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0e2c5d83-8a30-47d3-aaad-6433cb820cf3",
            "sourceColumn": "Donor Ind",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Camp Prod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "66214ca3-a204-4ed8-bd42-902c90d2fd17",
            "sourceColumn": "Total Camp Prod",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Camp Rev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "698f9dea-b9f0-4d7c-8767-53fd3011b558",
            "sourceColumn": "Total Camp Rev",
            "summarizeBy": "sum"
          },
          {
            "name": "Primary Ent ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45198ba4-cb01-453f-8bfb-daa350eed357",
            "sourceColumn": "Primary Ent ID",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Entity Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b97948d-8c5c-4ced-bbb3-938f85728499",
            "sourceColumn": "Primary Entity Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prim Inst Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fa047cb-88bf-4793-afb0-c99d0da83931",
            "sourceColumn": "Prim Inst Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "Spouse ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78d983d8-66be-4514-b480-f5e54c920cfa",
            "sourceColumn": "Spouse ID",
            "summarizeBy": "none"
          },
          {
            "name": "Spouse Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bcf648fe-3015-4477-88a9-437cb3d78bae",
            "sourceColumn": "Spouse Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sp Inst Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "508f28fe-0758-4982-afa1-e17b18a96ff7",
            "sourceColumn": "Sp Inst Suffix",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f854e171-69c1-46b8-8102-5e256e502670",
        "partitions": [
          {
            "name": "Entities w/Locations-d846f96f-f160-4c2d-bd39-a8ffaab10130",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(\"PADV\", [HierarchicalNavigation=true, Query=\"-- Query modified from the Strategic Targeting PBIX to simplify; will be used to create a new, simpler visual for Campaign Check-In and Leadership Reports. smk 6/3/2022#(lf)-- Modified to handle US addresses without Market Area codes; also changed to pull Campaign Production and Revenue.  smk 06/06/2022#(lf)-- Updated to allow for Non-US Addresses.  smk 10/3/2022#(lf)-- Revised to eliminate duplicate households, separating spouses into separate columns. smk 10/12/2022#(lf)#(lf)select distinct k.household_key                      \"\"Household Key\"\",#(lf)       g.primary_id_number                           \"\"Primary Ent ID\"\",#(lf)#(tab)#(tab)#(tab) CASE WHEN e.record_status_code IN ('D','P') THEN e.pref_mail_name||' *'#(lf)          ELSE e.pref_mail_name END                  \"\"Primary Entity Name\"\",#(lf)       e.institutional_suffix                        \"\"Prim Inst Suffix\"\",#(lf)#(tab)#(tab)#(tab) g.secondary_id_number                         \"\"Spouse ID\"\",#(lf)#(tab)#(tab)#(tab) sp.pref_mail_name                             \"\"Spouse Name\"\",#(lf)#(tab)#(tab)#(tab) sp.institutional_suffix                       \"\"Sp Inst Suffix\"\",#(lf)       CASE WHEN a.country_code > ' ' THEN c.short_desc#(lf)            WHEN a.zipcode = ' ' THEN 'Bad Address'#(lf)            WHEN a.geo_code <= '000' THEN a.geo_code#(lf)            WHEN a.geo_code IS NULL THEN 'Armed Forces & US Territories'#(lf)          ELSE a.geo_code||' - '||a.market_area END  \"\"Market Area\"\",#(lf)       substr(a.zipcode,1,5)                         \"\"Zipcode\"\",#(lf)       a.city                                        \"\"City\"\",#(lf)       a.State_Code                                  \"\"ST\"\",#(lf)       s.short_desc                                  \"\"State\"\",#(lf)       CASE WHEN a.country_code > ' ' THEN 'Foreign Address'#(lf)          ELSE r.short_desc END                      \"\"Region\"\",#(lf)       k.member_count                                \"\"HH Count\"\",#(lf)       CASE WHEN rev.ttl > 0 THEN 1#(lf)          ELSE 0 END                                 \"\"Donor Ind\"\",#(lf)       nvl(prod.ttl,0)                               \"\"Total Camp Prod\"\",#(lf)       nvl(rev.ttl,0)                                \"\"Total Camp Rev\"\"#(lf)from advur.mvw_hh_entities_gen g#(lf)inner join advur.mvw_ent_household_keys k ON g.household_key = k.household_key#(lf)inner join advur.mvw_ent_addresses a      ON g.primary_id_number = a.id_number#(lf)inner join advance.entity e               ON a.id_number = e.id_number#(lf)left join advance.entity sp               ON g.secondary_id_number = sp.id_number#(lf)inner join advance.tms_states s           ON a.state_code = s.state_code#(lf)left join advance.tms_national_region r   ON s.national_region = r.national_region_code#(lf)left join advance.tms_country c           ON a.country_code = c.country_code#(lf)left join (#(lf)           select xp.primary_recipient_ids did, sum(p.trans_amt) ttl#(lf)             from advur.mvw_total_production p#(lf)            inner join advur.mvw_total_production_ext xp ON p.trans_nbr = xp.trans_nbr#(lf)            where p.campaign_ind = 'Current Campaign'#(lf)            group by xp.primary_recipient_ids#(lf)            )prod ON e.id_number = prod.did#(lf)left join (#(lf)           select xr.primary_recipient_ids did, sum(r.trans_amt) ttl#(lf)             from advur.mvw_total_revenue r#(lf)            inner join advur.mvw_total_revenue_ext xr ON r.trans_nbr = xr.trans_nbr#(lf)            where r.campaign_ind = 'Current Campaign'#(lf)            group by xr.primary_recipient_ids#(lf)            )rev ON e.id_number = rev.did#(lf)#(lf)where e.record_status_code IN ('A','I','L')#(lf)  or  e.id_number IN (select xxpx.primary_recipient_ids#(lf)#(tab)                      from advur.mvw_total_production_ext xxpx#(lf)#(tab)                     inner join advur.mvw_total_production xxp ON xxpx.trans_nbr = xxp.trans_nbr#(lf)#(tab)                     where xxp.campaign_ind = 'Current Campaign'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) )#(lf)#(lf)order by \"\"Region\"\", \"\"Market Area\"\", \"\"Primary Ent ID\"\"\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"HH Count\", Int64.Type}, {\"Donor Ind\", Int64.Type}, {\"Total Camp Prod\", Currency.Type}, {\"Total Camp Rev\", Currency.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Household Giving",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Household Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7551dd3e-a0ec-4b66-86c6-1dee6f4e377e",
            "sourceColumn": "Household Key",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4f7f818-9547-4431-8701-34860908ba53",
            "sourceColumn": "Trans Nbr",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c6febf6-ddae-400c-a077-94534a0e8327",
            "sourceColumn": "Trans Type",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89e37302-e874-4f52-ab08-3788b7022fb4",
            "sourceColumn": "Campaign Ind",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9eeeef08-de69-409b-ae2f-f2f798f990e1",
            "sourceColumn": "Fiscal Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "d1d94ced-c96f-4a47-ac9b-cb95fbb35014",
            "sourceColumn": "Trans Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Alloc Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b42f5676-57f0-4feb-8d2f-8efcbf9fe370",
            "sourceColumn": "Alloc Code",
            "summarizeBy": "none"
          },
          {
            "name": "Allocation Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e8836d1-762b-4d27-90ed-aacf5822dc61",
            "sourceColumn": "Allocation Name",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "3d74b004-bef3-4425-9d6f-6ad0acbf6685",
            "sourceColumn": "Trans Amt",
            "summarizeBy": "sum"
          },
          {
            "name": "School",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "503ea3f5-2917-4729-85b2-5049f37fe97c",
            "sourceColumn": "School",
            "summarizeBy": "none"
          },
          {
            "name": "Finance Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db6f17c2-2a60-4aa3-a7b6-5547dc74381f",
            "sourceColumn": "Finance Category",
            "summarizeBy": "none"
          },
          {
            "name": "Goal Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f55d2ef8-957a-402d-abd8-25a7103ad9fb",
            "sourceColumn": "Goal Category",
            "summarizeBy": "none"
          },
          {
            "name": "Goal SubCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb047c66-6a6f-4c98-868c-fd181316af34",
            "sourceColumn": "Goal SubCategory",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebc556b5-b54b-46fb-9f90-994c94c6b6ca",
            "sourceColumn": "Campaign Bucket",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19093413-c889-473d-80aa-7460bed65169",
            "sourceColumn": "Campaign Priority",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign SubPriority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "969d665d-1ce6-4202-951a-eab41c563d62",
            "sourceColumn": "Campaign SubPriority",
            "summarizeBy": "none"
          },
          {
            "name": "Alloc Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d70da25e-f457-428a-b185-d262639287af",
            "sourceColumn": "Alloc Group",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Exclusions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb7fddc1-f87f-4e76-a6b6-9c956bc01ce7",
            "sourceColumn": "Trans Exclusions",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f303611-9c65-4719-bfa1-f1b9c7cad412",
            "sourceColumn": "Trans Month",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6914a07a-0fbd-4605-aad8-be617ee6f487",
            "sourceColumn": "Sort Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort TransType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a6509d5c-58f2-4a3d-9142-205d7605528e",
            "sourceColumn": "Sort TransType",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort School",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ae3c9ceb-9725-4308-bb98-66a5166e95a5",
            "sourceColumn": "Sort School",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort FinCat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06be0a0a-3619-4175-b348-cdfc614f5288",
            "sourceColumn": "Sort FinCat",
            "summarizeBy": "none"
          },
          {
            "name": "Sort GoalCat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8ec38634-3425-47d6-9355-e43a41c9b69b",
            "sourceColumn": "Sort GoalCat",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort GoalSubCat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cbb0dc2c-95de-47c9-9580-a5180f7dd930",
            "sourceColumn": "Sort GoalSubCat",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort CampBkt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1cdb7cc0-e8d9-4ed2-8e77-3416f7705262",
            "sourceColumn": "Sort CampBkt",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort CampPriority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "117912fa-e1c4-431d-95d9-785cc9374bdb",
            "sourceColumn": "Sort CampPriority",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort CampSubPriority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eadb9267-1c2f-4288-8936-21ef7f33cb79",
            "sourceColumn": "Sort CampSubPriority",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort Alloc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6268b2d-76dc-4d31-969d-d3f5e9df27f7",
            "sourceColumn": "Sort Alloc",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "fb02580a-24d3-4c25-b931-09cb60bb6c0c",
        "partitions": [
          {
            "name": "Household Giving-c795f13f-1f17-4eed-890f-218ea642bd8c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(\"PADV\", [HierarchicalNavigation=true, Query=\"-- Query for current and previous FY Production totals by household; provides details about each transaction. smk 10/12/2022#(lf)#(lf)select distinct k.household_key                     \"\"Household Key\"\",#(lf)       p.trans_nbr                                  \"\"Trans Nbr\"\",#(lf)       p.trans_type                                 \"\"Trans Type\"\",#(lf)       p.campaign_ind                               \"\"Campaign Ind\"\",#(lf)       p.fiscal_yr                                  \"\"Fiscal Yr\"\",#(lf)#(tab)#(tab)#(tab) trunc(p.trans_dt)                            \"\"Trans Dt\"\",#(lf)       p.allocation_code                            \"\"Alloc Code\"\", #(lf)       p.allocation_name                            \"\"Allocation Name\"\",#(lf)       p.trans_amt                                  \"\"Trans Amt\"\",#(lf)#(tab)#(tab)#(tab) tas.short_desc                               \"\"School\"\",#(lf)       p.finance_category                           \"\"Finance Category\"\",#(lf)#(tab)#(tab)#(tab) gc.short_desc                                \"\"Goal Category\"\",#(lf)#(tab)#(tab)#(tab) gsc.short_desc                               \"\"Goal SubCategory\"\",#(lf)#(tab)#(tab)#(tab) c1.short_desc                                \"\"Campaign Bucket\"\",#(lf)#(tab)#(tab)#(tab) c2.short_desc                                \"\"Campaign Priority\"\",#(lf)#(tab)#(tab)#(tab) c3.short_desc                                \"\"Campaign SubPriority\"\",#(lf)#(tab)#(tab)#(tab) ag.short_desc                                \"\"Alloc Group\"\",#(lf)       CASE WHEN p.allocation_code = 'OATHOTHJAYAUX' THEN 'Ath - Aux'#(lf)            WHEN p.allocation_code = 'OATHOTHJAYB01' THEN 'Ath - Jay'#(lf)            WHEN p.allocation_code = 'OATHOTHPRSV' THEN 'Ath - Persv'#(lf)            WHEN substr(p.allocation_code,2,3) = 'ATH' AND p.allocation_code NOT IN ('OATHOTHJAYAUX','OATHOTHJAYB01','OATHOTHPRSV') THEN 'Ath - Gen'#(lf)            WHEN substr(p.allocation_code,2,3) = 'ILC' THEN 'ILAC'#(lf)#(tab)#(tab)#(tab)      WHEN p.trans_category = 'Bequest Expectancies and Gifts' THEN 'Bequests'#(lf)          ELSE NULL END                             \"\"Trans Exclusions\"\",#(lf)       to_char(p.trans_dt,'Month')                  \"\"Trans Month\"\",#(lf)       EXTRACT(MONTH FROM ADD_MONTHS(p.trans_dt,6)) \"\"Sort Month\"\",#(lf)#(tab)#(tab)#(tab) p.transtype_sort                             \"\"Sort TransType\"\",#(lf)#(tab)#(tab)#(tab) tas.hierarchy_order                          \"\"Sort School\"\",#(lf)#(tab)#(tab)#(tab) p.fincat_sort                                \"\"Sort FinCat\"\",#(lf)#(tab)#(tab)#(tab) gc.hierarchy_order                           \"\"Sort GoalCat\"\",#(lf)#(tab)#(tab)#(tab) gsc.hierarchy_order                          \"\"Sort GoalSubCat\"\",#(lf)#(tab)#(tab)#(tab) c1.hierarchy_order                           \"\"Sort CampBkt\"\",#(lf)#(tab)#(tab)#(tab) c2.hierarchy_order                           \"\"Sort CampPriority\"\",#(lf)#(tab)#(tab)#(tab) c3.hierarchy_order                           \"\"Sort CampSubPriority\"\",#(lf)#(tab)#(tab)#(tab) a.alloc_sort                                 \"\"Sort Alloc\"\"#(lf)from advur.mvw_total_production p#(lf)inner join advur.mvw_total_production_ext px ON p.trans_nbr = px.trans_nbr#(lf)inner join advur.mvw_allocations a           ON p.allocation_code = a.allocation_code#(lf)left join advance.tms_endow_pool gc          ON a.campaign_goal_category = gc.endow_pool#(lf)left join advance.tms_endow_type gsc         ON a.campaign_goal_subcategory = gsc.endow_type#(lf)left join advance.tms_alloc_sub_dept ag      ON a.alloc_sub_dept = ag.alloc_sub_dept_code#(lf)left join advance.tms_category1 c1           ON a.category1_code = c1.category1_code#(lf)left join advance.tms_category2 c2           ON a.category2_code = c2.category2_code#(lf)left join advance.tms_category3 c3           ON a.category3_code = c3.category3_code#(lf)left join advance.tms_alloc_school tas       ON a.alloc_school_code = tas.alloc_school_code#(lf)inner join advur.mvw_hh_entities_gen g       ON (px.primary_recipient_ids = g.primary_id_number OR px.primary_recipient_ids = g.secondary_id_number)#(lf)inner join advur.mvw_ent_household_keys k    ON g.household_key = k.household_key#(lf)where p.fiscal_yr >= advur.fn_get_fytd_fiscalyear(TO_CHAR(SYSDATE, 'MM/DD/YYYY'))-1#(lf)#(lf)order by \"\"Fiscal Yr\"\", \"\"Sort Month\"\", \"\"Trans Nbr\"\"\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Trans Dt\", type date}, {\"Trans Amt\", Currency.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Household Keys",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "HH Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1397c17d-68e1-49a5-b192-9fd31c1a5688",
            "sourceColumn": "HH Key",
            "summarizeBy": "none"
          },
          {
            "name": "Mbr Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3ae432ac-21d0-4710-ab77-759ae888d1c7",
            "sourceColumn": "Mbr Count",
            "summarizeBy": "none"
          },
          {
            "name": "Act?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db71efd1-14d0-41ec-9ead-74c699087196",
            "sourceColumn": "Act?",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2277d23d-cd62-4142-8f88-e33aa4b5f41d",
        "partitions": [
          {
            "name": "Household Keys-3145be2b-c3ee-45e6-a7ad-07dc02c7200c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(\"PADV\", [HierarchicalNavigation=true, Query=\"select distinct xk.household_key  \"\"HH Key\"\",#(lf)       xk.member_count            \"\"Mbr Count\"\",#(lf)#(tab)#(tab)#(tab) xk.active_household        \"\"Act?\"\"#(lf)from advur.mvw_ent_household_keys xk\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Mbr Count\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Max Proposal Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "columns": [
          {
            "name": "Max Proposal Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b1be2193-c8b6-46c5-94ce-65ade46109e0",
            "sourceColumn": "Max Proposal Date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d931e443-bf52-4d8d-892d-bdf65b733b8a",
        "partitions": [
          {
            "name": "Max Proposal Date",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = List.Max( Proposals[Planned Dt] )",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Plg DD Cats",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Pledge Nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60d9c829-a7f3-4f2b-b883-2c38c513d1b0",
            "sourceColumn": "Pledge Nbr",
            "summarizeBy": "none"
          },
          {
            "name": "Due Date Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e788cd7-08bc-4a3a-a585-9b3db9b3c740",
            "sourceColumn": "Due Date Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sort DCat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b72ab047-9e3e-47e8-b5c1-8acb56657d56",
            "sourceColumn": "Sort DCat",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4f16ee57-d81f-47f6-9cbc-6ed99428f1ea",
        "partitions": [
          {
            "name": "Plg DD Cats",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(\"PADV\", [HierarchicalNavigation=true, Query=\"-- Query created to pull all the payment due ranges for each pledge; for the Gift Officer Dashbaord report. smk 10/13/2023#(lf)#(lf)select distinct xpp9.prim_pledge_number \"\"Pledge Nbr\"\",#(lf)       ducat.duecat                     \"\"Due Date Category\"\",#(lf)       ducat.srt                        \"\"Sort DCat\"\"#(lf) from advance.primary_pledge xpp9#(lf)inner join advance.pledge xp9  ON xpp9.prim_pledge_number = xp9.pledge_pledge_number#(lf)inner join (#(lf)            select distinct xpp13.prim_pledge_number nbr,#(lf)                   ' Past Due'  duecat,#(lf)                   '01' srt#(lf)              from advance.payment_schedule xps13#(lf)             inner join advance.primary_pledge xpp13 ON xps13.payment_schedule_pledge_nbr = xpp13.prim_pledge_number#(lf)             where xpp13.prim_pledge_status = 'A'#(lf)             and   xpp13.prim_pledge_type NOT IN ('AO','PO','E1','P1','L2')#(lf)             and   xps13.payment_schedule_status = 'U'#(lf)             and   xps13.payment_schedule_date <> '00000000'#(lf)             and   substr(xps13.payment_schedule_date,1,4) <> '0000'#(lf)             and   substr(xps13.payment_schedule_date,5,2) <> '00'#(lf)             and   substr(xps13.payment_schedule_date,7,2) <> '00'#(lf)             and   to_date(xps13.payment_schedule_date,'YYYYMMDD') < trunc(sysdate)#(lf)            UNION ALL#(lf)            select distinct xpp14.prim_pledge_number nbr,#(lf)                   '30 Days or Less'  duecat,#(lf)                   '02' srt#(lf)              from advance.payment_schedule xps14#(lf)             inner join advance.primary_pledge xpp14 ON xps14.payment_schedule_pledge_nbr = xpp14.prim_pledge_number#(lf)             where xpp14.prim_pledge_status = 'A'#(lf)             and   xpp14.prim_pledge_type NOT IN ('AO','PO','E1','P1','L2')#(lf)             and   xps14.payment_schedule_status = 'U'#(lf)             and   xps14.payment_schedule_date <> '00000000'#(lf)             and   substr(xps14.payment_schedule_date,1,4) <> '0000'#(lf)             and   substr(xps14.payment_schedule_date,5,2) <> '00'#(lf)             and   substr(xps14.payment_schedule_date,7,2) <> '00'#(lf)             and   to_date(xps14.payment_schedule_date,'YYYYMMDD') BETWEEN trunc(sysdate) AND trunc(sysdate)+30#(lf)            UNION ALL#(lf)            select distinct xpp15.prim_pledge_number nbr,#(lf)                   '31 to 60 Days'  duecat,#(lf)                   '03' srt#(lf)              from advance.payment_schedule xps15#(lf)             inner join advance.primary_pledge xpp15 ON xps15.payment_schedule_pledge_nbr = xpp15.prim_pledge_number#(lf)             where xpp15.prim_pledge_status = 'A'#(lf)             and   xpp15.prim_pledge_type NOT IN ('AO','PO','E1','P1','L2')#(lf)             and   xps15.payment_schedule_status = 'U'#(lf)             and   xps15.payment_schedule_date <> '00000000'#(lf)             and   substr(xps15.payment_schedule_date,1,4) <> '0000'#(lf)             and   substr(xps15.payment_schedule_date,5,2) <> '00'#(lf)             and   substr(xps15.payment_schedule_date,7,2) <> '00'#(lf)             and   to_date(xps15.payment_schedule_date,'YYYYMMDD') BETWEEN trunc(sysdate)+31 AND trunc(sysdate)+60#(lf)            UNION ALL#(lf)            select distinct xpp16.prim_pledge_number nbr,#(lf)                   '61 to 90 Days'  duecat,#(lf)                   '04' srt#(lf)              from advance.payment_schedule xps16#(lf)             inner join advance.primary_pledge xpp16 ON xps16.payment_schedule_pledge_nbr = xpp16.prim_pledge_number#(lf)             where xpp16.prim_pledge_status = 'A'#(lf)             and   xpp16.prim_pledge_type NOT IN ('AO','PO','E1','P1','L2')#(lf)             and   xps16.payment_schedule_status = 'U'#(lf)             and   xps16.payment_schedule_date <> '00000000'#(lf)             and   substr(xps16.payment_schedule_date,1,4) <> '0000'#(lf)             and   substr(xps16.payment_schedule_date,5,2) <> '00'#(lf)             and   substr(xps16.payment_schedule_date,7,2) <> '00'#(lf)             and   to_date(xps16.payment_schedule_date,'YYYYMMDD') BETWEEN trunc(sysdate)+61 AND trunc(sysdate)+90#(lf)            UNION ALL#(lf)            select distinct xpp17.prim_pledge_number nbr,#(lf)                   '91+ Days'  duecat,#(lf)                   '05' srt#(lf)              from advance.payment_schedule xps17#(lf)             inner join advance.primary_pledge xpp17 ON xps17.payment_schedule_pledge_nbr = xpp17.prim_pledge_number#(lf)             where xpp17.prim_pledge_status = 'A'#(lf)             and   xpp17.prim_pledge_type NOT IN ('AO','PO','E1','P1','L2')#(lf)             and   xps17.payment_schedule_status = 'U'#(lf)             and   xps17.payment_schedule_date <> '00000000'#(lf)             and   substr(xps17.payment_schedule_date,1,4) <> '0000'#(lf)             and   substr(xps17.payment_schedule_date,5,2) <> '00'#(lf)             and   substr(xps17.payment_schedule_date,7,2) <> '00'#(lf)             and   to_date(xps17.payment_schedule_date,'YYYYMMDD') > trunc(sysdate)+90#(lf)            )ducat ON xpp9.prim_pledge_number = ducat.nbr#(lf)where xpp9.prim_pledge_status = 'A'#(lf)and   xpp9.prim_pledge_type NOT IN ('AO','PO','E1','P1','L2')#(lf)#(lf)order by \"\"Pledge Nbr\"\", \"\"Sort DCat\"\"\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Proposal Solictors",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Proposal ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd261c95-610f-443f-b546-9821ee9dc952",
            "sourceColumn": "Proposal ID",
            "summarizeBy": "none"
          },
          {
            "name": "Act?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a33dcbf-f646-48ca-b946-1180379e3e00",
            "sourceColumn": "Act?",
            "summarizeBy": "none"
          },
          {
            "name": "PS ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b7edb1f-6312-40d5-898b-83d1367260ff",
            "sourceColumn": "PS ID",
            "summarizeBy": "none"
          },
          {
            "name": "PS Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0cbdb45-0903-4c4b-bac0-9bd32b94d3d3",
            "sourceColumn": "PS Name",
            "summarizeBy": "none"
          },
          {
            "name": "Start Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0e6f0cb0-074e-49a6-a0c3-a4fe46598371",
            "sourceColumn": "Start Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Stop Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8399c612-b50b-44ce-afdf-15f04770a076",
            "sourceColumn": "Stop Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b399c011-14e3-46e0-b864-bb29aad1f6ca",
            "sourceColumn": "Unit Code",
            "summarizeBy": "none"
          },
          {
            "name": "Sort PS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "383f256a-0e46-4ebd-84c2-ed503704e19f",
            "sourceColumn": "Sort PS",
            "summarizeBy": "none"
          },
          {
            "name": "PS Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b272a28b-6cbd-471b-abe1-59ed730ea12d",
            "sourceColumn": "PS Team",
            "summarizeBy": "none"
          },
          {
            "name": "Solicitor Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c941d97b-4c45-43fd-a542-91701b61726e",
            "sourceColumn": "Solicitor Key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4aa63a11-3a6d-4281-b380-9857f79bedc5",
        "partitions": [
          {
            "name": "Proposal Solictors",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(\"PADV\", [HierarchicalNavigation=true, Query=\"-- Query to pull all proposal solicitors assigned to each proposal (for Gift Officer Dashboard). smk 10/16/2023#(lf)-- Added a \"\"Solictor Key\"\" that combines the Proposal ID and the Solicitor's ID. smk 10/24/2023#(lf)#(lf)select xa.proposal_id                          \"\"Proposal ID\"\",#(lf)       xa.active_ind                           \"\"Act?\"\",#(lf)       xa.assignment_id_number                 \"\"PS ID\"\",#(lf)       CASE WHEN xs.active_ind <> 'Y' THEN xs.name||' (I)'#(lf)          ELSE xs.name END                     \"\"PS Name\"\",#(lf)       trunc(xa.start_date)                    \"\"Start Dt\"\",#(lf)       trunc(xa.stop_date)                     \"\"Stop Dt\"\",#(lf)       xs.unit_code                            \"\"Unit Code\"\",#(lf)       xtuc.short_desc                         \"\"PS Team\"\",#(lf)       to_char(xa.proposal_id||xs.id_number)   \"\"Solicitor Key\"\",#(lf)       xs.sort                                 \"\"Sort PS\"\"#(lf) from advance.assignment xa#(lf)inner join advance.staff xs                 ON xa.assignment_id_number = xs.id_number#(lf) left join advance.tms_unit_code xtuc       ON xs.unit_code = xtuc.unit_code#(lf)where xa.assignment_type = 'PS'    -- \"\"Proposal Solicitor\"\"#(lf)and   xa.proposal_id > 0           -- The data has some rows where the assignment type is 'PS' but there is no Proposal ID... so this.\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Start Dt\", type date}, {\"Stop Dt\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Prospect Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "a2a4c7cd-e542-4a71-9c18-a290114ba2f7",
        "measures": [
          {
            "name": "Assigned Prospect CFY Prod Donor Count",
            "expression": [
              "",
              "    var _AsnProsPrdDnrCnt = CALCULATE(",
              "                        DISTINCTCOUNTNOBLANK( 'Prospects and Scores'[Prospect ID] ),",
              "                            'Prospects and Scores'[PM ID] > \" \",",
              "                            'Prospects and Scores'[CFY Prod] > 0",
              "                             )",
              "   return",
              "   IF(ISBLANK(_AsnProsPrdDnrCnt),0,_AsnProsPrdDnrCnt)"
            ],
            "formatString": "0",
            "lineageTag": "86a865f4-18c1-48a1-9a0c-f002f211bb8b"
          },
          {
            "name": "Assigned Prospect CFY Prod Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _ProsPrdTtl = CALCULATE(",
              "                        SUMX( 'Prospects and Scores', 'Prospects and Scores'[CFY Prod] ),",
              "                    'Prospects and Scores'[PM ID] > \" \",",
              "                    'Prospects and Scores'[CFY Prod] > 0",
              "                    )",
              "   return",
              "   IF(ISBLANK(_ProsPrdTtl),0,_ProsPrdTtl)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "9081215f-966c-48b4-b624-67569fd2ed64"
          },
          {
            "name": "Assigned Prospect Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _AsnProsCnt = CALCULATE(",
              "                    DISTINCTCOUNTNOBLANK( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[PM ID] > \"\" )",
              "   return",
              "   IF(ISBLANK(_AsnProsCnt),0,_AsnProsCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "b07b42f8-9170-46cc-89bb-ba24c2fe1ddd"
          },
          {
            "name": "Average CFY Production",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        IF( [Assigned Prospect CFY Prod Donor Count] = 0, 0, [Assigned Prospect CFY Prod Total] / [Assigned Prospect CFY Prod Donor Count] )",
              "    )"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "761874e7-e41d-40d9-8ac2-ebc6945dd6eb"
          },
          {
            "name": "Prospect CFY Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _CFY = MAX('Current FY'[CFY] )",
              "    var _ProsTtl = CALCULATE(",
              "                    SUMX( 'Prospects and Scores', 'Prospects and Scores'[CFY Prod] )--,",
              "--                        ALL( 'Prospects and Scores' )",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_ProsTtl),0,_ProsTtl)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e167165b-0896-4ba8-9017-af4f36b12583"
          },
          {
            "name": "Prospect Donor Target",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _DnrTgt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Prospects and Scores'[Entity ID] ),",
              "                    'Prospects and Scores'[PM ID] > \"\",",
              "                    'Prospects and Scores'[Prospect Stage] IN {\"Identify\",\"Discovery\",\"Qualify\",\"Cultivate/Open\",\"Negotiate/Close\"}",
              "                    )",
              "   return",
              "   IF(ISBLANK(_DnrTgt),0,_DnrTgt*.75)"
            ],
            "formatString": "#,0",
            "lineageTag": "e886961f-8969-4af9-8308-066554ed659a"
          },
          {
            "name": "Prospect Move Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _MoveTrgt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Prospects and Scores'[Entity ID] ),",
              "                    'Prospects and Scores'[PM ID] > \"\" )",
              "   return",
              "   IF(ISBLANK(_MoveTrgt),0,_MoveTrgt*.8)"
            ],
            "lineageTag": "780a062b-d59e-4e1f-86f8-3952ac45d762"
          },
          {
            "name": "Average AES",
            "expression": [
              "",
              "    var _ESTotal = CALCULATE(",
              "        SUMX( 'Prospects and Scores', 'Prospects and Scores'[Alumni Engagement Score] ),",
              "        'Prospects and Scores'[Alumni Engagement Score] > 0 )",
              "    var _AsnProsCnt = CALCULATE(",
              "                    DISTINCTCOUNTNOBLANK( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[Alumni Engagement Score] > 0)",
              "return",
              "_ESTotal / _AsnProsCnt"
            ],
            "formatString": "0.0",
            "lineageTag": "91c8edcd-6b06-46dc-b014-a9b44a30adfb"
          },
          {
            "name": "Average AF EVI",
            "expression": [
              "",
              "    var _AFEVITotal = CALCULATE(",
              "        SUMX( 'Prospects and Scores', 'Prospects and Scores'[AF EVI] ),",
              "        'Prospects and Scores'[AF EVI] > 0 )",
              "    var _AsnProsCnt = CALCULATE(",
              "                    DISTINCTCOUNTNOBLANK( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[AF EVI] > 0)",
              "return",
              "_AFEVITotal / _AsnProsCnt"
            ],
            "formatString": "0.0",
            "lineageTag": "5d6da7b2-0502-4f01-87c3-6b0821946b06"
          },
          {
            "name": "Average MG Capacity",
            "expression": [
              "",
              "    var _MGCapTotal = CALCULATE(",
              "        SUMX( 'Prospects and Scores', 'Prospects and Scores'[MG Capacity] ),",
              "        'Prospects and Scores'[MG Capacity] > 0 )",
              "    var _AsnProsCnt = CALCULATE(",
              "                    DISTINCTCOUNTNOBLANK( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[MG Capacity] > 0)",
              "return",
              "_MGCapTotal / _AsnProsCnt"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "4473a4df-fd4f-43b2-9964-0acf3c0d76dc"
          },
          {
            "name": "Average MG EVI",
            "expression": [
              "",
              "    var _MGEVITotal = CALCULATE(",
              "        SUMX( 'Prospects and Scores', 'Prospects and Scores'[MG EVI] ),",
              "        'Prospects and Scores'[MG EVI] > 0 )",
              "    var _AsnProsCnt = CALCULATE(",
              "                    DISTINCTCOUNTNOBLANK( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[MG EVI] > 0)",
              "return",
              "_MGEVITotal / _AsnProsCnt"
            ],
            "formatString": "#,0.0",
            "lineageTag": "4cb66e4d-64c5-483e-b36f-9b30c449d27a"
          },
          {
            "name": "Average PDI",
            "expression": [
              "",
              "    var _PDITotal = CALCULATE(",
              "        SUMX( 'Prospects and Scores', 'Prospects and Scores'[AF PDI] ),",
              "        'Prospects and Scores'[AF PDI] > 0 )",
              "    var _AsnProsCnt = CALCULATE(",
              "                    DISTINCTCOUNTNOBLANK( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[AF PDI] > 0)",
              "return",
              "_PDITotal / _AsnProsCnt"
            ],
            "formatString": "0.0",
            "lineageTag": "bbee35e3-38c5-4908-bf29-d328e3454292"
          },
          {
            "name": "Assigned Prospect PFY Prod Donor Count",
            "expression": [
              "",
              "    var _AsnProsPrvPrdDnrCnt = CALCULATE(",
              "                        DISTINCTCOUNTNOBLANK( 'Prospects and Scores'[Prospect ID] ),",
              "                            'Prospects and Scores'[PM ID] > \" \",",
              "                            'Prospects and Scores'[PFY Prod] > 0",
              "                             )",
              "   return",
              "   IF(ISBLANK(_AsnProsPrvPrdDnrCnt),0,_AsnProsPrvPrdDnrCnt)"
            ],
            "formatString": "0",
            "lineageTag": "0311d221-40d1-4668-a92d-19dc9cba6c4e"
          },
          {
            "name": "Assigned Prospect PFY Prod Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _ProsPrvPrdTtl = CALCULATE(",
              "                        SUMX( 'Prospects and Scores', 'Prospects and Scores'[PFY Prod] ),",
              "                    'Prospects and Scores'[PM ID] > \" \",",
              "                    'Prospects and Scores'[PFY Prod] > 0",
              "                    )",
              "   return",
              "   IF(ISBLANK(_ProsPrvPrdTtl),0,_ProsPrvPrdTtl)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "ba427a1e-7886-4a84-947f-254150ea346c"
          },
          {
            "name": "Average PFY Production",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        IF( [Assigned Prospect PFY Prod Donor Count] = 0, 0, [Assigned Prospect PFY Prod Total] / [Assigned Prospect PFY Prod Donor Count] )",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "8452b6b3-d36d-4a00-92e0-2ea478f6d0ee"
          },
          {
            "name": "Prospects Identify Count",
            "expression": [
              "",
              "    var _IdenCnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[Prospect Stage] = \"Identify\",",
              "                    'Prospects and Scores'[PM ID] > \"\"",
              "                    )",
              "return",
              "IF(ISBLANK(_IdenCnt),0,_IdenCnt)"
            ],
            "formatString": "0",
            "lineageTag": "4917d214-bc4d-4467-b459-05bcb9761cb7"
          },
          {
            "name": "Prospects Qualify Count",
            "expression": [
              "",
              "    var _QualCnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[Prospect Stage] = \"Qualify\",",
              "                    'Prospects and Scores'[PM ID] > \"\"",
              "                    )",
              "return",
              "IF(ISBLANK(_QualCnt),0,_QualCnt)"
            ],
            "formatString": "0",
            "lineageTag": "40fb8b17-d57d-4a82-8b23-631e05a59b87"
          },
          {
            "name": "Prospects Discovery Count",
            "expression": [
              "",
              "    var _DiscCnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[Prospect Stage] = \"Discovery\",",
              "                    'Prospects and Scores'[PM ID] > \"\"",
              "                    )",
              "return",
              "IF(ISBLANK(_DiscCnt),0,_DiscCnt)"
            ],
            "formatString": "0",
            "lineageTag": "e69d29b9-796c-4e73-a590-e500587a91b0"
          },
          {
            "name": "Prospects Cultivate-Open Count",
            "expression": [
              "",
              "    var _OpenCnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[Prospect Stage] = \"Cultivate/Open\",",
              "                    'Prospects and Scores'[PM ID] > \"\"",
              "                    )",
              "return",
              "IF(ISBLANK(_OpenCnt),0,_OpenCnt)"
            ],
            "formatString": "0",
            "lineageTag": "b72e4724-df1c-4dd0-88a4-198ddf21dcc8"
          },
          {
            "name": "Prospects Negotiate-Close Count",
            "expression": [
              "",
              "    var _ClosCnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[Prospect Stage] = \"Negotiate/Close\",",
              "                    'Prospects and Scores'[PM ID] > \"\"",
              "                    )",
              "return",
              "IF(ISBLANK(_ClosCnt),0,_ClosCnt)"
            ],
            "formatString": "0",
            "lineageTag": "970b401c-7796-44cf-a767-f4a36c283cf8"
          },
          {
            "name": "Prospects Stewardship Count",
            "expression": [
              "",
              "    var _StewCnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[Prospect Stage] = \"Stewardship\",",
              "                    'Prospects and Scores'[PM ID] > \"\"",
              "                    )",
              "return",
              "IF(ISBLANK(_StewCnt),0,_StewCnt)"
            ],
            "formatString": "0",
            "lineageTag": "92269196-a369-4f9f-a033-a96c7b10bf51"
          },
          {
            "name": "Prospects PermStewardship Count",
            "expression": [
              "",
              "    var _PermCnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[Prospect Stage] = \"Permanent Stewardship\",",
              "                    'Prospects and Scores'[PM ID] > \"\"",
              "                    )",
              "return",
              "IF(ISBLANK(_PermCnt),0,_PermCnt)"
            ],
            "formatString": "0",
            "lineageTag": "f5171f46-591a-45b5-b557-eede79836f3c"
          },
          {
            "name": "Assigned Prospect Count w/Proposal",
            "expression": [
              "",
              "    var _ProsPropCnt = CALCULATE(",
              "                        DISTINCTCOUNTNOBLANK( 'Prospects and Scores'[Prospect ID] ),",
              "                            'Prospects and Scores'[PM ID] > \"\",",
              "                            Proposals[Proposal ID] > 0,",
              "//                            'Prospects and Scores'[Act Plg Count] = 0,",
              "                            'Prospects and Scores'[Prospect Stage] IN {\"Identify\",\"Discovery\",\"Qualify\",\"Cultivate/Open\",\"Negotiate/Close\"}",
              "                             )",
              "   return",
              "   IF(ISBLANK(_ProsPropCnt),0,_ProsPropCnt)"
            ],
            "formatString": "0",
            "lineageTag": "ba6cd49c-e549-4dd3-b232-be9381911a94"
          },
          {
            "name": "Assigned Prospect Act Plg Count",
            "expression": [
              "",
              "    var _AsnProsAPCnt = CALCULATE(",
              "                    DISTINCTCOUNTNOBLANK( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[PM ID] > \"\",",
              "                     'Prospects and Scores'[Act Plg Count] > 0)",
              "   return",
              "   IF(ISBLANK(_AsnProsAPCnt),0,_AsnProsAPCnt)"
            ],
            "formatString": "0",
            "lineageTag": "f3d7b869-fe95-4457-b436-3619ae47f0fc"
          },
          {
            "name": "Prospect Proposal Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _PropTgt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Prospects and Scores'[Prospect ID] ),",
              "                    'Prospects and Scores'[PM ID] > \"\",",
              "                    'Prospects and Scores'[Act Plg Count] = 0,",
              "                    'Prospects and Scores'[Prospect Stage] IN {\"Identify\",\"Discovery\",\"Qualify\",\"Cultivate/Open\",\"Negotiate/Close\"}",
              "                    )",
              "   return",
              "   IF(ISBLANK(_PropTgt),0,_PropTgt*.75)"
            ],
            "lineageTag": "34648852-0281-445d-9e3d-e7b70469fead"
          },
          {
            "name": "CFY Participation",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    [Assigned Prospect CFY Prod Donor Count] / [Assigned Prospect Count]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "eaa8889c-ace5-4125-8d3d-5a336d0c45e4"
          },
          {
            "name": "CFY Target Participation",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    [Assigned Prospect CFY Prod Donor Count] / [Prospect Donor Target]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b563e72d-e65a-4680-b938-d40bb55fa806"
          },
          {
            "name": "Proposal Penetration",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    [Assigned Prospect Count w/Proposal] / [Assigned Prospect Count]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "005d993b-8228-43e6-a279-ae051ba42805"
          },
          {
            "name": "Prospects w/CFY Move CRs Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    var _CFY = [Current Year]",
              "    var _MvPCRCnt = CALCULATE(",
              "                    DISTINCTCOUNT( 'Contact Reports'[Contacted ID] ),",
              "                    'Contact Reports'[Contact FY] = _CFY, ",
              "                    'Contact Reports'[Contact Purpose] IN {\"Qualification\",\"Cultivation\",\"Solicitation\",\"Follow Up on Solicitation\",\"Close Solicitation\"},",
              "                    'Contact Reports'[Assgnd Pros Ind] = 1,",
              "                    USERELATIONSHIP( 'Contact Reports'[GO Unique Key], 'Primary Managers'[GO Unique Key] )",
              "    )",
              "return",
              "IF(ISBLANK(_MvPCRCnt),0,_MvPCRCnt)"
            ],
            "formatString": "0",
            "lineageTag": "2146aa03-ac07-4138-ab1d-6db3d76f8ad8"
          },
          {
            "name": "Total Days in Stage",
            "expression": [
              "",
              "    CALCULATE(",
              "        SUMX( 'Prospects and Scores', 'Prospects and Scores'[Days In Stage] ),",
              "        'Prospects and Scores'[PM ID] > \"\"",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "8815b0f7-e5fd-425d-aa99-aafa7f4721b7"
          },
          {
            "name": "Average Days in Stage",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Days in Stage] / [Assigned Prospect Count]",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "e96662d4-5e62-4c63-8722-fac14b16bc3a"
          },
          {
            "name": "Total Days Assigned",
            "expression": [
              "",
              "    CALCULATE(",
              "        SUMX( 'Prospects and Scores', 'Prospects and Scores'[Days Assgnd] ),",
              "        'Prospects and Scores'[PM ID] > \"\"",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "7dc40484-7a36-4b2e-9f34-c3b70a23ec7a"
          },
          {
            "name": "Average Days Assigned",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        [Total Days Assigned] / [Assigned Prospect Count]",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "3cc3e289-04c6-44e9-9d4c-b2647eef8072"
          }
        ],
        "partitions": [
          {
            "name": "Prospect Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Primary Managers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "GO ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b171d21-57e2-4e2b-a719-7a48f5a1711f",
            "sourceColumn": "GO ID",
            "summarizeBy": "none"
          },
          {
            "name": "Gift Officer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "509049a4-1614-4992-9ce7-7314a616025c",
            "sortByColumn": "Sort Officer",
            "sourceColumn": "Gift Officer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Gift Officer Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "98f24e79-bc8d-4248-8a6d-a52520a3b5b4",
            "sortByColumn": "Sort Team",
            "sourceColumn": "Gift Officer Team",
            "summarizeBy": "none"
          },
          {
            "name": "GO Start Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9eb84341-c094-46d5-8304-984500985c73",
            "sourceColumn": "GO Start Dt",
            "summarizeBy": "none"
          },
          {
            "name": "GO Stop Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "49bf68c2-c92b-4cad-912b-82ba4323909d",
            "sourceColumn": "GO Stop Dt",
            "summarizeBy": "none"
          },
          {
            "name": "GO Act?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c2b3c71-c4d3-4d97-88c4-7671b72636c5",
            "sourceColumn": "GO Act?",
            "summarizeBy": "none"
          },
          {
            "name": "Pros ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c5641c33-9d44-4693-b86a-9d68ab26727d",
            "sourceColumn": "Pros ID",
            "summarizeBy": "none"
          },
          {
            "name": "Assgn Start Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d36457f8-6973-4cee-bbdf-cafb5bece19f",
            "sourceColumn": "Assgn Start Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Assgn Start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e59537a-0ed6-44dd-b592-2e87d137fc6b",
            "sourceColumn": "Assgn Start",
            "summarizeBy": "none"
          },
          {
            "name": "Assgn Stop Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4a7a84b8-c62a-40f2-8903-64d19bcd7b81",
            "sourceColumn": "Assgn Stop Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Assgn Stop",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f9dbc34-879a-499e-9439-398c7543ae44",
            "sourceColumn": "Assgn Stop",
            "summarizeBy": "none"
          },
          {
            "name": "Assgnmt Act?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffa2a21e-fc2e-48d5-827b-2d51c9884e4a",
            "sourceColumn": "Assgnmt Act?",
            "summarizeBy": "none"
          },
          {
            "name": "Office",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd6809eb-b4fb-4b16-9e81-b346c1709c6f",
            "sourceColumn": "Office",
            "summarizeBy": "none"
          },
          {
            "name": "Staff Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef8fe2a7-183e-4942-ba1e-eecd46c9fead",
            "sourceColumn": "Staff Type",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Officer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aad4bdaa-ebe4-469e-a082-adc90247fdc5",
            "sourceColumn": "Sort Officer",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "afc04a6a-2b7f-47a6-82da-0188809dca18",
            "sourceColumn": "Sort Team",
            "summarizeBy": "sum"
          },
          {
            "name": "GO Unique Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e447529-63a7-43df-812f-4fe0d7c012a8",
            "sourceColumn": "GO Unique Key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4364c06e-e9dd-4869-81f0-c348d6bbe619",
        "partitions": [
          {
            "name": "Primary Managers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(\"PADV\", [HierarchicalNavigation=true, Query=\"-- Simple query intended to pull Primary Managers   smk  10/24/2023#(lf)#(lf)select distinct s.id_number                            \"\"GO ID\"\",#(lf)       CASE WHEN s.active_ind <> 'Y' THEN s.name||' (I)'#(lf)          ELSE s.name END                              \"\"Gift Officer Name\"\",#(lf)       u.short_desc                                    \"\"Gift Officer Team\"\",#(lf)       trunc(s.start_date)                             \"\"GO Start Dt\"\",#(lf)       trunc(s.stop_date)                              \"\"GO Stop Dt\"\",#(lf)       CASE WHEN s.active_ind = 'Y' THEN 'Active'#(lf)          ELSE 'Inactive' END                          \"\"GO Act?\"\",#(lf)       asn.prospect_id                                 \"\"Pros ID\"\",#(lf)       trunc(asn.start_date)                           \"\"Assgn Start Dt\"\",#(lf)       EXTRACT(YEAR from add_months(asn.start_date,6)) \"\"Assgn Start\"\",#(lf)       trunc(asn.stop_date)                            \"\"Assgn Stop Dt\"\",#(lf)       EXTRACT(YEAR from add_months(asn.stop_date,6))  \"\"Assgn Stop\"\",#(lf)       CASE WHEN asn.active_ind = 'Y' THEN 'Active'#(lf)          ELSE 'Inactive' END                          \"\"Assgnmt Act?\"\",#(lf)       o.short_desc                                    \"\"Office\"\",#(lf)       st.short_desc                                   \"\"Staff Type\"\",#(lf)       asn.prospect_id||asn.assignment_id_number       \"\"GO Unique Key\"\",#(lf)       s.sort                                          \"\"Sort Officer\"\",#(lf)       u.hierarchy_order                               \"\"Sort Team\"\"#(lf)from advance.staff s#(lf)inner join advance.assignment asn    ON s.id_number = asn.assignment_id_number#(lf)inner join advance.tms_unit_code u   ON s.unit_code = u.unit_code#(lf) left join advance.tms_staff_type st ON s.staff_type_code = st.staff_type_code#(lf) left join advance.tms_office o      ON s.office_code = o.office_code#(lf)where asn.assignment_type = 'PM'#(lf)and   asn.active_ind = 'Y'#(lf)and   asn.stop_date IS NULL\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"GO Start Dt\", type date}, {\"GO Stop Dt\", type date}, {\"Assgn Start Dt\", type date}, {\"Assgn Start\", type text}, {\"Assgn Stop Dt\", type date}, {\"Assgn Stop\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}