{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.120.731.0 (23.08)"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"First Camp Gift\",\"Key Measures\",\"Scholarships\",\"Data Source\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Data Source",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "This parameter allows the user to select the live database or one of the Snapshots.",
        "expression": "\"PADV\" meta [IsParameterQuery=true, List={\"PADV\", \"ADVJUL20\", \"ADVJUL21\", \"ADVOCT21\", \"ADVJAN22\", \"ADVAPR22\", \"ADVJUL22\"}, DefaultValue=\"PADV\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "25f7b3a2-7e77-47f7-9740-ef0b6f9a51a5"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "First Camp Gift",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Donor ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8abb5114-b051-4f81-bc6b-3829b526cf1c",
            "sourceColumn": "Donor ID",
            "summarizeBy": "none"
          },
          {
            "name": "Donor Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87bd1339-38be-4396-b2d4-549f4ee6dd36",
            "sourceColumn": "Donor Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prim Rec Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a328d5e-c003-4818-89ca-ad3fc9291849",
            "sourceColumn": "Prim Rec Type",
            "summarizeBy": "none"
          },
          {
            "name": "First Gift Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "556d29cd-86a9-4827-a3df-171ccc63617f",
            "sourceColumn": "First Gift Date",
            "summarizeBy": "none"
          },
          {
            "name": "Donor Nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "e639af7a-257c-47e5-a36a-3b5d1e56205a",
            "sourceColumn": "Donor Nbr",
            "summarizeBy": "distinctCount"
          },
          {
            "name": "Gift Donor Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dfd830a2-e6a3-4cc2-9f31-eb31abcda860",
            "sourceColumn": "Gift Donor Group",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Gift Dnr Grp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84343f55-baaf-457a-a5bb-1f165e9bd987",
            "sourceColumn": "Sort Gift Dnr Grp",
            "summarizeBy": "none"
          },
          {
            "name": "Record Types",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3dd8e5f5-a455-425d-b44b-c9a16922498a",
            "sourceColumn": "Record Types",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3487218-3bc5-4287-a6f5-fa222f8d051f",
            "sortByColumn": "Sort CampYr",
            "sourceColumn": "Campaign Year",
            "summarizeBy": "none"
          },
          {
            "name": "Sort CampYr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c2070b3-7d81-478f-b212-34f20ac506c8",
            "sourceColumn": "Sort CampYr",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c2727743-7f12-4b9e-8968-b0565f669e4f",
        "partitions": [
          {
            "name": "First Camp Gift-9345622b-c468-4df8-b965-1a77a87185c4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(#\"Data Source\", [HierarchicalNavigation=true, Query=\"-- This logic developed to provide a distinct count of donors and the date on which we surpassed significant milestones.#(lf)-- 16 people pulled in with multiple \"\"Gift Record Types\"\" so I built a CASE statement to resolve that issue; it will likely need#(lf)-- to be updated periodically.  smk 02/15/2022#(lf)-- Updated to use just the Production view; no duplicates. Using the current record type of the donor as opposed to the record type on the gift. smk 8/21/2023#(lf)#(lf)select distinct e.id_number                               \"\"Donor ID\"\",#(lf)       e.pref_mail_name                                   \"\"Donor Name\"\",#(lf)       rt.short_desc                                      \"\"Prim Rec Type\"\",#(lf)       advdeploy.fn_get_record_type(e.id_number)          \"\"Record Types\"\",#(lf)       CASE WHEN e.record_type_code = 'A' THEN 'Alumni'#(lf)            WHEN e.record_type_code IN ('R','FR','FW','FL') THEN 'Resident/Fellow'#(lf)            WHEN e.record_type_code IN ('P','FP') THEN 'Parent'#(lf)            WHEN e.record_type_code IN ('FS','FF') THEN 'Faculty/Staff'#(lf)            WHEN e.record_type_code IN ('S','FD') THEN 'Student'#(lf)          ELSE 'Other Individuals' END                    \"\"Gift Donor Group\"\",#(lf)       dnr.dt                                             \"\"First Gift Date\"\",#(lf)       CASE WHEN dnr.dt < '01-OCT-2016' THEN 'Pre-Campaign'#(lf)            WHEN dnr.dt BETWEEN '01-OCT-2016' AND '30-JUN-2017' THEN 'FY2017 (Partial)'#(lf)          ELSE 'FY'||extract(year from ADD_MONTHS(dnr.dt,6)) END \"\"Campaign Year\"\",#(lf)       CASE WHEN dnr.dt < '01-OCT-2016' THEN '2000'#(lf)            WHEN dnr.dt BETWEEN '01-OCT-2016' AND '30-JUN-2017' THEN '2017'#(lf)          ELSE to_char(extract(year from ADD_MONTHS(dnr.dt,6))) END \"\"Sort CampYr\"\",#(lf)       CASE WHEN e.record_type_code = 'A' THEN '1'#(lf)            WHEN e.record_type_code IN ('R','FR','FW','FL') THEN '2'#(lf)            WHEN e.record_type_code IN ('P','FP') THEN '3'#(lf)            WHEN e.record_type_code IN ('FS','FF') THEN '4'#(lf)            WHEN e.record_type_code IN ('S','FD') THEN '5'#(lf)          ELSE '6' END                                    \"\"Sort Gift Dnr Grp\"\"#(lf)from advance.entity e#(lf)left join advance.tms_record_type rt     ON e.record_type_code = rt.record_type_code#(lf)inner join (#(lf)            select xte.donor_id did, min(xp.trans_dt) dt#(lf)              from advur.mvw_total_production xp#(lf)             inner join advur.mvw_trans_entities xte ON xp.trans_nbr = xte.trans_nbr#(lf)             where xp.campaign_ind = 'Current Campaign'#(lf)             group by xte.donor_id#(lf)             )dnr ON e.id_number = dnr.did#(lf)#(lf)where e.person_or_org = 'P'#(lf)#(lf)order by \"\"First Gift Date\"\", \"\"Donor ID\"\"\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"First Gift Date\", type date}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"Donor Nbr\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Key Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "e9bf9d2f-9154-466d-b391-95f1968691f1",
        "measures": [
          {
            "name": "Donor 10k",
            "expression": [
              "",
              "    LOOKUPVALUE('First Camp Gift'[First Gift Date],'First Camp Gift'[Donor Nbr],10000)"
            ],
            "formatString": "Short Date",
            "lineageTag": "21ba25e8-400d-4193-b55b-5c053414b365"
          },
          {
            "name": "Donor 20k",
            "expression": [
              "",
              "    LOOKUPVALUE('First Camp Gift'[First Gift Date],'First Camp Gift'[Donor Nbr],20000)"
            ],
            "formatString": "Short Date",
            "lineageTag": "6a7c18ea-4811-407d-8334-800a4e7ceb7e"
          },
          {
            "name": "Donor 30k",
            "expression": [
              "",
              "    LOOKUPVALUE('First Camp Gift'[First Gift Date],'First Camp Gift'[Donor Nbr],30000)"
            ],
            "formatString": "Short Date",
            "lineageTag": "99b0f2f8-f7ec-4d55-a9a3-b3cdaaee51a8"
          },
          {
            "name": "Last Gift Date",
            "expression": [
              "",
              "    MAXA( 'First Camp Gift'[First Gift Date] )"
            ],
            "formatString": "Short Date",
            "lineageTag": "71bcf8a9-733c-4495-ba60-24031df85183"
          },
          {
            "name": "Footer Date",
            "expression": [
              "",
              "    \"Most Recent Date of New Campaign Donor: \" & [Last Gift Date]"
            ],
            "lineageTag": "bc4f5319-bfb9-4cf4-94f3-6f532dd2f476"
          },
          {
            "name": "Donor Count To Date",
            "expression": [
              "",
              "    COUNTROWS( 'First Camp Gift' )"
            ],
            "formatString": "#,0",
            "lineageTag": "1742d0fc-200a-4b44-a697-ddf35a6a31a2"
          },
          {
            "name": "Last Schol Gift Date",
            "expression": [
              "",
              "    MAXA( Scholarships[Start Dt] )"
            ],
            "formatString": "General Date",
            "lineageTag": "637955d1-3661-4cee-a8b4-1b01a1cbdd9d"
          },
          {
            "name": "Schol Footer Date",
            "expression": [
              "",
              "    \"Most Recent Scholarship Established Date: \" & [Last Schol Gift Date]"
            ],
            "lineageTag": "98abc44e-faf8-4e35-90c3-2770c48d185d"
          },
          {
            "name": "Schol Donor 100",
            "expression": [
              "",
              "    LOOKUPVALUE( Scholarships[Start Dt], Scholarships[Scholarship Count],100)"
            ],
            "formatString": "Short Date",
            "lineageTag": "7d305868-cd79-4b8b-81bd-ce1c19f52333"
          },
          {
            "name": "Schol Donor 200",
            "expression": [
              "",
              "    LOOKUPVALUE( Scholarships[Start Dt] ,Scholarships[Scholarship Count],200)"
            ],
            "formatString": "Short Date",
            "lineageTag": "b67d6d88-2a48-404e-a2f4-a8230dc1b7bf"
          },
          {
            "name": "Schol Donor 300",
            "expression": [
              "",
              "    LOOKUPVALUE( Scholarships[Start Dt],Scholarships[Scholarship Count],300)"
            ],
            "formatString": "Short Date",
            "lineageTag": "d78d459b-6558-4169-9496-58cab18be786"
          },
          {
            "name": "Scholarship Count",
            "expression": [
              "",
              "    MAXA( Scholarships[Scholarship Count] )"
            ],
            "formatString": "0",
            "lineageTag": "55f9813b-a7da-4905-ae4a-ad97e4ff3c69"
          },
          {
            "name": "Cumulative Schol Counts",
            "expression": [
              "",
              "    CALCULATE(",
              "        COUNTA( Scholarships[Alloc Cd] ),",
              "        FILTER( ALL( Scholarships ), Scholarships[Start Dt] <= MAX( Scholarships[Start Dt]) ) ",
              "        )"
            ],
            "formatString": "0",
            "lineageTag": "33b47d9b-ce8e-4d02-b898-e4ed859ab47c"
          },
          {
            "name": "Cumulative Donor Counts",
            "expression": [
              "",
              "    CALCULATE(",
              "        COUNTA( 'First Camp Gift'[Donor ID] ),",
              "        FILTER( ALL( 'First Camp Gift' ), 'First Camp Gift'[First Gift Date] <= MAX( 'First Camp Gift'[First Gift Date]) ) ",
              "        )"
            ],
            "formatString": "0",
            "lineageTag": "9826196a-42ec-41cf-8031-d423fefac811"
          },
          {
            "name": "Donor 40k",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    LOOKUPVALUE('First Camp Gift'[First Gift Date],'First Camp Gift'[Donor Nbr],40000)"
            ],
            "formatString": "Short Date",
            "lineageTag": "76eac9d4-7d50-4bff-ac44-4ff9db1bb248"
          },
          {
            "name": "Schol Donor 400",
            "expression": [
              "",
              "    LOOKUPVALUE( Scholarships[Start Dt],Scholarships[Scholarship Count],400)"
            ],
            "formatString": "Short Date",
            "lineageTag": "8490b60b-a477-42bc-a422-decffa2fdfb4"
          }
        ],
        "partitions": [
          {
            "name": "Key Measures-a4e14984-fc61-4266-9a3b-56f096e1382b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Scholarships",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Scholarship Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "027c5c6f-5f16-486b-bcf6-ff5900640ed3",
            "sourceColumn": "Scholarship Type",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Est Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "811f3814-7362-4100-bfbe-3b60510a6f83",
            "sourceColumn": "Sort Est Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Alloc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "755ace71-1890-4b5d-a9f8-ce16d3f7e4af",
            "sourceColumn": "Sort Alloc",
            "summarizeBy": "sum"
          },
          {
            "name": "Scholarship Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "365d7e67-b6d4-4b45-9d35-426304955f0c",
            "sourceColumn": "Scholarship Count",
            "summarizeBy": "distinctCount"
          },
          {
            "name": "Start Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "4db15707-b01f-4a05-b893-1c05e269dc0f",
            "sourceColumn": "Start Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Est Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8355973-5f1f-4edf-851a-08d2a19eb485",
            "sourceColumn": "Est Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Scholarship Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b937d324-31e1-4853-b24f-cd2a4e2e75f2",
            "sourceColumn": "Scholarship Status",
            "summarizeBy": "none"
          },
          {
            "name": "School",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d891da79-ad06-4f65-9187-f4ea01051986",
            "sourceColumn": "School",
            "summarizeBy": "none"
          },
          {
            "name": "Alloc Cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08d0534e-b170-4d63-befc-0a184a5bebe0",
            "sourceColumn": "Alloc Cd",
            "summarizeBy": "none"
          },
          {
            "name": "Active?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93f5ee64-9450-445d-b599-b68e382f4a1b",
            "sourceColumn": "Active?",
            "summarizeBy": "none"
          },
          {
            "name": "Allocation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6c7e48c-c6b2-4520-bf07-f1d180f9455e",
            "sourceColumn": "Allocation",
            "summarizeBy": "none"
          },
          {
            "name": "Prod Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "df8dc63c-383a-45a0-993b-a53059a2855a",
            "sourceColumn": "Prod Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3cd90c3c-4468-4545-8327-fd94cbe63e77",
            "sourceColumn": "Account",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "22fc3f3c-7064-4c98-98fb-826ae2772e72",
        "partitions": [
          {
            "name": "Scholarships-91ee10f5-2a34-4a54-9622-7c1c791e310d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(#\"Data Source\", [HierarchicalNavigation=true, Query=\"-- This logic developed to provide a distinct count of new Campaign Scholarships and the dates on which we surpassed significant milestones.#(lf)-- It is based on the logic developed for the Campaign Scholarships page in Leadership Reports.  smk 02/15/2022#(lf)-- Updated to sync with changes made in the Campaign Scholarships logic changes.  smk 9/15/2022#(lf)SELECT distinct prd1.school                                     \"\"School\"\",#(lf)       prd1.allocation_code                                     \"\"Alloc Cd\"\",#(lf)       a.is_active                                              \"\"Active?\"\",#(lf)       a.allocation_name                                        \"\"Allocation\"\",#(lf)       a.start_date                                             \"\"Start Dt\"\",#(lf)       CASE WHEN a.start_date < '01-OCT-2016' THEN 'Pre-Campaign'#(lf)          ELSE to_char(EXTRACT(YEAR FROM ADD_MONTHS(a.start_date,6))) END   \"\"Est Yr\"\",#(lf)       CASE WHEN a.allocation_code = prd1.allocation_code AND a.category3_code IN ('CS7','CS8') THEN 'New in Pre-Campaign'#(lf)            WHEN a.category3_code IN ('CS1','CS2','CS3') THEN 'New in Campaign'#(lf)          ELSE 'Pre-Existing, Funded in Campaign' END           \"\"Scholarship Status\"\",#(lf)       prd1.finance_category                                    \"\"Scholarship Type\"\",#(lf)       SUM(prd1.trans_amt)                                      \"\"Prod Total\"\",#(lf)       a.alloc_fund||a.alloc_org||'5310'                        \"\"Account\"\",#(lf)       CASE WHEN a.start_date < '01-OCT-2016' THEN '2015'#(lf)          ELSE to_char(EXTRACT(YEAR FROM ADD_MONTHS(a.start_date,6))) END   \"\"Sort Est Yr\"\",#(lf)       prd1.alloc_sort                                          \"\"Sort Alloc\"\"#(lf)FROM   advur.mvw_total_production prd1#(lf)INNER JOIN advur.mvw_total_production_ext prd2     ON prd1.trans_nbr = prd2.trans_nbr#(lf)INNER JOIN advur.mvw_allocations a                 ON prd1.allocation_code = a.allocation_code#(lf)#(lf)WHERE prd1.campaign_ind = 'Current Campaign'#(lf)AND   a.category3_code IN ('CS1','CS2','CS3','CS7','CS8')#(lf)AND   a.start_date >= '01-OCT-2016'#(lf)#(lf)group by prd1.school, prd1.allocation_code, a.is_active, a.allocation_name, a.start_date,#(lf)         CASE WHEN a.start_date < '01-OCT-2016' THEN 'Pre-Campaign'#(lf)            ELSE to_char(EXTRACT(YEAR FROM ADD_MONTHS(a.start_date,6))) END,#(lf)         CASE WHEN a.allocation_code = prd1.allocation_code AND a.category3_code IN ('CS7','CS8') THEN 'New in Pre-Campaign'#(lf)            WHEN a.category3_code IN ('CS1','CS2','CS3') THEN 'New in Campaign'#(lf)          ELSE 'Pre-Existing, Funded in Campaign' END,#(lf)         prd1.finance_category, a.alloc_fund||a.alloc_org||'5310', #(lf)         CASE WHEN a.start_date < '01-OCT-2016' THEN '2015'#(lf)            ELSE to_char(EXTRACT(YEAR FROM ADD_MONTHS(a.start_date,6))) END, prd1.alloc_sort#(lf)order by a.start_date\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Start Dt\", type date}, {\"Prod Total\", Currency.Type}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"Scholarship Count\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}