{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.120.731.0 (23.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"RA_Giving\",\"Alumni_Counts\",\"Gift Band Group\",\"Custom Sort Table\",\"Report Inventory\",\"Last Refresh Date\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "ra_giving.alloc_desc": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "RA_Giving",
                    "ConceptualProperty": "ALLOC_DESC"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Allocation Name": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "ra_giving.appeal_channel": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "RA_Giving",
                    "ConceptualProperty": "APPEAL_CHANNEL"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Appeal Channel": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "ra_giving.appeal_description": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "RA_Giving",
                    "ConceptualProperty": "APPEAL_DESCRIPTION"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Appeal Name": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "ra_giving.athletics_ind": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "RA_Giving",
                    "ConceptualProperty": "ATHLETICS_IND"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Athletics": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "ra_giving.college": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "RA_Giving",
                    "ConceptualProperty": "College"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "School": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "ra_giving.degree_year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "RA_Giving",
                    "ConceptualProperty": "DEGREE_YEAR"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Degree Year": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "ra_giving.donor_count": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "RA_Giving",
                    "ConceptualProperty": "Donor_Count"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Total Donors": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "ra_giving.fiscal_yr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "RA_Giving",
                    "ConceptualProperty": "FISCAL_YR"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Fiscal Year": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "ra_giving.participation_rate": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "RA_Giving",
                    "ConceptualProperty": "Participation_Rate"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Participation Rate": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "6567c41e-52c6-48a6-9e9e-7821ce8251d3",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DEGREE_YEAR",
        "fromTable": "RA_Giving",
        "toColumn": "DEGREE_YEAR",
        "toTable": "Alumni_Counts"
      },
      {
        "name": "abe45750-e372-46c9-9c99-18f7561a69a9",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Giving Level",
        "fromTable": "Gift Band Group",
        "toColumn": "Type",
        "toTable": "Custom Sort Table"
      },
      {
        "name": "e69c1fb5-91c4-4fa3-a884-679b35d93cde",
        "fromColumn": "Last Refresh Date Time",
        "fromTable": "Last Refresh Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d8764fbc-dd33-4d21-b9ea-1ef4dd0e0698"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "RA_Giving",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DONOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "947775c0-987b-4bd2-bf59-f775aa20a2af",
            "sourceColumn": "DONOR",
            "sourceProviderType": "Varchar2",
            "summarizeBy": "none"
          },
          {
            "name": "PREF_MAIL_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "ae93afb4-5060-4cda-a3b3-e30542087dda",
            "sourceColumn": "PREF_MAIL_NAME",
            "sourceProviderType": "Varchar2",
            "summarizeBy": "none"
          },
          {
            "name": "PREF_NAME_SORT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "d6694657-952d-477e-b6a8-455c6a0ff5a5",
            "sourceColumn": "PREF_NAME_SORT",
            "sourceProviderType": "Varchar2",
            "summarizeBy": "none"
          },
          {
            "name": "FISCAL_YR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbb17043-25cd-4c6e-a6f3-43e984369736",
            "sourceColumn": "FISCAL_YR",
            "sourceProviderType": "Varchar2",
            "summarizeBy": "none"
          },
          {
            "name": "College",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "742c7f6c-2ebf-4ecb-97c9-5ab7eff3848e",
            "sourceColumn": "College",
            "sourceProviderType": "Varchar2",
            "summarizeBy": "none"
          },
          {
            "name": "AMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"RA_Giving\",\"TableItemName\":\"Gift BAnd Final\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5655d715-394a-4e48-9f7d-dfb0a3d2521a",
            "sourceColumn": "AMT",
            "sourceProviderType": "Double",
            "summarizeBy": "sum"
          },
          {
            "name": "DEGREE_YEAR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "f267f1ae-e86e-4a29-b17a-eaa5d323e281",
            "sourceColumn": "DEGREE_YEAR",
            "sourceProviderType": "Varchar2",
            "summarizeBy": "none"
          },
          {
            "name": "ATHLETICS_IND",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38dbe2c8-0dcc-4226-a1e1-4b965137488d",
            "sourceColumn": "ATHLETICS_IND",
            "sourceProviderType": "Char",
            "summarizeBy": "none"
          },
          {
            "name": "Allocation Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a1e1ce6-bee1-4b1e-bd46-fd9be839919c",
            "sourceColumn": "Allocation Code",
            "summarizeBy": "none"
          },
          {
            "name": "APPEAL_CHANNEL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee8faba1-06ee-4a33-9d44-688179c8f225",
            "sourceColumn": "APPEAL_CHANNEL",
            "summarizeBy": "none"
          },
          {
            "name": "TRANS_NBR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2dc0a5c-8255-4644-8d00-cfc1e7eddd25",
            "sourceColumn": "TRANS_NBR",
            "summarizeBy": "none"
          },
          {
            "name": "Gift BAnd Final",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"r\",\"Entity\":\"RA_Giving\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"r\"}},\"Property\":\"AMT\"}}],\"GroupItems\":[{\"DisplayName\":\"(Blank)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"$1,000 to $2,499\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"r\"}},\"Property\":\"AMT\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"1000D\"}}],[{\"Literal\":{\"Value\":\"1002D\"}}],[{\"Literal\":{\"Value\":\"1008D\"}}],[{\"Literal\":{\"Value\":\"1010D\"}}],[{\"Literal\":{\"Value\":\"1011D\"}}],[{\"Literal\":{\"Value\":\"1015D\"}}],[{\"Literal\":{\"Value\":\"1020D\"}}],[{\"Literal\":{\"Value\":\"1022D\"}}],[{\"Literal\":{\"Value\":\"1025D\"}}],[{\"Literal\":{\"Value\":\"1025.2D\"}}],[{\"Literal\":{\"Value\":\"1027.5D\"}}],[{\"Literal\":{\"Value\":\"1033D\"}}],[{\"Literal\":{\"Value\":\"1034.4D\"}}],[{\"Literal\":{\"Value\":\"1040D\"}}],[{\"Literal\":{\"Value\":\"1042D\"}}],[{\"Literal\":{\"Value\":\"1045D\"}}],[{\"Literal\":{\"Value\":\"1046D\"}}],[{\"Literal\":{\"Value\":\"1050D\"}}],[{\"Literal\":{\"Value\":\"1050.5D\"}}],[{\"Literal\":{\"Value\":\"1052D\"}}],[{\"Literal\":{\"Value\":\"1059.9D\"}}],[{\"Literal\":{\"Value\":\"1061D\"}}],[{\"Literal\":{\"Value\":\"1062.5D\"}}],[{\"Literal\":{\"Value\":\"1064D\"}}],[{\"Literal\":{\"Value\":\"1065D\"}}],[{\"Literal\":{\"Value\":\"1065.45D\"}}],[{\"Literal\":{\"Value\":\"1066.67D\"}}],[{\"Literal\":{\"Value\":\"1075D\"}}],[{\"Literal\":{\"Value\":\"1080D\"}}],[{\"Literal\":{\"Value\":\"1090.5D\"}}],[{\"Literal\":{\"Value\":\"1092D\"}}],[{\"Literal\":{\"Value\":\"1096.69D\"}}],[{\"Literal\":{\"Value\":\"1100D\"}}],[{\"Literal\":{\"Value\":\"1108.8500000000001D\"}}],[{\"Literal\":{\"Value\":\"1112.5D\"}}],[{\"Literal\":{\"Value\":\"1115D\"}}],[{\"Literal\":{\"Value\":\"1115.32D\"}}],[{\"Literal\":{\"Value\":\"1122D\"}}],[{\"Literal\":{\"Value\":\"1125D\"}}],[{\"Literal\":{\"Value\":\"1130D\"}}],[{\"Literal\":{\"Value\":\"1134D\"}}],[{\"Literal\":{\"Value\":\"1135D\"}}],[{\"Literal\":{\"Value\":\"1135.4D\"}}],[{\"Literal\":{\"Value\":\"1140D\"}}],[{\"Literal\":{\"Value\":\"1145D\"}}],[{\"Literal\":{\"Value\":\"1150D\"}}],[{\"Literal\":{\"Value\":\"1153.4D\"}}],[{\"Literal\":{\"Value\":\"1153.8500000000001D\"}}],[{\"Literal\":{\"Value\":\"1157D\"}}],[{\"Literal\":{\"Value\":\"1158.8500000000001D\"}}],[{\"Literal\":{\"Value\":\"1160D\"}}],[{\"Literal\":{\"Value\":\"1160.97D\"}}],[{\"Literal\":{\"Value\":\"1164.1000000000001D\"}}],[{\"Literal\":{\"Value\":\"1167.67D\"}}],[{\"Literal\":{\"Value\":\"1175D\"}}],[{\"Literal\":{\"Value\":\"1180D\"}}],[{\"Literal\":{\"Value\":\"1182.5D\"}}],[{\"Literal\":{\"Value\":\"1189D\"}}],[{\"Literal\":{\"Value\":\"1192D\"}}],[{\"Literal\":{\"Value\":\"1192.84D\"}}],[{\"Literal\":{\"Value\":\"1193D\"}}],[{\"Literal\":{\"Value\":\"1193.2D\"}}],[{\"Literal\":{\"Value\":\"1196D\"}}],[{\"Literal\":{\"Value\":\"1198.8500000000001D\"}}],[{\"Literal\":{\"Value\":\"1199D\"}}],[{\"Literal\":{\"Value\":\"1200D\"}}],[{\"Literal\":{\"Value\":\"1205D\"}}],[{\"Literal\":{\"Value\":\"1207.5D\"}}],[{\"Literal\":{\"Value\":\"1215.84D\"}}],[{\"Literal\":{\"Value\":\"1222.3600000000001D\"}}],[{\"Literal\":{\"Value\":\"1225D\"}}],[{\"Literal\":{\"Value\":\"1226D\"}}],[{\"Literal\":{\"Value\":\"1230D\"}}],[{\"Literal\":{\"Value\":\"1232.5D\"}}],[{\"Literal\":{\"Value\":\"1241D\"}}],[{\"Literal\":{\"Value\":\"1244.65D\"}}],[{\"Literal\":{\"Value\":\"1246D\"}}],[{\"Literal\":{\"Value\":\"1250D\"}}],[{\"Literal\":{\"Value\":\"1254.8D\"}}],[{\"Literal\":{\"Value\":\"1255.8D\"}}],[{\"Literal\":{\"Value\":\"1259D\"}}],[{\"Literal\":{\"Value\":\"1260D\"}}],[{\"Literal\":{\"Value\":\"1261D\"}}],[{\"Literal\":{\"Value\":\"1261.8D\"}}],[{\"Literal\":{\"Value\":\"1264.3600000000001D\"}}],[{\"Literal\":{\"Value\":\"1269.64D\"}}],[{\"Literal\":{\"Value\":\"1270D\"}}],[{\"Literal\":{\"Value\":\"1274.59D\"}}],[{\"Literal\":{\"Value\":\"1275D\"}}],[{\"Literal\":{\"Value\":\"1276D\"}}],[{\"Literal\":{\"Value\":\"1285D\"}}],[{\"Literal\":{\"Value\":\"1286D\"}}],[{\"Literal\":{\"Value\":\"1287.5D\"}}],[{\"Literal\":{\"Value\":\"1295D\"}}],[{\"Literal\":{\"Value\":\"1300D\"}}],[{\"Literal\":{\"Value\":\"1307.84D\"}}],[{\"Literal\":{\"Value\":\"1309D\"}}],[{\"Literal\":{\"Value\":\"1311D\"}}],[{\"Literal\":{\"Value\":\"1319.83D\"}}],[{\"Literal\":{\"Value\":\"1333D\"}}],[{\"Literal\":{\"Value\":\"1336D\"}}],[{\"Literal\":{\"Value\":\"1337D\"}}],[{\"Literal\":{\"Value\":\"1344D\"}}],[{\"Literal\":{\"Value\":\"1350D\"}}],[{\"Literal\":{\"Value\":\"1355D\"}}],[{\"Literal\":{\"Value\":\"1357.71D\"}}],[{\"Literal\":{\"Value\":\"1366D\"}}],[{\"Literal\":{\"Value\":\"1369.3600000000001D\"}}],[{\"Literal\":{\"Value\":\"1370D\"}}],[{\"Literal\":{\"Value\":\"1371.43D\"}}],[{\"Literal\":{\"Value\":\"1372.5D\"}}],[{\"Literal\":{\"Value\":\"1375D\"}}],[{\"Literal\":{\"Value\":\"1377D\"}}],[{\"Literal\":{\"Value\":\"1378.4D\"}}],[{\"Literal\":{\"Value\":\"1379.18D\"}}],[{\"Literal\":{\"Value\":\"1386.28D\"}}],[{\"Literal\":{\"Value\":\"1395.3700000000001D\"}}],[{\"Literal\":{\"Value\":\"1395.38D\"}}],[{\"Literal\":{\"Value\":\"1400D\"}}],[{\"Literal\":{\"Value\":\"1407.1000000000001D\"}}],[{\"Literal\":{\"Value\":\"1415.15D\"}}],[{\"Literal\":{\"Value\":\"1425D\"}}],[{\"Literal\":{\"Value\":\"1437D\"}}],[{\"Literal\":{\"Value\":\"1442D\"}}],[{\"Literal\":{\"Value\":\"1450D\"}}],[{\"Literal\":{\"Value\":\"1465D\"}}],[{\"Literal\":{\"Value\":\"1466D\"}}],[{\"Literal\":{\"Value\":\"1475D\"}}],[{\"Literal\":{\"Value\":\"1500D\"}}],[{\"Literal\":{\"Value\":\"1514.55D\"}}],[{\"Literal\":{\"Value\":\"1517.3D\"}}],[{\"Literal\":{\"Value\":\"1520D\"}}],[{\"Literal\":{\"Value\":\"1543D\"}}],[{\"Literal\":{\"Value\":\"1543.8D\"}}],[{\"Literal\":{\"Value\":\"1550D\"}}],[{\"Literal\":{\"Value\":\"1575D\"}}],[{\"Literal\":{\"Value\":\"1578D\"}}],[{\"Literal\":{\"Value\":\"1581D\"}}],[{\"Literal\":{\"Value\":\"1585D\"}}],[{\"Literal\":{\"Value\":\"1598D\"}}],[{\"Literal\":{\"Value\":\"1600D\"}}],[{\"Literal\":{\"Value\":\"1610D\"}}],[{\"Literal\":{\"Value\":\"1620D\"}}],[{\"Literal\":{\"Value\":\"1635D\"}}],[{\"Literal\":{\"Value\":\"1637.3D\"}}],[{\"Literal\":{\"Value\":\"1646.8D\"}}],[{\"Literal\":{\"Value\":\"1650D\"}}],[{\"Literal\":{\"Value\":\"1663.2D\"}}],[{\"Literal\":{\"Value\":\"1665D\"}}],[{\"Literal\":{\"Value\":\"1670D\"}}],[{\"Literal\":{\"Value\":\"1673.63D\"}}],[{\"Literal\":{\"Value\":\"1692D\"}}],[{\"Literal\":{\"Value\":\"1693.2D\"}}],[{\"Literal\":{\"Value\":\"1695D\"}}],[{\"Literal\":{\"Value\":\"1700D\"}}],[{\"Literal\":{\"Value\":\"1707.4D\"}}],[{\"Literal\":{\"Value\":\"1711.4D\"}}],[{\"Literal\":{\"Value\":\"1725D\"}}],[{\"Literal\":{\"Value\":\"1738D\"}}],[{\"Literal\":{\"Value\":\"1742.65D\"}}],[{\"Literal\":{\"Value\":\"1750D\"}}],[{\"Literal\":{\"Value\":\"1756.2D\"}}],[{\"Literal\":{\"Value\":\"1763D\"}}],[{\"Literal\":{\"Value\":\"1774D\"}}],[{\"Literal\":{\"Value\":\"1786.46D\"}}],[{\"Literal\":{\"Value\":\"1797.2D\"}}],[{\"Literal\":{\"Value\":\"1800D\"}}],[{\"Literal\":{\"Value\":\"1810D\"}}],[{\"Literal\":{\"Value\":\"1816.5D\"}}],[{\"Literal\":{\"Value\":\"1850D\"}}],[{\"Literal\":{\"Value\":\"1853.46D\"}}],[{\"Literal\":{\"Value\":\"1870D\"}}],[{\"Literal\":{\"Value\":\"1875D\"}}],[{\"Literal\":{\"Value\":\"1882.04D\"}}],[{\"Literal\":{\"Value\":\"1894D\"}}],[{\"Literal\":{\"Value\":\"1900D\"}}],[{\"Literal\":{\"Value\":\"1915D\"}}],[{\"Literal\":{\"Value\":\"1941.4D\"}}],[{\"Literal\":{\"Value\":\"1950D\"}}],[{\"Literal\":{\"Value\":\"1978.1000000000001D\"}}],[{\"Literal\":{\"Value\":\"1981.3400000000001D\"}}],[{\"Literal\":{\"Value\":\"2000D\"}}],[{\"Literal\":{\"Value\":\"2014D\"}}],[{\"Literal\":{\"Value\":\"2016D\"}}],[{\"Literal\":{\"Value\":\"2083.5D\"}}],[{\"Literal\":{\"Value\":\"2100D\"}}],[{\"Literal\":{\"Value\":\"2102D\"}}],[{\"Literal\":{\"Value\":\"2127.87D\"}}],[{\"Literal\":{\"Value\":\"2130D\"}}],[{\"Literal\":{\"Value\":\"2150D\"}}],[{\"Literal\":{\"Value\":\"2200D\"}}],[{\"Literal\":{\"Value\":\"2218.4D\"}}],[{\"Literal\":{\"Value\":\"2238.26D\"}}],[{\"Literal\":{\"Value\":\"2300D\"}}],[{\"Literal\":{\"Value\":\"2300.12D\"}}],[{\"Literal\":{\"Value\":\"2350D\"}}],[{\"Literal\":{\"Value\":\"2391D\"}}],[{\"Literal\":{\"Value\":\"2400D\"}}],[{\"Literal\":{\"Value\":\"2450D\"}}]]}}},{\"DisplayName\":\"$10,000 to $24,999\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"r\"}},\"Property\":\"AMT\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"10000D\"}}],[{\"Literal\":{\"Value\":\"12340.2D\"}}],[{\"Literal\":{\"Value\":\"12500D\"}}],[{\"Literal\":{\"Value\":\"20000D\"}}]]}}},{\"DisplayName\":\"$100 to $249\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"r\"}},\"Property\":\"AMT\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"100D\"}}],[{\"Literal\":{\"Value\":\"100.03D\"}}],[{\"Literal\":{\"Value\":\"100.5D\"}}],[{\"Literal\":{\"Value\":\"101D\"}}],[{\"Literal\":{\"Value\":\"102D\"}}],[{\"Literal\":{\"Value\":\"102.86D\"}}],[{\"Literal\":{\"Value\":\"103D\"}}],[{\"Literal\":{\"Value\":\"103.13D\"}}],[{\"Literal\":{\"Value\":\"105D\"}}],[{\"Literal\":{\"Value\":\"107.5D\"}}],[{\"Literal\":{\"Value\":\"108.2D\"}}],[{\"Literal\":{\"Value\":\"109.10000000000001D\"}}],[{\"Literal\":{\"Value\":\"110D\"}}],[{\"Literal\":{\"Value\":\"110.02D\"}}],[{\"Literal\":{\"Value\":\"110.03D\"}}],[{\"Literal\":{\"Value\":\"110.05D\"}}],[{\"Literal\":{\"Value\":\"112.5D\"}}],[{\"Literal\":{\"Value\":\"114D\"}}],[{\"Literal\":{\"Value\":\"115D\"}}],[{\"Literal\":{\"Value\":\"115.5D\"}}],[{\"Literal\":{\"Value\":\"116D\"}}],[{\"Literal\":{\"Value\":\"119D\"}}],[{\"Literal\":{\"Value\":\"120D\"}}],[{\"Literal\":{\"Value\":\"120.5D\"}}],[{\"Literal\":{\"Value\":\"120.83D\"}}],[{\"Literal\":{\"Value\":\"122.5D\"}}],[{\"Literal\":{\"Value\":\"122.66D\"}}],[{\"Literal\":{\"Value\":\"123D\"}}],[{\"Literal\":{\"Value\":\"123.10000000000001D\"}}],[{\"Literal\":{\"Value\":\"124.25D\"}}],[{\"Literal\":{\"Value\":\"124.99000000000001D\"}}],[{\"Literal\":{\"Value\":\"125D\"}}],[{\"Literal\":{\"Value\":\"125.12D\"}}],[{\"Literal\":{\"Value\":\"125.5D\"}}],[{\"Literal\":{\"Value\":\"125.8D\"}}],[{\"Literal\":{\"Value\":\"126.24000000000001D\"}}],[{\"Literal\":{\"Value\":\"130D\"}}],[{\"Literal\":{\"Value\":\"131.25D\"}}],[{\"Literal\":{\"Value\":\"132.86D\"}}],[{\"Literal\":{\"Value\":\"133.33D\"}}],[{\"Literal\":{\"Value\":\"134.76D\"}}],[{\"Literal\":{\"Value\":\"135D\"}}],[{\"Literal\":{\"Value\":\"136.5D\"}}],[{\"Literal\":{\"Value\":\"137D\"}}],[{\"Literal\":{\"Value\":\"137.5D\"}}],[{\"Literal\":{\"Value\":\"140D\"}}],[{\"Literal\":{\"Value\":\"142.79D\"}}],[{\"Literal\":{\"Value\":\"142.86D\"}}],[{\"Literal\":{\"Value\":\"142.87D\"}}],[{\"Literal\":{\"Value\":\"144D\"}}],[{\"Literal\":{\"Value\":\"144.38D\"}}],[{\"Literal\":{\"Value\":\"145D\"}}],[{\"Literal\":{\"Value\":\"145.9D\"}}],[{\"Literal\":{\"Value\":\"146D\"}}],[{\"Literal\":{\"Value\":\"147.5D\"}}],[{\"Literal\":{\"Value\":\"147.70000000000002D\"}}],[{\"Literal\":{\"Value\":\"148D\"}}],[{\"Literal\":{\"Value\":\"148.5D\"}}],[{\"Literal\":{\"Value\":\"150D\"}}],[{\"Literal\":{\"Value\":\"150.25D\"}}],[{\"Literal\":{\"Value\":\"152.5D\"}}],[{\"Literal\":{\"Value\":\"153.85D\"}}],[{\"Literal\":{\"Value\":\"153.95000000000002D\"}}],[{\"Literal\":{\"Value\":\"155D\"}}],[{\"Literal\":{\"Value\":\"157.5D\"}}],[{\"Literal\":{\"Value\":\"157.9D\"}}],[{\"Literal\":{\"Value\":\"159.1D\"}}],[{\"Literal\":{\"Value\":\"160D\"}}],[{\"Literal\":{\"Value\":\"162.5D\"}}],[{\"Literal\":{\"Value\":\"163.5D\"}}],[{\"Literal\":{\"Value\":\"164.06D\"}}],[{\"Literal\":{\"Value\":\"165D\"}}],[{\"Literal\":{\"Value\":\"165.25D\"}}],[{\"Literal\":{\"Value\":\"166.5D\"}}],[{\"Literal\":{\"Value\":\"166.59D\"}}],[{\"Literal\":{\"Value\":\"166.66D\"}}],[{\"Literal\":{\"Value\":\"166.67000000000002D\"}}],[{\"Literal\":{\"Value\":\"166.68D\"}}],[{\"Literal\":{\"Value\":\"167D\"}}],[{\"Literal\":{\"Value\":\"168.65D\"}}],[{\"Literal\":{\"Value\":\"168.75D\"}}],[{\"Literal\":{\"Value\":\"169D\"}}],[{\"Literal\":{\"Value\":\"170D\"}}],[{\"Literal\":{\"Value\":\"171.87D\"}}],[{\"Literal\":{\"Value\":\"171.88D\"}}],[{\"Literal\":{\"Value\":\"175D\"}}],[{\"Literal\":{\"Value\":\"175.20000000000002D\"}}],[{\"Literal\":{\"Value\":\"177.5D\"}}],[{\"Literal\":{\"Value\":\"178.5D\"}}],[{\"Literal\":{\"Value\":\"180D\"}}],[{\"Literal\":{\"Value\":\"181D\"}}],[{\"Literal\":{\"Value\":\"181.20000000000002D\"}}],[{\"Literal\":{\"Value\":\"181.8D\"}}],[{\"Literal\":{\"Value\":\"182.5D\"}}],[{\"Literal\":{\"Value\":\"184D\"}}],[{\"Literal\":{\"Value\":\"185D\"}}],[{\"Literal\":{\"Value\":\"186.5D\"}}],[{\"Literal\":{\"Value\":\"187.5D\"}}],[{\"Literal\":{\"Value\":\"188D\"}}],[{\"Literal\":{\"Value\":\"190.1D\"}}],[{\"Literal\":{\"Value\":\"192.5D\"}}],[{\"Literal\":{\"Value\":\"198D\"}}],[{\"Literal\":{\"Value\":\"200D\"}}],[{\"Literal\":{\"Value\":\"200.5D\"}}],[{\"Literal\":{\"Value\":\"204.57D\"}}],[{\"Literal\":{\"Value\":\"205D\"}}],[{\"Literal\":{\"Value\":\"206.25D\"}}],[{\"Literal\":{\"Value\":\"207D\"}}],[{\"Literal\":{\"Value\":\"207.4D\"}}],[{\"Literal\":{\"Value\":\"207.5D\"}}],[{\"Literal\":{\"Value\":\"208.32D\"}}],[{\"Literal\":{\"Value\":\"208.33D\"}}],[{\"Literal\":{\"Value\":\"208.34D\"}}],[{\"Literal\":{\"Value\":\"210D\"}}],[{\"Literal\":{\"Value\":\"211D\"}}],[{\"Literal\":{\"Value\":\"212.5D\"}}],[{\"Literal\":{\"Value\":\"213.8D\"}}],[{\"Literal\":{\"Value\":\"216D\"}}],[{\"Literal\":{\"Value\":\"217.5D\"}}],[{\"Literal\":{\"Value\":\"218.75D\"}}],[{\"Literal\":{\"Value\":\"220D\"}}],[{\"Literal\":{\"Value\":\"223D\"}}],[{\"Literal\":{\"Value\":\"224D\"}}],[{\"Literal\":{\"Value\":\"225D\"}}],[{\"Literal\":{\"Value\":\"228D\"}}],[{\"Literal\":{\"Value\":\"228.5D\"}}],[{\"Literal\":{\"Value\":\"229.16D\"}}],[{\"Literal\":{\"Value\":\"229.17000000000002D\"}}],[{\"Literal\":{\"Value\":\"229.18D\"}}],[{\"Literal\":{\"Value\":\"230D\"}}],[{\"Literal\":{\"Value\":\"231D\"}}],[{\"Literal\":{\"Value\":\"235D\"}}],[{\"Literal\":{\"Value\":\"237D\"}}],[{\"Literal\":{\"Value\":\"237.5D\"}}],[{\"Literal\":{\"Value\":\"240D\"}}],[{\"Literal\":{\"Value\":\"246.8D\"}}],[{\"Literal\":{\"Value\":\"248.1D\"}}],[{\"Literal\":{\"Value\":\"248.36D\"}}]]}}},{\"DisplayName\":\"$2,500 to $4,999\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"r\"}},\"Property\":\"AMT\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"2500D\"}}],[{\"Literal\":{\"Value\":\"2550D\"}}],[{\"Literal\":{\"Value\":\"2600D\"}}],[{\"Literal\":{\"Value\":\"2666D\"}}],[{\"Literal\":{\"Value\":\"2750D\"}}],[{\"Literal\":{\"Value\":\"2800D\"}}],[{\"Literal\":{\"Value\":\"2888D\"}}],[{\"Literal\":{\"Value\":\"2892D\"}}],[{\"Literal\":{\"Value\":\"3000D\"}}],[{\"Literal\":{\"Value\":\"3042D\"}}],[{\"Literal\":{\"Value\":\"3106D\"}}],[{\"Literal\":{\"Value\":\"3325D\"}}],[{\"Literal\":{\"Value\":\"3418.91D\"}}],[{\"Literal\":{\"Value\":\"3500D\"}}],[{\"Literal\":{\"Value\":\"3600D\"}}],[{\"Literal\":{\"Value\":\"3800D\"}}],[{\"Literal\":{\"Value\":\"3850D\"}}],[{\"Literal\":{\"Value\":\"4000D\"}}],[{\"Literal\":{\"Value\":\"4750D\"}}]]}}},{\"DisplayName\":\"$25 to $49\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"r\"}},\"Property\":\"AMT\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"25D\"}}],[{\"Literal\":{\"Value\":\"25.18D\"}}],[{\"Literal\":{\"Value\":\"26D\"}}],[{\"Literal\":{\"Value\":\"26.2D\"}}],[{\"Literal\":{\"Value\":\"26.66D\"}}],[{\"Literal\":{\"Value\":\"26.67D\"}}],[{\"Literal\":{\"Value\":\"26.900000000000002D\"}}],[{\"Literal\":{\"Value\":\"27D\"}}],[{\"Literal\":{\"Value\":\"27.5D\"}}],[{\"Literal\":{\"Value\":\"28D\"}}],[{\"Literal\":{\"Value\":\"28.080000000000002D\"}}],[{\"Literal\":{\"Value\":\"28.46D\"}}],[{\"Literal\":{\"Value\":\"29D\"}}],[{\"Literal\":{\"Value\":\"30D\"}}],[{\"Literal\":{\"Value\":\"31.25D\"}}],[{\"Literal\":{\"Value\":\"31.5D\"}}],[{\"Literal\":{\"Value\":\"31.82D\"}}],[{\"Literal\":{\"Value\":\"32D\"}}],[{\"Literal\":{\"Value\":\"32.5D\"}}],[{\"Literal\":{\"Value\":\"32.8D\"}}],[{\"Literal\":{\"Value\":\"33D\"}}],[{\"Literal\":{\"Value\":\"33.33D\"}}],[{\"Literal\":{\"Value\":\"33.34D\"}}],[{\"Literal\":{\"Value\":\"33.5D\"}}],[{\"Literal\":{\"Value\":\"34D\"}}],[{\"Literal\":{\"Value\":\"34.800000000000004D\"}}],[{\"Literal\":{\"Value\":\"34.99D\"}}],[{\"Literal\":{\"Value\":\"35D\"}}],[{\"Literal\":{\"Value\":\"35.800000000000004D\"}}],[{\"Literal\":{\"Value\":\"36D\"}}],[{\"Literal\":{\"Value\":\"37.5D\"}}],[{\"Literal\":{\"Value\":\"38D\"}}],[{\"Literal\":{\"Value\":\"38.050000000000004D\"}}],[{\"Literal\":{\"Value\":\"38.4D\"}}],[{\"Literal\":{\"Value\":\"40D\"}}],[{\"Literal\":{\"Value\":\"41.67D\"}}],[{\"Literal\":{\"Value\":\"41.68D\"}}],[{\"Literal\":{\"Value\":\"41.94D\"}}],[{\"Literal\":{\"Value\":\"42D\"}}],[{\"Literal\":{\"Value\":\"42.5D\"}}],[{\"Literal\":{\"Value\":\"42.67D\"}}],[{\"Literal\":{\"Value\":\"43D\"}}],[{\"Literal\":{\"Value\":\"43.2D\"}}],[{\"Literal\":{\"Value\":\"43.75D\"}}],[{\"Literal\":{\"Value\":\"45D\"}}],[{\"Literal\":{\"Value\":\"45.4D\"}}],[{\"Literal\":{\"Value\":\"45.74D\"}}],[{\"Literal\":{\"Value\":\"46D\"}}],[{\"Literal\":{\"Value\":\"46.5D\"}}],[{\"Literal\":{\"Value\":\"46.87D\"}}],[{\"Literal\":{\"Value\":\"46.88D\"}}],[{\"Literal\":{\"Value\":\"47.5D\"}}],[{\"Literal\":{\"Value\":\"47.74D\"}}],[{\"Literal\":{\"Value\":\"47.76D\"}}],[{\"Literal\":{\"Value\":\"48.75D\"}}],[{\"Literal\":{\"Value\":\"48.76D\"}}],[{\"Literal\":{\"Value\":\"49D\"}}],[{\"Literal\":{\"Value\":\"49.5D\"}}]]}}},{\"DisplayName\":\"$25,000 to $49,999\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"r\"}},\"Property\":\"AMT\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"25000D\"}}],[{\"Literal\":{\"Value\":\"30000D\"}}],[{\"Literal\":{\"Value\":\"40000D\"}}]]}}},{\"DisplayName\":\"$250 to $499\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"r\"}},\"Property\":\"AMT\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"250D\"}}],[{\"Literal\":{\"Value\":\"250.25D\"}}],[{\"Literal\":{\"Value\":\"250.5D\"}}],[{\"Literal\":{\"Value\":\"253.37D\"}}],[{\"Literal\":{\"Value\":\"253.44D\"}}],[{\"Literal\":{\"Value\":\"255D\"}}],[{\"Literal\":{\"Value\":\"256.25D\"}}],[{\"Literal\":{\"Value\":\"257.5D\"}}],[{\"Literal\":{\"Value\":\"260D\"}}],[{\"Literal\":{\"Value\":\"262.5D\"}}],[{\"Literal\":{\"Value\":\"265D\"}}],[{\"Literal\":{\"Value\":\"268.5D\"}}],[{\"Literal\":{\"Value\":\"268.65D\"}}],[{\"Literal\":{\"Value\":\"270D\"}}],[{\"Literal\":{\"Value\":\"271.99D\"}}],[{\"Literal\":{\"Value\":\"272.2D\"}}],[{\"Literal\":{\"Value\":\"272.5D\"}}],[{\"Literal\":{\"Value\":\"275D\"}}],[{\"Literal\":{\"Value\":\"277.5D\"}}],[{\"Literal\":{\"Value\":\"280D\"}}],[{\"Literal\":{\"Value\":\"281.25D\"}}],[{\"Literal\":{\"Value\":\"282.27D\"}}],[{\"Literal\":{\"Value\":\"283.33D\"}}],[{\"Literal\":{\"Value\":\"283.34000000000003D\"}}],[{\"Literal\":{\"Value\":\"285.5D\"}}],[{\"Literal\":{\"Value\":\"287.5D\"}}],[{\"Literal\":{\"Value\":\"287.83D\"}}],[{\"Literal\":{\"Value\":\"288.6D\"}}],[{\"Literal\":{\"Value\":\"288.75D\"}}],[{\"Literal\":{\"Value\":\"290D\"}}],[{\"Literal\":{\"Value\":\"292.5D\"}}],[{\"Literal\":{\"Value\":\"295D\"}}],[{\"Literal\":{\"Value\":\"296.67D\"}}],[{\"Literal\":{\"Value\":\"297.5D\"}}],[{\"Literal\":{\"Value\":\"298.3D\"}}],[{\"Literal\":{\"Value\":\"299.15000000000003D\"}}],[{\"Literal\":{\"Value\":\"300D\"}}],[{\"Literal\":{\"Value\":\"305D\"}}],[{\"Literal\":{\"Value\":\"307.40000000000003D\"}}],[{\"Literal\":{\"Value\":\"307.5D\"}}],[{\"Literal\":{\"Value\":\"308.3D\"}}],[{\"Literal\":{\"Value\":\"309.40000000000003D\"}}],[{\"Literal\":{\"Value\":\"310D\"}}],[{\"Literal\":{\"Value\":\"312.5D\"}}],[{\"Literal\":{\"Value\":\"315D\"}}],[{\"Literal\":{\"Value\":\"318.75D\"}}],[{\"Literal\":{\"Value\":\"320D\"}}],[{\"Literal\":{\"Value\":\"321.7D\"}}],[{\"Literal\":{\"Value\":\"323.3D\"}}],[{\"Literal\":{\"Value\":\"325D\"}}],[{\"Literal\":{\"Value\":\"326.73D\"}}],[{\"Literal\":{\"Value\":\"328.2D\"}}],[{\"Literal\":{\"Value\":\"330D\"}}],[{\"Literal\":{\"Value\":\"332D\"}}],[{\"Literal\":{\"Value\":\"333D\"}}],[{\"Literal\":{\"Value\":\"333.33D\"}}],[{\"Literal\":{\"Value\":\"333.34000000000003D\"}}],[{\"Literal\":{\"Value\":\"335.40000000000003D\"}}],[{\"Literal\":{\"Value\":\"335.8D\"}}],[{\"Literal\":{\"Value\":\"337.5D\"}}],[{\"Literal\":{\"Value\":\"340D\"}}],[{\"Literal\":{\"Value\":\"342.45D\"}}],[{\"Literal\":{\"Value\":\"342.5D\"}}],[{\"Literal\":{\"Value\":\"343.75D\"}}],[{\"Literal\":{\"Value\":\"345D\"}}],[{\"Literal\":{\"Value\":\"349.2D\"}}],[{\"Literal\":{\"Value\":\"350D\"}}],[{\"Literal\":{\"Value\":\"354D\"}}],[{\"Literal\":{\"Value\":\"360D\"}}],[{\"Literal\":{\"Value\":\"364.29D\"}}],[{\"Literal\":{\"Value\":\"366.5D\"}}],[{\"Literal\":{\"Value\":\"367D\"}}],[{\"Literal\":{\"Value\":\"368D\"}}],[{\"Literal\":{\"Value\":\"370D\"}}],[{\"Literal\":{\"Value\":\"373D\"}}],[{\"Literal\":{\"Value\":\"375D\"}}],[{\"Literal\":{\"Value\":\"375.01D\"}}],[{\"Literal\":{\"Value\":\"378D\"}}],[{\"Literal\":{\"Value\":\"380D\"}}],[{\"Literal\":{\"Value\":\"381.90000000000003D\"}}],[{\"Literal\":{\"Value\":\"386D\"}}],[{\"Literal\":{\"Value\":\"386.55D\"}}],[{\"Literal\":{\"Value\":\"387.5D\"}}],[{\"Literal\":{\"Value\":\"387.8D\"}}],[{\"Literal\":{\"Value\":\"389.2D\"}}],[{\"Literal\":{\"Value\":\"389.7D\"}}],[{\"Literal\":{\"Value\":\"390D\"}}],[{\"Literal\":{\"Value\":\"391D\"}}],[{\"Literal\":{\"Value\":\"392.5D\"}}],[{\"Literal\":{\"Value\":\"393.5D\"}}],[{\"Literal\":{\"Value\":\"395D\"}}],[{\"Literal\":{\"Value\":\"397.76D\"}}],[{\"Literal\":{\"Value\":\"398.68D\"}}],[{\"Literal\":{\"Value\":\"399.98D\"}}],[{\"Literal\":{\"Value\":\"400D\"}}],[{\"Literal\":{\"Value\":\"402D\"}}],[{\"Literal\":{\"Value\":\"404D\"}}],[{\"Literal\":{\"Value\":\"405D\"}}],[{\"Literal\":{\"Value\":\"410D\"}}],[{\"Literal\":{\"Value\":\"412.21000000000004D\"}}],[{\"Literal\":{\"Value\":\"412.5D\"}}],[{\"Literal\":{\"Value\":\"415D\"}}],[{\"Literal\":{\"Value\":\"415.15000000000003D\"}}],[{\"Literal\":{\"Value\":\"416.66D\"}}],[{\"Literal\":{\"Value\":\"416.67D\"}}],[{\"Literal\":{\"Value\":\"417.5D\"}}],[{\"Literal\":{\"Value\":\"420D\"}}],[{\"Literal\":{\"Value\":\"425D\"}}],[{\"Literal\":{\"Value\":\"426.92D\"}}],[{\"Literal\":{\"Value\":\"427D\"}}],[{\"Literal\":{\"Value\":\"430D\"}}],[{\"Literal\":{\"Value\":\"430.6D\"}}],[{\"Literal\":{\"Value\":\"431.8D\"}}],[{\"Literal\":{\"Value\":\"432.5D\"}}],[{\"Literal\":{\"Value\":\"433.75D\"}}],[{\"Literal\":{\"Value\":\"435D\"}}],[{\"Literal\":{\"Value\":\"437.5D\"}}],[{\"Literal\":{\"Value\":\"440D\"}}],[{\"Literal\":{\"Value\":\"442.5D\"}}],[{\"Literal\":{\"Value\":\"443.5D\"}}],[{\"Literal\":{\"Value\":\"443.7D\"}}],[{\"Literal\":{\"Value\":\"445D\"}}],[{\"Literal\":{\"Value\":\"447.5D\"}}],[{\"Literal\":{\"Value\":\"448.1D\"}}],[{\"Literal\":{\"Value\":\"450D\"}}],[{\"Literal\":{\"Value\":\"452.6D\"}}],[{\"Literal\":{\"Value\":\"454D\"}}],[{\"Literal\":{\"Value\":\"455D\"}}],[{\"Literal\":{\"Value\":\"458.33D\"}}],[{\"Literal\":{\"Value\":\"458.34000000000003D\"}}],[{\"Literal\":{\"Value\":\"460D\"}}],[{\"Literal\":{\"Value\":\"462.5D\"}}],[{\"Literal\":{\"Value\":\"465.15000000000003D\"}}],[{\"Literal\":{\"Value\":\"466D\"}}],[{\"Literal\":{\"Value\":\"470.5D\"}}],[{\"Literal\":{\"Value\":\"473.77D\"}}],[{\"Literal\":{\"Value\":\"475D\"}}],[{\"Literal\":{\"Value\":\"475.05D\"}}],[{\"Literal\":{\"Value\":\"480D\"}}],[{\"Literal\":{\"Value\":\"480.2D\"}}],[{\"Literal\":{\"Value\":\"485D\"}}],[{\"Literal\":{\"Value\":\"489.43D\"}}],[{\"Literal\":{\"Value\":\"490D\"}}],[{\"Literal\":{\"Value\":\"493D\"}}],[{\"Literal\":{\"Value\":\"493.1D\"}}],[{\"Literal\":{\"Value\":\"494.55D\"}}],[{\"Literal\":{\"Value\":\"494.8D\"}}],[{\"Literal\":{\"Value\":\"498.40000000000003D\"}}]]}}},{\"DisplayName\":\"$5,000 to $9,999\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"r\"}},\"Property\":\"AMT\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"5000D\"}}],[{\"Literal\":{\"Value\":\"6000D\"}}],[{\"Literal\":{\"Value\":\"6250D\"}}],[{\"Literal\":{\"Value\":\"7500D\"}}]]}}},{\"DisplayName\":\"$50 to $99\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"r\"}},\"Property\":\"AMT\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"50D\"}}],[{\"Literal\":{\"Value\":\"50.26D\"}}],[{\"Literal\":{\"Value\":\"50.5D\"}}],[{\"Literal\":{\"Value\":\"50.75D\"}}],[{\"Literal\":{\"Value\":\"51D\"}}],[{\"Literal\":{\"Value\":\"52.21D\"}}],[{\"Literal\":{\"Value\":\"52.5D\"}}],[{\"Literal\":{\"Value\":\"53.75D\"}}],[{\"Literal\":{\"Value\":\"54D\"}}],[{\"Literal\":{\"Value\":\"55D\"}}],[{\"Literal\":{\"Value\":\"55.5D\"}}],[{\"Literal\":{\"Value\":\"55.800000000000004D\"}}],[{\"Literal\":{\"Value\":\"56.25D\"}}],[{\"Literal\":{\"Value\":\"57D\"}}],[{\"Literal\":{\"Value\":\"57.5D\"}}],[{\"Literal\":{\"Value\":\"58D\"}}],[{\"Literal\":{\"Value\":\"58.33D\"}}],[{\"Literal\":{\"Value\":\"58.34D\"}}],[{\"Literal\":{\"Value\":\"59D\"}}],[{\"Literal\":{\"Value\":\"59.5D\"}}],[{\"Literal\":{\"Value\":\"60D\"}}],[{\"Literal\":{\"Value\":\"60.910000000000004D\"}}],[{\"Literal\":{\"Value\":\"61D\"}}],[{\"Literal\":{\"Value\":\"62.08D\"}}],[{\"Literal\":{\"Value\":\"62.1D\"}}],[{\"Literal\":{\"Value\":\"62.5D\"}}],[{\"Literal\":{\"Value\":\"63D\"}}],[{\"Literal\":{\"Value\":\"63.4D\"}}],[{\"Literal\":{\"Value\":\"65D\"}}],[{\"Literal\":{\"Value\":\"66.5D\"}}],[{\"Literal\":{\"Value\":\"66.66D\"}}],[{\"Literal\":{\"Value\":\"66.67D\"}}],[{\"Literal\":{\"Value\":\"67D\"}}],[{\"Literal\":{\"Value\":\"67.5D\"}}],[{\"Literal\":{\"Value\":\"68.75D\"}}],[{\"Literal\":{\"Value\":\"70D\"}}],[{\"Literal\":{\"Value\":\"71D\"}}],[{\"Literal\":{\"Value\":\"71.32000000000001D\"}}],[{\"Literal\":{\"Value\":\"71.64D\"}}],[{\"Literal\":{\"Value\":\"72D\"}}],[{\"Literal\":{\"Value\":\"72.5D\"}}],[{\"Literal\":{\"Value\":\"72.8D\"}}],[{\"Literal\":{\"Value\":\"73D\"}}],[{\"Literal\":{\"Value\":\"75D\"}}],[{\"Literal\":{\"Value\":\"75.01D\"}}],[{\"Literal\":{\"Value\":\"76.10000000000001D\"}}],[{\"Literal\":{\"Value\":\"77D\"}}],[{\"Literal\":{\"Value\":\"77.5D\"}}],[{\"Literal\":{\"Value\":\"80D\"}}],[{\"Literal\":{\"Value\":\"80.9D\"}}],[{\"Literal\":{\"Value\":\"81.41D\"}}],[{\"Literal\":{\"Value\":\"82.24D\"}}],[{\"Literal\":{\"Value\":\"82.5D\"}}],[{\"Literal\":{\"Value\":\"83D\"}}],[{\"Literal\":{\"Value\":\"83.06D\"}}],[{\"Literal\":{\"Value\":\"83.33D\"}}],[{\"Literal\":{\"Value\":\"83.34D\"}}],[{\"Literal\":{\"Value\":\"83.42D\"}}],[{\"Literal\":{\"Value\":\"83.79D\"}}],[{\"Literal\":{\"Value\":\"83.88D\"}}],[{\"Literal\":{\"Value\":\"84D\"}}],[{\"Literal\":{\"Value\":\"84.24D\"}}],[{\"Literal\":{\"Value\":\"84.3D\"}}],[{\"Literal\":{\"Value\":\"84.34D\"}}],[{\"Literal\":{\"Value\":\"85D\"}}],[{\"Literal\":{\"Value\":\"85.3D\"}}],[{\"Literal\":{\"Value\":\"86.64D\"}}],[{\"Literal\":{\"Value\":\"87.5D\"}}],[{\"Literal\":{\"Value\":\"89D\"}}],[{\"Literal\":{\"Value\":\"90D\"}}],[{\"Literal\":{\"Value\":\"90.5D\"}}],[{\"Literal\":{\"Value\":\"91D\"}}],[{\"Literal\":{\"Value\":\"91.48D\"}}],[{\"Literal\":{\"Value\":\"92D\"}}],[{\"Literal\":{\"Value\":\"92.5D\"}}],[{\"Literal\":{\"Value\":\"93.75D\"}}],[{\"Literal\":{\"Value\":\"94D\"}}],[{\"Literal\":{\"Value\":\"95D\"}}],[{\"Literal\":{\"Value\":\"95.48D\"}}],[{\"Literal\":{\"Value\":\"97D\"}}],[{\"Literal\":{\"Value\":\"97.5D\"}}],[{\"Literal\":{\"Value\":\"98.8D\"}}],[{\"Literal\":{\"Value\":\"99D\"}}]]}}},{\"DisplayName\":\"$50,000+\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"r\"}},\"Property\":\"AMT\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"100000D\"}}]]}}},{\"DisplayName\":\"$500 to $999\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"r\"}},\"Property\":\"AMT\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"500D\"}}],[{\"Literal\":{\"Value\":\"500.5D\"}}],[{\"Literal\":{\"Value\":\"502.5D\"}}],[{\"Literal\":{\"Value\":\"504.15000000000003D\"}}],[{\"Literal\":{\"Value\":\"504.3D\"}}],[{\"Literal\":{\"Value\":\"506.67D\"}}],[{\"Literal\":{\"Value\":\"509.91D\"}}],[{\"Literal\":{\"Value\":\"510D\"}}],[{\"Literal\":{\"Value\":\"514.97D\"}}],[{\"Literal\":{\"Value\":\"514.98D\"}}],[{\"Literal\":{\"Value\":\"516.28D\"}}],[{\"Literal\":{\"Value\":\"517.84D\"}}],[{\"Literal\":{\"Value\":\"520D\"}}],[{\"Literal\":{\"Value\":\"520.16D\"}}],[{\"Literal\":{\"Value\":\"522.36D\"}}],[{\"Literal\":{\"Value\":\"525D\"}}],[{\"Literal\":{\"Value\":\"527.33D\"}}],[{\"Literal\":{\"Value\":\"529.1D\"}}],[{\"Literal\":{\"Value\":\"532D\"}}],[{\"Literal\":{\"Value\":\"534.15D\"}}],[{\"Literal\":{\"Value\":\"542.4300000000001D\"}}],[{\"Literal\":{\"Value\":\"542.51D\"}}],[{\"Literal\":{\"Value\":\"548D\"}}],[{\"Literal\":{\"Value\":\"550D\"}}],[{\"Literal\":{\"Value\":\"550.66D\"}}],[{\"Literal\":{\"Value\":\"553D\"}}],[{\"Literal\":{\"Value\":\"555D\"}}],[{\"Literal\":{\"Value\":\"557.84D\"}}],[{\"Literal\":{\"Value\":\"558.1D\"}}],[{\"Literal\":{\"Value\":\"560D\"}}],[{\"Literal\":{\"Value\":\"565D\"}}],[{\"Literal\":{\"Value\":\"570D\"}}],[{\"Literal\":{\"Value\":\"572.8000000000001D\"}}],[{\"Literal\":{\"Value\":\"573.85D\"}}],[{\"Literal\":{\"Value\":\"575D\"}}],[{\"Literal\":{\"Value\":\"579D\"}}],[{\"Literal\":{\"Value\":\"579.8000000000001D\"}}],[{\"Literal\":{\"Value\":\"580D\"}}],[{\"Literal\":{\"Value\":\"582D\"}}],[{\"Literal\":{\"Value\":\"583D\"}}],[{\"Literal\":{\"Value\":\"585D\"}}],[{\"Literal\":{\"Value\":\"586D\"}}],[{\"Literal\":{\"Value\":\"587.5D\"}}],[{\"Literal\":{\"Value\":\"589.2D\"}}],[{\"Literal\":{\"Value\":\"592D\"}}],[{\"Literal\":{\"Value\":\"592.6D\"}}],[{\"Literal\":{\"Value\":\"596.5D\"}}],[{\"Literal\":{\"Value\":\"596.84D\"}}],[{\"Literal\":{\"Value\":\"598D\"}}],[{\"Literal\":{\"Value\":\"599.1D\"}}],[{\"Literal\":{\"Value\":\"600D\"}}],[{\"Literal\":{\"Value\":\"602D\"}}],[{\"Literal\":{\"Value\":\"605D\"}}],[{\"Literal\":{\"Value\":\"607.84D\"}}],[{\"Literal\":{\"Value\":\"609D\"}}],[{\"Literal\":{\"Value\":\"610D\"}}],[{\"Literal\":{\"Value\":\"610.8000000000001D\"}}],[{\"Literal\":{\"Value\":\"611.12D\"}}],[{\"Literal\":{\"Value\":\"617.21D\"}}],[{\"Literal\":{\"Value\":\"620D\"}}],[{\"Literal\":{\"Value\":\"620.25D\"}}],[{\"Literal\":{\"Value\":\"621D\"}}],[{\"Literal\":{\"Value\":\"625D\"}}],[{\"Literal\":{\"Value\":\"629.5D\"}}],[{\"Literal\":{\"Value\":\"630D\"}}],[{\"Literal\":{\"Value\":\"635D\"}}],[{\"Literal\":{\"Value\":\"635.1D\"}}],[{\"Literal\":{\"Value\":\"637.5D\"}}],[{\"Literal\":{\"Value\":\"646D\"}}],[{\"Literal\":{\"Value\":\"650D\"}}],[{\"Literal\":{\"Value\":\"650.46D\"}}],[{\"Literal\":{\"Value\":\"651D\"}}],[{\"Literal\":{\"Value\":\"651.45D\"}}],[{\"Literal\":{\"Value\":\"655D\"}}],[{\"Literal\":{\"Value\":\"660D\"}}],[{\"Literal\":{\"Value\":\"663.6D\"}}],[{\"Literal\":{\"Value\":\"666.67D\"}}],[{\"Literal\":{\"Value\":\"675D\"}}],[{\"Literal\":{\"Value\":\"676.8000000000001D\"}}],[{\"Literal\":{\"Value\":\"678.85D\"}}],[{\"Literal\":{\"Value\":\"680D\"}}],[{\"Literal\":{\"Value\":\"686.2D\"}}],[{\"Literal\":{\"Value\":\"687.5D\"}}],[{\"Literal\":{\"Value\":\"691D\"}}],[{\"Literal\":{\"Value\":\"700D\"}}],[{\"Literal\":{\"Value\":\"705.2D\"}}],[{\"Literal\":{\"Value\":\"708D\"}}],[{\"Literal\":{\"Value\":\"708.4D\"}}],[{\"Literal\":{\"Value\":\"716D\"}}],[{\"Literal\":{\"Value\":\"717.5D\"}}],[{\"Literal\":{\"Value\":\"721.8000000000001D\"}}],[{\"Literal\":{\"Value\":\"725D\"}}],[{\"Literal\":{\"Value\":\"730D\"}}],[{\"Literal\":{\"Value\":\"739.95D\"}}],[{\"Literal\":{\"Value\":\"740D\"}}],[{\"Literal\":{\"Value\":\"742.5D\"}}],[{\"Literal\":{\"Value\":\"748.02D\"}}],[{\"Literal\":{\"Value\":\"750D\"}}],[{\"Literal\":{\"Value\":\"750.1D\"}}],[{\"Literal\":{\"Value\":\"752.0500000000001D\"}}],[{\"Literal\":{\"Value\":\"753.8000000000001D\"}}],[{\"Literal\":{\"Value\":\"756D\"}}],[{\"Literal\":{\"Value\":\"762.5D\"}}],[{\"Literal\":{\"Value\":\"764.8000000000001D\"}}],[{\"Literal\":{\"Value\":\"765D\"}}],[{\"Literal\":{\"Value\":\"772D\"}}],[{\"Literal\":{\"Value\":\"772.1D\"}}],[{\"Literal\":{\"Value\":\"775D\"}}],[{\"Literal\":{\"Value\":\"777D\"}}],[{\"Literal\":{\"Value\":\"790D\"}}],[{\"Literal\":{\"Value\":\"792D\"}}],[{\"Literal\":{\"Value\":\"794.8000000000001D\"}}],[{\"Literal\":{\"Value\":\"796.1D\"}}],[{\"Literal\":{\"Value\":\"799.5D\"}}],[{\"Literal\":{\"Value\":\"800D\"}}],[{\"Literal\":{\"Value\":\"803.3000000000001D\"}}],[{\"Literal\":{\"Value\":\"804.5D\"}}],[{\"Literal\":{\"Value\":\"805D\"}}],[{\"Literal\":{\"Value\":\"805.15D\"}}],[{\"Literal\":{\"Value\":\"806.5D\"}}],[{\"Literal\":{\"Value\":\"807.5D\"}}],[{\"Literal\":{\"Value\":\"807.84D\"}}],[{\"Literal\":{\"Value\":\"810D\"}}],[{\"Literal\":{\"Value\":\"812.08D\"}}],[{\"Literal\":{\"Value\":\"814D\"}}],[{\"Literal\":{\"Value\":\"818D\"}}],[{\"Literal\":{\"Value\":\"820D\"}}],[{\"Literal\":{\"Value\":\"822.4D\"}}],[{\"Literal\":{\"Value\":\"822.5D\"}}],[{\"Literal\":{\"Value\":\"824.95D\"}}],[{\"Literal\":{\"Value\":\"825D\"}}],[{\"Literal\":{\"Value\":\"826.1D\"}}],[{\"Literal\":{\"Value\":\"832.84D\"}}],[{\"Literal\":{\"Value\":\"833.34D\"}}],[{\"Literal\":{\"Value\":\"833.75D\"}}],[{\"Literal\":{\"Value\":\"840D\"}}],[{\"Literal\":{\"Value\":\"847.9300000000001D\"}}],[{\"Literal\":{\"Value\":\"849.15D\"}}],[{\"Literal\":{\"Value\":\"850D\"}}],[{\"Literal\":{\"Value\":\"855D\"}}],[{\"Literal\":{\"Value\":\"859.9D\"}}],[{\"Literal\":{\"Value\":\"865D\"}}],[{\"Literal\":{\"Value\":\"870D\"}}],[{\"Literal\":{\"Value\":\"874.69D\"}}],[{\"Literal\":{\"Value\":\"875D\"}}],[{\"Literal\":{\"Value\":\"875.2D\"}}],[{\"Literal\":{\"Value\":\"880D\"}}],[{\"Literal\":{\"Value\":\"886.9D\"}}],[{\"Literal\":{\"Value\":\"890D\"}}],[{\"Literal\":{\"Value\":\"891.66D\"}}],[{\"Literal\":{\"Value\":\"892.5D\"}}],[{\"Literal\":{\"Value\":\"895D\"}}],[{\"Literal\":{\"Value\":\"897D\"}}],[{\"Literal\":{\"Value\":\"900D\"}}],[{\"Literal\":{\"Value\":\"904D\"}}],[{\"Literal\":{\"Value\":\"904.75D\"}}],[{\"Literal\":{\"Value\":\"915D\"}}],[{\"Literal\":{\"Value\":\"919D\"}}],[{\"Literal\":{\"Value\":\"921D\"}}],[{\"Literal\":{\"Value\":\"922.38D\"}}],[{\"Literal\":{\"Value\":\"923.7D\"}}],[{\"Literal\":{\"Value\":\"925D\"}}],[{\"Literal\":{\"Value\":\"935D\"}}],[{\"Literal\":{\"Value\":\"937.5D\"}}],[{\"Literal\":{\"Value\":\"938.28D\"}}],[{\"Literal\":{\"Value\":\"940D\"}}],[{\"Literal\":{\"Value\":\"947.6D\"}}],[{\"Literal\":{\"Value\":\"948.5D\"}}],[{\"Literal\":{\"Value\":\"950D\"}}],[{\"Literal\":{\"Value\":\"954D\"}}],[{\"Literal\":{\"Value\":\"960D\"}}],[{\"Literal\":{\"Value\":\"963.5D\"}}],[{\"Literal\":{\"Value\":\"965.15D\"}}],[{\"Literal\":{\"Value\":\"965.4D\"}}],[{\"Literal\":{\"Value\":\"966.66D\"}}],[{\"Literal\":{\"Value\":\"968.4D\"}}],[{\"Literal\":{\"Value\":\"969D\"}}],[{\"Literal\":{\"Value\":\"970D\"}}],[{\"Literal\":{\"Value\":\"972.5D\"}}],[{\"Literal\":{\"Value\":\"975D\"}}],[{\"Literal\":{\"Value\":\"976D\"}}],[{\"Literal\":{\"Value\":\"979.9D\"}}],[{\"Literal\":{\"Value\":\"981D\"}}],[{\"Literal\":{\"Value\":\"989.1700000000001D\"}}],[{\"Literal\":{\"Value\":\"990.2D\"}}],[{\"Literal\":{\"Value\":\"992.1D\"}}],[{\"Literal\":{\"Value\":\"992.5D\"}}]]}}},{\"DisplayName\":\"Less than $25\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"r\"}},\"Property\":\"AMT\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"0D\"}}],[{\"Literal\":{\"Value\":\"0.01D\"}}],[{\"Literal\":{\"Value\":\"0.02D\"}}],[{\"Literal\":{\"Value\":\"0.03D\"}}],[{\"Literal\":{\"Value\":\"0.12D\"}}],[{\"Literal\":{\"Value\":\"0.19D\"}}],[{\"Literal\":{\"Value\":\"0.21D\"}}],[{\"Literal\":{\"Value\":\"0.5D\"}}],[{\"Literal\":{\"Value\":\"0.54D\"}}],[{\"Literal\":{\"Value\":\"0.62D\"}}],[{\"Literal\":{\"Value\":\"0.63D\"}}],[{\"Literal\":{\"Value\":\"0.75D\"}}],[{\"Literal\":{\"Value\":\"0.9400000000000001D\"}}],[{\"Literal\":{\"Value\":\"1D\"}}],[{\"Literal\":{\"Value\":\"1.1500000000000001D\"}}],[{\"Literal\":{\"Value\":\"1.25D\"}}],[{\"Literal\":{\"Value\":\"1.28D\"}}],[{\"Literal\":{\"Value\":\"1.3D\"}}],[{\"Literal\":{\"Value\":\"1.34D\"}}],[{\"Literal\":{\"Value\":\"1.5D\"}}],[{\"Literal\":{\"Value\":\"1.6D\"}}],[{\"Literal\":{\"Value\":\"1.6300000000000001D\"}}],[{\"Literal\":{\"Value\":\"1.84D\"}}],[{\"Literal\":{\"Value\":\"1.98D\"}}],[{\"Literal\":{\"Value\":\"2D\"}}],[{\"Literal\":{\"Value\":\"2.06D\"}}],[{\"Literal\":{\"Value\":\"2.07D\"}}],[{\"Literal\":{\"Value\":\"2.12D\"}}],[{\"Literal\":{\"Value\":\"2.13D\"}}],[{\"Literal\":{\"Value\":\"2.19D\"}}],[{\"Literal\":{\"Value\":\"2.2D\"}}],[{\"Literal\":{\"Value\":\"2.31D\"}}],[{\"Literal\":{\"Value\":\"2.32D\"}}],[{\"Literal\":{\"Value\":\"2.34D\"}}],[{\"Literal\":{\"Value\":\"2.5D\"}}],[{\"Literal\":{\"Value\":\"2.75D\"}}],[{\"Literal\":{\"Value\":\"2.8000000000000003D\"}}],[{\"Literal\":{\"Value\":\"2.97D\"}}],[{\"Literal\":{\"Value\":\"3D\"}}],[{\"Literal\":{\"Value\":\"3.13D\"}}],[{\"Literal\":{\"Value\":\"3.33D\"}}],[{\"Literal\":{\"Value\":\"3.34D\"}}],[{\"Literal\":{\"Value\":\"3.37D\"}}],[{\"Literal\":{\"Value\":\"3.38D\"}}],[{\"Literal\":{\"Value\":\"3.5D\"}}],[{\"Literal\":{\"Value\":\"3.75D\"}}],[{\"Literal\":{\"Value\":\"3.87D\"}}],[{\"Literal\":{\"Value\":\"3.88D\"}}],[{\"Literal\":{\"Value\":\"4D\"}}],[{\"Literal\":{\"Value\":\"4.38D\"}}],[{\"Literal\":{\"Value\":\"4.41D\"}}],[{\"Literal\":{\"Value\":\"4.48D\"}}],[{\"Literal\":{\"Value\":\"4.7D\"}}],[{\"Literal\":{\"Value\":\"4.8D\"}}],[{\"Literal\":{\"Value\":\"4.84D\"}}],[{\"Literal\":{\"Value\":\"4.95D\"}}],[{\"Literal\":{\"Value\":\"5D\"}}],[{\"Literal\":{\"Value\":\"5.01D\"}}],[{\"Literal\":{\"Value\":\"5.0200000000000005D\"}}],[{\"Literal\":{\"Value\":\"5.03D\"}}],[{\"Literal\":{\"Value\":\"5.15D\"}}],[{\"Literal\":{\"Value\":\"5.24D\"}}],[{\"Literal\":{\"Value\":\"5.26D\"}}],[{\"Literal\":{\"Value\":\"5.5D\"}}],[{\"Literal\":{\"Value\":\"5.55D\"}}],[{\"Literal\":{\"Value\":\"6D\"}}],[{\"Literal\":{\"Value\":\"6.03D\"}}],[{\"Literal\":{\"Value\":\"6.25D\"}}],[{\"Literal\":{\"Value\":\"6.66D\"}}],[{\"Literal\":{\"Value\":\"6.74D\"}}],[{\"Literal\":{\"Value\":\"6.76D\"}}],[{\"Literal\":{\"Value\":\"7D\"}}],[{\"Literal\":{\"Value\":\"7.12D\"}}],[{\"Literal\":{\"Value\":\"7.17D\"}}],[{\"Literal\":{\"Value\":\"7.24D\"}}],[{\"Literal\":{\"Value\":\"7.26D\"}}],[{\"Literal\":{\"Value\":\"7.3D\"}}],[{\"Literal\":{\"Value\":\"7.5D\"}}],[{\"Literal\":{\"Value\":\"8D\"}}],[{\"Literal\":{\"Value\":\"8.32D\"}}],[{\"Literal\":{\"Value\":\"8.33D\"}}],[{\"Literal\":{\"Value\":\"8.34D\"}}],[{\"Literal\":{\"Value\":\"8.75D\"}}],[{\"Literal\":{\"Value\":\"9D\"}}],[{\"Literal\":{\"Value\":\"9.07D\"}}],[{\"Literal\":{\"Value\":\"9.35D\"}}],[{\"Literal\":{\"Value\":\"9.43D\"}}],[{\"Literal\":{\"Value\":\"9.5D\"}}],[{\"Literal\":{\"Value\":\"10D\"}}],[{\"Literal\":{\"Value\":\"10.040000000000001D\"}}],[{\"Literal\":{\"Value\":\"10.05D\"}}],[{\"Literal\":{\"Value\":\"10.08D\"}}],[{\"Literal\":{\"Value\":\"10.09D\"}}],[{\"Literal\":{\"Value\":\"10.14D\"}}],[{\"Literal\":{\"Value\":\"10.41D\"}}],[{\"Literal\":{\"Value\":\"10.42D\"}}],[{\"Literal\":{\"Value\":\"11D\"}}],[{\"Literal\":{\"Value\":\"11.35D\"}}],[{\"Literal\":{\"Value\":\"11.36D\"}}],[{\"Literal\":{\"Value\":\"11.370000000000001D\"}}],[{\"Literal\":{\"Value\":\"11.43D\"}}],[{\"Literal\":{\"Value\":\"11.44D\"}}],[{\"Literal\":{\"Value\":\"11.5D\"}}],[{\"Literal\":{\"Value\":\"11.64D\"}}],[{\"Literal\":{\"Value\":\"11.66D\"}}],[{\"Literal\":{\"Value\":\"11.94D\"}}],[{\"Literal\":{\"Value\":\"12D\"}}],[{\"Literal\":{\"Value\":\"12.5D\"}}],[{\"Literal\":{\"Value\":\"12.8D\"}}],[{\"Literal\":{\"Value\":\"13D\"}}],[{\"Literal\":{\"Value\":\"13.5D\"}}],[{\"Literal\":{\"Value\":\"14D\"}}],[{\"Literal\":{\"Value\":\"14.200000000000001D\"}}],[{\"Literal\":{\"Value\":\"14.4D\"}}],[{\"Literal\":{\"Value\":\"14.48D\"}}],[{\"Literal\":{\"Value\":\"14.84D\"}}],[{\"Literal\":{\"Value\":\"15D\"}}],[{\"Literal\":{\"Value\":\"15.5D\"}}],[{\"Literal\":{\"Value\":\"15.63D\"}}],[{\"Literal\":{\"Value\":\"16D\"}}],[{\"Literal\":{\"Value\":\"16.1D\"}}],[{\"Literal\":{\"Value\":\"16.57D\"}}],[{\"Literal\":{\"Value\":\"16.66D\"}}],[{\"Literal\":{\"Value\":\"16.67D\"}}],[{\"Literal\":{\"Value\":\"16.68D\"}}],[{\"Literal\":{\"Value\":\"17D\"}}],[{\"Literal\":{\"Value\":\"17.34D\"}}],[{\"Literal\":{\"Value\":\"17.41D\"}}],[{\"Literal\":{\"Value\":\"17.44D\"}}],[{\"Literal\":{\"Value\":\"17.5D\"}}],[{\"Literal\":{\"Value\":\"18D\"}}],[{\"Literal\":{\"Value\":\"18.1D\"}}],[{\"Literal\":{\"Value\":\"18.75D\"}}],[{\"Literal\":{\"Value\":\"18.78D\"}}],[{\"Literal\":{\"Value\":\"20D\"}}],[{\"Literal\":{\"Value\":\"20.1D\"}}],[{\"Literal\":{\"Value\":\"20.12D\"}}],[{\"Literal\":{\"Value\":\"20.13D\"}}],[{\"Literal\":{\"Value\":\"20.150000000000002D\"}}],[{\"Literal\":{\"Value\":\"20.16D\"}}],[{\"Literal\":{\"Value\":\"20.17D\"}}],[{\"Literal\":{\"Value\":\"20.18D\"}}],[{\"Literal\":{\"Value\":\"20.82D\"}}],[{\"Literal\":{\"Value\":\"20.830000000000002D\"}}],[{\"Literal\":{\"Value\":\"20.84D\"}}],[{\"Literal\":{\"Value\":\"21D\"}}],[{\"Literal\":{\"Value\":\"22D\"}}],[{\"Literal\":{\"Value\":\"22.5D\"}}],[{\"Literal\":{\"Value\":\"22.75D\"}}],[{\"Literal\":{\"Value\":\"23D\"}}],[{\"Literal\":{\"Value\":\"23.63D\"}}],[{\"Literal\":{\"Value\":\"24D\"}}],[{\"Literal\":{\"Value\":\"24.900000000000002D\"}}]]}}},{\"DisplayName\":\"Other\"}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "  TRUE,",
              "  ISBLANK('RA_Giving'[AMT]),",
              "  \"(Blank)\",",
              "  'RA_Giving'[AMT] IN {1000,",
              "    1002,",
              "    1008,",
              "    1010,",
              "    1011,",
              "    1015,",
              "    1020,",
              "    1022,",
              "    1025,",
              "    1025.2,",
              "    1027.5,",
              "    1033,",
              "    1034.4,",
              "    1040,",
              "    1042,",
              "    1045,",
              "    1046,",
              "    1050,",
              "    1050.5,",
              "    1052,",
              "    1059.9,",
              "    1061,",
              "    1062.5,",
              "    1064,",
              "    1065,",
              "    1065.45,",
              "    1066.67,",
              "    1075,",
              "    1080,",
              "    1090.5,",
              "    1092,",
              "    1096.69,",
              "    1100,",
              "    1108.8500000000001,",
              "    1112.5,",
              "    1115,",
              "    1115.32,",
              "    1122,",
              "    1125,",
              "    1130,",
              "    1134,",
              "    1135,",
              "    1135.4,",
              "    1140,",
              "    1145,",
              "    1150,",
              "    1153.4,",
              "    1153.8500000000001,",
              "    1157,",
              "    1158.8500000000001,",
              "    1160,",
              "    1160.97,",
              "    1164.1000000000001,",
              "    1167.67,",
              "    1175,",
              "    1180,",
              "    1182.5,",
              "    1189,",
              "    1192,",
              "    1192.84,",
              "    1193,",
              "    1193.2,",
              "    1196,",
              "    1198.8500000000001,",
              "    1199,",
              "    1200,",
              "    1205,",
              "    1207.5,",
              "    1215.84,",
              "    1222.3600000000001,",
              "    1225,",
              "    1226,",
              "    1230,",
              "    1232.5,",
              "    1241,",
              "    1244.65,",
              "    1246,",
              "    1250,",
              "    1254.8,",
              "    1255.8,",
              "    1259,",
              "    1260,",
              "    1261,",
              "    1261.8,",
              "    1264.3600000000001,",
              "    1269.64,",
              "    1270,",
              "    1274.59,",
              "    1275,",
              "    1276,",
              "    1285,",
              "    1286,",
              "    1287.5,",
              "    1295,",
              "    1300,",
              "    1307.84,",
              "    1309,",
              "    1311,",
              "    1319.83,",
              "    1333,",
              "    1336,",
              "    1337,",
              "    1344,",
              "    1350,",
              "    1355,",
              "    1357.71,",
              "    1366,",
              "    1369.3600000000001,",
              "    1370,",
              "    1371.43,",
              "    1372.5,",
              "    1375,",
              "    1377,",
              "    1378.4,",
              "    1379.18,",
              "    1386.28,",
              "    1395.3700000000001,",
              "    1395.38,",
              "    1400,",
              "    1407.1000000000001,",
              "    1415.15,",
              "    1425,",
              "    1437,",
              "    1442,",
              "    1450,",
              "    1465,",
              "    1466,",
              "    1475,",
              "    1500,",
              "    1514.55,",
              "    1517.3,",
              "    1520,",
              "    1543,",
              "    1543.8,",
              "    1550,",
              "    1575,",
              "    1578,",
              "    1581,",
              "    1585,",
              "    1598,",
              "    1600,",
              "    1610,",
              "    1620,",
              "    1635,",
              "    1637.3,",
              "    1646.8,",
              "    1650,",
              "    1663.2,",
              "    1665,",
              "    1670,",
              "    1673.63,",
              "    1692,",
              "    1693.2,",
              "    1695,",
              "    1700,",
              "    1707.4,",
              "    1711.4,",
              "    1725,",
              "    1738,",
              "    1742.65,",
              "    1750,",
              "    1756.2,",
              "    1763,",
              "    1774,",
              "    1786.46,",
              "    1797.2,",
              "    1800,",
              "    1810,",
              "    1816.5,",
              "    1850,",
              "    1853.46,",
              "    1870,",
              "    1875,",
              "    1882.04,",
              "    1894,",
              "    1900,",
              "    1915,",
              "    1941.4,",
              "    1950,",
              "    1978.1000000000001,",
              "    1981.3400000000001,",
              "    2000,",
              "    2014,",
              "    2016,",
              "    2083.5,",
              "    2100,",
              "    2102,",
              "    2127.87,",
              "    2130,",
              "    2150,",
              "    2200,",
              "    2218.4,",
              "    2238.26,",
              "    2300,",
              "    2300.12,",
              "    2350,",
              "    2391,",
              "    2400,",
              "    2450},",
              "  \"$1,000 to $2,499\",",
              "  'RA_Giving'[AMT] IN {10000,",
              "    12340.2,",
              "    12500,",
              "    20000},",
              "  \"$10,000 to $24,999\",",
              "  'RA_Giving'[AMT] IN {100,",
              "    100.03,",
              "    100.5,",
              "    101,",
              "    102,",
              "    102.86,",
              "    103,",
              "    103.13,",
              "    105,",
              "    107.5,",
              "    108.2,",
              "    109.10000000000001,",
              "    110,",
              "    110.02,",
              "    110.03,",
              "    110.05,",
              "    112.5,",
              "    114,",
              "    115,",
              "    115.5,",
              "    116,",
              "    119,",
              "    120,",
              "    120.5,",
              "    120.83,",
              "    122.5,",
              "    122.66,",
              "    123,",
              "    123.10000000000001,",
              "    124.25,",
              "    124.99000000000001,",
              "    125,",
              "    125.12,",
              "    125.5,",
              "    125.8,",
              "    126.24000000000001,",
              "    130,",
              "    131.25,",
              "    132.86,",
              "    133.33,",
              "    134.76,",
              "    135,",
              "    136.5,",
              "    137,",
              "    137.5,",
              "    140,",
              "    142.79,",
              "    142.86,",
              "    142.87,",
              "    144,",
              "    144.38,",
              "    145,",
              "    145.9,",
              "    146,",
              "    147.5,",
              "    147.70000000000002,",
              "    148,",
              "    148.5,",
              "    150,",
              "    150.25,",
              "    152.5,",
              "    153.85,",
              "    153.95000000000002,",
              "    155,",
              "    157.5,",
              "    157.9,",
              "    159.1,",
              "    160,",
              "    162.5,",
              "    163.5,",
              "    164.06,",
              "    165,",
              "    165.25,",
              "    166.5,",
              "    166.59,",
              "    166.66,",
              "    166.67000000000002,",
              "    166.68,",
              "    167,",
              "    168.65,",
              "    168.75,",
              "    169,",
              "    170,",
              "    171.87,",
              "    171.88,",
              "    175,",
              "    175.20000000000002,",
              "    177.5,",
              "    178.5,",
              "    180,",
              "    181,",
              "    181.20000000000002,",
              "    181.8,",
              "    182.5,",
              "    184,",
              "    185,",
              "    186.5,",
              "    187.5,",
              "    188,",
              "    190.1,",
              "    192.5,",
              "    198,",
              "    200,",
              "    200.5,",
              "    204.57,",
              "    205,",
              "    206.25,",
              "    207,",
              "    207.4,",
              "    207.5,",
              "    208.32,",
              "    208.33,",
              "    208.34,",
              "    210,",
              "    211,",
              "    212.5,",
              "    213.8,",
              "    216,",
              "    217.5,",
              "    218.75,",
              "    220,",
              "    223,",
              "    224,",
              "    225,",
              "    228,",
              "    228.5,",
              "    229.16,",
              "    229.17000000000002,",
              "    229.18,",
              "    230,",
              "    231,",
              "    235,",
              "    237,",
              "    237.5,",
              "    240,",
              "    246.8,",
              "    248.1,",
              "    248.36},",
              "  \"$100 to $249\",",
              "  'RA_Giving'[AMT] IN {2500,",
              "    2550,",
              "    2600,",
              "    2666,",
              "    2750,",
              "    2800,",
              "    2888,",
              "    2892,",
              "    3000,",
              "    3042,",
              "    3106,",
              "    3325,",
              "    3418.91,",
              "    3500,",
              "    3600,",
              "    3800,",
              "    3850,",
              "    4000,",
              "    4750},",
              "  \"$2,500 to $4,999\",",
              "  'RA_Giving'[AMT] IN {25,",
              "    25.18,",
              "    26,",
              "    26.2,",
              "    26.66,",
              "    26.67,",
              "    26.900000000000002,",
              "    27,",
              "    27.5,",
              "    28,",
              "    28.080000000000002,",
              "    28.46,",
              "    29,",
              "    30,",
              "    31.25,",
              "    31.5,",
              "    31.82,",
              "    32,",
              "    32.5,",
              "    32.8,",
              "    33,",
              "    33.33,",
              "    33.34,",
              "    33.5,",
              "    34,",
              "    34.800000000000004,",
              "    34.99,",
              "    35,",
              "    35.800000000000004,",
              "    36,",
              "    37.5,",
              "    38,",
              "    38.050000000000004,",
              "    38.4,",
              "    40,",
              "    41.67,",
              "    41.68,",
              "    41.94,",
              "    42,",
              "    42.5,",
              "    42.67,",
              "    43,",
              "    43.2,",
              "    43.75,",
              "    45,",
              "    45.4,",
              "    45.74,",
              "    46,",
              "    46.5,",
              "    46.87,",
              "    46.88,",
              "    47.5,",
              "    47.74,",
              "    47.76,",
              "    48.75,",
              "    48.76,",
              "    49,",
              "    49.5},",
              "  \"$25 to $49\",",
              "  'RA_Giving'[AMT] IN {25000,",
              "    30000,",
              "    40000},",
              "  \"$25,000 to $49,999\",",
              "  'RA_Giving'[AMT] IN {250,",
              "    250.25,",
              "    250.5,",
              "    253.37,",
              "    253.44,",
              "    255,",
              "    256.25,",
              "    257.5,",
              "    260,",
              "    262.5,",
              "    265,",
              "    268.5,",
              "    268.65,",
              "    270,",
              "    271.99,",
              "    272.2,",
              "    272.5,",
              "    275,",
              "    277.5,",
              "    280,",
              "    281.25,",
              "    282.27,",
              "    283.33,",
              "    283.34000000000003,",
              "    285.5,",
              "    287.5,",
              "    287.83,",
              "    288.6,",
              "    288.75,",
              "    290,",
              "    292.5,",
              "    295,",
              "    296.67,",
              "    297.5,",
              "    298.3,",
              "    299.15000000000003,",
              "    300,",
              "    305,",
              "    307.40000000000003,",
              "    307.5,",
              "    308.3,",
              "    309.40000000000003,",
              "    310,",
              "    312.5,",
              "    315,",
              "    318.75,",
              "    320,",
              "    321.7,",
              "    323.3,",
              "    325,",
              "    326.73,",
              "    328.2,",
              "    330,",
              "    332,",
              "    333,",
              "    333.33,",
              "    333.34000000000003,",
              "    335.40000000000003,",
              "    335.8,",
              "    337.5,",
              "    340,",
              "    342.45,",
              "    342.5,",
              "    343.75,",
              "    345,",
              "    349.2,",
              "    350,",
              "    354,",
              "    360,",
              "    364.29,",
              "    366.5,",
              "    367,",
              "    368,",
              "    370,",
              "    373,",
              "    375,",
              "    375.01,",
              "    378,",
              "    380,",
              "    381.90000000000003,",
              "    386,",
              "    386.55,",
              "    387.5,",
              "    387.8,",
              "    389.2,",
              "    389.7,",
              "    390,",
              "    391,",
              "    392.5,",
              "    393.5,",
              "    395,",
              "    397.76,",
              "    398.68,",
              "    399.98,",
              "    400,",
              "    402,",
              "    404,",
              "    405,",
              "    410,",
              "    412.21000000000004,",
              "    412.5,",
              "    415,",
              "    415.15000000000003,",
              "    416.66,",
              "    416.67,",
              "    417.5,",
              "    420,",
              "    425,",
              "    426.92,",
              "    427,",
              "    430,",
              "    430.6,",
              "    431.8,",
              "    432.5,",
              "    433.75,",
              "    435,",
              "    437.5,",
              "    440,",
              "    442.5,",
              "    443.5,",
              "    443.7,",
              "    445,",
              "    447.5,",
              "    448.1,",
              "    450,",
              "    452.6,",
              "    454,",
              "    455,",
              "    458.33,",
              "    458.34000000000003,",
              "    460,",
              "    462.5,",
              "    465.15000000000003,",
              "    466,",
              "    470.5,",
              "    473.77,",
              "    475,",
              "    475.05,",
              "    480,",
              "    480.2,",
              "    485,",
              "    489.43,",
              "    490,",
              "    493,",
              "    493.1,",
              "    494.55,",
              "    494.8,",
              "    498.40000000000003},",
              "  \"$250 to $499\",",
              "  'RA_Giving'[AMT] IN {5000,",
              "    6000,",
              "    6250,",
              "    7500},",
              "  \"$5,000 to $9,999\",",
              "  'RA_Giving'[AMT] IN {50,",
              "    50.26,",
              "    50.5,",
              "    50.75,",
              "    51,",
              "    52.21,",
              "    52.5,",
              "    53.75,",
              "    54,",
              "    55,",
              "    55.5,",
              "    55.800000000000004,",
              "    56.25,",
              "    57,",
              "    57.5,",
              "    58,",
              "    58.33,",
              "    58.34,",
              "    59,",
              "    59.5,",
              "    60,",
              "    60.910000000000004,",
              "    61,",
              "    62.08,",
              "    62.1,",
              "    62.5,",
              "    63,",
              "    63.4,",
              "    65,",
              "    66.5,",
              "    66.66,",
              "    66.67,",
              "    67,",
              "    67.5,",
              "    68.75,",
              "    70,",
              "    71,",
              "    71.320000000000007,",
              "    71.64,",
              "    72,",
              "    72.5,",
              "    72.8,",
              "    73,",
              "    75,",
              "    75.01,",
              "    76.100000000000009,",
              "    77,",
              "    77.5,",
              "    80,",
              "    80.9,",
              "    81.41,",
              "    82.24,",
              "    82.5,",
              "    83,",
              "    83.06,",
              "    83.33,",
              "    83.34,",
              "    83.42,",
              "    83.79,",
              "    83.88,",
              "    84,",
              "    84.24,",
              "    84.3,",
              "    84.34,",
              "    85,",
              "    85.3,",
              "    86.64,",
              "    87.5,",
              "    89,",
              "    90,",
              "    90.5,",
              "    91,",
              "    91.48,",
              "    92,",
              "    92.5,",
              "    93.75,",
              "    94,",
              "    95,",
              "    95.48,",
              "    97,",
              "    97.5,",
              "    98.8,",
              "    99},",
              "  \"$50 to $99\",",
              "  'RA_Giving'[AMT] IN {100000},",
              "  \"$50,000+\",",
              "  'RA_Giving'[AMT] IN {500,",
              "    500.5,",
              "    502.5,",
              "    504.15000000000003,",
              "    504.3,",
              "    506.67,",
              "    509.91,",
              "    510,",
              "    514.97,",
              "    514.98,",
              "    516.28,",
              "    517.84,",
              "    520,",
              "    520.16,",
              "    522.36,",
              "    525,",
              "    527.33,",
              "    529.1,",
              "    532,",
              "    534.15,",
              "    542.43000000000006,",
              "    542.51,",
              "    548,",
              "    550,",
              "    550.66,",
              "    553,",
              "    555,",
              "    557.84,",
              "    558.1,",
              "    560,",
              "    565,",
              "    570,",
              "    572.80000000000007,",
              "    573.85,",
              "    575,",
              "    579,",
              "    579.80000000000007,",
              "    580,",
              "    582,",
              "    583,",
              "    585,",
              "    586,",
              "    587.5,",
              "    589.2,",
              "    592,",
              "    592.6,",
              "    596.5,",
              "    596.84,",
              "    598,",
              "    599.1,",
              "    600,",
              "    602,",
              "    605,",
              "    607.84,",
              "    609,",
              "    610,",
              "    610.80000000000007,",
              "    611.12,",
              "    617.21,",
              "    620,",
              "    620.25,",
              "    621,",
              "    625,",
              "    629.5,",
              "    630,",
              "    635,",
              "    635.1,",
              "    637.5,",
              "    646,",
              "    650,",
              "    650.46,",
              "    651,",
              "    651.45,",
              "    655,",
              "    660,",
              "    663.6,",
              "    666.67,",
              "    675,",
              "    676.80000000000007,",
              "    678.85,",
              "    680,",
              "    686.2,",
              "    687.5,",
              "    691,",
              "    700,",
              "    705.2,",
              "    708,",
              "    708.4,",
              "    716,",
              "    717.5,",
              "    721.80000000000007,",
              "    725,",
              "    730,",
              "    739.95,",
              "    740,",
              "    742.5,",
              "    748.02,",
              "    750,",
              "    750.1,",
              "    752.05000000000007,",
              "    753.80000000000007,",
              "    756,",
              "    762.5,",
              "    764.80000000000007,",
              "    765,",
              "    772,",
              "    772.1,",
              "    775,",
              "    777,",
              "    790,",
              "    792,",
              "    794.80000000000007,",
              "    796.1,",
              "    799.5,",
              "    800,",
              "    803.30000000000007,",
              "    804.5,",
              "    805,",
              "    805.15,",
              "    806.5,",
              "    807.5,",
              "    807.84,",
              "    810,",
              "    812.08,",
              "    814,",
              "    818,",
              "    820,",
              "    822.4,",
              "    822.5,",
              "    824.95,",
              "    825,",
              "    826.1,",
              "    832.84,",
              "    833.34,",
              "    833.75,",
              "    840,",
              "    847.93000000000006,",
              "    849.15,",
              "    850,",
              "    855,",
              "    859.9,",
              "    865,",
              "    870,",
              "    874.69,",
              "    875,",
              "    875.2,",
              "    880,",
              "    886.9,",
              "    890,",
              "    891.66,",
              "    892.5,",
              "    895,",
              "    897,",
              "    900,",
              "    904,",
              "    904.75,",
              "    915,",
              "    919,",
              "    921,",
              "    922.38,",
              "    923.7,",
              "    925,",
              "    935,",
              "    937.5,",
              "    938.28,",
              "    940,",
              "    947.6,",
              "    948.5,",
              "    950,",
              "    954,",
              "    960,",
              "    963.5,",
              "    965.15,",
              "    965.4,",
              "    966.66,",
              "    968.4,",
              "    969,",
              "    970,",
              "    972.5,",
              "    975,",
              "    976,",
              "    979.9,",
              "    981,",
              "    989.17000000000007,",
              "    990.2,",
              "    992.1,",
              "    992.5},",
              "  \"$500 to $999\",",
              "  'RA_Giving'[AMT] IN {0,",
              "    0.01,",
              "    0.02,",
              "    0.03,",
              "    0.12,",
              "    0.19,",
              "    0.21,",
              "    0.5,",
              "    0.54,",
              "    0.62,",
              "    0.63,",
              "    0.75,",
              "    0.94000000000000006,",
              "    1,",
              "    1.1500000000000001,",
              "    1.25,",
              "    1.28,",
              "    1.3,",
              "    1.34,",
              "    1.5,",
              "    1.6,",
              "    1.6300000000000001,",
              "    1.84,",
              "    1.98,",
              "    2,",
              "    2.06,",
              "    2.07,",
              "    2.12,",
              "    2.13,",
              "    2.19,",
              "    2.2,",
              "    2.31,",
              "    2.32,",
              "    2.34,",
              "    2.5,",
              "    2.75,",
              "    2.8000000000000003,",
              "    2.97,",
              "    3,",
              "    3.13,",
              "    3.33,",
              "    3.34,",
              "    3.37,",
              "    3.38,",
              "    3.5,",
              "    3.75,",
              "    3.87,",
              "    3.88,",
              "    4,",
              "    4.38,",
              "    4.41,",
              "    4.48,",
              "    4.7,",
              "    4.8,",
              "    4.84,",
              "    4.95,",
              "    5,",
              "    5.01,",
              "    5.0200000000000005,",
              "    5.03,",
              "    5.15,",
              "    5.24,",
              "    5.26,",
              "    5.5,",
              "    5.55,",
              "    6,",
              "    6.03,",
              "    6.25,",
              "    6.66,",
              "    6.74,",
              "    6.76,",
              "    7,",
              "    7.12,",
              "    7.17,",
              "    7.24,",
              "    7.26,",
              "    7.3,",
              "    7.5,",
              "    8,",
              "    8.32,",
              "    8.33,",
              "    8.34,",
              "    8.75,",
              "    9,",
              "    9.07,",
              "    9.35,",
              "    9.43,",
              "    9.5,",
              "    10,",
              "    10.040000000000001,",
              "    10.05,",
              "    10.08,",
              "    10.09,",
              "    10.14,",
              "    10.41,",
              "    10.42,",
              "    11,",
              "    11.35,",
              "    11.36,",
              "    11.370000000000001,",
              "    11.43,",
              "    11.44,",
              "    11.5,",
              "    11.64,",
              "    11.66,",
              "    11.94,",
              "    12,",
              "    12.5,",
              "    12.8,",
              "    13,",
              "    13.5,",
              "    14,",
              "    14.200000000000001,",
              "    14.4,",
              "    14.48,",
              "    14.84,",
              "    15,",
              "    15.5,",
              "    15.63,",
              "    16,",
              "    16.1,",
              "    16.57,",
              "    16.66,",
              "    16.67,",
              "    16.68,",
              "    17,",
              "    17.34,",
              "    17.41,",
              "    17.44,",
              "    17.5,",
              "    18,",
              "    18.1,",
              "    18.75,",
              "    18.78,",
              "    20,",
              "    20.1,",
              "    20.12,",
              "    20.13,",
              "    20.150000000000002,",
              "    20.16,",
              "    20.17,",
              "    20.18,",
              "    20.82,",
              "    20.830000000000002,",
              "    20.84,",
              "    21,",
              "    22,",
              "    22.5,",
              "    22.75,",
              "    23,",
              "    23.63,",
              "    24,",
              "    24.900000000000002},",
              "  \"Less than $25\",",
              "  \"Other\"",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "RA_Giving"
                          }
                        },
                        "Property": "AMT"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "04840d7b-b843-4098-8107-18dcebce1ef2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ALLOC_DESC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af454ea3-ccba-4723-87ec-5986a16be3ea",
            "sourceColumn": "ALLOC_DESC",
            "summarizeBy": "none"
          },
          {
            "name": "APPEAL_DESCRIPTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7a781c1-0865-45f2-8fc9-cafcbe92a8b0",
            "sourceColumn": "APPEAL_DESCRIPTION",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dc670dc6-16a8-4f54-b831-429bc8622a49",
        "measures": [
          {
            "name": "Participation_Rate",
            "expression": "[Donor_Count] / SUM(Alumni_Counts[TOTAL_DONORS])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ea7e68d1-ccde-4edb-b5d9-ff3d9dc3f608"
          },
          {
            "name": "Donor_Count",
            "expression": "DISTINCTCOUNT(RA_Giving[DONOR])",
            "formatString": "0",
            "lineageTag": "370c1ec3-c9dd-4d57-a612-be5fb6278890"
          },
          {
            "name": "Avg_Gift",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "AVERAGE(RA_Giving[AMT])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "6cf4608c-88d8-4831-b145-00762b167749"
          },
          {
            "name": "Mdn_Gift",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MEDIAN(RA_Giving[AMT]) ",
            "lineageTag": "86b8bb16-0b02-46d5-b54e-6ac54083c2ba"
          },
          {
            "name": "Gift Band Measure",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM(RA_Giving[AMT]),",
              "FILTER(VALUES(RA_Giving[AMT]),",
              "COUNTROWS(",
              "FILTER('Gift Band Group',",
              "RA_Giving[AMT] >= 'Gift Band Group'[Min]",
              "&& RA_Giving[AMT] < 'Gift Band Group'[Max]))",
              "> 0 ))"
            ],
            "lineageTag": "06d16182-6893-436a-a5b0-67ae77391210"
          },
          {
            "name": "Difference",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(HASONEVALUE(RA_Giving[FISCAL_YR]),",
              "BLANK(),",
              "CALCULATE(",
              "SUM(RA_Giving[AMT]),",
              "FILTER(RA_Giving,RA_Giving[FISCAL_YR] = MAX(RA_Giving[FISCAL_YR]))",
              ")",
              "- CALCULATE(",
              "SUM(RA_Giving[AMT]),",
              "FILTER(RA_Giving,RA_Giving[FISCAL_YR] = MIN(RA_Giving[FISCAL_YR]))",
              ")",
              ") "
            ],
            "lineageTag": "fe393657-8ceb-4adf-b2fd-3e674af4bc3b"
          }
        ],
        "partitions": [
          {
            "name": "RA_Giving-2b21f57f-21f6-4825-8143-970c399065e9",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(\"padv\", [HierarchicalNavigation=true, Query=\"#(lf)with#(lf)#(lf)RA as#(lf)(#(lf)SELECT#(lf)       e.pref_school_code,#(lf)       e.id_number,#(lf)       (E.FIRST_NAME || ' ' ||E.LAST_NAME) AS NAME,#(lf)       E.INSTITUTIONAL_SUFFIX,#(lf)       E.PREF_NAME_SORT,#(lf)       ra.long_desc,#(lf)       ra.degree_year#(lf)FROM advance.entity e#(lf)#(lf)JOIN (SELECT DISTINCT dx.id_number,dx.degree_year, DX.DEGREE_LEVEL_CODE,ts.school_code long_desc#(lf)      FROM advance.degrees dx inner join advance.tms_school ts on dx.school_code = ts.school_code#(lf)      WHERE dx.institution_code = '6121'#(lf)            AND   qou61115.qou_fn_latest_degree_seq(dx.id_number,'L','yyyy') = dx.xsequence#(lf)            AND   dx.degree_year >='2000'#(lf)            AND   dx.degree_type <> 'S'#(lf)            AND   DX.NON_GRAD_CODE <> 'Y'#(lf)     ) ra#(lf)ON   e.id_number = ra.id_number#(lf))#(lf)#(lf)SELECT#(lf)       x.DONOR,#(lf)       E.PREF_MAIL_NAME,#(lf)       E.PREF_NAME_SORT,#(lf)       x.fiscal_yr,#(lf)       ra.degree_year,#(lf)       ra.long_desc,#(lf)       x.athletics_ind,#(lf)       substr(x.allocation_code,1,5),#(lf)       x.alloc_desc,#(lf)       x.appeal_channel,#(lf)       x.appeal_description,#(lf)       x.trans_nbr,#(lf)       COLA AS AMT#(lf)FROM#(lf)(#(lf)--OUTRIGHT GIFTS#(lf)select DISTINCT#(lf)       G.GIFT_DONOR_ID                                 DONOR,#(lf)       pg.prim_gift_receipt_number                     Trans_Nbr,#(lf)       pg.prim_gift_year_of_giving                     Fiscal_Yr,#(lf)       c.alloc_school,#(lf)       c.athletics_ind,#(lf)       g.gift_associated_amount   AS cola,#(lf)       c.allocation_code,#(lf)       c.short_name alloc_desc,#(lf)       appl.appeal_channel,#(lf)       appl.appeal_description#(lf)from advance.primary_gift pg,#(lf)     advance.tms_transaction_type tt,#(lf)     advance.tms_payment_type tpt,#(lf)     advance.gift g,#(lf)     advance.allocation c,#(lf)     ADVDEPLOY.mvw_min_proc_date mv,#(lf)      (SELECT ah.appeal_code, ah.description appeal_description, tat.full_desc appeal_channel,#(lf)      CASE WHEN ah.unit_code = 'CF' THEN 'Y' ELSE 'N' END creighton_fund#(lf)      FROM advance.appeal_header ah#(lf)      INNER JOIN advance.tms_appeal_type tat ON ah.appeal_type = tat.appeal_type_code) appl#(lf)where#(lf)      pg.prim_gift_year_of_giving >= '2000'#(lf)      and   pg.pledge_payment_ind <> 'Y'#(lf)      and   g.gift_appeal = appl.appeal_code(+)#(lf)      and   pg.prim_gift_transaction_type = tt.transaction_type_code#(lf)      and   pg.prim_gift_payment_type = tpt.payment_type_code#(lf)      and   pg.prim_gift_receipt_number = g.gift_receipt_number#(lf)      AND   mv.receipt_number = pg.PRIM_GIFT_RECEIPT_NUMBER#(lf)      AND   g.GIFT_ASSOCIATED_ALLOCATION = C.ALLOCATION_CODE#(lf)      and   g.gift_associated_amount > 0#(lf)      AND   mv.grp = 'gift'#(lf)      #(lf)      and   tt.ignore_ind <> 'Y'#(lf)      and   tpt.ignore_ind <> 'Y'#(lf)#(lf)#(lf)UNION#(lf)#(lf)--OPEN PLEDGE PMTS GIFTS#(lf)select DISTINCT#(lf)       G.GIFT_DONOR_ID                                 DONOR,#(lf)       pg.prim_gift_receipt_number                     Trans_Nbr,#(lf)       pg.prim_gift_year_of_giving                     Fiscal_Yr,#(lf)       c.alloc_school,#(lf)       c.athletics_ind,#(lf)       g.gift_associated_amount                            AS cola,#(lf)       c.allocation_code,#(lf)       c.short_name alloc_desc,#(lf)       appl.appeal_channel,#(lf)       appl.appeal_description#(lf)#(lf)from advance.primary_gift pg,#(lf)     (select DISTINCT pp1.prim_pledge_number pnbr, pt1.short_desc ptyp, ps1.short_desc pstat#(lf)        from advance.primary_pledge pp1, advance.tms_pledge_type pt1, advance.tms_pledge_status ps1#(lf)       where pp1.prim_pledge_type IN ('E1','P1','L2')#(lf)       and   pp1.prim_pledge_status NOT IN ('D','X')#(lf)       and   pp1.prim_pledge_type = pt1.pledge_type_code#(lf)       and   pp1.prim_pledge_status = ps1.pledge_status_code#(lf)      )plg,#(lf)     advance.tms_transaction_type tt,#(lf)     advance.tms_payment_type tpt,#(lf)     advance.gift g,#(lf)     advance.allocation c,#(lf)     ADVDEPLOY.mvw_min_proc_date mv,#(lf)     (SELECT ah.appeal_code, ah.description appeal_description, tat.full_desc appeal_channel,#(lf)     CASE WHEN ah.unit_code = 'CF' THEN 'Y' ELSE 'N' END creighton_fund#(lf)     FROM advance.appeal_header ah#(lf)     INNER JOIN advance.tms_appeal_type tat ON ah.appeal_type = tat.appeal_type_code) appl#(lf)where#(lf)      pg.prim_gift_year_of_giving >= '2000'#(lf)      and   pg.pledge_payment_ind = 'Y'#(lf)      AND   pg.prim_gift_pledge_number = plg.pnbr#(lf)      and   g.gift_appeal = appl.appeal_code(+)#(lf)      and   pg.prim_gift_transaction_type = tt.transaction_type_code#(lf)      and   pg.prim_gift_payment_type = tpt.payment_type_code#(lf)      and   pg.prim_gift_receipt_number = g.gift_receipt_number#(lf)      AND   mv.receipt_number = pg.prim_gift_receipt_number#(lf)      AND   g.GIFT_ASSOCIATED_ALLOCATION = C.ALLOCATION_CODE#(lf)      AND   mv.grp = 'gift'#(lf)      #(lf)      and   tt.ignore_ind <> 'Y'#(lf)      and   tpt.ignore_ind <> 'Y'#(lf)#(lf)   #(lf)) X#(lf)INNER JOIN ADVANCE.ENTITY E#(lf)ON E.ID_NUMBER = X.DONOR#(lf)#(lf)inner join ra#(lf)on ra.id_number = e.id_number#(lf)#(lf)--GROUP BY#(lf)--      x.DONOR, E.PREF_MAIL_NAME,E.PREF_NAME_SORT,x.fiscal_yr#(lf)\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"SUBSTR(X.ALLOCATION_CODE,1,5)\", \"Allocation Code\"}, {\"LONG_DESC\", \"College\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Alumni_Counts",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TOTAL_DONORS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8245c270-c4e5-4d26-9028-68bb1ec9be75",
            "sourceColumn": "TOTAL_DONORS",
            "summarizeBy": "none"
          },
          {
            "name": "DEGREE_YEAR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4a0566d-f5d1-491b-a6b8-8dda4572b914",
            "sourceColumn": "DEGREE_YEAR",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4f1aa402-8a95-4ddb-929d-713b9237dfa0",
        "partitions": [
          {
            "name": "Alumni_Counts-0751516a-3bfc-4fc1-a451-3c8e018481b0",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(\"padv\", [HierarchicalNavigation=true, Query=\"#(lf)with#(lf)#(lf)RA as#(lf)(#(lf)SELECT#(lf)       e.pref_school_code,#(lf)       e.id_number,#(lf)       (E.FIRST_NAME || ' ' ||E.LAST_NAME) AS NAME,#(lf)       E.INSTITUTIONAL_SUFFIX,#(lf)       E.PREF_NAME_SORT,#(lf)       ra.long_desc,#(lf)       ra.degree_year#(lf)FROM advance.entity e#(lf)#(lf)JOIN (SELECT DISTINCT dx.id_number,dx.degree_year, DX.DEGREE_LEVEL_CODE,ts.long_desc#(lf)      FROM advance.degrees dx inner join advance.tms_school ts on dx.school_code = ts.school_code#(lf)      WHERE dx.institution_code = '6121'#(lf)            AND   qou61115.qou_fn_latest_degree_seq(dx.id_number,'L','yyyy') = dx.xsequence#(lf)            AND   dx.degree_year >='2010'#(lf)            AND   dx.degree_type <> 'S'#(lf)            AND   DX.NON_GRAD_CODE <> 'Y'#(lf)     ) ra#(lf)ON   e.id_number = ra.id_number#(lf))#(lf)#(lf)select distinct count(ra.id_number) as total_donors,ra.degree_year#(lf)from ra#(lf)group by ra.degree_year#(lf)order by ra.degree_year#(lf)\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_9ad04f5f-ab49-45e1-9710-3674a90caa24",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a7322b0f-6bc2-449d-b95f-e025716d4e6e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d8cbf25f-99a5-4ac1-b83e-6c37d3c3cee9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f7a5443b-2f2d-49d5-80d0-9db07d5da8a4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ba7b997c-0179-47a4-8739-431b93cd143b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fb19c4d4-39f0-4872-b725-4d0ff0dd8002",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2986bca5-c6df-43f0-893e-9925a4a358fb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8d920d58-e86e-4ab8-9c9c-4fd19ee24b01",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "70ec1c2f-c89d-449e-9c15-cc4a181c4876",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c47af45f-8c2f-4dde-8669-7f8977774c04",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bf85ad92-40cb-4cb1-a097-246007dae37b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5a36c679-08ab-4dbe-8a17-bc67dee06d76",
                "ordinal": 3
              }
            ],
            "lineageTag": "143cbb21-1a04-4719-bac4-d944c964779c"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "0b48f339-3b54-42bf-bd82-3c3295624d28",
        "partitions": [
          {
            "name": "DateTableTemplate_9ad04f5f-ab49-45e1-9710-3674a90caa24-b74ac3fd-cd00-477f-a98f-9b3781213110",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Gift Band Group",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Giving Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9c5fed2-998c-4f01-8486-1a11e817d691",
            "sortByColumn": "Column",
            "sourceColumn": "Giving Level",
            "summarizeBy": "none"
          },
          {
            "name": "Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7dc90ca7-0759-402f-8c0e-1cf594a9bf98",
            "sourceColumn": "Min",
            "summarizeBy": "sum"
          },
          {
            "name": "Max",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0cd7f1f9-01fd-4a86-b2e7-dd93f2534a4e",
            "sourceColumn": "Max",
            "summarizeBy": "sum"
          },
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "RELATED('Custom Sort Table'[ID])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "4d86dc08-f260-474e-8886-c64dc2c08fbf",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "6bf76e4a-46cd-4d6f-94b5-d5de0cc2fe64",
        "partitions": [
          {
            "name": "Gift Band Group-5bbb3e69-1878-42be-b3a9-0bdbe3c29a6d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"TY9BCgMxCEWvEmR2leKEBOodeoOQRReFrtrFzP2pJppxETB+fQ9bg+f7ONL5eX3TlisgkLxc7szQsYH00vlLW2Fta14eK6s0Mtas6h5f2U4zzGNTfgPLgUsGnmTNpQ5sh0/6wId8R3IDToY4TBIs6JyC7CZTBddiMS6fCYORLqXT1OnSeNuaLBy8Lo5X6uTNjOTEUff+Bw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Group = _t, Min = _t, Max = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Group\", type text}, {\"Min\", Int64.Type}, {\"Max\", type number}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Group\", \"Giving Level\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",48.99,49.99,Replacer.ReplaceValue,{\"Max\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",98.99,99.99,Replacer.ReplaceValue,{\"Max\"})",
                "in",
                "    #\"Replaced Value1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Custom Sort Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68019f19-33dd-475f-8ad3-5981bb1ff149",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4261f851-0442-4f44-befa-de0cec1ea90b",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "13930bab-a344-4428-8e4d-a2ba3f0b7ca3",
        "partitions": [
          {
            "name": "Custom Sort Table-b779ea1d-553b-4fac-8722-df1e20e422c8",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"RY+xDcMwDARXEQh3ZkHKUhLt4A0EFykCpEoKe39ENPlOJ9z/PajeaX3tezrez0+aciUmpY07jXc6vmkqbaDsqMqJmqHFkYqzfPYKVAnXYIUM2+AtdBYMsLfvMcHoF3bjETOX0SJouOS/BUcFB11ZgaaKuyybjYxvbj8=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Type = _t, ID = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Type\", type text}, {\"ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Report Inventory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Report ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e041fac3-8974-4c3d-8afd-64fdc6eb48b3",
            "sourceColumn": "Report ID",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04d54a0a-80f4-4297-a1e4-c32181a28212",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5524d2ca-ed47-4255-bc68-96665ebb8164",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Report Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c96fa25e-9749-47f8-b841-258d7cd2509d",
            "sourceColumn": "Report Group",
            "summarizeBy": "none"
          },
          {
            "name": "Report Platform",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d116494-f017-4392-9e9f-11c25bd63448",
            "sourceColumn": "Report Platform",
            "summarizeBy": "none"
          },
          {
            "name": "Last Updated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ad2f630-6bd4-484b-829a-e823152bfa89",
            "sourceColumn": "Last Updated",
            "summarizeBy": "none"
          },
          {
            "name": "Change Log",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "421cb54c-e5bc-4475-9016-f0583cf93bb2",
            "sourceColumn": "Change Log",
            "summarizeBy": "none"
          },
          {
            "name": "Changed By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8e8dffd-3009-4354-a21c-a6a8953a3987",
            "sourceColumn": "Changed By",
            "summarizeBy": "none"
          },
          {
            "name": "Technical Support Co",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a52b2ba-ac87-4c13-93aa-9d2c96fb58e2",
            "sourceColumn": "Technical Support Co",
            "summarizeBy": "none"
          },
          {
            "name": "Report Directory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4cfc4f49-32db-468e-bc1f-e4d781a7c26d",
            "sourceColumn": "Report Directory",
            "summarizeBy": "none"
          },
          {
            "name": "Published Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16c851d9-dc89-44ea-be6a-bc71a42323c4",
            "sourceColumn": "Published Date",
            "summarizeBy": "none"
          },
          {
            "name": "Data Source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b86476ef-9efc-4d86-a90d-897e43777e50",
            "sourceColumn": "Data Source",
            "summarizeBy": "none"
          },
          {
            "name": "URL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68bb68b2-c156-4055-b60f-0b0f185f3fbf",
            "sourceColumn": "URL",
            "summarizeBy": "none"
          },
          {
            "name": "Stored Procedure _x0",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e45655d-9dc7-4ca6-bc48-70e15aede601",
            "sourceColumn": "Stored Procedure _x0",
            "summarizeBy": "none"
          },
          {
            "name": "Views",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7df05182-e95f-4b46-a4da-21d1b4a7f257",
            "sourceColumn": "Views",
            "summarizeBy": "none"
          },
          {
            "name": "Subreport",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7de78697-0e52-4af7-9cb5-4816bb643bd1",
            "sourceColumn": "Subreport",
            "summarizeBy": "none"
          },
          {
            "name": "Requestor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a605054-738a-46a6-b7c7-afc3d8385034",
            "sourceColumn": "Requestor",
            "summarizeBy": "none"
          },
          {
            "name": "IntendedAudience",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fce078ad-6024-4d4a-8a74-5925877231a7",
            "sourceColumn": "IntendedAudience",
            "summarizeBy": "none"
          },
          {
            "name": "DescriptionofLogic",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "437ac9e0-a804-4000-9710-de28b910d359",
            "sourceColumn": "DescriptionofLogic",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f796c697-89f3-4dbf-a77c-61f76eac16c8",
        "partitions": [
          {
            "name": "Report Inventory-86e1d226-475a-40b1-a1ac-487d6d837f6e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = SharePoint.Tables(\"https://creightonuniv.sharepoint.com/teams/UR/DevProgs/AdvSvcs/\", [ApiVersion = 15]),",
                "    #\"f37cb0b4-383d-4f4d-ae7d-6741cb3f1566\" = Source{[Id=\"f37cb0b4-383d-4f4d-ae7d-6741cb3f1566\"]}[Items],",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"f37cb0b4-383d-4f4d-ae7d-6741cb3f1566\",{{\"ID\", \"ID.1\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"FileSystemObjectType\", \"Id\", \"ServerRedirectedEmbedUri\", \"ServerRedirectedEmbedUrl\"}),",
                "    #\"Extracted Values\" = Table.TransformColumns(#\"Removed Columns\", {\"Report Group\", each Text.Combine(List.Transform(_, Text.From), \",\"), type text}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Extracted Values\",{\"ContentTypeId\", \"ComplianceAssetId\", \"ID.1\", \"Modified\", \"Created\", \"AuthorId\", \"EditorId\", \"OData__UIVersionString\", \"Attachments\", \"GUID\", \"FirstUniqueAncestorSecurableObject\", \"RoleAssignments\", \"AttachmentFiles\", \"ContentType\", \"GetDlpPolicyTip\", \"FieldValuesAsHtml\", \"FieldValuesAsText\", \"FieldValuesForEdit\", \"File\", \"Folder\", \"LikedByInformation\", \"ParentList\", \"Properties\", \"Versions\", \"Author\", \"Editor\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns1\", each ([Report Platform] = \"Power BI\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Last Refresh Date",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Last Refresh Date Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3f960aa8-567d-4a0e-81c7-3045e80749ca",
            "sourceColumn": "Last Refresh Date Time",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d8764fbc-dd33-4d21-b9ea-1ef4dd0e0698"
                },
                "isDefault": true,
                "relationship": "e69c1fb5-91c4-4fa3-a884-679b35d93cde"
              }
            ]
          }
        ],
        "lineageTag": "5b4ee6cd-60b6-4e52-bd66-88bc396d6902",
        "partitions": [
          {
            "name": "Last Refresh Date-1470bbf5-d4ce-493c-9256-877b155d7911",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DateTime.From(DateTimeZone.SwitchZone(DateTimeZone.FixedLocalNow(),10)),",
                "    #\"Converted to Table\" = #table(1, {{Source}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Last Refresh Date Time\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Last Refresh Date Time\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_d8764fbc-dd33-4d21-b9ea-1ef4dd0e0698",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1107593b-cd76-47f0-818b-92a63cf5bf0c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e0488eba-eceb-46c5-a0be-3cfa0db9debb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8fc72422-d257-41a3-9078-46e6f6fe0555",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7ec3466a-cb22-42c2-939b-06fb0f09fccd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e6d0e868-3759-4887-8f94-6cc4cf575668",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "23a2f860-4ab7-44e2-9750-4778db0a4570",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9f8865a6-e454-4182-980d-0aad53caa6de",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ad9dfc0e-0edb-4d5d-bf22-cf0af357004e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "94fefda4-3c8e-4ec6-83e0-382c13540961",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d8447473-9335-465d-b165-936f667c0726",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e89a75ec-ef57-45ba-a1ca-bc372b039c02",
                "ordinal": 3
              }
            ],
            "lineageTag": "391ed7bd-25a4-4ca5-ad26-32d87566babe"
          }
        ],
        "isHidden": true,
        "lineageTag": "53d910f0-24fd-493a-997b-ad9e06868b51",
        "partitions": [
          {
            "name": "LocalDateTable_d8764fbc-dd33-4d21-b9ea-1ef4dd0e0698-ebb730a0-e931-4820-b42a-5dc430b6e525",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Last Refresh Date'[Last Refresh Date Time])), 1, 1), Date(Year(MAX('Last Refresh Date'[Last Refresh Date Time])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}