{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.746.0 (23.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Calendar - FY13+\",\"Current Parents_5Yr\",\"Current Parents_Unique\",\"Revenue_5Yrs\",\"Production_5Yrs\",\"PLC Members\",\"Assigned Prim Managers\",\"Fac-Staff (Primary)\",\"Fac-Staff (Spouse)\",\"Students\",\"General Measures\",\"Key Measures\",\"PLC Measures\",\"Alumni Measures\",\"F/S Measures\",\"Assigned Measures\",\"Ignatian Merit Indicator\",\"Data Source\",\"DataSource\",\"Max Rev Date\",\"Fiscal Yrs\",\"F/S (Primary)_Unique\",\"F/S (Spouse)_Unique\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Data Source",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "This parameter allows the user to select one of the Snapshots or the live database.",
        "expression": "\"PADV\" meta [IsParameterQuery=true, List={\"PADV\", \"ADVJUL21\", \"ADVJUL22\", \"ADVJUL23\"}, DefaultValue=\"PADV\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "635c3c2b-9de5-4dc3-aafc-5efaab0e2efe"
      }
    ],
    "relationships": [
      {
        "name": "ea55c0c5-6008-4302-acee-1528d86e4edb",
        "fromColumn": "ComboKey",
        "fromTable": "PLC Members",
        "toColumn": "ComboKey",
        "toTable": "Current Parents_5Yr"
      },
      {
        "name": "a66eb81d-0a6d-439b-8337-3dd4887e8054",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ComboKey",
        "fromTable": "Revenue_5Yrs",
        "isActive": false,
        "toColumn": "ComboKey",
        "toTable": "Current Parents_5Yr"
      },
      {
        "name": "f84e5d4c-ffa2-4251-be8b-8c4072c90555",
        "fromColumn": "Trans Dt",
        "fromTable": "Revenue_5Yrs",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar - FY13+"
      },
      {
        "name": "432dc646-5c5c-42a7-8300-9e221ab506e8",
        "fromColumn": "ComboKey",
        "fromTable": "Assigned Prim Managers",
        "toColumn": "ComboKey",
        "toTable": "Current Parents_5Yr"
      },
      {
        "name": "f10750b4-2643-4b69-a3f5-1025d0f7a209",
        "fromColumn": "ComboIDKey",
        "fromTable": "Fac-Staff (Primary)",
        "toColumn": "ComboIDKey",
        "toTable": "Current Parents_5Yr"
      },
      {
        "name": "7e7657e8-06c8-4db2-a1b3-23880622a922",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ComboIDKey2",
        "fromTable": "Current Parents_5Yr",
        "toCardinality": "many",
        "toColumn": "ComboIDKey",
        "toTable": "Fac-Staff (Spouse)"
      },
      {
        "name": "cf32353e-d470-423e-84cf-cdc5b5bcfcf6",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ComboKey",
        "fromTable": "Production_5Yrs",
        "isActive": false,
        "toColumn": "ComboKey",
        "toTable": "Current Parents_5Yr"
      },
      {
        "name": "dde3441b-1ce9-441b-a5ce-eb456e1dff80",
        "fromColumn": "Ignatian Ind",
        "fromTable": "Revenue_5Yrs",
        "toColumn": "Indicator",
        "toTable": "Ignatian Merit Indicator"
      },
      {
        "name": "efe66f60-671e-48c9-a012-592883883edc",
        "fromColumn": "Ignatian Ind",
        "fromTable": "Production_5Yrs",
        "toColumn": "Indicator",
        "toTable": "Ignatian Merit Indicator"
      },
      {
        "name": "82d3166f-bf46-4ec2-9e1c-a190863a7263",
        "fromColumn": "Trans Dt",
        "fromTable": "Production_5Yrs",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar - FY13+"
      },
      {
        "name": "b61341ef-eacb-47fc-bb34-9fda10cdb3dd",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "HH Key",
        "fromTable": "Current Parents_5Yr",
        "toCardinality": "many",
        "toColumn": "HH Key",
        "toTable": "Students"
      },
      {
        "name": "b39840f6-16b4-4216-b9a3-402fbfc4718f",
        "fromColumn": "HH Key",
        "fromTable": "Current Parents_5Yr",
        "toColumn": "HH Key",
        "toTable": "Current Parents_Unique"
      },
      {
        "name": "5ab2ac1f-3e00-4c47-a320-f8a1bcf316bf",
        "fromColumn": "HH Key",
        "fromTable": "Students",
        "isActive": false,
        "toColumn": "HH Key",
        "toTable": "Current Parents_Unique"
      },
      {
        "name": "9146e6fd-e7da-4965-8991-55b3bdf9d026",
        "fromColumn": "HH Key",
        "fromTable": "Revenue_5Yrs",
        "toColumn": "HH Key",
        "toTable": "Current Parents_Unique"
      },
      {
        "name": "fc3140b1-d10f-446e-81d7-f47ca69cce1d",
        "fromColumn": "HH Key",
        "fromTable": "Production_5Yrs",
        "toColumn": "HH Key",
        "toTable": "Current Parents_Unique"
      },
      {
        "name": "e4ee9898-7648-408f-b934-c54a6d700a46",
        "fromColumn": "Fiscal Yr",
        "fromTable": "Current Parents_5Yr",
        "toColumn": "Fiscal Yr",
        "toTable": "Fiscal Yrs"
      },
      {
        "name": "fe1cc58b-e36e-4d9c-ae4a-bd2aa0dfebf9",
        "fromColumn": "Fiscal Yr",
        "fromTable": "PLC Members",
        "isActive": false,
        "toColumn": "Fiscal Yr",
        "toTable": "Fiscal Yrs"
      },
      {
        "name": "7505ae99-660d-4a64-a073-38af58c921ec",
        "fromColumn": "Fiscal Yr",
        "fromTable": "Revenue_5Yrs",
        "toColumn": "Fiscal Yr",
        "toTable": "Fiscal Yrs"
      },
      {
        "name": "6107be29-4c30-4ef6-ae7f-03de5a9e73dc",
        "fromColumn": "Fiscal Yr",
        "fromTable": "Production_5Yrs",
        "toColumn": "Fiscal Yr",
        "toTable": "Fiscal Yrs"
      },
      {
        "name": "d120de95-abd7-4424-9ae2-79f263216fda",
        "fromColumn": "Fiscal Yr",
        "fromTable": "Assigned Prim Managers",
        "isActive": false,
        "toColumn": "Fiscal Yr",
        "toTable": "Fiscal Yrs"
      },
      {
        "name": "82e7049b-d729-4620-b66b-c6f9359acb7f",
        "fromColumn": "F/S ID",
        "fromTable": "Fac-Staff (Primary)",
        "toColumn": "F/S ID",
        "toTable": "F/S (Primary)_Unique"
      },
      {
        "name": "9d16947b-b652-4880-90a9-361066034e30",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Prim Parent ID",
        "fromTable": "Current Parents_Unique",
        "isActive": false,
        "toColumn": "F/S ID",
        "toTable": "F/S (Primary)_Unique"
      },
      {
        "name": "d051e5f0-7d04-4e37-b8e7-01016fe573b3",
        "fromColumn": "F/S ID",
        "fromTable": "Fac-Staff (Spouse)",
        "toColumn": "F/S ID",
        "toTable": "F/S (Spouse)_Unique"
      },
      {
        "name": "af0e8b29-1e40-49f2-890b-73f02a1680df",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Sec Parent ID",
        "fromTable": "Current Parents_Unique",
        "isActive": false,
        "toColumn": "F/S ID",
        "toTable": "F/S (Spouse)_Unique"
      },
      {
        "name": "5ffbd130-dfca-462f-a52e-ecee0a895c5d",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "FiscalYear",
        "fromTable": "Calendar - FY13+",
        "toColumn": "Fiscal Yr",
        "toTable": "Fiscal Yrs"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Current Parents_5Yr",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "HH Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "baf113c9-f467-45ac-b559-ce953187e180",
            "sourceColumn": "HH Key",
            "summarizeBy": "none"
          },
          {
            "name": "ComboKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72975c99-2eb6-4159-ac9b-58eca32088d5",
            "sourceColumn": "ComboKey",
            "summarizeBy": "none"
          },
          {
            "name": "Prim Parent ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b5e24b9-6fa6-46cb-a664-7678f4f85cab",
            "sourceColumn": "Prim Parent ID",
            "summarizeBy": "none"
          },
          {
            "name": "Prim Parent Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a93dd64-5ffc-4c87-aed7-1af5fa521909",
            "sourceColumn": "Prim Parent Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prim Inst Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f25df459-d69c-4d8b-9059-7db103feeffe",
            "sourceColumn": "Prim Inst Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Rec Types",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34d776da-827d-4f4c-9f9c-9dc7b6bce5c1",
            "sourceColumn": "Primary Rec Types",
            "summarizeBy": "none"
          },
          {
            "name": "Sec Parent ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c18b2dc-ea99-4710-a4eb-d1014c353734",
            "sourceColumn": "Sec Parent ID",
            "summarizeBy": "none"
          },
          {
            "name": "Sec Parent Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3807442a-d5fc-4e07-9a25-7011bdea2cd5",
            "sourceColumn": "Sec Parent Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sec Inst Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b7d501e-6da6-4953-a71d-3c0f40dc388c",
            "sourceColumn": "Sec Inst Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "Sec Rec Types",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "024f756f-bde8-4658-b924-b572a01b7e16",
            "sourceColumn": "Sec Rec Types",
            "summarizeBy": "none"
          },
          {
            "name": "MG EVI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f9f4f761-8e7b-4d3a-88ea-f6850cd01176",
            "sourceColumn": "MG EVI",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Worth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "727145f4-64c7-4c32-9f1d-29ad2b6dabfd",
            "sourceColumn": "Net Worth",
            "summarizeBy": "none"
          },
          {
            "name": "Six Square",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfb0dada-cb80-410b-8062-22aa5d457a34",
            "sourceColumn": "Six Square",
            "summarizeBy": "none"
          },
          {
            "name": "Engagement Score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6cc50d66-1015-42d4-baa0-ec8205764c8b",
            "sourceColumn": "Engagement Score",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "861b0a20-3ddc-44f9-845f-ba1408965498",
            "sourceColumn": "Fiscal Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Parent Cnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e82a8611-f4b4-43a8-a6e7-3d61ae93d0d6",
            "sourceColumn": "Parent Cnt",
            "summarizeBy": "sum"
          },
          {
            "name": "Alumni",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bcac498d-764f-4e66-968a-33e3240ba6e4",
            "sourceColumn": "Alumni",
            "summarizeBy": "none"
          },
          {
            "name": "Alumni Cnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fd3e8489-83b7-456b-b932-baca5479951e",
            "sourceColumn": "Alumni Cnt",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort Parent Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a7acf64-82bf-4b3d-86f3-f5dfe38d61da",
            "sourceColumn": "Sort Parent Name",
            "summarizeBy": "none"
          },
          {
            "name": "PLC Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6a33d1d8-70c2-446f-9990-f5feb1872803",
            "sourceColumn": "PLC Ind",
            "summarizeBy": "sum"
          },
          {
            "name": "Assigned Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e77598d6-ac72-4839-b5d4-aad2bd47ce06",
            "sourceColumn": "Assigned Ind",
            "summarizeBy": "sum"
          },
          {
            "name": "F/S Cnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "637819e0-4c35-4335-a9ef-dc48e861b071",
            "sourceColumn": "F/S Cnt",
            "summarizeBy": "sum"
          },
          {
            "name": "ComboIDKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b43084e2-1fa7-4f28-bf33-1c4a1436e675",
            "sourceColumn": "ComboIDKey",
            "summarizeBy": "none"
          },
          {
            "name": "ComboIDKey2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19607cc4-c401-4cf4-983a-ea1e2eca122d",
            "sourceColumn": "ComboIDKey2",
            "summarizeBy": "none"
          },
          {
            "name": "Rev Donor Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5cc92865-d744-4ff2-b8cd-52ee9a8aca53",
            "sourceColumn": "Rev Donor Ind",
            "summarizeBy": "sum"
          },
          {
            "name": "Prod Donor Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b8c30c80-3828-408f-94d3-a5d6bc9182f9",
            "sourceColumn": "Prod Donor Ind",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "a50325f1-8860-47c9-8cc4-6d803303941f",
        "partitions": [
          {
            "name": "Current Parents_5Yr-30d3a8c5-69ec-4a4f-8ceb-487cb1839c4f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(#\"Data Source\", [HierarchicalNavigation=true, Query=\"-- Query developed for the Current Parent Dashboard; this logic is intended to pull the Current Parents for each of the last five FYs,#(lf)--   with indicators for each FY to show which parents are Alumni, as well as indicators for each FY to show which households have assigned #(lf)--   Primary Managers and which households are members of the PLC.  smk 8/22/2023#(lf)-- Added indicators for Prod vs. Rev Donors, and Faculty-Staff. smk 9/1/2023#(lf)#(lf)-- The following subquery pulls who was a Current Parent in each of the current and previous four fiscal years. The Current Parent View#(lf)-- is based on relationships to children who were Current Students each fiscal year.#(lf)WITH parents as (#(lf)            select xp4.parent_household_key hk,#(lf)                   (select * from advur.vw_current_fiscal_year)-4 fy,#(lf)                   CASE WHEN (select * from advur.vw_current_fiscal_year)-4 #(lf)                                            BETWEEN advur.fn_get_fytd_fiscalyear(to_char(add_months(xp4.start_date, 6),'mm/dd/yyyy'))#(lf)                                                AND advur.fn_get_fytd_fiscalyear(to_char(add_months(xp4.stop_date, 6),'mm/dd/yyyy'))#(lf)                        THEN 1 ELSE 0 END p_ind#(lf)              from advur.mvw_hh_parents xp4#(lf)            UNION ALL#(lf)            select xp3.parent_household_key hk,#(lf)                   (select * from advur.vw_current_fiscal_year)-3 fy,#(lf)                   CASE WHEN (select * from advur.vw_current_fiscal_year)-3 #(lf)                                            BETWEEN advur.fn_get_fytd_fiscalyear(to_char(add_months(xp3.start_date, 6),'mm/dd/yyyy'))#(lf)                                                AND advur.fn_get_fytd_fiscalyear(to_char(add_months(xp3.stop_date, 6),'mm/dd/yyyy'))#(lf)                        THEN 1 ELSE 0 END p_ind#(lf)              from advur.mvw_hh_parents xp3#(lf)            UNION ALL#(lf)            select xp2.parent_household_key hk,#(lf)                   (select * from advur.vw_current_fiscal_year)-2 fy,#(lf)                   CASE WHEN (select * from advur.vw_current_fiscal_year)-2 #(lf)                                            BETWEEN advur.fn_get_fytd_fiscalyear(to_char(add_months(xp2.start_date, 6),'mm/dd/yyyy'))#(lf)                                                AND advur.fn_get_fytd_fiscalyear(to_char(add_months(xp2.stop_date, 6),'mm/dd/yyyy'))#(lf)                        THEN 1 ELSE 0 END p_ind#(lf)              from advur.mvw_hh_parents xp2#(lf)            UNION ALL#(lf)            select xp1.parent_household_key hk,#(lf)                   (select * from advur.vw_current_fiscal_year)-1 fy,#(lf)                   CASE WHEN (select * from advur.vw_current_fiscal_year)-1 #(lf)                                            BETWEEN advur.fn_get_fytd_fiscalyear(to_char(add_months(xp1.start_date, 6),'mm/dd/yyyy'))#(lf)                                                AND advur.fn_get_fytd_fiscalyear(to_char(add_months(xp1.stop_date, 6),'mm/dd/yyyy'))#(lf)                        THEN 1 ELSE 0 END p_ind#(lf)              from advur.mvw_hh_parents xp1#(lf)            UNION ALL#(lf)            select xp0.parent_household_key hk,#(lf)                   (select * from advur.vw_current_fiscal_year)-0 fy,#(lf)                    CASE WHEN (select * from advur.vw_current_fiscal_year) #(lf)                                             BETWEEN advur.fn_get_fytd_fiscalyear(to_char(add_months(xp0.start_date, 6),'mm/dd/yyyy'))#(lf)                                                 AND advur.fn_get_fytd_fiscalyear(to_char(add_months(xp0.stop_date, 6),'mm/dd/yyyy'))#(lf)                         THEN 1 ELSE 0 END p_ind#(lf)              from advur.mvw_hh_parents xp0#(lf)            ),#(lf)-- The following subquery provides indicators for each household to show if they were members of the PLC each FY. smk 8/22/2023#(lf)plccomm as (#(lf)            select distinct xg4.household_key hk,#(lf)                   xg4.household_key||to_char((select * from advur.vw_current_fiscal_year)-4) uniq,#(lf)                   CASE WHEN xg4.secondary_id_number > ' ' THEN 2#(lf)                      ELSE 1 END              par_cnt,#(lf)                   (select * from advur.vw_current_fiscal_year)-4 fy,#(lf)                   EXTRACT(YEAR FROM to_date(xc4.start_dt,'YYYYMMDD')) start_yr,#(lf)                   EXTRACT(YEAR FROM CASE WHEN xc4.stop_dt = '00000000' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc4.stop_dt,1,4) = '0000' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc4.stop_dt,5,4) = '0000' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc4.stop_dt,5,2) = '00' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc4.stop_dt,7,2) = '00' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460 #(lf)                                        ELSE add_months(to_date(xc4.stop_dt,'YYYYMMDD'),6) END) stop_yr,#(lf)                   1  p_ind#(lf)              from advance.committee xc4#(lf)             inner join advur.mvw_hh_entities_with_deceased xg4 ON (xc4.id_number = xg4.primary_id_number OR xc4.id_number = xg4.secondary_id_number)#(lf)             inner join advance.entity e1                       ON xc4.id_number = e1.id_number#(lf)             where xc4.committee_code = 'PLC'#(lf)             and   xc4.start_dt <> '00000000'#(lf)             and   substr(xc4.start_dt,1,4) <> '0000'#(lf)             and   substr(xc4.start_dt,5,4) <> '0000'#(lf)             and   substr(xc4.start_dt,5,2) <> '00'#(lf)             and   substr(xc4.start_dt,7,2) <> '00'#(lf)             and   (select * from advur.vw_current_fiscal_year)-4 BETWEEN EXTRACT(YEAR FROM add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)) #(lf)                                                                      AND EXTRACT(YEAR FROM add_months(to_date(#(lf)                                                                          CASE WHEN xc4.stop_dt = '00000000' OR substr(xc4.stop_dt,1,4) = '0000'#(lf)                                                                               OR substr(xc4.stop_dt,5,4) = '0000' OR substr(xc4.stop_dt,5,2) = '00'#(lf)                                                                               OR substr(xc4.stop_dt,7,2) = '00' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),48) #(lf)                                                                             ELSE to_date(xc4.stop_dt,'YYYYMMDD') END),6))#(lf)            UNION ALL#(lf)            select distinct xg3.household_key hk,#(lf)                   xg3.household_key||to_char((select * from advur.vw_current_fiscal_year)-3) uniq,#(lf)                   CASE WHEN xg3.secondary_id_number > ' ' THEN 2#(lf)                      ELSE 1 END              par_cnt,#(lf)                   (select * from advur.vw_current_fiscal_year)-3 fy,#(lf)                   EXTRACT(YEAR FROM to_date(xc3.start_dt,'YYYYMMDD')) start_yr,#(lf)                   EXTRACT(YEAR FROM CASE WHEN xc3.stop_dt = '00000000' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc3.stop_dt,1,4) = '0000' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc3.stop_dt,5,4) = '0000' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc3.stop_dt,5,2) = '00' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc3.stop_dt,7,2) = '00' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460 #(lf)                                        ELSE add_months(to_date(xc3.stop_dt,'YYYYMMDD'),6) END) stop_yr,#(lf)                   1  p_ind#(lf)              from advance.committee xc3#(lf)             inner join advur.mvw_hh_entities_with_deceased xg3 ON (xc3.id_number = xg3.primary_id_number OR xc3.id_number = xg3.secondary_id_number)#(lf)             inner join advance.entity e1                       ON xc3.id_number = e1.id_number#(lf)             where xc3.committee_code = 'PLC'#(lf)             and   xc3.start_dt <> '00000000'#(lf)             and   substr(xc3.start_dt,1,4) <> '0000'#(lf)             and   substr(xc3.start_dt,5,4) <> '0000'#(lf)             and   substr(xc3.start_dt,5,2) <> '00'#(lf)             and   substr(xc3.start_dt,7,2) <> '00'#(lf)             and   (select * from advur.vw_current_fiscal_year)-3 BETWEEN EXTRACT(YEAR FROM add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)) #(lf)                                                                      AND EXTRACT(YEAR FROM add_months(to_date(#(lf)                                                                      CASE WHEN xc3.stop_dt = '00000000' OR substr(xc3.stop_dt,1,4) = '0000'#(lf)                                                                           OR substr(xc3.stop_dt,5,4) = '0000' OR substr(xc3.stop_dt,5,2) = '00'#(lf)                                                                           OR substr(xc3.stop_dt,7,2) = '00' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),48) #(lf)                                                                         ELSE to_date(xc3.stop_dt,'YYYYMMDD') END),6))#(lf)            UNION ALL#(lf)            select distinct xg2.household_key hk,#(lf)                   xg2.household_key||to_char((select * from advur.vw_current_fiscal_year)-2) uniq,#(lf)                   CASE WHEN xg2.secondary_id_number > ' ' THEN 2#(lf)                      ELSE 1 END              par_cnt,#(lf)                   (select * from advur.vw_current_fiscal_year)-2 fy,#(lf)                   EXTRACT(YEAR FROM to_date(xc2.start_dt,'YYYYMMDD')) start_yr,#(lf)                   EXTRACT(YEAR FROM CASE WHEN xc2.stop_dt = '00000000' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc2.stop_dt,1,4) = '0000' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc2.stop_dt,5,4) = '0000' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc2.stop_dt,5,2) = '00' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc2.stop_dt,7,2) = '00' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460 #(lf)                                        ELSE add_months(to_date(xc2.stop_dt,'YYYYMMDD'),6) END) stop_yr,#(lf)                   1  p_ind#(lf)              from advance.committee xc2#(lf)             inner join advur.mvw_hh_entities_with_deceased xg2 ON (xc2.id_number = xg2.primary_id_number OR xc2.id_number = xg2.secondary_id_number)#(lf)             inner join advance.entity e1                       ON xc2.id_number = e1.id_number#(lf)             where xc2.committee_code = 'PLC'#(lf)             and   xc2.start_dt <> '00000000'#(lf)             and   substr(xc2.start_dt,1,4) <> '0000'#(lf)             and   substr(xc2.start_dt,5,4) <> '0000'#(lf)             and   substr(xc2.start_dt,5,2) <> '00'#(lf)             and   substr(xc2.start_dt,7,2) <> '00'#(lf)             and   (select * from advur.vw_current_fiscal_year)-2 BETWEEN EXTRACT(YEAR FROM add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)) #(lf)                                                                      AND EXTRACT(YEAR FROM add_months(to_date(#(lf)                                                                      CASE WHEN xc2.stop_dt = '00000000' OR substr(xc2.stop_dt,1,4) = '0000'#(lf)                                                                             OR substr(xc2.stop_dt,5,4) = '0000' OR substr(xc2.stop_dt,5,2) = '00'#(lf)                                                                             OR substr(xc2.stop_dt,7,2) = '00' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),48) #(lf)                                                                         ELSE to_date(xc2.stop_dt,'YYYYMMDD') END),6))#(lf)            UNION ALL#(lf)            select distinct xg1.household_key hk,#(lf)                   xg1.household_key||to_char((select * from advur.vw_current_fiscal_year)-1) uniq,#(lf)                   CASE WHEN xg1.secondary_id_number > ' ' THEN 2#(lf)                      ELSE 1 END              par_cnt,#(lf)                   (select * from advur.vw_current_fiscal_year)-1 fy,#(lf)                   EXTRACT(YEAR FROM to_date(xc1.start_dt,'YYYYMMDD')) start_yr,#(lf)                   EXTRACT(YEAR FROM CASE WHEN xc1.stop_dt = '00000000' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc1.stop_dt,1,4) = '0000' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc1.stop_dt,5,4) = '0000' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc1.stop_dt,5,2) = '00' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc1.stop_dt,7,2) = '00' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460 #(lf)                                        ELSE add_months(to_date(xc1.stop_dt,'YYYYMMDD'),6) END) stop_yr,#(lf)                   1  p_ind#(lf)              from advance.committee xc1#(lf)             inner join advur.mvw_hh_entities_with_deceased xg1 ON (xc1.id_number = xg1.primary_id_number OR xc1.id_number = xg1.secondary_id_number)#(lf)             inner join advance.entity e1                       ON xc1.id_number = e1.id_number#(lf)             where xc1.committee_code = 'PLC'#(lf)             and   xc1.start_dt <> '00000000'#(lf)             and   substr(xc1.start_dt,1,4) <> '0000'#(lf)             and   substr(xc1.start_dt,5,4) <> '0000'#(lf)             and   substr(xc1.start_dt,5,2) <> '00'#(lf)             and   substr(xc1.start_dt,7,2) <> '00'#(lf)             and   (select * from advur.vw_current_fiscal_year)-1 BETWEEN EXTRACT(YEAR FROM add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)) #(lf)                                                                      AND EXTRACT(YEAR FROM add_months(to_date(#(lf)                                                                      CASE WHEN xc1.stop_dt = '00000000' OR substr(xc1.stop_dt,1,4) = '0000'#(lf)                                                                            OR substr(xc1.stop_dt,5,4) = '0000' OR substr(xc1.stop_dt,5,2) = '00'#(lf)                                                                            OR substr(xc1.stop_dt,7,2) = '00' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),48) #(lf)                                                                         ELSE to_date(xc1.stop_dt,'YYYYMMDD') END),6))#(lf)#(lf)            UNION ALL#(lf)            select distinct xg0.household_key hk,#(lf)                   xg0.household_key||to_char((select * from advur.vw_current_fiscal_year)-0) uniq,#(lf)                   CASE WHEN xg0.secondary_id_number > ' ' THEN 2#(lf)                      ELSE 1 END              par_cnt,#(lf)                   (select * from advur.vw_current_fiscal_year)-0 fy,#(lf)                   EXTRACT(YEAR FROM to_date(xc0.start_dt,'YYYYMMDD')) start_yr,#(lf)                   EXTRACT(YEAR FROM CASE WHEN xc0.stop_dt = '00000000' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc0.stop_dt,1,4) = '0000' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc0.stop_dt,5,4) = '0000' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc0.stop_dt,5,2) = '00' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460#(lf)                                          WHEN substr(xc0.stop_dt,7,2) = '00' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460 #(lf)                                        ELSE add_months(to_date(xc0.stop_dt,'YYYYMMDD'),6) END) stop_yr,#(lf)                   1  p_ind#(lf)              from advance.committee xc0#(lf)             inner join advur.mvw_hh_entities_with_deceased xg0 ON (xc0.id_number = xg0.primary_id_number OR xc0.id_number = xg0.secondary_id_number)#(lf)             inner join advance.entity e1                       ON xc0.id_number = e1.id_number#(lf)             where xc0.committee_code = 'PLC'#(lf)             and   xc0.start_dt <> '00000000'#(lf)             and   substr(xc0.start_dt,1,4) <> '0000'#(lf)             and   substr(xc0.start_dt,5,4) <> '0000'#(lf)             and   substr(xc0.start_dt,5,2) <> '00'#(lf)             and   substr(xc0.start_dt,7,2) <> '00'#(lf)             and   (select * from advur.vw_current_fiscal_year)-0 BETWEEN EXTRACT(YEAR FROM add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)) #(lf)                                                                      AND EXTRACT(YEAR FROM add_months(to_date(#(lf)                                                                      CASE WHEN xc0.stop_dt = '00000000' OR substr(xc0.stop_dt,1,4) = '0000'#(lf)                                                                            OR substr(xc0.stop_dt,5,4) = '0000' OR substr(xc0.stop_dt,5,2) = '00'#(lf)                                                                            OR substr(xc0.stop_dt,7,2) = '00' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),48) #(lf)                                                                         ELSE to_date(xc0.stop_dt,'YYYYMMDD') END),6))#(lf)      ),#(lf)-- The following subquery provides indicators for each household to show if they were assigned to a PM each FY. smk 8/22/2023#(lf)managers AS (#(lf)            SELECT DISTINCT hk4.HOUSEHOLD_KEY     HH_Key,#(lf)                   hk4.HOUSEHOLD_KEY||to_char((select * from advur.vw_current_fiscal_year)-4) ComboKey,#(lf)                   hk4.member_count               Par_Cnt,#(lf)                   to_char((select * from advur.vw_current_fiscal_year)-4) qual_yr#(lf)              FROM advance.assignment assn4#(lf)             INNER JOIN advance.staff s4                ON s4.id_number = assn4.assignment_id_number#(lf)             INNER JOIN advance.prospect_entity pe4     ON assn4.prospect_id = pe4.prospect_id#(lf)             INNER JOIN advur.VW_ENT_HOUSEHOLD_KEYS hk4 ON pe4.ID_NUMBER = hk4.ID_NUMBER #(lf)             WHERE assn4.assignment_type = 'PM' #(lf)             AND   pe4.primary_ind = 'Y'#(lf)             AND   trunc(assn4.date_added) <> '04-FEB-1999'#(lf)             AND   ((s4.unit_code IN ('DEV', 'SG', 'ATH', 'TRF')#(lf)             AND     s4.staff_type_code IN ('GO','MO','SR')) #(lf)                OR   s4.unit_code = 'ARO')#(lf)             and   (select * from advur.vw_current_fiscal_year)-4 BETWEEN EXTRACT(YEAR FROM add_months(NVL(trunc(assn4.start_date), #(lf)                                                                          TRUNC(assn4.date_added)),6))#(lf)                                                                  AND nvl(EXTRACT(YEAR FROM add_months(trunc(assn4.stop_date),6)),#(lf)                                                                          EXTRACT(YEAR FROM add_months(NVL(trunc(assn4.start_date), #(lf)                                                                          TRUNC(assn4.date_added)),6))+4)#(lf)            UNION ALL#(lf)            SELECT DISTINCT hk3.HOUSEHOLD_KEY     HH_Key,#(lf)                   hk3.HOUSEHOLD_KEY||to_char((select * from advur.vw_current_fiscal_year)-3) ComboKey,#(lf)                   hk3.member_count               Par_Cnt,#(lf)                   to_char((select * from advur.vw_current_fiscal_year)-3) qual_yr#(lf)              FROM advance.assignment assn3#(lf)             INNER JOIN advance.staff s3                ON s3.id_number = assn3.assignment_id_number#(lf)             INNER JOIN advance.prospect_entity pe3     ON assn3.prospect_id = pe3.prospect_id#(lf)             INNER JOIN advur.VW_ENT_HOUSEHOLD_KEYS hk3 ON pe3.ID_NUMBER = hk3.ID_NUMBER #(lf)             WHERE assn3.assignment_type = 'PM' #(lf)             AND   pe3.primary_ind = 'Y'#(lf)             AND   trunc(assn3.date_added) <> '04-FEB-1999'#(lf)             AND   ((s3.unit_code IN ('DEV', 'SG', 'ATH', 'TRF')#(lf)             AND     s3.staff_type_code IN ('GO','MO','SR')) #(lf)                OR   s3.unit_code = 'ARO')#(lf)             and   (select * from advur.vw_current_fiscal_year)-3 BETWEEN EXTRACT(YEAR FROM add_months(NVL(trunc(assn3.start_date), #(lf)                                                                          TRUNC(assn3.date_added)),6))#(lf)                                                                  AND nvl(EXTRACT(YEAR FROM add_months(trunc(assn3.stop_date),6)),#(lf)                                                                          EXTRACT(YEAR FROM add_months(NVL(trunc(assn3.start_date), #(lf)                                                                          TRUNC(assn3.date_added)),6))+4)#(lf)            UNION ALL#(lf)            SELECT DISTINCT hk2.HOUSEHOLD_KEY     HH_Key,#(lf)                   hk2.HOUSEHOLD_KEY||to_char((select * from advur.vw_current_fiscal_year)-2) ComboKey,#(lf)                   hk2.member_count               Par_Cnt,#(lf)                   to_char((select * from advur.vw_current_fiscal_year)-2) qual_yr#(lf)              FROM advance.assignment assn2#(lf)             INNER JOIN advance.staff s2                ON s2.id_number = assn2.assignment_id_number#(lf)             INNER JOIN advance.prospect_entity pe2     ON assn2.prospect_id = pe2.prospect_id#(lf)             INNER JOIN advur.VW_ENT_HOUSEHOLD_KEYS hk2 ON pe2.ID_NUMBER = hk2.ID_NUMBER #(lf)             WHERE assn2.assignment_type = 'PM' #(lf)             AND   pe2.primary_ind = 'Y'#(lf)             AND   trunc(assn2.date_added) <> '04-FEB-1999'#(lf)             AND   ((s2.unit_code IN ('DEV', 'SG', 'ATH', 'TRF')#(lf)             AND     s2.staff_type_code IN ('GO','MO','SR')) #(lf)                OR   s2.unit_code = 'ARO')#(lf)             and   (select * from advur.vw_current_fiscal_year)-2 BETWEEN EXTRACT(YEAR FROM add_months(NVL(trunc(assn2.start_date), #(lf)                                                                          TRUNC(assn2.date_added)),6))#(lf)                                                                  AND nvl(EXTRACT(YEAR FROM add_months(trunc(assn2.stop_date),6)),#(lf)                                                                          EXTRACT(YEAR FROM add_months(NVL(trunc(assn2.start_date), #(lf)                                                                          TRUNC(assn2.date_added)),6))+4)#(lf)            UNION ALL#(lf)            SELECT DISTINCT hk1.HOUSEHOLD_KEY     HH_Key,#(lf)                   hk1.HOUSEHOLD_KEY||to_char((select * from advur.vw_current_fiscal_year)-1) ComboKey,#(lf)                   hk1.member_count               Par_Cnt,#(lf)                   to_char((select * from advur.vw_current_fiscal_year)-1) qual_yr#(lf)              FROM advance.assignment assn1#(lf)             INNER JOIN advance.staff s1                ON s1.id_number = assn1.assignment_id_number#(lf)             INNER JOIN advance.prospect_entity pe1     ON assn1.prospect_id = pe1.prospect_id#(lf)             INNER JOIN advur.VW_ENT_HOUSEHOLD_KEYS hk1 ON pe1.ID_NUMBER = hk1.ID_NUMBER #(lf)             WHERE assn1.assignment_type = 'PM' #(lf)             AND   pe1.primary_ind = 'Y'#(lf)             AND   trunc(assn1.date_added) <> '04-FEB-1999'#(lf)             AND   ((s1.unit_code IN ('DEV', 'SG', 'ATH', 'TRF')#(lf)             AND     s1.staff_type_code IN ('GO','MO','SR')) #(lf)                OR   s1.unit_code = 'ARO')#(lf)             and   (select * from advur.vw_current_fiscal_year)-1 BETWEEN EXTRACT(YEAR FROM add_months(NVL(trunc(assn1.start_date), #(lf)                                                                          TRUNC(assn1.date_added)),6))#(lf)                                                                  AND nvl(EXTRACT(YEAR FROM add_months(trunc(assn1.stop_date),6)),#(lf)                                                                          EXTRACT(YEAR FROM add_months(NVL(trunc(assn1.start_date), #(lf)                                                                          TRUNC(assn1.date_added)),6))+4)#(lf)            UNION ALL#(lf)            SELECT DISTINCT hk0.HOUSEHOLD_KEY     HH_Key,#(lf)                   hk0.HOUSEHOLD_KEY||to_char((select * from advur.vw_current_fiscal_year)) ComboKey,#(lf)                   hk0.member_count               Par_Cnt,#(lf)                   to_char((select * from advur.vw_current_fiscal_year)) qual_yr#(lf)              FROM advance.assignment assn0#(lf)             INNER JOIN advance.staff s0                ON s0.id_number = assn0.assignment_id_number#(lf)             INNER JOIN advance.prospect_entity pe0     ON assn0.prospect_id = pe0.prospect_id#(lf)             INNER JOIN advur.VW_ENT_HOUSEHOLD_KEYS hk0 ON pe0.ID_NUMBER = hk0.ID_NUMBER #(lf)             WHERE assn0.assignment_type = 'PM' #(lf)             AND   pe0.primary_ind = 'Y'#(lf)             AND   trunc(assn0.date_added) <> '04-FEB-1999'#(lf)             AND   ((s0.unit_code IN ('DEV', 'SG', 'ATH', 'TRF')#(lf)             AND     s0.staff_type_code IN ('GO','MO','SR')) #(lf)                OR   s0.unit_code = 'ARO')#(lf)             and   (select * from advur.vw_current_fiscal_year) BETWEEN EXTRACT(YEAR FROM add_months(NVL(trunc(assn0.start_date), #(lf)                                                                        TRUNC(assn0.date_added)),6))#(lf)                                                                AND nvl(EXTRACT(YEAR FROM add_months(trunc(assn0.stop_date),6)),#(lf)                                                                        EXTRACT(YEAR FROM add_months(NVL(trunc(assn0.start_date), #(lf)                                                                        TRUNC(assn0.date_added)),6))+4)#(lf)          ),#(lf)donors_rev AS (#(lf)           select distinct r.household_key  HH_Key,#(lf)                  rev.fiscal_yr             fy,#(lf)                  CASE WHEN p.parent_household_key > ' ' THEN 1#(lf)                     ELSE 0 END             par_ind,#(lf)                  CASE WHEN hh.secondary_id_number > ' ' THEN 2#(lf)                       WHEN hh.primary_id_number > ' ' THEN 1#(lf)                     ELSE 0 END             par_cnt#(lf)             from advur.mvw_trans_households r#(lf)            inner join advur.mvw_total_revenue rev  ON r.trans_nbr = rev.trans_nbr#(lf)             left join advur.mvw_hh_parents p        ON r.household_key = p.parent_household_key AND rev.fiscal_yr BETWEEN EXTRACT(YEAR FROM add_months(p.start_date,6)) #(lf)                                                                                                 AND EXTRACT(YEAR FROM add_months(p.stop_date,6))#(lf)             left join advur.mvw_hh_entities_with_deceased hh ON p.parent_household_key = hh.household_key#(lf)            inner join (#(lf)                        select xp4.parent_household_key hk,#(lf)                               to_char((select * from advur.vw_current_fiscal_year)-4) fy,#(lf)                               CASE WHEN (select * from advur.vw_current_fiscal_year)-4 BETWEEN EXTRACT(YEAR FROM add_months(xp4.start_date,6)) #(lf)                                                                                           AND EXTRACT(YEAR FROM add_months(xp4.stop_date,6)) THEN 1#(lf)                                  ELSE 0 END p_ind#(lf)                          from advur.mvw_hh_parents xp4#(lf)                        UNION ALL#(lf)                        select xp3.parent_household_key hk,#(lf)                               to_char((select * from advur.vw_current_fiscal_year)-3) fy,#(lf)                               CASE WHEN (select * from advur.vw_current_fiscal_year)-3 BETWEEN EXTRACT(YEAR FROM add_months(xp3.start_date,6)) #(lf)                                                                                           AND EXTRACT(YEAR FROM add_months(xp3.stop_date,6)) THEN 1#(lf)                                  ELSE 0 END p_ind#(lf)                          from advur.mvw_hh_parents xp3#(lf)                        UNION ALL#(lf)                        select xp2.parent_household_key hk,#(lf)                               to_char((select * from advur.vw_current_fiscal_year)-2) fy,#(lf)                               CASE WHEN (select * from advur.vw_current_fiscal_year)-2 BETWEEN EXTRACT(YEAR FROM add_months(xp2.start_date,6)) #(lf)                                                                                           AND EXTRACT(YEAR FROM add_months(xp2.stop_date,6)) THEN 1#(lf)                                  ELSE 0 END p_ind#(lf)                          from advur.mvw_hh_parents xp2#(lf)                        UNION ALL#(lf)                        select xp1.parent_household_key hk,#(lf)                               to_char((select * from advur.vw_current_fiscal_year)-1) fy,#(lf)                               CASE WHEN (select * from advur.vw_current_fiscal_year)-1 BETWEEN EXTRACT(YEAR FROM add_months(xp1.start_date,6)) #(lf)                                                                                           AND EXTRACT(YEAR FROM add_months(xp1.stop_date,6)) THEN 1#(lf)                                  ELSE 0 END p_ind#(lf)                          from advur.mvw_hh_parents xp1#(lf)                        UNION ALL#(lf)                        select xp0.parent_household_key hk,#(lf)                               to_char((select * from advur.vw_current_fiscal_year)) fy,#(lf)                               CASE WHEN (select * from advur.vw_current_fiscal_year) BETWEEN EXTRACT(YEAR FROM add_months(xp0.start_date,6)) #(lf)                                                                                         AND EXTRACT(YEAR FROM add_months(xp0.stop_date,6)) THEN 1#(lf)                                  ELSE 0 END p_ind#(lf)                          from advur.mvw_hh_parents xp0#(lf)                         )par ON hh.household_key = par.hk#(lf)#(lf)           where rev.fiscal_yr BETWEEN to_char((select * from advur.vw_current_fiscal_year)-4) AND to_char((select * from advur.vw_current_fiscal_year))#(lf)           ),#(lf)donors_prd AS (#(lf)               select distinct p.household_key  HH_Key,#(lf)                  prd.fiscal_yr             fy,#(lf)                  CASE WHEN par.parent_household_key > ' ' THEN 1#(lf)                     ELSE 0 END             par_ind,#(lf)                  CASE WHEN hh.secondary_id_number > ' ' THEN 2#(lf)                       WHEN hh.primary_id_number > ' ' THEN 1#(lf)                     ELSE 0 END             par_cnt#(lf)             from advur.mvw_trans_households p#(lf)            inner join advur.mvw_total_production prd  ON p.trans_nbr = prd.trans_nbr#(lf)             left join advur.mvw_hh_parents par        ON p.household_key = par.parent_household_key AND #(lf)                                                          prd.fiscal_yr BETWEEN EXTRACT(YEAR FROM add_months(par.start_date,6)) #(lf)                                                                            AND EXTRACT(YEAR FROM add_months(par.stop_date,6))#(lf)             left join advur.mvw_hh_entities_with_deceased hh ON par.parent_household_key = hh.household_key#(lf)            inner join (#(lf)                        select xp4.parent_household_key hk,#(lf)                               to_char((select * from advur.vw_current_fiscal_year)-4) fy,#(lf)                               CASE WHEN (select * from advur.vw_current_fiscal_year)-4 BETWEEN EXTRACT(YEAR FROM add_months(xp4.start_date,6)) #(lf)                                                                                           AND EXTRACT(YEAR FROM add_months(xp4.stop_date,6)) THEN 1#(lf)                                  ELSE 0 END p_ind#(lf)                          from advur.mvw_hh_parents xp4#(lf)                        UNION ALL#(lf)                        select xp3.parent_household_key hk,#(lf)                               to_char((select * from advur.vw_current_fiscal_year)-3) fy,#(lf)                               CASE WHEN (select * from advur.vw_current_fiscal_year)-3 BETWEEN EXTRACT(YEAR FROM add_months(xp3.start_date,6)) #(lf)                                                                                           AND EXTRACT(YEAR FROM add_months(xp3.stop_date,6)) THEN 1#(lf)                                  ELSE 0 END p_ind#(lf)                          from advur.mvw_hh_parents xp3#(lf)                        UNION ALL#(lf)                        select xp2.parent_household_key hk,#(lf)                               to_char((select * from advur.vw_current_fiscal_year)-2) fy,#(lf)                               CASE WHEN (select * from advur.vw_current_fiscal_year)-2 BETWEEN EXTRACT(YEAR FROM add_months(xp2.start_date,6)) #(lf)                                                                                           AND EXTRACT(YEAR FROM add_months(xp2.stop_date,6)) THEN 1#(lf)                                  ELSE 0 END p_ind#(lf)                          from advur.mvw_hh_parents xp2#(lf)                        UNION ALL#(lf)                        select xp1.parent_household_key hk,#(lf)                               to_char((select * from advur.vw_current_fiscal_year)-1) fy,#(lf)                               CASE WHEN to_char((select * from advur.vw_current_fiscal_year)-1) BETWEEN EXTRACT(YEAR FROM add_months(xp1.start_date,6)) #(lf)                                                                                           AND EXTRACT(YEAR FROM add_months(xp1.stop_date,6)) THEN 1#(lf)                                  ELSE 0 END p_ind#(lf)                          from advur.mvw_hh_parents xp1#(lf)                        UNION ALL#(lf)                        select xp0.parent_household_key hk,#(lf)                               to_char((select * from advur.vw_current_fiscal_year)) fy,#(lf)                               CASE WHEN (select * from advur.vw_current_fiscal_year) BETWEEN EXTRACT(YEAR FROM add_months(xp0.start_date,6)) #(lf)                                                                                         AND EXTRACT(YEAR FROM add_months(xp0.stop_date,6)) THEN 1#(lf)                                  ELSE 0 END p_ind#(lf)                          from advur.mvw_hh_parents xp0#(lf)                         )par ON hh.household_key = par.hk#(lf)#(lf)           where prd.fiscal_yr BETWEEN to_char((select * from advur.vw_current_fiscal_year)-4) AND to_char((select * from advur.vw_current_fiscal_year))           #(lf)           ),#(lf)facstaff AS (#(lf)            -- Current FY Active#(lf)            select distinct mp.id_number                                             fsid,#(lf)                    'Active'                                                          status,#(lf)                    to_char((select * from advur.vw_current_fiscal_year))             yr,#(lf)                    to_date(mp.start_dt, 'YYYYMMDD')                                  startdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) fyr,#(lf)                    NULL                                                              stopdt,#(lf)                    NULL                                                              xfyr#(lf)               from advance.employment mp#(lf)              where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)              and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)              and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)              and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)              and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year))#(lf)             UNION ALL#(lf)             -- Current FY Inactive#(lf)             select distinct mp2.id_number       fsid,#(lf)                    'Inactive'                   status,#(lf)                    to_char((select * from advur.vw_current_fiscal_year)) yr,#(lf)                    to_date(mp2.start_dt, 'YYYYMMDD') startdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) fyr,#(lf)                    to_date(mp2.stop_dt, 'YYYYMMDD') stopdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) xfyr#(lf)               from advance.employment mp2#(lf)              where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)              and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)              and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)              and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)              and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)              and   substr(mp2.stop_dt,7,2) <> '00'#(lf)              and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year))#(lf)              and   (mp2.stop_dt = '00000000' OR #(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)))#(lf)            UNION ALL#(lf)            -- Current FY - 1 Active#(lf)            select distinct mp.id_number                                             fsid,#(lf)                    'Active'                                                          status,#(lf)                    to_char((select * from advur.vw_current_fiscal_year)-1)           yr,#(lf)                    to_date(mp.start_dt, 'YYYYMMDD')                                  startdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) fyr,#(lf)                    NULL                                                              stopdt,#(lf)                    NULL                                                              xfyr#(lf)               from advance.employment mp#(lf)              where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)              and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)              and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)              and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)              and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-1)#(lf)             UNION ALL#(lf)             -- Current FY - 1 Inactive#(lf)             select distinct mp2.id_number       fsid,#(lf)                    'Inactive'                   status,#(lf)                    to_char((select * from advur.vw_current_fiscal_year)-1) yr,#(lf)                    to_date(mp2.start_dt, 'YYYYMMDD') startdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) fyr,#(lf)                    to_date(mp2.stop_dt, 'YYYYMMDD') stopdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) xfyr#(lf)               from advance.employment mp2#(lf)              where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)              and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)              and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)              and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)              and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)              and   substr(mp2.stop_dt,7,2) <> '00'#(lf)              and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-1)#(lf)              and   (mp2.stop_dt = '00000000' OR #(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)-1))#(lf)             UNION ALL#(lf)             -- Current FY - 2 Active#(lf)             select distinct mp.id_number                                             fsid,#(lf)                    'Active'                                                          status,#(lf)                    to_char((select * from advur.vw_current_fiscal_year)-2)           yr,#(lf)                    to_date(mp.start_dt, 'YYYYMMDD')                                  startdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) fyr,#(lf)                    NULL                                                              stopdt,#(lf)                    NULL                                                              xfyr#(lf)               from advance.employment mp#(lf)              where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)              and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)              and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)              and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)              and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-2)#(lf)             UNION ALL#(lf)             -- Current FY - 2 Inactive#(lf)             select distinct mp2.id_number       fsid,#(lf)                    'Inactive'                   status,#(lf)                    to_char((select * from advur.vw_current_fiscal_year)-2) yr,#(lf)                    to_date(mp2.start_dt, 'YYYYMMDD') startdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) fyr,#(lf)                    to_date(mp2.stop_dt, 'YYYYMMDD') stopdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) xfyr#(lf)               from advance.employment mp2#(lf)              where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)              and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)              and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)              and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)              and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)              and   substr(mp2.stop_dt,7,2) <> '00'#(lf)              and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-2)#(lf)              and   (mp2.stop_dt = '00000000' OR #(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)-2))#(lf)             UNION ALL#(lf)             -- Current FY - 3 Active#(lf)             select distinct mp.id_number                                             fsid,#(lf)                    'Active'                                                          status,#(lf)                    to_char((select * from advur.vw_current_fiscal_year)-3)           yr,#(lf)                    to_date(mp.start_dt, 'YYYYMMDD')                                  startdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) fyr,#(lf)                    NULL                                                              stopdt,#(lf)                    NULL                                                              xfyr#(lf)               from advance.employment mp#(lf)              where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)              and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)              and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)              and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)              and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-3)#(lf)             UNION ALL#(lf)             -- Current FY - 3 Inactive#(lf)             select distinct mp2.id_number       fsid,#(lf)                    'Inactive'                   status,#(lf)                    to_char((select * from advur.vw_current_fiscal_year)-3) yr,#(lf)                    to_date(mp2.start_dt, 'YYYYMMDD') startdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) fyr,#(lf)                    to_date(mp2.stop_dt, 'YYYYMMDD') stopdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) xfyr#(lf)               from advance.employment mp2#(lf)              where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)              and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)              and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)              and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)              and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)              and   substr(mp2.stop_dt,7,2) <> '00'#(lf)              and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-3)#(lf)              and   (mp2.stop_dt = '00000000' OR #(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)-3))#(lf)             UNION ALL#(lf)             -- Current FY - 4 Active#(lf)             select distinct mp.id_number                                             fsid,#(lf)                    'Active'                                                          status,#(lf)                    to_char((select * from advur.vw_current_fiscal_year)-4)           yr,#(lf)                    to_date(mp.start_dt, 'YYYYMMDD')                                  startdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) fyr,#(lf)                    NULL                                                              stopdt,#(lf)                    NULL                                                              xfyr#(lf)               from advance.employment mp#(lf)              where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)              and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)              and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)              and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)              and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-4)#(lf)             UNION ALL#(lf)             -- Current FY - 4 Inactive#(lf)             select distinct mp2.id_number       fsid,#(lf)                    'Inactive'                   status,#(lf)                    to_char((select * from advur.vw_current_fiscal_year)-4) yr,#(lf)                    to_date(mp2.start_dt, 'YYYYMMDD') startdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) fyr,#(lf)                    to_date(mp2.stop_dt, 'YYYYMMDD') stopdt,#(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) xfyr#(lf)               from advance.employment mp2#(lf)              where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)              and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)              and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)              and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)              and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)              and   substr(mp2.stop_dt,7,2) <> '00'#(lf)              and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-4)#(lf)              and   (mp2.stop_dt = '00000000' OR #(lf)                    EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)-4))#(lf)           ),#(lf)-- The following subquery provides indicators for the primary parent in the household to show if they are an Alumni. smk 8/22/2023#(lf)degalum AS (#(lf)            select distinct xe2.id_number aid, 'Yes' ind#(lf)             from advance.entity xe2#(lf)            inner join advance.degrees xd2 ON xe2.id_number = xd2.id_number#(lf)            where xe2.record_type_code = 'A'#(lf)            and   xd2.institution_code = '6121'#(lf)            and   xd2.degree_type <> 'S'#(lf)            and   xd2.degree_level_code IN ('A','B','D','M')#(lf)            and   xd2.admiss_status_code = ' '#(lf)            and   xd2.non_grad_code <> 'Y'#(lf)            ),#(lf)-- The following subquery provides indicators for the primary parent's spouse to show if they are an Alumni. smk 8/22/2023#(lf)spdegalum AS (#(lf)              select distinct xe5.id_number aid, 'Yes' ind#(lf)                from advance.entity xe5#(lf)               inner join advance.degrees xd5 ON xe5.id_number = xd5.id_number#(lf)               where xe5.record_type_code = 'A'#(lf)               and   xd5.institution_code = '6121'#(lf)               and   xd5.degree_type <> 'S'#(lf)               and   xd5.degree_level_code IN ('A','B','D','M')#(lf)               and   xd5.admiss_status_code = ' '#(lf)               and   xd5.non_grad_code <> 'Y'#(lf)              )#(lf)#(lf)-- New Current Parent query to pull all current parents from the last 5 FYs. smk 6/23/2023#(lf)#(lf)select distinct p.parent_household_key               \"\"HH Key\"\",#(lf)       p.parent_household_key||par.fy                \"\"ComboKey\"\",#(lf)       g.primary_id_number                           \"\"Prim Parent ID\"\",#(lf)       g.primary_id_number||par.fy                   \"\"ComboIDKey\"\",#(lf)       pe.pref_mail_name                             \"\"Prim Parent Name\"\",#(lf)       pe.institutional_suffix                       \"\"Prim Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(pe.id_number)    \"\"Primary Rec Types\"\",#(lf)       g.secondary_id_number                         \"\"Sec Parent ID\"\",#(lf)       CASE WHEN g.secondary_id_number IS NULL THEN NULL#(lf)            WHEN g.secondary_id_number = ' ' THEN ' '#(lf)          ELSE g.secondary_id_number||par.fy END     \"\"ComboIDKey2\"\",#(lf)       se.pref_mail_name                             \"\"Sec Parent Name\"\",#(lf)       se.institutional_suffix                       \"\"Sec Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(se.id_number)    \"\"Sec Rec Types\"\",#(lf)       CASE WHEN r.mg_evi = 'N/A' THEN -1#(lf)          ELSE nvl(to_number(r.mg_evi),-2) END       \"\"MG EVI\"\",#(lf)       r.reeher_net_worth                            \"\"Net Worth\"\",#(lf)       r.six_square_segment                          \"\"Six Square\"\",#(lf)       r.alumni_engagement_score                     \"\"Engagement Score\"\",#(lf)       par.fy                                        \"\"Fiscal Yr\"\",#(lf)       CASE WHEN g.secondary_id_number > ' ' THEN 2#(lf)          ELSE par.p_ind END                         \"\"Parent Cnt\"\",#(lf)       CASE WHEN da.ind = 'Yes' AND sda.ind = 'Yes' THEN 'Both'#(lf)            WHEN da.ind = 'Yes' AND sda.ind IS NULL THEN 'Primary'#(lf)            WHEN da.ind IS NULL AND sda.ind = 'Yes' THEN 'Spouse'#(lf)          ELSE 'No' END                              \"\"Alumni\"\",#(lf)       CASE WHEN da.ind = 'Yes' AND sda.ind = 'Yes' THEN 2#(lf)            WHEN da.ind = 'Yes' AND sda.ind IS NULL THEN 1#(lf)            WHEN da.ind IS NULL AND sda.ind = 'Yes' THEN 1#(lf)          ELSE 0 END                                 \"\"Alumni Cnt\"\",#(lf)       nvl(plc.par_cnt,0)                            \"\"PLC Ind\"\",#(lf)       nvl(asgn.Par_Cnt,0)                           \"\"Assigned Ind\"\",#(lf)       nvl(rdnr.par_cnt,0)                           \"\"Rev Donor Ind\"\",#(lf)       nvl(pdnr.par_cnt,0)                           \"\"Prod Donor Ind\"\",#(lf)       CASE WHEN pfs.fsid > ' ' AND sfs.fsid IS NULL THEN 1#(lf)            WHEN pfs.fsid IS NULL AND sfs.fsid > ' ' THEN 1#(lf)            WHEN pfs.fsid > ' ' AND sfs.fsid > ' ' THEN 2#(lf)          ELSE 0 END                                 \"\"F/S Cnt\"\",#(lf)       pe.pref_name_sort                             \"\"Sort Parent Name\"\"#(lf)from advur.mvw_hh_parents p#(lf)inner join advur.mvw_hh_entities_with_deceased g ON p.parent_household_key = g.household_key#(lf)inner join parents par                           ON p.parent_household_key = par.hk#(lf)inner join advance.entity pe                     ON g.primary_id_number = pe.id_number#(lf)left join advance.entity se                      ON g.secondary_id_number = se.id_number#(lf)left join advur.mvw_ent_ratings r                ON g.primary_id_number = r.id_number#(lf)left join plccomm  plc                           ON par.hk = plc.hk and par.fy = plc.fy  --p.parent_household_key = plc.hk#(lf)left join managers asgn                          ON par.hk = asgn.HH_Key and par.fy = asgn.qual_yr  --p.parent_household_key = asgn.HH_Key#(lf)left join donors_rev rdnr                        ON par.hk = rdnr.HH_Key and par.fy = rdnr.fy#(lf)left join donors_prd pdnr                        ON par.hk = pdnr.HH_Key and par.fy = pdnr.fy#(lf)left join degalum da                             ON pe.id_number = da.aid#(lf)left join spdegalum sda                          ON se.id_number = sda.aid#(lf)left join facstaff pfs                           ON pe.id_number = pfs.fsid#(lf)left join facstaff sfs                           ON se.id_number = sfs.fsid#(lf)#(lf)where par.p_ind = 1#(lf)#(lf)order by \"\"ComboKey\"\"\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"MG EVI\", Int64.Type}, {\"Engagement Score\", Int64.Type}, {\"Fiscal Yr\", type text}, {\"Parent Cnt\", Int64.Type}, {\"Alumni Cnt\", Int64.Type}, {\"PLC Ind\", Int64.Type}, {\"Assigned Ind\", Int64.Type}, {\"Rev Donor Ind\", Int64.Type}, {\"Prod Donor Ind\", Int64.Type}, {\"F/S Cnt\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PLC Members",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "HH Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33d076f2-2964-4fe4-ab5b-1f8e52620259",
            "sourceColumn": "HH Key",
            "summarizeBy": "none"
          },
          {
            "name": "ComboKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11a0a106-394c-4ce7-9b51-8fc341e72f02",
            "sourceColumn": "ComboKey",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da9c10c1-92b4-40a5-9ba8-ff44f90cfd4e",
            "sourceColumn": "Fiscal Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Parent ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ca90cb7-1ced-48b1-bb86-6f1d7a72a10a",
            "sourceColumn": "Parent ID",
            "summarizeBy": "none"
          },
          {
            "name": "PLC Member Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3c4d805-0c2d-4c77-a477-7a112eb15173",
            "sourceColumn": "PLC Member Name",
            "summarizeBy": "none"
          },
          {
            "name": "Start Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "4433dcae-9151-4f35-b21f-6966d8a87f62",
            "sourceColumn": "Start Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Start Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "748852c7-1643-424c-9181-f46486729ad1",
            "sourceColumn": "Start Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Stop Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "6368a0b1-45ac-4cf5-9deb-77a5f8e43a99",
            "sourceColumn": "Stop Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Stop Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93dea13c-1913-4f0e-a59e-b94f207fc865",
            "sourceColumn": "Stop Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Parent Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8706298e-92e9-4752-865d-93aeaf778129",
            "sourceColumn": "Parent Count",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ca18defc-007b-49c8-a74b-c7206a78f754",
        "partitions": [
          {
            "name": "PLC Members-5ab9f69e-bc0b-48c3-8a0d-6ee46dd78323",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(#\"Data Source\", [HierarchicalNavigation=true, Query=\"-- Query to pull five FYs of PLC members, including the current FY. smk 6/23/2023#(lf)-- Updated to add a parent count for the Household.  smk  8/11/2023#(lf)-- Updated to change the FY calculation to use the fiscal year view. smk 9/19/2023#(lf)#(lf)WITH members as (#(lf)                 select distinct xg4.household_key hk,#(lf)                        xg4.household_key||to_char((select * from advur.vw_current_fiscal_year)-4) uniq,#(lf)                        CASE WHEN xg4.secondary_id_number > ' ' THEN 2#(lf)                           ELSE 1 END              par_cnt,#(lf)                        xg4.primary_id_number      par1_id,#(lf)                        e1.pref_mail_name          prim_parent_name,#(lf)                        xg4.secondary_id_number    par2_id,#(lf)                        e2.pref_mail_name          sec_parent_name,#(lf)                        to_char((select * from advur.vw_current_fiscal_year)-4) fy,#(lf)                        to_date(xc4.start_dt,'YYYYMMDD') start_dt,#(lf)                        EXTRACT(YEAR FROM to_date(xc4.start_dt,'YYYYMMDD')) start_yr,#(lf)                        CASE WHEN xc4.stop_dt = '00000000' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc4.stop_dt,1,4) = '0000' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc4.stop_dt,5,4) = '0000' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc4.stop_dt,5,2) = '00' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc4.stop_dt,7,2) = '00' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460 #(lf)                           ELSE to_date(xc4.stop_dt,'YYYYMMDD') END stop_dt,#(lf)                        EXTRACT(YEAR FROM CASE WHEN xc4.stop_dt = '00000000' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc4.stop_dt,1,4) = '0000' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc4.stop_dt,5,4) = '0000' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc4.stop_dt,5,2) = '00' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc4.stop_dt,7,2) = '00' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)+1460 #(lf)                                             ELSE to_date(xc4.stop_dt,'YYYYMMDD') END) stop_yr,#(lf)                        1  p_ind#(lf)                   from advance.committee xc4#(lf)                  inner join advur.mvw_hh_entities_with_deceased xg4 ON (xc4.id_number = xg4.primary_id_number OR xc4.id_number = xg4.secondary_id_number)#(lf)                  inner join advance.entity e1                       ON xg4.primary_id_number = e1.id_number#(lf)                   left join advance.entity e2                        ON xg4.secondary_id_number = e2.id_number#(lf)                  where xc4.committee_code = 'PLC'#(lf)                  and   xc4.start_dt <> '00000000'#(lf)                  and   substr(xc4.start_dt,1,4) <> '0000'#(lf)                  and   substr(xc4.start_dt,5,4) <> '0000'#(lf)                  and   substr(xc4.start_dt,5,2) <> '00'#(lf)                  and   substr(xc4.start_dt,7,2) <> '00'#(lf)                  and   to_char((select * from advur.vw_current_fiscal_year)-4) BETWEEN EXTRACT(YEAR FROM add_months(to_date(xc4.start_dt,'YYYYMMDD'),6)) #(lf)                                                                              AND EXTRACT(YEAR FROM add_months(to_date(#(lf)                                                                                  CASE WHEN xc4.stop_dt = '00000000' OR substr(xc4.stop_dt,1,4) = '0000'#(lf)                                                                                       OR substr(xc4.stop_dt,5,4) = '0000' OR substr(xc4.stop_dt,5,2) = '00'#(lf)                                                                                       OR substr(xc4.stop_dt,7,2) = '00' THEN add_months(to_date(xc4.start_dt,'YYYYMMDD')+1460,6) #(lf)                                                                                     ELSE to_date(xc4.stop_dt,'YYYYMMDD') END),6))#(lf)                 UNION ALL#(lf)                 select distinct xg3.household_key hk,#(lf)                        xg3.household_key||to_char((select * from advur.vw_current_fiscal_year)-3) uniq,#(lf)                        CASE WHEN xg3.secondary_id_number > ' ' THEN 2#(lf)                           ELSE 1 END              par_cnt,#(lf)                        xg3.primary_id_number      par1_id,#(lf)                        e1.pref_mail_name          prim_parent_name,#(lf)                        xg3.secondary_id_number    par2_id,#(lf)                        e2.pref_mail_name          sec_parent_name,#(lf)                        to_char((select * from advur.vw_current_fiscal_year)-3) fy,#(lf)                        to_date(xc3.start_dt,'YYYYMMDD') start_dt,#(lf)                        EXTRACT(YEAR FROM to_date(xc3.start_dt,'YYYYMMDD')) start_yr,#(lf)                        CASE WHEN xc3.stop_dt = '00000000' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc3.stop_dt,1,4) = '0000' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc3.stop_dt,5,4) = '0000' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc3.stop_dt,5,2) = '00' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc3.stop_dt,7,2) = '00' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460 #(lf)                           ELSE to_date(xc3.stop_dt,'YYYYMMDD') END stop_dt,#(lf)                        EXTRACT(YEAR FROM CASE WHEN xc3.stop_dt = '00000000' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc3.stop_dt,1,4) = '0000' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc3.stop_dt,5,4) = '0000' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc3.stop_dt,5,2) = '00' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc3.stop_dt,7,2) = '00' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)+1460 #(lf)                                             ELSE to_date(xc3.stop_dt,'YYYYMMDD') END) stop_yr,#(lf)                        1  p_ind#(lf)                   from advance.committee xc3#(lf)                  inner join advur.mvw_hh_entities_with_deceased xg3 ON (xc3.id_number = xg3.primary_id_number OR xc3.id_number = xg3.secondary_id_number)#(lf)                  inner join advance.entity e1                       ON xg3.primary_id_number = e1.id_number#(lf)                   left join advance.entity e2                        ON xg3.secondary_id_number = e2.id_number#(lf)                  where xc3.committee_code = 'PLC'#(lf)                  and   xc3.start_dt <> '00000000'#(lf)                  and   substr(xc3.start_dt,1,4) <> '0000'#(lf)                  and   substr(xc3.start_dt,5,4) <> '0000'#(lf)                  and   substr(xc3.start_dt,5,2) <> '00'#(lf)                  and   substr(xc3.start_dt,7,2) <> '00'#(lf)                  and   to_char((select * from advur.vw_current_fiscal_year)-3) BETWEEN EXTRACT(YEAR FROM add_months(to_date(xc3.start_dt,'YYYYMMDD'),6)) #(lf)                                                                            AND EXTRACT(YEAR FROM add_months(to_date(#(lf)                                                                                            CASE WHEN xc3.stop_dt = '00000000' OR substr(xc3.stop_dt,1,4) = '0000'#(lf)                                                                                              OR substr(xc3.stop_dt,5,4) = '0000' OR substr(xc3.stop_dt,5,2) = '00'#(lf)                                                                                              OR substr(xc3.stop_dt,7,2) = '00' THEN add_months(to_date(xc3.start_dt,'YYYYMMDD')+1460,6) #(lf)                                                                                             ELSE to_date(xc3.stop_dt,'YYYYMMDD') END),6))#(lf)                 UNION ALL#(lf)                 select distinct xg2.household_key hk,#(lf)                        xg2.household_key||to_char((select * from advur.vw_current_fiscal_year)-2) uniq,#(lf)                        CASE WHEN xg2.secondary_id_number > ' ' THEN 2#(lf)                           ELSE 1 END              par_cnt,#(lf)                        xg2.primary_id_number      par1_id,#(lf)                        e1.pref_mail_name          prim_parent_name,#(lf)                        xg2.secondary_id_number    par2_id,#(lf)                        e2.pref_mail_name          sec_parent_name,#(lf)                        to_char((select * from advur.vw_current_fiscal_year)-2) fy,#(lf)                        to_date(xc2.start_dt,'YYYYMMDD') start_dt,#(lf)                        EXTRACT(YEAR FROM to_date(xc2.start_dt,'YYYYMMDD')) start_yr,#(lf)                        CASE WHEN xc2.stop_dt = '00000000' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc2.stop_dt,1,4) = '0000' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc2.stop_dt,5,4) = '0000' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc2.stop_dt,5,2) = '00' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc2.stop_dt,7,2) = '00' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460 #(lf)                           ELSE to_date(xc2.stop_dt,'YYYYMMDD') END stop_dt,#(lf)                        EXTRACT(YEAR FROM CASE WHEN xc2.stop_dt = '00000000' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc2.stop_dt,1,4) = '0000' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc2.stop_dt,5,4) = '0000' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc2.stop_dt,5,2) = '00' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc2.stop_dt,7,2) = '00' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)+1460 #(lf)                                             ELSE to_date(xc2.stop_dt,'YYYYMMDD') END) stop_yr,#(lf)                        1  p_ind#(lf)                   from advance.committee xc2#(lf)                  inner join advur.mvw_hh_entities_with_deceased xg2 ON (xc2.id_number = xg2.primary_id_number OR xc2.id_number = xg2.secondary_id_number)#(lf)                  inner join advance.entity e1                       ON xg2.primary_id_number = e1.id_number#(lf)                   left join advance.entity e2                        ON xg2.secondary_id_number = e2.id_number#(lf)                   where xc2.committee_code = 'PLC'#(lf)                   and   xc2.start_dt <> '00000000'#(lf)                   and   substr(xc2.start_dt,1,4) <> '0000'#(lf)                   and   substr(xc2.start_dt,5,4) <> '0000'#(lf)                   and   substr(xc2.start_dt,5,2) <> '00'#(lf)                   and   substr(xc2.start_dt,7,2) <> '00'#(lf)                   and   to_char((select * from advur.vw_current_fiscal_year)-2) BETWEEN EXTRACT(YEAR FROM add_months(to_date(xc2.start_dt,'YYYYMMDD'),6)) #(lf)                                                                               AND EXTRACT(YEAR FROM add_months(to_date(#(lf)                                                                              CASE WHEN xc2.stop_dt = '00000000' OR substr(xc2.stop_dt,1,4) = '0000'#(lf)                                                                               OR substr(xc2.stop_dt,5,4) = '0000' OR substr(xc2.stop_dt,5,2) = '00'#(lf)                                                                               OR substr(xc2.stop_dt,7,2) = '00' THEN add_months(to_date(xc2.start_dt,'YYYYMMDD')+1460,6) #(lf)                                                                              ELSE to_date(xc2.stop_dt,'YYYYMMDD') END),6))#(lf)                 UNION ALL#(lf)                 select distinct xg1.household_key hk,#(lf)                        xg1.household_key||to_char((select * from advur.vw_current_fiscal_year)-1) uniq,#(lf)                        CASE WHEN xg1.secondary_id_number > ' ' THEN 2#(lf)                           ELSE 1 END              par_cnt,#(lf)                        xg1.primary_id_number      par1_id,#(lf)                        e1.pref_mail_name          prim_parent_name,#(lf)                        xg1.secondary_id_number    par2_id,#(lf)                        e2.pref_mail_name          sec_parent_name,#(lf)                        to_char((select * from advur.vw_current_fiscal_year)-1) fy,#(lf)                        to_date(xc1.start_dt,'YYYYMMDD') start_dt,#(lf)                        EXTRACT(YEAR FROM to_date(xc1.start_dt,'YYYYMMDD')) start_yr,#(lf)                        CASE WHEN xc1.stop_dt = '00000000' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc1.stop_dt,1,4) = '0000' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc1.stop_dt,5,4) = '0000' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc1.stop_dt,5,2) = '00' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc1.stop_dt,7,2) = '00' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460 #(lf)                           ELSE to_date(xc1.stop_dt,'YYYYMMDD') END stop_dt,#(lf)                        EXTRACT(YEAR FROM CASE WHEN xc1.stop_dt = '00000000' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc1.stop_dt,1,4) = '0000' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc1.stop_dt,5,4) = '0000' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc1.stop_dt,5,2) = '00' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc1.stop_dt,7,2) = '00' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)+1460 #(lf)                                             ELSE to_date(xc1.stop_dt,'YYYYMMDD') END) stop_yr,#(lf)                        1  p_ind#(lf)                   from advance.committee xc1#(lf)                   inner join advur.mvw_hh_entities_with_deceased xg1 ON (xc1.id_number = xg1.primary_id_number OR xc1.id_number = xg1.secondary_id_number)#(lf)                   inner join advance.entity e1                       ON xg1.primary_id_number = e1.id_number#(lf)                    left join advance.entity e2                        ON xg1.secondary_id_number = e2.id_number#(lf)                   where xc1.committee_code = 'PLC'#(lf)                   and   xc1.start_dt <> '00000000'#(lf)                   and   substr(xc1.start_dt,1,4) <> '0000'#(lf)                   and   substr(xc1.start_dt,5,4) <> '0000'#(lf)                   and   substr(xc1.start_dt,5,2) <> '00'#(lf)                   and   substr(xc1.start_dt,7,2) <> '00'#(lf)                   and   to_char((select * from advur.vw_current_fiscal_year)-1) BETWEEN EXTRACT(YEAR FROM add_months(to_date(xc1.start_dt,'YYYYMMDD'),6)) #(lf)                                                                               AND EXTRACT(YEAR FROM add_months(to_date(#(lf)                                                                              CASE WHEN xc1.stop_dt = '00000000' OR substr(xc1.stop_dt,1,4) = '0000'#(lf)                                                                               OR substr(xc1.stop_dt,5,4) = '0000' OR substr(xc1.stop_dt,5,2) = '00'#(lf)                                                                               OR substr(xc1.stop_dt,7,2) = '00' THEN add_months(to_date(xc1.start_dt,'YYYYMMDD')+1460,6) #(lf)                                                                              ELSE to_date(xc1.stop_dt,'YYYYMMDD') END),6))#(lf)                 UNION ALL#(lf)                 select distinct xg0.household_key hk,#(lf)                        xg0.household_key||to_char((select * from advur.vw_current_fiscal_year)) uniq,#(lf)                        CASE WHEN xg0.secondary_id_number > ' ' THEN 2#(lf)                           ELSE 1 END              par_cnt,#(lf)                        xg0.primary_id_number      par1_id,#(lf)                        e1.pref_mail_name          prim_parent_name,#(lf)                        xg0.secondary_id_number    par2_id,#(lf)                        e2.pref_mail_name          sec_parent_name,#(lf)                        to_char((select * from advur.vw_current_fiscal_year)) fy,#(lf)                        to_date(xc0.start_dt,'YYYYMMDD') start_dt,#(lf)                        EXTRACT(YEAR FROM to_date(xc0.start_dt,'YYYYMMDD')) start_yr,#(lf)                        CASE WHEN xc0.stop_dt = '00000000' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc0.stop_dt,1,4) = '0000' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc0.stop_dt,5,4) = '0000' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc0.stop_dt,5,2) = '00' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460#(lf)                             WHEN substr(xc0.stop_dt,7,2) = '00' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460 #(lf)                           ELSE to_date(xc0.stop_dt,'YYYYMMDD') END stop_dt,#(lf)                        EXTRACT(YEAR FROM CASE WHEN xc0.stop_dt = '00000000' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc0.stop_dt,1,4) = '0000' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc0.stop_dt,5,4) = '0000' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc0.stop_dt,5,2) = '00' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460#(lf)                                               WHEN substr(xc0.stop_dt,7,2) = '00' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)+1460 #(lf)                                             ELSE to_date(xc0.stop_dt,'YYYYMMDD') END) stop_yr,#(lf)                        1  p_ind#(lf)                   from advance.committee xc0#(lf)                  inner join advur.mvw_hh_entities_with_deceased xg0 ON (xc0.id_number = xg0.primary_id_number OR xc0.id_number = xg0.secondary_id_number)#(lf)                  inner join advance.entity e1                       ON xg0.primary_id_number = e1.id_number#(lf)                   left join advance.entity e2                        ON xg0.secondary_id_number = e2.id_number#(lf)                  where xc0.committee_code = 'PLC'#(lf)                  and   xc0.start_dt <> '00000000'#(lf)                  and   substr(xc0.start_dt,1,4) <> '0000'#(lf)                  and   substr(xc0.start_dt,5,4) <> '0000'#(lf)                  and   substr(xc0.start_dt,5,2) <> '00'#(lf)                  and   substr(xc0.start_dt,7,2) <> '00'#(lf)                  and   to_char((select * from advur.vw_current_fiscal_year)) BETWEEN EXTRACT(YEAR FROM add_months(to_date(xc0.start_dt,'YYYYMMDD'),6)) #(lf)                                                                            AND EXTRACT(YEAR FROM add_months(to_date(#(lf)                                                                           CASE WHEN xc0.stop_dt = '00000000' OR substr(xc0.stop_dt,1,4) = '0000'#(lf)                                                                             OR substr(xc0.stop_dt,5,4) = '0000' OR substr(xc0.stop_dt,5,2) = '00'#(lf)                                                                             OR substr(xc0.stop_dt,7,2) = '00' THEN add_months(to_date(xc0.start_dt,'YYYYMMDD')+1460,6) #(lf)                                                                           ELSE to_date(xc0.stop_dt,'YYYYMMDD') END),6))#(lf)                 )#(lf)#(lf)select distinct x.household_key                  \"\"HH Key\"\",#(lf)       m.uniq                                    \"\"ComboKey\"\",#(lf)       m.par_cnt                                 \"\"Parent Count\"\",#(lf)       m.fy                                      \"\"Fiscal Yr\"\",#(lf)       m.par1_id                                 \"\"Parent ID\"\",#(lf)       m.prim_parent_name                        \"\"PLC Member Name\"\",#(lf)       m.start_dt                                \"\"Start Dt\"\",#(lf)       m.start_yr                                \"\"Start Yr\"\",#(lf)       m.stop_dt                                 \"\"Stop Dt\"\",#(lf)       stop_yr                                   \"\"Stop Yr\"\"#(lf)from advur.mvw_hh_entities_with_deceased x#(lf)inner join members m ON x.household_key = m.hk#(lf)#(lf)order by \"\"HH Key\"\", \"\"Fiscal Yr\"\"\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Fiscal Yr\", type text}, {\"Start Dt\", type date}, {\"Start Yr\", type text}, {\"Stop Dt\", type date}, {\"Stop Yr\", type text}, {\"Parent Count\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Revenue_5Yrs",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "HH Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff41cf76-67e7-4c01-8da9-fc164b6cebe4",
            "sourceColumn": "HH Key",
            "summarizeBy": "none"
          },
          {
            "name": "ComboKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "822f8241-b4a8-4cbb-995c-10dbbb93e8bf",
            "sourceColumn": "ComboKey",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebd40f2b-8fa2-40e8-b871-118b760e85cf",
            "sourceColumn": "Trans Nbr",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff78bfd7-04cb-4f4e-9ce8-dc5967b0f63d",
            "sourceColumn": "Trans Category",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b802b3d-6f43-474e-b78a-c869949903b0",
            "sourceColumn": "Campaign Ind",
            "summarizeBy": "none"
          },
          {
            "name": "Finance Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88364849-6cc5-49cb-9ab7-cfba04f453bb",
            "sourceColumn": "Finance Category",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "6f348b1d-076b-4d2c-ad48-2c572bf334c0",
            "sourceColumn": "Trans Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46fe7dfb-9384-4f46-9988-9bbfa25dda85",
            "sourceColumn": "Fiscal Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Alloc Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82c04ea6-5d19-4efe-ae04-42cdd41f895a",
            "sourceColumn": "Alloc Code",
            "summarizeBy": "none"
          },
          {
            "name": "Allocation Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c81d6217-3454-414b-9754-aa2362fc39da",
            "sourceColumn": "Allocation Name",
            "summarizeBy": "none"
          },
          {
            "name": "School",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "383ec4d1-e103-4867-8114-e8ca54e46509",
            "sourceColumn": "School",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "549f6af3-36cf-48f4-9129-4b99a9390a1b",
            "sourceColumn": "Trans Amt",
            "summarizeBy": "sum"
          },
          {
            "name": "Goal Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43ed8e11-36af-4599-9773-498c76488e7a",
            "sourceColumn": "Goal Category",
            "summarizeBy": "none"
          },
          {
            "name": "Goal SubCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b392106-0cf3-4981-b31d-a3da7ccbfb13",
            "sourceColumn": "Goal SubCategory",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bab31297-f4fe-4a8b-936d-ff39c3d3f3dc",
            "sourceColumn": "Campaign Bucket",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cce957bf-5102-4cf2-9e1c-7df4750767c2",
            "sourceColumn": "Campaign Priority",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign SubPriority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db14a59a-13e9-4606-9c23-30329a5d9af0",
            "sourceColumn": "Campaign SubPriority",
            "summarizeBy": "none"
          },
          {
            "name": "Sort FinCat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bdb7308-eddc-4e09-b1d3-4fa00668bd31",
            "sourceColumn": "Sort FinCat",
            "summarizeBy": "none"
          },
          {
            "name": "Sort TransType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3c6c6edd-4167-495c-8798-21a3d7fe34f2",
            "sourceColumn": "Sort TransType",
            "summarizeBy": "sum"
          },
          {
            "name": "Par Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "85c1bcd7-6b31-4205-aa22-6f15047b0f2b",
            "sourceColumn": "Par Ind",
            "summarizeBy": "sum"
          },
          {
            "name": "Par Cnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e3a56df6-e8de-42df-b6e0-b848aa2d161f",
            "sourceColumn": "Par Cnt",
            "summarizeBy": "sum"
          },
          {
            "name": "Parent Program Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b86f168-fb1a-4fe6-bbf0-0a90ffddf643",
            "sortByColumn": "Sort Program Category",
            "sourceColumn": "Parent Program Category",
            "summarizeBy": "none"
          },
          {
            "name": "Est Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad90c98f-a172-4aaa-a382-26e39fa6b35a",
            "sourceColumn": "Est Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Scholarship Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2d3dccd-ac8a-4fa5-9c95-8a3fa83aa628",
            "sourceColumn": "Scholarship Status",
            "summarizeBy": "none"
          },
          {
            "name": "Alloc Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7af00fcc-c96f-47d5-897b-c78f7511312b",
            "sourceColumn": "Alloc Group",
            "summarizeBy": "none"
          },
          {
            "name": "Ignatian Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e5100b4-04cd-4b3f-b869-08e9c5ca310b",
            "sourceColumn": "Ignatian Ind",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Est Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f40bd31b-3cb5-4af6-a641-fa35bf97d8f2",
            "sourceColumn": "Sort Est Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Program Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97a1c654-836e-41bb-897b-ccbcb52501e3",
            "sourceColumn": "Sort Program Category",
            "summarizeBy": "none"
          },
          {
            "name": "Orig Proc Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "00d76a8f-ddce-4c3c-be67-6820c8ad769d",
            "sourceColumn": "Orig Proc Dt",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "55d85da5-0f93-434b-9c2d-637081f135ec",
        "partitions": [
          {
            "name": "Revenue_5Yrs-e63bbb29-5c3d-4579-aec0-00d2e0939468",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(#\"Data Source\", [HierarchicalNavigation=true, Query=\"-- Revenue query for the Parent Report (can be used for others). smk 6/23/2023#(lf)-- Updated to add a \"\"Parent Indicator\"\" and \"\"Parent Count\"\" for use in the Parent Dashboard. smk 8/4/2023#(lf)-- Updated to add proprietary \"\"Parent Program Category\"\" to the query and make it equivalent to previous Parent query. smk 9/7/2023#(lf)-- Updated query to restrict transactions to only those from Current Parents. smk 9/21/2023#(lf)#(lf)select distinct r.household_key                                            \"\"HH Key\"\",#(lf)       r.household_key||rev.fiscal_yr                                      \"\"ComboKey\"\",#(lf)       CASE WHEN p.parent_household_key > ' ' THEN 1#(lf)          ELSE 0 END                                                       \"\"Par Ind\"\",#(lf)       CASE WHEN hh.secondary_id_number > ' ' THEN 2#(lf)            WHEN hh.primary_id_number > ' ' THEN 1#(lf)          ELSE 0 END                                                       \"\"Par Cnt\"\",#(lf)       r.trans_nbr                                                         \"\"Trans Nbr\"\",#(lf)       rev.trans_category                                                  \"\"Trans Category\"\",#(lf)       rev.campaign_ind                                                    \"\"Campaign Ind\"\",#(lf)       rev.finance_category                                                \"\"Finance Category\"\",#(lf)       CASE WHEN a.allocation_code = 'RGENOTHPART' THEN 'Parent Fund'#(lf)            WHEN a.allocation_code = 'OATHOTHJAYAUX' THEN 'Mens BB Auxiliary Income'#(lf)            WHEN a.athletics_ind = 'Y' AND a.allocation_code <> 'OATHOTHJAYAUX' THEN 'Other Athletics Gifts'#(lf)          ELSE nvl(rev.finance_category,'Missing') END                     \"\"Parent Program Category\"\",#(lf)       trunc(rev.trans_dt)                                                 \"\"Trans Dt\"\",#(lf)       rev.fiscal_yr                                                       \"\"Fiscal Yr\"\",#(lf)       rev.allocation_code                                                 \"\"Alloc Code\"\",#(lf)       rev.allocation_name                                                 \"\"Allocation Name\"\",#(lf)       CASE WHEN a.start_date < '01-OCT-2016' THEN 'Pre-Campaign'#(lf)          ELSE to_char(EXTRACT(YEAR FROM ADD_MONTHS(a.start_date,6))) END  \"\"Est Yr\"\",#(lf)       CASE WHEN a.allocation_code = revx.allc THEN 'New in Pre-Campaign'#(lf)            WHEN a.category3_code IN ('CS1','CS2','CS3') THEN 'New in Campaign'#(lf)          ELSE 'Pre-Existing, Funded in Campaign' END                      \"\"Scholarship Status\"\",#(lf)       ag.short_desc                                                       \"\"Alloc Group\"\",#(lf)       CASE WHEN a.alloc_sub_dept = 'IGN' THEN 'Ignatian Merit Scholarship'#(lf)          ELSE 'Other' END                                                 \"\"Ignatian Ind\"\",#(lf)       rev.school                                                          \"\"School\"\",#(lf)       rev.trans_amt                                                       \"\"Trans Amt\"\",#(lf)       gc.short_desc                                                       \"\"Goal Category\"\",#(lf)       gsc.short_desc                                                      \"\"Goal SubCategory\"\",#(lf)       c1.short_desc                                                       \"\"Campaign Bucket\"\",#(lf)       c2.short_desc                                                       \"\"Campaign Priority\"\",#(lf)       c3.short_desc                                                       \"\"Campaign SubPriority\"\",#(lf)       rev.orig_proc_dt                                                    \"\"Orig Proc Dt\"\",#(lf)       rev.fincat_sort                                                     \"\"Sort FinCat\"\",#(lf)       CASE WHEN a.start_date < '01-OCT-2016' THEN '2000'#(lf)          ELSE to_char(EXTRACT(YEAR FROM ADD_MONTHS(a.start_date,6))) END  \"\"Sort Est Yr\"\",#(lf)       CASE WHEN a.allocation_code = 'RGENOTHPART' THEN '025'#(lf)            WHEN a.allocation_code = 'OATHOTHJAYAUX' THEN '050'#(lf)            WHEN a.athletics_ind = 'Y' AND a.allocation_code <> 'OATHOTHJAYAUX' THEN '075'#(lf)            WHEN rev.fincat_sort = '001' THEN '100'#(lf)            WHEN rev.fincat_sort = '050' THEN '150'#(lf)          ELSE nvl(rev.fincat_sort,'999') END                              \"\"Sort Program Category\"\",#(lf)       rev.transtype_sort                                                  \"\"Sort TransType\"\"#(lf)from advur.mvw_trans_households r#(lf)inner join advur.mvw_total_revenue rev           ON r.trans_nbr = rev.trans_nbr#(lf)inner join advur.vw_current_fiscal_year fy       ON rev.fiscal_yr BETWEEN fy.fiscal_yr-4 and fy.fiscal_yr#(lf)inner join advur.mvw_hh_parents p                 ON r.household_key = p.parent_household_key #(lf)                                                    AND rev.fiscal_yr BETWEEN EXTRACT(YEAR FROM add_months(p.start_date,6)) #(lf)                                                                          AND EXTRACT(YEAR FROM add_months(p.stop_date,6))#(lf)inner join advur.mvw_hh_entities_with_deceased hh ON p.parent_household_key = hh.household_key#(lf)inner join (#(lf)            select distinct xp.parent_household_key  HHKey,#(lf)                   xpar.fy FY#(lf)              from advur.mvw_hh_parents xp#(lf)             inner join (#(lf)                         select xp4.parent_household_key hk,#(lf)                                to_char((select * from advur.vw_current_fiscal_year)-4) fy,#(lf)                                CASE WHEN (select * from advur.vw_current_fiscal_year)-4 BETWEEN EXTRACT(YEAR FROM add_months(xp4.start_date,6)) #(lf)                                                                                   AND EXTRACT(YEAR FROM add_months(xp4.stop_date,6)) THEN 1#(lf)                                   ELSE 0 END p_ind#(lf)                           from advur.mvw_hh_parents xp4#(lf)                          UNION ALL#(lf)                         select xp3.parent_household_key hk,#(lf)                                to_char((select * from advur.vw_current_fiscal_year)-3) fy,#(lf)                                CASE WHEN (select * from advur.vw_current_fiscal_year)-3 BETWEEN EXTRACT(YEAR FROM add_months(xp3.start_date,6)) #(lf)                                                                                   AND EXTRACT(YEAR FROM add_months(xp3.stop_date,6)) THEN 1#(lf)                                   ELSE 0 END p_ind#(lf)                           from advur.mvw_hh_parents xp3#(lf)                          UNION ALL#(lf)                         select xp2.parent_household_key hk,#(lf)                                to_char((select * from advur.vw_current_fiscal_year)-2) fy,#(lf)                                CASE WHEN (select * from advur.vw_current_fiscal_year)-2 BETWEEN EXTRACT(YEAR FROM add_months(xp2.start_date,6)) #(lf)                                                                                   AND EXTRACT(YEAR FROM add_months(xp2.stop_date,6)) THEN 1#(lf)                                ELSE 0 END p_ind#(lf)                           from advur.mvw_hh_parents xp2#(lf)                          UNION ALL#(lf)                         select xp1.parent_household_key hk,#(lf)                                to_char((select * from advur.vw_current_fiscal_year)-1) fy,#(lf)                                CASE WHEN (select * from advur.vw_current_fiscal_year)-1 BETWEEN EXTRACT(YEAR FROM add_months(xp1.start_date,6)) #(lf)                                                                                   AND EXTRACT(YEAR FROM add_months(xp1.stop_date,6)) THEN 1#(lf)                                   ELSE 0 END p_ind#(lf)                           from advur.mvw_hh_parents xp1#(lf)                          UNION ALL#(lf)                         select xp0.parent_household_key hk,#(lf)                                to_char((select * from advur.vw_current_fiscal_year)) fy,#(lf)                                CASE WHEN (select * from advur.vw_current_fiscal_year) BETWEEN EXTRACT(YEAR FROM add_months(xp0.start_date,6)) #(lf)                                                                                 AND EXTRACT(YEAR FROM add_months(xp0.stop_date,6)) THEN 1#(lf)                                   ELSE 0 END p_ind#(lf)                           from advur.mvw_hh_parents xp0#(lf)                         )xpar ON xp.parent_household_key = xpar.hk#(lf)             where xpar.p_ind = 1#(lf)            )prnt ON hh.household_key = prnt.HHKey AND rev.fiscal_yr = prnt.FY#(lf)inner join advance.allocation a                  ON rev.allocation_code = a.allocation_code#(lf)left join advance.tms_alloc_sub_dept ag          ON a.alloc_sub_dept = ag.alloc_sub_dept_code#(lf)left join advance.tms_endow_pool gc              ON a.endow_pool_code = gc.endow_pool#(lf)left join advance.tms_endow_type gsc             ON a.endow_type_code = gsc.endow_type#(lf)left join advance.tms_category1 c1               ON a.category1_code = c1.category1_code#(lf)left join advance.tms_category2 c2               ON a.category2_code = c2.category2_code#(lf)left join advance.tms_category3 c3               ON a.category3_code = c3.category3_code#(lf)left join (#(lf)            select distinct xr2.allocation_code allc#(lf)              from advur.mvw_total_revenue xr2#(lf)             inner join advur.mvw_total_revenue_ext xxr2    ON xr2.trans_nbr = xxr2.trans_nbr#(lf)             inner join advur.mvw_allocations xa2           ON xr2.allocation_code = xa2.allocation_code#(lf)              left join advance.tms_category3 xxc32         ON xxr2.category3_code = xxc32.category3_code#(lf)             where xr2.finance_category IN ('Annual Scholarships','Endowed Scholarships')#(lf)             and   xr2.campaign_ind = 'Current Campaign'#(lf)             and   xa2.start_date BETWEEN '01-JUL-2013' AND '30-SEP-2016'#(lf)             and   xr2.trans_dt BETWEEN '01-JUL-2013' AND '30-SEP-2016'#(lf)            )revx ON a.allocation_code = revx.allc#(lf)#(lf)order by \"\"Trans Dt\"\"\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Trans Dt\", type date}, {\"Trans Amt\", Currency.Type}, {\"Par Ind\", Int64.Type}, {\"Par Cnt\", Int64.Type}, {\"Orig Proc Dt\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Key Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "6eced31a-ec53-407f-a292-ac1fc3771391",
        "measures": [
          {
            "name": "FY Revenue",
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYRev = CALCULATE(",
              "                        SUMX( Revenue_5Yrs, Revenue_5Yrs[Trans Amt] ),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelYr,",
              "                            Revenue_5Yrs[Par Ind] = 1",
              "                        )",
              "return",
              "IF(ISBLANK(_FYRev),0,_FYRev)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "229b7849-fcb9-4ec2-9f62-95acf2a35427"
          },
          {
            "name": "FY Rev HH Dnr Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYRevDnrCnt = CALCULATE(",
              "                        DISTINCTCOUNT( Revenue_5Yrs[HH Key] ),",
              "                        FILTER( Revenue_5Yrs, Revenue_5Yrs[Fiscal Yr] = _SelFY),",
              "                        FILTER( Revenue_5Yrs, Revenue_5Yrs[Par Ind] = 1)",
              "                    )",
              "return",
              "IF(ISBLANK(_FYRevDnrCnt),0,_FYRevDnrCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "8261c131-1c2b-4dc1-8127-92ee44312f46"
          },
          {
            "name": "FY Rev Gift Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYRevGiftCnt2 = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( Revenue_5Yrs[Trans Nbr]),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelFY && Revenue_5Yrs[Par Ind] = 1 )",
              "return",
              "IF(ISBLANK(_FYRevGiftCnt2),0,_FYRevGiftCnt2)"
            ],
            "formatString": "#,0",
            "lineageTag": "8a2b9211-31c2-41e4-a800-9acbb9caab0c"
          },
          {
            "name": "FY Parent HH Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYHHCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( 'Current Parents_5Yr'[HH Key] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY",
              "                            )",
              "return",
              "IF(ISBLANK(_FYHHCnt),0,_FYHHCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "67e2a4fc-a529-4186-8697-f3b6fb263aba"
          },
          {
            "name": "FY Parent Ind Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYIndCnt = CALCULATE(",
              "                            SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[Parent Cnt] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY)",
              "return",
              "IF(ISBLANK(_FYIndCnt),0,_FYIndCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "888e81e2-97e3-45fb-93ff-4454f87212de"
          },
          {
            "name": "FY Production",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYProd = CALCULATE(",
              "                        SUMX( Production_5Yrs, Production_5Yrs[Trans Amt] ),",
              "                            Production_5Yrs[Fiscal Yr] = _SelYr,",
              "                            Production_5Yrs[Par Ind] = 1",
              "                        )",
              "return",
              "IF(ISBLANK(_FYProd),0,_FYProd)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "56f91351-d2ea-40aa-b866-643638879a45"
          },
          {
            "name": "FY Prod HH Dnr Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYProdDnrCnt = CALCULATE(",
              "                        DISTINCTCOUNTNOBLANK( Production_5Yrs[HH Key] ),",
              "                        FILTER( Production_5Yrs, Production_5Yrs[Fiscal Yr] = _SelFY),",
              "                        FILTER( 'Current Parents_5Yr', 'Current Parents_5Yr'[Parent Cnt] > 0 ),",
              "                        USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                    )",
              "return",
              "IF(ISBLANK(_FYProdDnrCnt),0,_FYProdDnrCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "673b8e3b-da2b-41ba-a16f-09dfe8246049"
          },
          {
            "name": "FY Prod Trans Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYProdTransCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( Production_5Yrs[Trans Nbr] ),",
              "                            Production_5Yrs[Fiscal Yr] = _SelFY && Production_5Yrs[Par Ind] = 1 )",
              "return",
              "IF(ISBLANK(_FYProdTransCnt),0,_FYProdTransCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "ee4ab441-8cd7-415a-9930-513481aed9fc"
          },
          {
            "name": "FY Prod Ind Dnr Cnt",
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYProdIndDnr = CALCULATE(",
              "                        SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[Prod Donor Ind] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelYr",
              "                        )",
              "return",
              "IF(ISBLANK(_FYProdIndDnr),0,_FYProdIndDnr)"
            ],
            "formatString": "#,0",
            "lineageTag": "43b3c259-f6ea-4903-b68c-988127ee6874"
          },
          {
            "name": "FY Rev Ind Dnr Cnt",
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYRevIndDnr = CALCULATE(",
              "                        SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[Rev Donor Ind] ),",
              "                            'Calendar - FY13+'[FiscalYear] = _SelYr",
              "                        )",
              "return",
              "IF(ISBLANK(_FYRevIndDnr),0,_FYRevIndDnr)"
            ],
            "formatString": "#,0",
            "lineageTag": "45718f3a-c965-4c0f-bd78-35accf6a3453"
          },
          {
            "name": "Avg MG EVI",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _AvgEVI = CALCULATE(",
              "                            AVERAGE( 'Current Parents_5Yr'[MG EVI] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[MG EVI] >= 1 )",
              "return",
              "IF(ISBLANK(_AvgEVI),0,_AvgEVI)"
            ],
            "formatString": "0",
            "lineageTag": "ae400ebc-81d5-491d-8a22-e29d9aa20a30"
          },
          {
            "name": "Median Engagement Score",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _MedES = CALCULATE(",
              "                            MEDIAN( 'Current Parents_5Yr'[Engagement Score] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[Engagement Score] > 0 )",
              "return",
              "IF(ISBLANK(_MedES),0,_MedES)"
            ],
            "formatString": "0.0",
            "lineageTag": "1e40eeca-0be1-448d-8ad1-e92d612d6e46"
          },
          {
            "name": "Avg Engagement Score",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _AvgES = CALCULATE(",
              "                            AVERAGE( 'Current Parents_5Yr'[Engagement Score] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[Engagement Score] > 0 )",
              "return",
              "IF(ISBLANK(_AvgES),0,_AvgES)"
            ],
            "formatString": "0.0",
            "lineageTag": "1f850792-13c3-421b-9729-8ae6170a0cac"
          },
          {
            "name": "Median MG EVI",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _MedEVI = CALCULATE(",
              "                            MEDIAN( 'Current Parents_5Yr'[MG EVI] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[MG EVI] >= 1 ",
              "                            )",
              "return",
              "IF(ISBLANK(_MedEVI),0,_MedEVI)"
            ],
            "formatString": "0.0",
            "lineageTag": "782a6a3f-6c28-4f2e-8612-697ed5b46041"
          },
          {
            "name": "HH Six Segment Green Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _HHSSGrnCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( 'Current Parents_5Yr'[HH Key] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY && 'Current Parents_5Yr'[Six Square] = \"Green\"",
              "                            )",
              "return",
              "IF(ISBLANK(_HHSSGrnCnt),0,_HHSSGrnCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "2295fd4f-a6f8-4297-8d6d-2e32bf38cde4"
          },
          {
            "name": "HH Six Segment Blue Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _HHSSBluCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( 'Current Parents_5Yr'[HH Key] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[Six Square] = \"Blue\"",
              "                            )",
              "return",
              "IF(ISBLANK(_HHSSBluCnt),0,_HHSSBluCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "5c85479e-a618-4cc4-87fc-f3ae6f3fe3b7"
          },
          {
            "name": "HH Six Segment Orange Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _HHSSOraCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( 'Current Parents_5Yr'[HH Key] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY && 'Current Parents_5Yr'[Six Square] = \"Orange\"",
              "                            )",
              "return",
              "IF(ISBLANK(_HHSSOraCnt),0,_HHSSOraCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "a0774a8e-72ff-403f-86c3-943984ccc01a"
          },
          {
            "name": "HH Six Segment Red Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _HHSSRedCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( 'Current Parents_5Yr'[HH Key] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY && 'Current Parents_5Yr'[Six Square] = \"Red\"",
              "                            )",
              "return",
              "IF(ISBLANK(_HHSSRedCnt),0,_HHSSRedCnt)"
            ],
            "formatString": "0",
            "lineageTag": "600e876e-d803-4ec3-8922-593fa48b7c2e"
          },
          {
            "name": "HH Six Segment Yellow Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _HHSSYelCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( 'Current Parents_5Yr'[HH Key] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY && 'Current Parents_5Yr'[Six Square] = \"Yellow\"",
              "                            )",
              "return",
              "IF(ISBLANK(_HHSSYelCnt),0,_HHSSYelCnt)"
            ],
            "formatString": "0",
            "lineageTag": "10c00d9a-5385-48bf-8ddc-c4957f3c4625"
          },
          {
            "name": "HH Six Segment Purple Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _HHSSPurCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( 'Current Parents_5Yr'[HH Key] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY && 'Current Parents_5Yr'[Six Square] = \"Purple\"",
              "                            )",
              "return",
              "IF(ISBLANK(_HHSSPurCnt),0,_HHSSPurCnt)"
            ],
            "formatString": "0",
            "lineageTag": "ee53a849-30f2-4c75-a0c2-4dccecdc0b80"
          },
          {
            "name": "Avg HH Trans (Prod)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY Production] / [FY Prod HH Dnr Count]"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "3593a6d6-d91a-4be8-8429-5337113f5fc9"
          },
          {
            "name": "HH Prod Part Rate",
            "expression": [
              "",
              "    [FY Prod HH Dnr Count] / [FY Parent HH Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2442c98a-ea58-41b3-b686-be50a81f82a2"
          },
          {
            "name": "Ind Prod Part Rate",
            "expression": [
              "",
              "    [FY Prod Ind Dnr Cnt] / [FY Parent Ind Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "613e191d-8184-469f-ba3e-e3f60991a333"
          },
          {
            "name": "Avg Per Trans (Prod)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY Production] / [FY Prod Trans Count]"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a03caff9-0e91-4b2e-9b81-875de804a008"
          },
          {
            "name": "Avg HH Trans (Rev)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY Revenue] / [FY Rev HH Dnr Count]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "89625afd-9874-4f3c-9e82-34675a6466df"
          },
          {
            "name": "HH Rev Part Rate",
            "expression": [
              "",
              "    [FY Rev HH Dnr Count] / [FY Parent HH Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "36ffa5af-5197-46da-b42f-c573e418f036"
          },
          {
            "name": "Ind Rev Part Rate",
            "expression": [
              "",
              "    [FY Rev Ind Dnr Cnt] / [FY Parent Ind Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "785c4b7a-5a56-4e0d-a88d-2941426501d6"
          },
          {
            "name": "Avg Per Trans (Rev)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY Revenue] / [FY Rev Gift Count]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "b61d6856-0cfe-4a28-9a86-ee7cb12266b2"
          },
          {
            "name": "Total Production",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    SUMX( Production_5Yrs, Production_5Yrs[Trans Amt] )"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a1271cf1-f0d0-4d22-9320-f939a8f201a8"
          },
          {
            "name": "Total Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    SUMX( Revenue_5Yrs, Revenue_5Yrs[Trans Amt] )"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f635209b-e1fb-471d-bc24-97d35a7dd6ce"
          },
          {
            "name": "Total Schol Prod",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _ScholTtl = CALCULATE(",
              "                    SUMX( Production_5Yrs, Production_5Yrs[Trans Amt] ),",
              "                    Production_5Yrs[Finance Category] IN  {\"Annual Scholarships\",\"Endowed Scholarships\"}",
              "                    ) + 0",
              "   return",
              "   IF(ISBLANK(_ScholTtl),0,_ScholTtl)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "386052e7-2b64-4211-8078-0c3c3e59865a"
          },
          {
            "name": "Total Schol Rev",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _ScholTtlRev = CALCULATE(",
              "                        SUMX( Revenue_5Yrs, Revenue_5Yrs[Trans Amt] ),",
              "                            Revenue_5Yrs[Finance Category] IN {\"Annual Scholarships\",\"Endowed Scholarships\"}",
              "                        ) + 0",
              "   return",
              "   IF(ISBLANK(_ScholTtlRev),0,_ScholTtlRev)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "1b8ddbfd-a993-48a9-8520-9b745cf21b7a"
          },
          {
            "name": "Count Schol Prod",
            "expression": [
              "",
              "    var _ScholCnt = CALCULATE(",
              "                        DISTINCTCOUNT( Production_5Yrs[Allocation Name] ),",
              "                            Production_5Yrs[Goal Category] = \"Scholarships\"",
              "                        )",
              "   return",
              "   IF(ISBLANK(_ScholCnt),0,_ScholCnt)"
            ],
            "formatString": "0",
            "lineageTag": "c849dde8-1652-4e68-94e0-9cbef5b0f539"
          },
          {
            "name": "Count Schol Rev",
            "expression": [
              "",
              "    var _ScholCnt = CALCULATE(",
              "                        DISTINCTCOUNT( Revenue_5Yrs[Allocation Name] ),",
              "                            Revenue_5Yrs[Goal Category] = \"Scholarships\"",
              "                        )",
              "   return",
              "   IF(ISBLANK(_ScholCnt),0,_ScholCnt)"
            ],
            "formatString": "0",
            "lineageTag": "dcb95b3d-b9b0-4504-bf81-cfb74232fd44"
          },
          {
            "name": "Student Count",
            "expression": [
              "",
              "    var _StdntCnt = DISTINCTCOUNT( Students[Student ID] )",
              "return",
              "IF(ISBLANK(_StdntCnt),0,_StdntCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "0205361b-d934-489f-b9e0-bbc35a5227cf"
          },
          {
            "name": "Total 5-Yr Production",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "            [Total Production],",
              "            ALLSELECTED( Production_5Yrs[Fiscal Yr] )",
              "    )"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "89f1e32a-4110-4652-a3c1-33903e7e0cef"
          },
          {
            "name": "Median Trans (Prod)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    MEDIANX( Production_5Yrs, Production_5Yrs[Trans Amt] )"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "35b033d4-6dca-40a5-ad94-3df1d4b6fbf6"
          },
          {
            "name": "FY Rev Trans Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYRevTransCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( Revenue_5Yrs[Trans Nbr] ),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelFY && Revenue_5Yrs[Par Ind] = 1 )",
              "return",
              "IF(ISBLANK(_FYRevTransCnt),0,_FYRevTransCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "78ca8663-0d12-49b2-8520-03af13b61671"
          },
          {
            "name": "Median Trans (Rev)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    MEDIANX( Revenue_5Yrs, Revenue_5Yrs[Trans Amt] )"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "77dfdac5-117f-4367-a855-17e9dfda333d"
          },
          {
            "name": "Month Production",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _MthProd = CALCULATE(",
              "                        SUMX( Production_5Yrs, Production_5Yrs[Trans Amt] ),",
              "                            Production_5Yrs[Fiscal Yr] = _SelYr,",
              "                            Production_5Yrs[Par Ind] = 1,",
              "                            USERELATIONSHIP( 'Calendar - FY13+'[Date], Production_5Yrs[Trans Dt] )",
              "                        )",
              "return",
              "IF(ISBLANK(_MthProd),0,_MthProd)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "0542edcb-6731-4de2-a7e6-6574c4984729"
          },
          {
            "name": "Month Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _MthRev = CALCULATE(",
              "                        SUMX( Revenue_5Yrs, Revenue_5Yrs[Trans Amt] ),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelYr,",
              "                            Revenue_5Yrs[Par Ind] = 1,",
              "                            USERELATIONSHIP( 'Calendar - FY13+'[Date], Revenue_5Yrs[Trans Dt] )",
              "                        )",
              "return",
              "IF(ISBLANK(_MthRev),0,_MthRev)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7cbc81d9-b233-4d93-bce9-64a538e8f9a6"
          }
        ],
        "partitions": [
          {
            "name": "Key Measures-6c8cce5d-2a8f-4685-8934-a2b8bd558f08",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar - FY13+",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "3fa75144-9e84-49d2-9708-b654328a136a",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "32e1d493-9d57-40ed-a620-3f35e133b397",
            "sourceColumn": "MonthNum",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "121fbde8-a2cb-47aa-876e-7d46d0f932ce",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "MonthLong",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d3a5c11-3c44-47ff-9466-91839b9dcc9f",
            "sourceColumn": "MonthLong",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39792401-560b-4c90-ad67-a57d75a39f3c",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fcc899df-4d5f-4555-8bc8-dcc9c6f2f3b1",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "SortFiscalMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "57029d71-7e87-427a-ab04-2d88cda10813",
            "sourceColumn": "SortFiscalMonth",
            "summarizeBy": "sum"
          },
          {
            "name": "FiscalMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "12b0c6b3-f436-4fb2-9ed6-9218eb06c6ac",
            "sortByColumn": "SortFiscalMonth",
            "sourceColumn": "FiscalMonth",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalMonthLong",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4793257-0cb8-45d7-aac8-07ef5087ff6b",
            "sourceColumn": "FiscalMonthLong",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb7a0fda-6998-414d-ba57-c734ae26da1a",
            "sourceColumn": "FiscalQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1fa9321-4008-41e1-a1bd-726cfd76dbc0",
            "sourceColumn": "FiscalYear",
            "summarizeBy": "none"
          },
          {
            "name": "CurMonthOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7327894f-d771-4a7d-9331-df7e5a659a29",
            "sourceColumn": "CurMonthOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "CurQuarterOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4d900d57-06f7-4b3c-8472-a5c57d54aa50",
            "sourceColumn": "CurQuarterOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "CurYearOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d7fbf5a3-afc7-4bed-b692-5035a536b312",
            "sourceColumn": "CurYearOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "FutureDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a5ca2b7-7b02-4509-b241-4362ae31e561",
            "sourceColumn": "FutureDate",
            "summarizeBy": "none"
          },
          {
            "name": "CurFiscalYearOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "302ae644-8155-4a0b-8943-f0d8872667fa",
            "sourceColumn": "CurFiscalYearOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "SortMonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0ca53e9c-6520-4faa-a7f2-c242df693166",
            "sourceColumn": "SortMonthYear",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82626633-ce2f-4cda-8364-47549d1f7650",
            "sourceColumn": "MonthYear",
            "summarizeBy": "none"
          },
          {
            "name": "MonthYearLong",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6d2df05-d6dd-4dfd-8ec3-3fd4740f010e",
            "sourceColumn": "MonthYearLong",
            "summarizeBy": "none"
          },
          {
            "name": "SortWeekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "da14ac19-9f96-4b22-83d9-f428ead2bb98",
            "sourceColumn": "SortWeekday",
            "summarizeBy": "sum"
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb589603-a21f-46d9-8ee5-4d37371b26f8",
            "sourceColumn": "Weekday",
            "summarizeBy": "none"
          },
          {
            "name": "WeekdayWeekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58f3a54e-34d1-4463-b8fb-ccfce1153132",
            "sourceColumn": "WeekdayWeekend",
            "summarizeBy": "none"
          },
          {
            "name": "SortWeekSequence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2503dc92-00f5-47b7-a5b6-f9018a82007d",
            "sourceColumn": "SortWeekSequence",
            "summarizeBy": "sum"
          },
          {
            "name": "CurWeekOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "93561ed0-155b-4d15-95e3-6491db958051",
            "sourceColumn": "CurWeekOffset",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "1172d20d-578f-43e3-9d6a-37fccfc9873f",
        "partitions": [
          {
            "name": "Calendar - FY13+-fb15ef98-a11e-46d3-a648-524af124e6ba",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    /*",
                "    ****This Calendar was created and provided by Avi Singh****",
                "    ****This can be freely shared as long as this text comment is retained.****",
                "    http://www.youtube.com/PowerBIPro",
                "    www.LearnPowerBI.com by Avi Singh",
                "    */",
                "    #\"LearnPowerBI.com by Avi Singh\" = 1,",
                "    StartDate = #date(2017, 7, 1),",
                "    EndDate = Date.AddMonths( Date.EndOfYear( #\"Max Rev Date\" ), FiscalYearEndMonth ) //= Date.EndOfYear( #\"Max Rev Date\" )",
                " //= Date.EndOfYear(DateTime.Date(DateTime.FixedLocalNow()))",
                " /*was \"#date(2017, 1, 1)\" Updated on 201802027: hard Coded End of Year caused some formulas to break, switching to dynamic date*/,",
                "    //Used for 'Offset' Column calculations, you may Hard code CurrentDate for testing e.g. #date(2017,9,1)",
                "    CurrentDate = DateTime.Date(DateTime.FixedLocalNow()),",
                "    // Specify the last month in your Fiscal Year, e.g. if June is the last month of your Fiscal Year, specify 6",
                "    FiscalYearEndMonth = 6,",
                "    #\"==SET PARAMETERS ABOVE==\" = 1,",
                "    #\"==Build Date Column==\" = #\"==SET PARAMETERS ABOVE==\",",
                "    ListDates = List.Dates(StartDate, Number.From(EndDate - StartDate)+1, #duration(1,0,0,0)),",
                "    #\"Converted to Table\" = Table.FromList(ListDates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Renamed Columns as Date\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Date\"}}),",
                "    // As far as Power BI is concerned, the 'Date' column is all that is needed :-) But we will continue and add a few Human-Friendly Columns",
                "    #\"Changed Type to Date\" = Table.TransformColumnTypes(#\"Renamed Columns as Date\",{{\"Date\", type date}}),",
                "    #\"==Add Calendar Columns==\" = #\"Changed Type to Date\",",
                "    #\"Added Calendar MonthNum\" = Table.AddColumn(#\"==Add Calendar Columns==\", \"MonthNum\", each Date.Month([Date]), Int64.Type),",
                "    #\"Added Month Name\" = Table.AddColumn(#\"Added Calendar MonthNum\", \"Month\", each Text.Start(Date.MonthName([Date]),3), type text),",
                "    #\"Added Month Name Long\" = Table.AddColumn(#\"Added Month Name\", \"MonthLong\", each Date.MonthName([Date]), type text),",
                "    #\"Added Calendar Quarter\" = Table.AddColumn(#\"Added Month Name Long\", \"Quarter\", each \"Q\" & Text.From(Date.QuarterOfYear([Date]))),",
                "    #\"Added Calendar Year\" = Table.AddColumn(#\"Added Calendar Quarter\", \"Year\", each Date.Year([Date]), Int64.Type),",
                "    #\"==Add Fiscal Calendar Columns==\" = #\"Added Calendar Year\",",
                "    #\"Added FiscalMonthNum\" = Table.AddColumn(#\"==Add Fiscal Calendar Columns==\", \"FiscalMonthNum\", each if [MonthNum] > FiscalYearEndMonth",
                "then [MonthNum] - FiscalYearEndMonth",
                "else [MonthNum] + (12 - FiscalYearEndMonth), type number),",
                "    #\"Added FiscalMonth Name\" = Table.AddColumn(#\"Added FiscalMonthNum\", \"FiscalMonth\", each [Month]),",
                "    #\"Added FiscalMonth Name Long\" = Table.AddColumn(#\"Added FiscalMonth Name\", \"FiscalMonthLong\", each [MonthLong]),",
                "    #\"Added FiscalQuarter\" = Table.AddColumn(#\"Added FiscalMonth Name Long\", \"FiscalQuarter\", each \"FQ\" & Text.From(Number.RoundUp([FiscalMonthNum] / 3,0))),",
                "    #\"Added FiscalYear\" = Table.AddColumn(#\"Added FiscalQuarter\", \"FiscalYear\", each ",
                "Text.End(",
                "  Text.From(",
                "    if [MonthNum] > FiscalYearEndMonth",
                "    then [Year] + 1",
                "    else [Year]",
                "  )",
                "  , 4",
                ")),",
                "",
                "    #\"==Add Calendar Date Offset Columns==\" = #\"Added FiscalYear\",",
                "    // Can be used to for example to show the past 3 months(CurMonthOffset = 0, -1, -2)",
                "    #\"Added CurMonthOffset\" = Table.AddColumn(#\"==Add Calendar Date Offset Columns==\", \"CurMonthOffset\", each ( Date.Year([Date]) - Date.Year(CurrentDate) ) * 12",
                "+ Date.Month([Date]) - Date.Month(CurrentDate), Int64.Type),",
                "    // Can be used to for example to show the past 3 quarters (CurQuarterOffset = 0, -1, -2)",
                "    #\"Added CurQuarterOffset\" = Table.AddColumn(#\"Added CurMonthOffset\", \"CurQuarterOffset\", each /*Year Difference*/",
                "       ( Date.Year([Date]) - Date.Year(CurrentDate) )*4",
                "       /*Quarter Difference*/",
                "      + Number.RoundUp(Date.Month([Date]) / 3) ",
                "      - Number.RoundUp(Date.Month(CurrentDate) / 3),",
                "Int64.Type),",
                "    // Can be used to for example to show the past 3 years (CurYearOffset = 0, -1, -2)",
                "    #\"Added CurYearOffset\" = Table.AddColumn(#\"Added CurQuarterOffset\", \"CurYearOffset\", each Date.Year([Date]) - Date.Year(CurrentDate), Int64.Type),",
                "    // Can be used to for example filter out all future dates",
                "    #\"Added FutureDate Flag\" = Table.AddColumn(#\"Added CurYearOffset\", \"FutureDate\", each if [Date] > CurrentDate then \"Future\" else \"Past\" ),",
                "    // FiscalYearOffset is the only Offset that is different.",
                "    // FiscalQuarterOffset = is same as CurQuarterOffset",
                "    // FiscalMonthOffset = is same as CurMonthOffset",
                "    #\"==Add FiscalYearOffset==\" = #\"Added FutureDate Flag\",",
                "    #\"Filtered Rows to CurrentDate\" = Table.SelectRows(#\"==Add FiscalYearOffset==\", each ([Date] = CurrentDate)),",
                "    CurrentFiscalYear = #\"Filtered Rows to CurrentDate\"{0}[FiscalYear],",
                "    #\"Continue...Orig Table\" = #\"==Add FiscalYearOffset==\",",
                "    #\"Added CurFiscalYearOffset\" = Table.AddColumn(#\"Continue...Orig Table\", \"CurFiscalYearOffset\", each Number.From(Text.Range([FiscalYear],2,2)) - ",
                "Number.From(Text.Range(CurrentFiscalYear,2,2))",
                "/*Extract the numerical portion, e.g. FY18 = 18*/),",
                "    #\"==Add General Columns==\" = #\"Added CurFiscalYearOffset\",",
                "    // Used as 'Sort by Column' for MonthYear columns",
                "    #\"Added MonthYearNum\" = Table.AddColumn(#\"==Add General Columns==\", \"MonthYearNum\", each [Year]*100 + [MonthNum] /*e.g. Sep-2016 would become 201609*/, Int64.Type),",
                "    #\"Added MonthYear\" = Table.AddColumn(#\"Added MonthYearNum\", \"MonthYear\", each [Month] & \"-\" & Text.End(Text.From([Year]),2)),",
                "    #\"Added MonthYearLong\" = Table.AddColumn(#\"Added MonthYear\", \"MonthYearLong\", each [Month] & \"-\" & Text.From([Year])),",
                "    #\"Added WeekdayNum\" = Table.AddColumn(#\"Added MonthYearLong\", \"WeekdayNum\", each Date.DayOfWeek([Date]), Int64.Type),",
                "    #\"Added Weekday Name\" = Table.AddColumn(#\"Added WeekdayNum\", \"Weekday\", each Text.Start(Date.DayOfWeekName([Date]),3), type text),",
                "    #\"Added WeekdayWeekend\" = Table.AddColumn(#\"Added Weekday Name\", \"WeekdayWeekend\", each if [WeekdayNum] = 0 or [WeekdayNum] = 6",
                "then \"Weekend\"",
                "else \"Weekday\"),",
                "    #\"==Improve Ultimate Table\" = #\"Added WeekdayWeekend\",",
                "    #\"----Add WeekSequenceNum----\" = #\"==Improve Ultimate Table\",",
                "    #\"Filtered Rows Sundays Only (Start of Week)\" = Table.SelectRows(#\"----Add WeekSequenceNum----\", each ([WeekdayNum] = 0)),",
                "    #\"Added Index WeekSequenceNum\" = Table.AddIndexColumn(#\"Filtered Rows Sundays Only (Start of Week)\", \"WeekSequenceNum\", 2, 1),",
                "    #\"Merged Queries Ultimate Table to WeekSequenceNum\" = Table.NestedJoin(#\"==Improve Ultimate Table\",{\"Date\"},#\"Added Index WeekSequenceNum\",{\"Date\"},\"Added Index WeekNum\",JoinKind.LeftOuter),",
                "    #\"Expanded Added Index WeekNum\" = Table.ExpandTableColumn(#\"Merged Queries Ultimate Table to WeekSequenceNum\", \"Added Index WeekNum\", {\"WeekSequenceNum\"}, {\"WeekSequenceNum\"}),",
                "    // somehow it ends up being unsorted after Expand Column, should not matter for the end table, but makes it harder to debug and check everything is correct. Thus sorting it.",
                "    #\"ReSorted Rows by Date\" = Table.Sort(#\"Expanded Added Index WeekNum\",{{\"Date\", Order.Ascending}}),",
                "    #\"Filled Down WeekSequenceNum\" = Table.FillDown(#\"ReSorted Rows by Date\",{\"WeekSequenceNum\"}),",
                "    #\"Replaced Value WeekSequenceNum null with 1\" = Table.ReplaceValue(#\"Filled Down WeekSequenceNum\",null,1,Replacer.ReplaceValue,{\"WeekSequenceNum\"}),",
                "    #\"----WeekSequenceNum Complete----\" = #\"Replaced Value WeekSequenceNum null with 1\",",
                "    Current_WeekSequenceNum = #\"----WeekSequenceNum Complete----\"{[Date = CurrentDate]}?[WeekSequenceNum],",
                "    #\"Added Custom CurWeekOffset\" = Table.AddColumn(#\"----WeekSequenceNum Complete----\", \"CurWeekOffset\", each [WeekSequenceNum] - Current_WeekSequenceNum, Int64.Type),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom CurWeekOffset\",{{\"Quarter\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"FiscalMonthNum\", \"SortFiscalMonth\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"FiscalMonth\", type text}, {\"FiscalMonthLong\", type text}, {\"FiscalQuarter\", type text}, {\"FiscalYear\", type text}, {\"FutureDate\", type text}, {\"CurFiscalYearOffset\", Int64.Type}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type1\",{{\"MonthYearNum\", \"SortMonthYear\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"MonthYear\", type text}, {\"MonthYearLong\", type text}}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Changed Type2\",{{\"WeekdayNum\", \"SortWeekday\"}}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"WeekdayWeekend\", type text}}),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Changed Type3\",{{\"WeekSequenceNum\", \"SortWeekSequence\"}})",
                "in",
                "    #\"Renamed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Production_5Yrs",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "HH Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "960008a3-d22a-4913-ab67-f6664dbcf591",
            "sourceColumn": "HH Key",
            "summarizeBy": "none"
          },
          {
            "name": "ComboKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36053953-3cfe-46f2-a63e-51f0720355f8",
            "sourceColumn": "ComboKey",
            "summarizeBy": "none"
          },
          {
            "name": "Par Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "14433b7c-17e3-499f-8271-9cdf4aa46476",
            "sourceColumn": "Par Ind",
            "summarizeBy": "sum"
          },
          {
            "name": "Par Cnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f7d659a7-4bb2-4092-9ab0-5c2766260c04",
            "sourceColumn": "Par Cnt",
            "summarizeBy": "sum"
          },
          {
            "name": "Trans Nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff2e1294-2321-49eb-81b4-e737c7290c30",
            "sourceColumn": "Trans Nbr",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "420c81c4-e2ad-4efe-a5f4-6e6265c69937",
            "sourceColumn": "Trans Category",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec08c636-58d5-4c50-81cd-5d75a358c221",
            "sourceColumn": "Campaign Ind",
            "summarizeBy": "none"
          },
          {
            "name": "Finance Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d28d6f1-ab3d-4d76-8ceb-d36862e22bc1",
            "sourceColumn": "Finance Category",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "e81122ee-518e-4f19-b107-778e39a9640f",
            "sourceColumn": "Trans Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5f802fb-8c2d-416d-bd0b-b5225172f38c",
            "sourceColumn": "Fiscal Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Alloc Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32ce30e1-09b6-4a51-830b-821d9aa62d78",
            "sourceColumn": "Alloc Code",
            "summarizeBy": "none"
          },
          {
            "name": "Allocation Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "178cdd90-ce3e-4f71-ac7d-8a159bd2ce05",
            "sourceColumn": "Allocation Name",
            "summarizeBy": "none"
          },
          {
            "name": "School",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffef164a-1728-46aa-82f9-6c49606b4988",
            "sourceColumn": "School",
            "summarizeBy": "none"
          },
          {
            "name": "Trans Amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "4b66b608-5f5f-4056-b430-c16dad2c3506",
            "sourceColumn": "Trans Amt",
            "summarizeBy": "sum"
          },
          {
            "name": "Goal Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16c6abc0-1b4a-49fa-b505-9f46532523c6",
            "sourceColumn": "Goal Category",
            "summarizeBy": "none"
          },
          {
            "name": "Goal SubCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "732089a3-4083-4819-9f70-0cd7b6d40a3c",
            "sourceColumn": "Goal SubCategory",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1fed282-aada-4f6d-8bf1-f7f00b5ff8f4",
            "sourceColumn": "Campaign Bucket",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign Priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94da77dd-ff1a-4662-9f1c-92e561705b66",
            "sourceColumn": "Campaign Priority",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign SubPriority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a834de05-a75a-4976-9c02-b6d68cbd0446",
            "sourceColumn": "Campaign SubPriority",
            "summarizeBy": "none"
          },
          {
            "name": "Sort FinCat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf28e882-4502-43ba-abd3-74143cc209d2",
            "sourceColumn": "Sort FinCat",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Trans Cat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cff44ee6-af22-43bb-ab12-a5d1e124168a",
            "sourceColumn": "Sort Trans Cat",
            "summarizeBy": "none"
          },
          {
            "name": "Parent Program Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a34798e-3a0b-44c2-914a-49e97c0f6996",
            "sortByColumn": "Sort Program Category",
            "sourceColumn": "Parent Program Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Program Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afda6308-e6b9-4a61-9b4c-afd798b25b79",
            "sourceColumn": "Sort Program Category",
            "summarizeBy": "none"
          },
          {
            "name": "Est Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42831e70-ef77-4e34-b534-dca707e22f82",
            "sourceColumn": "Est Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Scholarship Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1465dab3-1fb1-4dfa-8d35-12247b5eeba1",
            "sourceColumn": "Scholarship Status",
            "summarizeBy": "none"
          },
          {
            "name": "Alloc Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9719e1a5-56d7-4960-99d1-b8de82bdef2e",
            "sourceColumn": "Alloc Group",
            "summarizeBy": "none"
          },
          {
            "name": "Ignatian Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8dd0977-57de-4e27-bfdb-0163948db80d",
            "sourceColumn": "Ignatian Ind",
            "summarizeBy": "none"
          },
          {
            "name": "Orig Proc Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4ff6f435-f7d8-48ef-af4e-9184107c2b0a",
            "sourceColumn": "Orig Proc Dt",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "babc6cc8-9a06-463f-a753-49994d85f77d",
        "partitions": [
          {
            "name": "Production_5Yrs",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(#\"Data Source\", [HierarchicalNavigation=true, Query=\"-- Production query for the Parent Report (can be used for others). smk 8/10/2023#(lf)-- Added the proprietary \"\"Parent Program Category\"\" per the original report and to sync the logic with the previous version. smk 9/7/2023#(lf)-- Updated to restrict transactions to just those from Current Parents. smk 9/21/2023#(lf)#(lf)select distinct p.household_key                                            \"\"HH Key\"\",#(lf)       p.household_key||prd.fiscal_yr                                      \"\"ComboKey\"\",#(lf)       CASE WHEN par.parent_household_key > ' ' THEN 1#(lf)          ELSE 0 END                                                       \"\"Par Ind\"\",#(lf)       CASE WHEN hh.secondary_id_number > ' ' THEN 2#(lf)            WHEN hh.primary_id_number > ' ' THEN 1#(lf)          ELSE 0 END                                                       \"\"Par Cnt\"\",#(lf)       p.trans_nbr                                                         \"\"Trans Nbr\"\",#(lf)       prd.trans_category                                                  \"\"Trans Category\"\",#(lf)       prd.campaign_ind                                                    \"\"Campaign Ind\"\",#(lf)       prd.finance_category                                                \"\"Finance Category\"\",#(lf)       CASE WHEN a.allocation_code = 'RGENOTHPART' THEN 'Parent Fund'#(lf)            WHEN a.allocation_code = 'OATHOTHJAYAUX' THEN 'Mens BB Auxiliary Income'#(lf)            WHEN a.athletics_ind = 'Y' AND a.allocation_code <> 'OATHOTHJAYAUX' THEN 'Other Athletics Gifts'#(lf)          ELSE nvl(prd.finance_category,'Missing') END                     \"\"Parent Program Category\"\",#(lf)       trunc(prd.trans_dt)                                                 \"\"Trans Dt\"\",#(lf)       prd.fiscal_yr                                                       \"\"Fiscal Yr\"\",#(lf)       prd.allocation_code                                                 \"\"Alloc Code\"\",#(lf)       prd.allocation_name                                                 \"\"Allocation Name\"\",#(lf)       CASE WHEN a.start_date < '01-OCT-2016' THEN 'Pre-Campaign'#(lf)          ELSE to_char(EXTRACT(YEAR FROM ADD_MONTHS(a.start_date,6))) END  \"\"Est Yr\"\",#(lf)       CASE WHEN a.allocation_code = prdx.allc THEN 'New in Pre-Campaign'#(lf)            WHEN a.category3_code IN ('CS1','CS2','CS3') THEN 'New in Campaign'#(lf)          ELSE 'Pre-Existing, Funded in Campaign' END                      \"\"Scholarship Status\"\",#(lf)       ag.short_desc                                                       \"\"Alloc Group\"\",#(lf)       CASE WHEN a.alloc_sub_dept = 'IGN' THEN 'Ignatian Merit Scholarship'#(lf)          ELSE 'Other' END                                                 \"\"Ignatian Ind\"\",#(lf)       prd.school                                                          \"\"School\"\",#(lf)       prd.trans_amt                                                       \"\"Trans Amt\"\",#(lf)       gc.short_desc                                                       \"\"Goal Category\"\",#(lf)       gsc.short_desc                                                      \"\"Goal SubCategory\"\",#(lf)       c1.short_desc                                                       \"\"Campaign Bucket\"\",#(lf)       c2.short_desc                                                       \"\"Campaign Priority\"\",#(lf)       c3.short_desc                                                       \"\"Campaign SubPriority\"\",#(lf)       prd.orig_proc_dt                                                    \"\"Orig Proc Dt\"\",#(lf)       prd.fincat_sort                                                     \"\"Sort FinCat\"\",#(lf)       CASE WHEN a.allocation_code = 'RGENOTHPART' THEN '025'#(lf)            WHEN a.allocation_code = 'OATHOTHJAYAUX' THEN '050'#(lf)            WHEN a.athletics_ind = 'Y' AND a.allocation_code <> 'OATHOTHJAYAUX' THEN '075'#(lf)            WHEN prd.fincat_sort = '001' THEN '100'#(lf)            WHEN prd.fincat_sort = '050' THEN '150'#(lf)          ELSE nvl(prd.fincat_sort,'999') END                              \"\"Sort Program Category\"\",#(lf)       CASE WHEN prd.trans_category = 'Pledge Activity' THEN '100'#(lf)            WHEN prd.trans_category = 'Outright Gifts' THEN '200'#(lf)            WHEN prd.trans_category = 'Deferred Gifts' THEN '300'#(lf)            WHEN prd.trans_category = 'Bequest Expectancies and Gifts' THEN '400'#(lf)          ELSE '999' END                                                   \"\"Sort Trans Cat\"\"#(lf)from advur.mvw_trans_households p#(lf)inner join advur.mvw_total_production prd        ON p.trans_nbr = prd.trans_nbr#(lf)inner join advur.vw_current_fiscal_year fy       ON prd.fiscal_yr BETWEEN fy.fiscal_yr-4 and fy.fiscal_yr#(lf)inner join advur.mvw_hh_parents par              ON p.household_key = par.parent_household_key #(lf)                                                    AND prd.fiscal_yr BETWEEN EXTRACT(YEAR FROM add_months(par.start_date,6)) #(lf)                                                                      AND EXTRACT(YEAR FROM add_months(par.stop_date,6))#(lf)inner join advur.mvw_hh_entities_with_deceased hh ON par.parent_household_key = hh.household_key#(lf)inner join (#(lf)            select distinct xp.parent_household_key  HHKey,#(lf)                   xpar.fy FY#(lf)              from advur.mvw_hh_parents xp#(lf)             inner join (#(lf)                         select xp4.parent_household_key hk,#(lf)                                to_char((select * from advur.vw_current_fiscal_year)-4) fy,#(lf)                                CASE WHEN (select * from advur.vw_current_fiscal_year)-4 BETWEEN EXTRACT(YEAR FROM add_months(xp4.start_date,6)) #(lf)                                                                                   AND EXTRACT(YEAR FROM add_months(xp4.stop_date,6)) THEN 1#(lf)                                   ELSE 0 END p_ind#(lf)                           from advur.mvw_hh_parents xp4#(lf)                          UNION ALL#(lf)                         select xp3.parent_household_key hk,#(lf)                                to_char((select * from advur.vw_current_fiscal_year)-3) fy,#(lf)                                CASE WHEN (select * from advur.vw_current_fiscal_year)-3 BETWEEN EXTRACT(YEAR FROM add_months(xp3.start_date,6)) #(lf)                                                                                   AND EXTRACT(YEAR FROM add_months(xp3.stop_date,6)) THEN 1#(lf)                                   ELSE 0 END p_ind#(lf)                           from advur.mvw_hh_parents xp3#(lf)                          UNION ALL#(lf)                         select xp2.parent_household_key hk,#(lf)                                to_char((select * from advur.vw_current_fiscal_year)-2) fy,#(lf)                                CASE WHEN (select * from advur.vw_current_fiscal_year)-2 BETWEEN EXTRACT(YEAR FROM add_months(xp2.start_date,6)) #(lf)                                                                                   AND EXTRACT(YEAR FROM add_months(xp2.stop_date,6)) THEN 1#(lf)                                ELSE 0 END p_ind#(lf)                           from advur.mvw_hh_parents xp2#(lf)                          UNION ALL#(lf)                         select xp1.parent_household_key hk,#(lf)                                to_char((select * from advur.vw_current_fiscal_year)-1) fy,#(lf)                                CASE WHEN (select * from advur.vw_current_fiscal_year)-1 BETWEEN EXTRACT(YEAR FROM add_months(xp1.start_date,6)) #(lf)                                                                                   AND EXTRACT(YEAR FROM add_months(xp1.stop_date,6)) THEN 1#(lf)                                   ELSE 0 END p_ind#(lf)                           from advur.mvw_hh_parents xp1#(lf)                          UNION ALL#(lf)                         select xp0.parent_household_key hk,#(lf)                                to_char((select * from advur.vw_current_fiscal_year)) fy,#(lf)                                CASE WHEN (select * from advur.vw_current_fiscal_year) BETWEEN EXTRACT(YEAR FROM add_months(xp0.start_date,6)) #(lf)                                                                                 AND EXTRACT(YEAR FROM add_months(xp0.stop_date,6)) THEN 1#(lf)                                   ELSE 0 END p_ind#(lf)                           from advur.mvw_hh_parents xp0#(lf)                         )xpar ON xp.parent_household_key = xpar.hk#(lf)             where xpar.p_ind = 1#(lf)            )prnt ON hh.household_key = prnt.HHKey AND prd.fiscal_yr = prnt.FY#(lf)inner join advance.allocation a                  ON prd.allocation_code = a.allocation_code#(lf)left join advance.tms_alloc_sub_dept ag          ON a.alloc_sub_dept = ag.alloc_sub_dept_code#(lf)left join advance.tms_endow_pool gc              ON a.endow_pool_code = gc.endow_pool#(lf)left join advance.tms_endow_type gsc             ON a.endow_type_code = gsc.endow_type#(lf)left join advance.tms_category1 c1               ON a.category1_code = c1.category1_code#(lf)left join advance.tms_category2 c2               ON a.category2_code = c2.category2_code#(lf)left join advance.tms_category3 c3               ON a.category3_code = c3.category3_code#(lf)left join (#(lf)            select distinct xp2.allocation_code allc#(lf)              from advur.mvw_total_production xp2#(lf)             inner join advur.mvw_total_production_ext xxp2  ON xp2.trans_nbr = xxp2.trans_nbr#(lf)             inner join advur.mvw_allocations xa2            ON xp2.allocation_code = xa2.allocation_code#(lf)              left join advance.tms_category3 xxc32         ON xxp2.category3_code = xxc32.category3_code#(lf)             where xp2.finance_category IN ('Annual Scholarships','Endowed Scholarships')#(lf)             and   xp2.campaign_ind = 'Current Campaign'#(lf)             and   xa2.start_date BETWEEN '01-JUL-2013' AND '30-SEP-2016'#(lf)             and   xp2.trans_dt BETWEEN '01-JUL-2013' AND '30-SEP-2016'#(lf)            )prdx ON a.allocation_code = prdx.allc#(lf)#(lf)order by \"\"Trans Dt\"\"\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Par Ind\", Int64.Type}, {\"Par Cnt\", Int64.Type}, {\"Trans Dt\", type date}, {\"Trans Amt\", Currency.Type}, {\"Orig Proc Dt\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Assigned Prim Managers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "HH Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4045504a-ece1-4eba-9230-12476cd218ab",
            "sourceColumn": "HH Key",
            "summarizeBy": "none"
          },
          {
            "name": "ComboKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eeef743d-a8e8-4ffa-8634-b0073ce58075",
            "sourceColumn": "ComboKey",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7fe4144-f8ba-4bf7-ba8f-bd50c99c2a3e",
            "sourceColumn": "Fiscal Yr",
            "summarizeBy": "none"
          },
          {
            "name": "PM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "272a1cc2-317d-4e97-ac05-64ad9c774b5b",
            "sourceColumn": "PM_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Prim Mgr Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "a430fad7-0ed5-4b1b-9bdc-30854d4321a0",
            "sortByColumn": "Main Sort",
            "sourceColumn": "Prim Mgr Name",
            "summarizeBy": "none"
          },
          {
            "name": "Parent ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "627683b1-9ab0-4b6d-be8a-63abf31a76c2",
            "sourceColumn": "Parent ID",
            "summarizeBy": "none"
          },
          {
            "name": "Prospect ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "038fc632-84bd-48ec-b31d-3c6f559a4659",
            "sourceColumn": "Prospect ID",
            "summarizeBy": "count"
          },
          {
            "name": "Mgr Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9d60ea3-efd0-4de9-b346-6df981b08e15",
            "sourceColumn": "Mgr Team",
            "summarizeBy": "none"
          },
          {
            "name": "Start Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "02dfc639-09e4-4733-9d21-480a177f8cd4",
            "sourceColumn": "Start Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Start Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0786d8ce-2514-49ae-ae23-26ca5a74350b",
            "sourceColumn": "Start Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Stop Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e6a007f4-ec18-4140-af9b-ea1a8f4e6cd8",
            "sourceColumn": "Stop Date",
            "summarizeBy": "none"
          },
          {
            "name": "Stop Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34351edd-0690-4ca8-bcc7-8e9215927635",
            "sourceColumn": "Stop Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Par Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e9477c29-faa9-46dd-b2f7-cef373b4c457",
            "sourceColumn": "Par Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Main Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "441c0bfb-348f-4665-80f9-e32ad126ffdb",
            "sourceColumn": "Main Sort",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6665c4e-aa13-4494-8216-528e2384283e",
            "sourceColumn": "Sort Team",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Mgr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "225f4cce-bfb1-4c58-80c2-e1c5c5b021d1",
            "sourceColumn": "Sort Mgr",
            "summarizeBy": "none"
          },
          {
            "name": "Parent Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "418e31e4-70d1-4f4a-8bcc-46e1ffa750d6",
            "sourceColumn": "Parent Manager",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4de867a4-b16a-42c7-87c4-5db407b6708e",
        "partitions": [
          {
            "name": "Assigned Prim Managers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(#\"Data Source\", [HierarchicalNavigation=true, Query=\"-- The following logic pulls historical Primary Manager assignment data based on the Primary Entity on the prospect record.#(lf)--   This also pulls only the current and previous four FYs. This was written initially for the Current Parent Dashboard. smk 8/11/2023#(lf)-- Updated to use the fiscal year view. smk 09/19/2023#(lf)-- Updated to add the \"\"Parent Mgr\"\" and sort fields. smk 9/27/2023#(lf)#(lf)WITH managers AS (#(lf)SELECT DISTINCT hk.HOUSEHOLD_KEY     HH_Key,#(lf)       hk.HOUSEHOLD_KEY||to_char((select * from advur.vw_current_fiscal_year)-4) ComboKey,#(lf)       hk.member_count               Par_Cnt,#(lf)       CASE WHEN s.id_number = '0000083442' THEN 'Mrs. Judith Richmeier Pritza, APRN'#(lf)            WHEN s.id_number = '0000040131' THEN 'Mrs. Diane Glow'#(lf)          ELSE 'All Others' END      Parent_Mgr,#(lf)       s.id_number                   PM_ID,#(lf)       s.name                        PM_Name,#(lf)       pe.id_number                  Assnd_EntID,#(lf)       pe.prospect_id                Prospect_ID,#(lf)       s.unit_code                   PM_Unit_Cd,#(lf)       CASE WHEN s.unit_code IN ('DEV', 'SG') THEN 'Frontline'#(lf)            WHEN s.unit_code = 'ATH' THEN 'Athletics Development'#(lf)            WHEN s.unit_code = 'TRF' THEN 'Principal Gifts'#(lf)            WHEN s.unit_code = 'ARO' THEN 'Alumni Relations'#(lf)          ELSE s.unit_code END       Team_Name,#(lf)-- The next line calculates a Start Date based on the Date Added if there is no Start Date#(lf)       NVL(trunc(assn.start_date), TRUNC(assn.date_added)) start_date,#(lf)       EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6)) start_yr,#(lf)       trunc(assn.stop_date)         real_stop_date,#(lf)-- The next line calculates a Stop Year based on the Start Year plus 4 years if there is no Stop Date#(lf)       nvl(EXTRACT(YEAR FROM add_months(trunc(assn.stop_date),6)),#(lf)                        EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))+4) stop_yr,#(lf)       to_char((select * from advur.vw_current_fiscal_year)-4) qual_yr,#(lf)       CASE WHEN s.unit_code IN ('DEV', 'SG') THEN '200'#(lf)            WHEN s.unit_code = 'ATH' THEN '300'#(lf)            WHEN s.unit_code = 'TRF' THEN '100'#(lf)            WHEN s.unit_code = 'ARO' THEN '400'#(lf)          ELSE '500' END             sort_team,#(lf)       s.sort                        sort_mgr,#(lf)       e.last_name                   sort_assgnd#(lf)FROM advance.assignment assn#(lf)INNER JOIN advance.staff s                ON s.id_number = assn.assignment_id_number#(lf)INNER JOIN advance.prospect_entity pe     ON pe.prospect_id = assn.prospect_id#(lf)INNER JOIN advance.entity e               ON pe.id_number = e.id_number#(lf)INNER JOIN advur.VW_ENT_HOUSEHOLD_KEYS hk ON pe.ID_NUMBER = hk.ID_NUMBER #(lf)WHERE assn.assignment_type = 'PM' #(lf)AND   pe.primary_ind = 'Y'#(lf)AND   trunc(assn.date_added) <> '04-FEB-1999'#(lf)AND   ((s.unit_code IN ('DEV', 'SG', 'ATH', 'TRF')#(lf)AND     s.staff_type_code IN ('GO','MO','SR')) OR#(lf)        s.unit_code = 'ARO')#(lf)and   to_char((select * from advur.vw_current_fiscal_year)-4) BETWEEN EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))#(lf)                                                              AND nvl(EXTRACT(YEAR FROM add_months(trunc(assn.stop_date),6)),#(lf)                                                              EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))+4)#(lf)UNION ALL#(lf)SELECT DISTINCT hk.HOUSEHOLD_KEY     HH_Key,#(lf)       hk.HOUSEHOLD_KEY||to_char((select * from advur.vw_current_fiscal_year)-3) ComboKey,#(lf)       hk.member_count               Par_Cnt,#(lf)       CASE WHEN s.id_number = '0000083442' THEN 'Mrs. Judith Richmeier Pritza, APRN'#(lf)            WHEN s.id_number = '0000040131' THEN 'Mrs. Diane Glow'#(lf)          ELSE 'All Others' END      Parent_Mgr,#(lf)       s.id_number                   PM_ID,#(lf)       s.name                        PM_Name,#(lf)       pe.id_number                  Assnd_EntID,#(lf)       pe.prospect_id                Prospect_ID,#(lf)       s.unit_code                   PM_Unit_Cd,#(lf)       CASE WHEN s.unit_code IN ('DEV', 'SG') THEN 'Frontline'#(lf)            WHEN s.unit_code = 'ATH' THEN 'Athletics Development'#(lf)            WHEN s.unit_code = 'TRF' THEN 'Principal Gifts'#(lf)            WHEN s.unit_code = 'ARO' THEN 'Alumni Relations'#(lf)          ELSE s.unit_code END       Team_Name,#(lf)-- The next line calculates a Start Date based on the Date Added if there is no Start Date#(lf)       NVL(trunc(assn.start_date), TRUNC(assn.date_added)) start_date,#(lf)       EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6)) start_yr,#(lf)       trunc(assn.stop_date) real_stop_date,#(lf)-- The next line calculates a Stop Year based on the Start Year plus 4 years if there is no Stop Date#(lf)       nvl(EXTRACT(YEAR FROM add_months(trunc(assn.stop_date),6)),#(lf)                        EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))+4) stop_yr,#(lf)       to_char((select * from advur.vw_current_fiscal_year)-3) qual_yr,#(lf)       CASE WHEN s.unit_code IN ('DEV', 'SG') THEN '200'#(lf)            WHEN s.unit_code = 'ATH' THEN '300'#(lf)            WHEN s.unit_code = 'TRF' THEN '100'#(lf)            WHEN s.unit_code = 'ARO' THEN '400'#(lf)          ELSE '500' END             sort_team,#(lf)       s.sort                        sort_mgr,#(lf)       e.last_name                   sort_assgnd#(lf)FROM advance.assignment assn#(lf)INNER JOIN advance.staff s                ON s.id_number = assn.assignment_id_number#(lf)INNER JOIN advance.prospect_entity pe     ON pe.prospect_id = assn.prospect_id#(lf)INNER JOIN advance.entity e               ON pe.id_number = e.id_number#(lf)INNER JOIN advur.VW_ENT_HOUSEHOLD_KEYS hk ON pe.ID_NUMBER = hk.ID_NUMBER #(lf)WHERE assn.assignment_type = 'PM' #(lf)AND   pe.primary_ind = 'Y'#(lf)AND   trunc(assn.date_added) <> '04-FEB-1999'#(lf)AND   ((s.unit_code IN ('DEV', 'SG', 'ATH', 'TRF')#(lf)AND     s.staff_type_code IN ('GO','MO','SR')) OR#(lf)        s.unit_code = 'ARO')#(lf)and   to_char((select * from advur.vw_current_fiscal_year)-3) BETWEEN EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))#(lf)                                                              AND nvl(EXTRACT(YEAR FROM add_months(trunc(assn.stop_date),6)),#(lf)                                                              EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))+4)#(lf)UNION ALL#(lf)SELECT DISTINCT hk.HOUSEHOLD_KEY     HH_Key,#(lf)       hk.HOUSEHOLD_KEY||to_char((select * from advur.vw_current_fiscal_year)-2) ComboKey,#(lf)       hk.member_count               Par_Cnt,#(lf)       CASE WHEN s.id_number = '0000083442' THEN 'Mrs. Judith Richmeier Pritza, APRN'#(lf)            WHEN s.id_number = '0000040131' THEN 'Mrs. Diane Glow'#(lf)          ELSE 'All Others' END      Parent_Mgr,#(lf)       s.id_number                   PM_ID,#(lf)       s.name                        PM_Name,#(lf)       pe.id_number                  Assnd_EntID,#(lf)       pe.prospect_id                Prospect_ID,#(lf)       s.unit_code                   PM_Unit_Cd,#(lf)       CASE WHEN s.unit_code IN ('DEV', 'SG') THEN 'Frontline'#(lf)            WHEN s.unit_code = 'ATH' THEN 'Athletics Development'#(lf)            WHEN s.unit_code = 'TRF' THEN 'Principal Gifts'#(lf)            WHEN s.unit_code = 'ARO' THEN 'Alumni Relations'#(lf)          ELSE s.unit_code END       Team_Name,#(lf)-- The next line calculates a Start Date based on the Date Added if there is no Start Date#(lf)       NVL(trunc(assn.start_date), TRUNC(assn.date_added)) start_date,#(lf)       EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6)) start_yr,#(lf)       trunc(assn.stop_date) real_stop_date,#(lf)-- The next line calculates a Stop Year based on the Start Year plus 4 years if there is no Stop Date#(lf)       nvl(EXTRACT(YEAR FROM add_months(trunc(assn.stop_date),6)),#(lf)                        EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))+4) stop_yr,#(lf)       to_char((select * from advur.vw_current_fiscal_year)-2) qual_yr,#(lf)       CASE WHEN s.unit_code IN ('DEV', 'SG') THEN '200'#(lf)            WHEN s.unit_code = 'ATH' THEN '300'#(lf)            WHEN s.unit_code = 'TRF' THEN '100'#(lf)            WHEN s.unit_code = 'ARO' THEN '400'#(lf)          ELSE '500' END             sort_team,#(lf)       s.sort                        sort_mgr,#(lf)       e.last_name                   sort_assgnd#(lf)FROM advance.assignment assn#(lf)INNER JOIN advance.staff s                ON s.id_number = assn.assignment_id_number#(lf)INNER JOIN advance.prospect_entity pe     ON pe.prospect_id = assn.prospect_id#(lf)INNER JOIN advance.entity e               ON pe.id_number = e.id_number#(lf)INNER JOIN advur.VW_ENT_HOUSEHOLD_KEYS hk ON pe.ID_NUMBER = hk.ID_NUMBER #(lf)WHERE assn.assignment_type = 'PM' #(lf)AND   pe.primary_ind = 'Y'#(lf)AND   trunc(assn.date_added) <> '04-FEB-1999'#(lf)AND   ((s.unit_code IN ('DEV', 'SG', 'ATH', 'TRF')#(lf)AND     s.staff_type_code IN ('GO','MO','SR')) OR#(lf)        s.unit_code = 'ARO')#(lf)and   to_char((select * from advur.vw_current_fiscal_year)-2) BETWEEN EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))#(lf)                                                              AND nvl(EXTRACT(YEAR FROM add_months(trunc(assn.stop_date),6)),#(lf)                                                              EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))+4)#(lf)UNION ALL#(lf)SELECT DISTINCT hk.HOUSEHOLD_KEY     HH_Key,#(lf)       hk.HOUSEHOLD_KEY||to_char((select * from advur.vw_current_fiscal_year)-1) ComboKey,#(lf)       hk.member_count               Par_Cnt,#(lf)       CASE WHEN s.id_number = '0000083442' THEN 'Mrs. Judith Richmeier Pritza, APRN'#(lf)            WHEN s.id_number = '0000040131' THEN 'Mrs. Diane Glow'#(lf)          ELSE 'All Others' END      Parent_Mgr,#(lf)       s.id_number                   PM_ID,#(lf)       s.name                        PM_Name,#(lf)       pe.id_number                  Assnd_EntID,#(lf)       pe.prospect_id                Prospect_ID,#(lf)       s.unit_code                   PM_Unit_Cd,#(lf)       CASE WHEN s.unit_code IN ('DEV', 'SG') THEN 'Frontline'#(lf)            WHEN s.unit_code = 'ATH' THEN 'Athletics Development'#(lf)            WHEN s.unit_code = 'TRF' THEN 'Principal Gifts'#(lf)            WHEN s.unit_code = 'ARO' THEN 'Alumni Relations'#(lf)          ELSE s.unit_code END       Team_Name,#(lf)-- The next line calculates a Start Date based on the Date Added if there is no Start Date#(lf)       NVL(trunc(assn.start_date), TRUNC(assn.date_added)) start_date,#(lf)       EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6)) start_yr,#(lf)       trunc(assn.stop_date) real_stop_date,#(lf)-- The next line calculates a Stop Year based on the Start Year plus 4 years if there is no Stop Date#(lf)       nvl(EXTRACT(YEAR FROM add_months(trunc(assn.stop_date),6)),#(lf)                        EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))+4) stop_yr,#(lf)       to_char((select * from advur.vw_current_fiscal_year)-1) qual_yr,#(lf)       CASE WHEN s.unit_code IN ('DEV', 'SG') THEN '200'#(lf)            WHEN s.unit_code = 'ATH' THEN '300'#(lf)            WHEN s.unit_code = 'TRF' THEN '100'#(lf)            WHEN s.unit_code = 'ARO' THEN '400'#(lf)          ELSE '500' END             sort_team,#(lf)       s.sort                        sort_mgr,#(lf)       e.last_name                   sort_assgnd#(lf)FROM advance.assignment assn#(lf)INNER JOIN advance.staff s                ON s.id_number = assn.assignment_id_number#(lf)INNER JOIN advance.prospect_entity pe     ON pe.prospect_id = assn.prospect_id#(lf)INNER JOIN advance.entity e               ON pe.id_number = e.id_number#(lf)INNER JOIN advur.VW_ENT_HOUSEHOLD_KEYS hk ON pe.ID_NUMBER = hk.ID_NUMBER #(lf)WHERE assn.assignment_type = 'PM' #(lf)AND   pe.primary_ind = 'Y'#(lf)AND   trunc(assn.date_added) <> '04-FEB-1999'#(lf)AND   ((s.unit_code IN ('DEV', 'SG', 'ATH', 'TRF')#(lf)AND     s.staff_type_code IN ('GO','MO','SR')) OR#(lf)        s.unit_code = 'ARO')#(lf)and   to_char((select * from advur.vw_current_fiscal_year)-1) BETWEEN EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))#(lf)                                                              AND nvl(EXTRACT(YEAR FROM add_months(trunc(assn.stop_date),6)),#(lf)                                                              EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))+4)#(lf)UNION ALL#(lf)SELECT DISTINCT hk.HOUSEHOLD_KEY     HH_Key,#(lf)       hk.HOUSEHOLD_KEY||to_char((select * from advur.vw_current_fiscal_year)) ComboKey,#(lf)       hk.member_count               Par_Cnt,#(lf)       CASE WHEN s.id_number = '0000083442' THEN 'Mrs. Judith Richmeier Pritza, APRN'#(lf)            WHEN s.id_number = '0000040131' THEN 'Mrs. Diane Glow'#(lf)          ELSE 'All Others' END      Parent_Mgr,#(lf)       s.id_number                   PM_ID,#(lf)       s.name                        PM_Name,#(lf)       pe.id_number                  Assnd_EntID,#(lf)       pe.prospect_id                Prospect_ID,#(lf)       s.unit_code                   PM_Unit_Cd,#(lf)       CASE WHEN s.unit_code IN ('DEV', 'SG') THEN 'Frontline'#(lf)            WHEN s.unit_code = 'ATH' THEN 'Athletics Development'#(lf)            WHEN s.unit_code = 'TRF' THEN 'Principal Gifts'#(lf)            WHEN s.unit_code = 'ARO' THEN 'Alumni Relations'#(lf)          ELSE s.unit_code END       Team_Name,#(lf)-- The next line calculates a Start Date based on the Date Added if there is no Start Date#(lf)       NVL(trunc(assn.start_date), TRUNC(assn.date_added)) start_date,#(lf)       EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6)) start_yr,#(lf)       trunc(assn.stop_date) real_stop_date,#(lf)-- The next line calculates a Stop Year based on the Start Year plus 4 years if there is no Stop Date#(lf)       nvl(EXTRACT(YEAR FROM add_months(trunc(assn.stop_date),6)),#(lf)                        EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))+4) stop_yr,#(lf)       to_char((select * from advur.vw_current_fiscal_year)) qual_yr,#(lf)       CASE WHEN s.unit_code IN ('DEV', 'SG') THEN '200'#(lf)            WHEN s.unit_code = 'ATH' THEN '300'#(lf)            WHEN s.unit_code = 'TRF' THEN '100'#(lf)            WHEN s.unit_code = 'ARO' THEN '400'#(lf)          ELSE '500' END             sort_team,#(lf)       s.sort                        sort_mgr,#(lf)       e.last_name                   sort_assgnd#(lf)FROM advance.assignment assn#(lf)INNER JOIN advance.staff s                ON s.id_number = assn.assignment_id_number#(lf)INNER JOIN advance.prospect_entity pe     ON pe.prospect_id = assn.prospect_id#(lf)INNER JOIN advance.entity e               ON pe.id_number = e.id_number#(lf)INNER JOIN advur.VW_ENT_HOUSEHOLD_KEYS hk ON pe.ID_NUMBER = hk.ID_NUMBER#(lf)WHERE assn.assignment_type = 'PM' #(lf)AND   pe.primary_ind = 'Y'#(lf)AND   trunc(assn.date_added) <> '04-FEB-1999'#(lf)AND   ((s.unit_code IN ('DEV', 'SG', 'ATH', 'TRF')#(lf)AND     s.staff_type_code IN ('GO','MO','SR')) OR#(lf)        s.unit_code = 'ARO')#(lf)and   to_char((select * from advur.vw_current_fiscal_year)) BETWEEN EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))#(lf)                                                            AND nvl(EXTRACT(YEAR FROM add_months(trunc(assn.stop_date),6)),#(lf)                                                            EXTRACT(YEAR FROM add_months(NVL(trunc(assn.start_date), TRUNC(assn.date_added)),6))+4)#(lf) )#(lf)#(lf)select pm.Team_Name              \"\"Mgr Team\"\",#(lf)       pm.PM_ID                  \"\"PM_ID\"\",#(lf)       pm.PM_Name                \"\"Prim Mgr Name\"\",#(lf)       pm.Parent_Mgr             \"\"Parent Manager\"\",#(lf)       pm.HH_Key                 \"\"HH Key\"\",#(lf)       pm.ComboKey               \"\"ComboKey\"\",#(lf)       pm.qual_yr                \"\"Fiscal Yr\"\",#(lf)       pm.Par_Cnt                \"\"Par Count\"\",#(lf)       pm.Assnd_EntID            \"\"Parent ID\"\",#(lf)       pm.Prospect_ID            \"\"Prospect ID\"\",#(lf)       pm.start_date             \"\"Start Dt\"\",#(lf)       pm.start_yr               \"\"Start Yr\"\",#(lf)       pm.real_stop_date         \"\"Stop Date\"\",#(lf)       pm.stop_yr                \"\"Stop Yr\"\",#(lf)       CASE WHEN pm.PM_ID = '0000083442' THEN '075'||pm.sort_assgnd#(lf)            WHEN pm.PM_ID = '0000040131' THEN '050'||pm.sort_assgnd#(lf)          ELSE pm.sort_team||pm.sort_mgr||pm.sort_assgnd END  \"\"Main Sort\"\",#(lf)       pm.sort_team              \"\"Sort Team\"\",#(lf)       pm.sort_mgr               \"\"Sort Mgr\"\"#(lf)from managers pm#(lf)where pm.Par_Cnt > 0#(lf)#(lf)order by \"\"Main Sort\"\"\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Fiscal Yr\", type text}, {\"Start Dt\", type date}, {\"Start Yr\", type text}, {\"Stop Date\", type date}, {\"Stop Yr\", type text}, {\"Par Count\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fac-Staff (Primary)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "F/S ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "083593d8-1b81-4d28-9e4a-6cd820200326",
            "sourceColumn": "F/S ID",
            "summarizeBy": "none"
          },
          {
            "name": "Fac-Staff Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c15a0ef1-a2c3-4e02-acab-530185d75450",
            "sourceColumn": "Fac-Staff Name",
            "summarizeBy": "none"
          },
          {
            "name": "Inst Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39cd93b2-47ac-4169-b365-b72ee3903e3b",
            "sourceColumn": "Inst Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "Record Types",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03837915-a726-4a6b-ba33-930d92a3dfe4",
            "sourceColumn": "Record Types",
            "summarizeBy": "none"
          },
          {
            "name": "Job Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b729d342-ffe3-464d-9aac-2d564262a3e4",
            "sourceColumn": "Job Title",
            "summarizeBy": "none"
          },
          {
            "name": "School/College/Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a29861e3-26b6-4465-94e7-64f6d2218c41",
            "sourceColumn": "School/College/Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1272f148-ad75-4ba7-a1f5-e5ec3789e0bc",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Pos Lvl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b33a4c9-f452-4b78-8a9a-610edc371150",
            "sourceColumn": "Pos Lvl",
            "summarizeBy": "none"
          },
          {
            "name": "Start Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b724c8e0-ce72-47f8-9523-fe85ec8df86e",
            "sourceColumn": "Start Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Stop Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8c19f52-6837-4073-8f53-ea8f012aa0f2",
            "sourceColumn": "Stop Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eac3a327-2f7d-49a0-bab2-38df46f4a44e",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "ComboIDKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e922b79d-1351-495c-a0e8-b2ab0c042908",
            "sourceColumn": "ComboIDKey",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e80b3cc-2fa9-4523-bb9a-bcebf414d21b",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Start Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "320a4766-09b6-4410-a6c9-ecab3d3fae1d",
            "sourceColumn": "Start Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Stop Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f734ede-2ae1-41b3-8952-6916ebd4a5f5",
            "sourceColumn": "Stop Yr",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "05daeffc-66c4-4c0e-9405-298f67d892f7",
        "partitions": [
          {
            "name": "Fac-Staff (Primary)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(#\"Data Source\", [HierarchicalNavigation=true, Query=\"-- Query written to pull Faculty-Staff data for the current and previous four fiscal years... each person is pulled for a given FY based solely on their #(lf)--   Start and Stop Dates. People who are missing a Start Date and those who are past employees who are missing a Stop Date are excluded from this pull.#(lf)--   Anyone missing part of a date (MM, DD or YYYY) are also excluded as we cannot determine a year from a partial date. smk 9/1/2023#(lf)-- Updated to use the fiscal year view so it works against the Snapshots. smk 9/26/2023#(lf)#(lf)select distinct mp.id_number                                             \"\"F/S ID\"\",#(lf)       'Active'                                                          \"\"Status\"\",#(lf)       mp.id_number||to_char((select * from advur.vw_current_fiscal_year))  \"\"ComboIDKey\"\",#(lf)       e.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e.id_number)                         \"\"Record Types\"\",#(lf)       mp.job_title                                                      \"\"Job Title\"\",#(lf)       pow.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp.employer_unit                                                  \"\"Department\"\",#(lf)       pl.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year))             \"\"Year\"\",#(lf)       to_date(mp.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                              \"\"Stop Dt\"\",#(lf)       NULL                                                              \"\"Stop Yr\"\"#(lf) from advance.employment mp#(lf)inner join advance.entity e              ON mp.id_number = e.id_number#(lf) left join advance.tms_place_of_work pow ON mp.place_of_work_code = pow.place_of_work_code#(lf) left join advance.tms_position_level pl ON mp.position_level_code = pl.position_level_code#(lf)where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year))#(lf)UNION ALL#(lf)-- Current FY Inactive#(lf)select distinct mp2.id_number                                             \"\"F/S ID\"\",#(lf)       'Inactive'                                                         \"\"Status\"\",#(lf)       mp2.id_number||to_char((select * from advur.vw_current_fiscal_year))  \"\"ComboIDKey\"\",#(lf)       e2.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e2.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e2.id_number)                         \"\"Record Types\"\",#(lf)       mp2.job_title                                                      \"\"Job Title\"\",#(lf)       pow2.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp2.employer_unit                                                  \"\"Department\"\",#(lf)       pl2.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year))              \"\"Year\"\",#(lf)       to_date(mp2.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                               \"\"Stop Dt\"\",#(lf)       NULL                                                               \"\"Stop Yr\"\"#(lf) from advance.employment mp2#(lf)inner join advance.entity e2              ON mp2.id_number = e2.id_number#(lf) left join advance.tms_place_of_work pow2 ON mp2.place_of_work_code = pow2.place_of_work_code#(lf) left join advance.tms_position_level pl2 ON mp2.position_level_code = pl2.position_level_code#(lf)where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)and   substr(mp2.stop_dt,7,2) <> '00'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year))#(lf)and   (mp2.stop_dt = '00000000' OR #(lf)      EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)))#(lf)UNION ALL#(lf)-- Current FY - 1 Active#(lf)select distinct mp.id_number                                             \"\"F/S ID\"\",#(lf)       'Active'                                                          \"\"Status\"\",#(lf)       mp.id_number||to_char((select * from advur.vw_current_fiscal_year)-1)    \"\"ComboIDKey\"\",#(lf)       e.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e.id_number)                         \"\"Record Types\"\",#(lf)       mp.job_title                                                      \"\"Job Title\"\",#(lf)       pow.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp.employer_unit                                                  \"\"Department\"\",#(lf)       pl.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-1)           \"\"Year\"\",#(lf)       to_date(mp.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                              \"\"Stop Dt\"\",#(lf)       NULL                                                              \"\"Stop Yr\"\"#(lf) from advance.employment mp#(lf)inner join advance.entity e              ON mp.id_number = e.id_number#(lf) left join advance.tms_place_of_work pow ON mp.place_of_work_code = pow.place_of_work_code#(lf) left join advance.tms_position_level pl ON mp.position_level_code = pl.position_level_code#(lf)where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-1)#(lf)UNION ALL#(lf)-- Current FY - 1 Inactive#(lf)select distinct mp2.id_number                                             \"\"F/S ID\"\",#(lf)       'Inactive'                                                         \"\"Status\"\",#(lf)       mp2.id_number||to_char((select * from advur.vw_current_fiscal_year)-1)    \"\"ComboIDKey\"\",#(lf)       e2.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e2.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e2.id_number)                         \"\"Record Types\"\",#(lf)       mp2.job_title                                                      \"\"Job Title\"\",#(lf)       pow2.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp2.employer_unit                                                  \"\"Department\"\",#(lf)       pl2.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-1)            \"\"Year\"\",#(lf)       to_date(mp2.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                               \"\"Stop Dt\"\",#(lf)       NULL                                                               \"\"Stop Yr\"\"#(lf) from advance.employment mp2#(lf)inner join advance.entity e2              ON mp2.id_number = e2.id_number#(lf) left join advance.tms_place_of_work pow2 ON mp2.place_of_work_code = pow2.place_of_work_code#(lf) left join advance.tms_position_level pl2 ON mp2.position_level_code = pl2.position_level_code#(lf)where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)and   substr(mp2.stop_dt,7,2) <> '00'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-1)#(lf)and   (mp2.stop_dt = '00000000' OR #(lf)      EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)-1))#(lf)UNION ALL#(lf)-- Current FY - 2 Active#(lf)select distinct mp.id_number                                             \"\"F/S ID\"\",#(lf)       'Active'                                                          status,#(lf)       mp.id_number||to_char((select * from advur.vw_current_fiscal_year)-2)    \"\"ComboIDKey\"\",#(lf)       e.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e.id_number)                         \"\"Record Types\"\",#(lf)       mp.job_title                                                      \"\"Job Title\"\",#(lf)       pow.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp.employer_unit                                                  \"\"Department\"\",#(lf)       pl.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-2)           \"\"Year\"\",#(lf)       to_date(mp.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                              \"\"Stop Dt\"\",#(lf)       NULL                                                              \"\"Stop Yr\"\"#(lf) from advance.employment mp#(lf)inner join advance.entity e              ON mp.id_number = e.id_number#(lf) left join advance.tms_place_of_work pow ON mp.place_of_work_code = pow.place_of_work_code#(lf) left join advance.tms_position_level pl ON mp.position_level_code = pl.position_level_code#(lf)where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-2)#(lf)UNION ALL#(lf)-- Current FY - 2 Inactive#(lf)select distinct mp2.id_number                                             \"\"F/S ID\"\",#(lf)       'Inactive'                                                         \"\"Status\"\",#(lf)       mp2.id_number||to_char((select * from advur.vw_current_fiscal_year)-2)    \"\"ComboIDKey\"\",#(lf)       e2.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e2.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e2.id_number)                         \"\"Record Types\"\",#(lf)       mp2.job_title                                                      \"\"Job Title\"\",#(lf)       pow2.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp2.employer_unit                                                  \"\"Department\"\",#(lf)       pl2.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-2)            \"\"Year\"\",#(lf)       to_date(mp2.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                               \"\"Stop Dt\"\",#(lf)       NULL                                                               \"\"Stop Yr\"\"#(lf) from advance.employment mp2#(lf)inner join advance.entity e2              ON mp2.id_number = e2.id_number#(lf) left join advance.tms_place_of_work pow2 ON mp2.place_of_work_code = pow2.place_of_work_code#(lf) left join advance.tms_position_level pl2 ON mp2.position_level_code = pl2.position_level_code#(lf)where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)and   substr(mp2.stop_dt,7,2) <> '00'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-2)#(lf)and   (mp2.stop_dt = '00000000' OR #(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)-2))#(lf)UNION ALL#(lf)-- Current FY - 3 Active#(lf)select distinct mp.id_number                                             \"\"F/S ID\"\",#(lf)       'Active'                                                          status,#(lf)       mp.id_number||to_char((select * from advur.vw_current_fiscal_year)-3)    \"\"ComboIDKey\"\",#(lf)       e.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e.id_number)                         \"\"Record Types\"\",#(lf)       mp.job_title                                                      \"\"Job Title\"\",#(lf)       pow.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp.employer_unit                                                  \"\"Department\"\",#(lf)       pl.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-3)             \"\"Year\"\",#(lf)       to_date(mp.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                              \"\"Stop Dt\"\",#(lf)       NULL                                                              \"\"Stop Yr\"\"#(lf) from advance.employment mp#(lf)inner join advance.entity e              ON mp.id_number = e.id_number#(lf) left join advance.tms_place_of_work pow ON mp.place_of_work_code = pow.place_of_work_code#(lf) left join advance.tms_position_level pl ON mp.position_level_code = pl.position_level_code#(lf)where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-3)#(lf)UNION ALL#(lf)-- Current FY - 3 Inactive#(lf)select distinct mp2.id_number                                             \"\"F/S ID\"\",#(lf)       'Inactive'                                                         \"\"Status\"\",#(lf)       mp2.id_number||to_char((select * from advur.vw_current_fiscal_year)-3)    \"\"ComboIDKey\"\",#(lf)       e2.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e2.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e2.id_number)                         \"\"Record Types\"\",#(lf)       mp2.job_title                                                      \"\"Job Title\"\",#(lf)       pow2.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp2.employer_unit                                                  \"\"Department\"\",#(lf)       pl2.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-3)            \"\"Year\"\",#(lf)       to_date(mp2.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                               \"\"Stop Dt\"\",#(lf)       NULL                                                               \"\"Stop Yr\"\"#(lf) from advance.employment mp2#(lf)inner join advance.entity e2              ON mp2.id_number = e2.id_number#(lf) left join advance.tms_place_of_work pow2 ON mp2.place_of_work_code = pow2.place_of_work_code#(lf) left join advance.tms_position_level pl2 ON mp2.position_level_code = pl2.position_level_code#(lf)where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)and   substr(mp2.stop_dt,7,2) <> '00'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-3)#(lf)and   (mp2.stop_dt = '00000000' OR #(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)-3))#(lf)UNION ALL#(lf)-- Current FY - 4 Active#(lf)select distinct mp.id_number                                             \"\"F/S ID\"\",#(lf)       'Active'                                                          status,#(lf)       mp.id_number||to_char((select * from advur.vw_current_fiscal_year)-4)    \"\"ComboIDKey\"\",#(lf)       e.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e.id_number)                         \"\"Record Types\"\",#(lf)       mp.job_title                                                      \"\"Job Title\"\",#(lf)       pow.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp.employer_unit                                                  \"\"Department\"\",#(lf)       pl.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-4)           \"\"Year\"\",#(lf)       to_date(mp.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                              \"\"Stop Dt\"\",#(lf)       NULL                                                              \"\"Stop Yr\"\"#(lf) from advance.employment mp#(lf)inner join advance.entity e              ON mp.id_number = e.id_number#(lf) left join advance.tms_place_of_work pow ON mp.place_of_work_code = pow.place_of_work_code#(lf) left join advance.tms_position_level pl ON mp.position_level_code = pl.position_level_code#(lf)where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-4)#(lf)UNION ALL#(lf)-- Current FY - 4 Inactive#(lf)select distinct mp2.id_number                                             \"\"F/S ID\"\",#(lf)       'Inactive'                                                         \"\"Status\"\",#(lf)       mp2.id_number||to_char((select * from advur.vw_current_fiscal_year)-4)    \"\"ComboIDKey\"\",#(lf)       e2.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e2.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e2.id_number)                         \"\"Record Types\"\",#(lf)       mp2.job_title                                                      \"\"Job Title\"\",#(lf)       pow2.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp2.employer_unit                                                  \"\"Department\"\",#(lf)       pl2.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-4)            \"\"Year\"\",#(lf)       to_date(mp2.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                               \"\"Stop Dt\"\",#(lf)       NULL                                                               \"\"Stop Yr\"\"#(lf) from advance.employment mp2#(lf)inner join advance.entity e2              ON mp2.id_number = e2.id_number#(lf) left join advance.tms_place_of_work pow2 ON mp2.place_of_work_code = pow2.place_of_work_code#(lf) left join advance.tms_position_level pl2 ON mp2.position_level_code = pl2.position_level_code#(lf)where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)and   substr(mp2.stop_dt,7,2) <> '00'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-4)#(lf)and   (mp2.stop_dt = '00000000' OR #(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)-4))#(lf)order by \"\"F/S ID\"\", \"\"Year\"\"\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Year\", type text}, {\"Start Dt\", type date}, {\"Start Yr\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fac-Staff (Spouse)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "F/S ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "713f508e-bd0e-4c1c-8794-c3b1a7a26534",
            "sourceColumn": "F/S ID",
            "summarizeBy": "none"
          },
          {
            "name": "Fac-Staff Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b961ef07-632b-4a47-a063-221d260a5b81",
            "sourceColumn": "Fac-Staff Name",
            "summarizeBy": "none"
          },
          {
            "name": "Inst Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80da22c9-6ac4-494f-bd5e-340cff1d878a",
            "sourceColumn": "Inst Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "Record Types",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1556c4c9-0f67-4176-968c-9ae414fd3102",
            "sourceColumn": "Record Types",
            "summarizeBy": "none"
          },
          {
            "name": "Job Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8d33f5f-8967-4660-a60c-5959069ec09a",
            "sourceColumn": "Job Title",
            "summarizeBy": "none"
          },
          {
            "name": "School/College/Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3732954e-0b19-4bf6-91ca-bcf25dbb2355",
            "sourceColumn": "School/College/Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d614d434-155f-447f-8502-b63970d43131",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Pos Lvl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "768d2db1-feb6-45e1-a140-fab59c42f7d2",
            "sourceColumn": "Pos Lvl",
            "summarizeBy": "none"
          },
          {
            "name": "Start Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "387ba6e5-e363-43b6-bd3c-d3a4d49fd891",
            "sourceColumn": "Start Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Stop Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a66ea93a-715c-4899-8068-51d66c6de8eb",
            "sourceColumn": "Stop Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6630915-ea09-4351-9cc1-0fdc52c0bc92",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "ComboIDKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5db72458-f1e7-4e85-8aec-fede094cc986",
            "sourceColumn": "ComboIDKey",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ec35f29-c2b8-4c87-a13f-7617124ea74e",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Start Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e0644d7-0dae-4f00-af3c-da27882eb105",
            "sourceColumn": "Start Yr",
            "summarizeBy": "none"
          },
          {
            "name": "Stop Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3dcfea59-b5ec-41d6-baf8-f7ab7d5515c7",
            "sourceColumn": "Stop Yr",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "66a7916f-4880-4b68-b6ee-74da3112fb7c",
        "partitions": [
          {
            "name": "Fac-Staff (Spouse)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(#\"Data Source\", [HierarchicalNavigation=true, Query=\"-- Query written to pull Faculty-Staff data for the current and previous four fiscal years... each person is pulled for a given FY based solely on their #(lf)--   Start and Stop Dates. People who are missing a Start Date and those who are past employees who are missing a Stop Date are excluded from this pull.#(lf)--   Anyone missing part of a date (MM, DD or YYYY) are also excluded as we cannot determine a year from a partial date. smk 9/1/2023#(lf)-- Updated to use the fiscal year view so it works against the Snapshots. smk 9/26/2023#(lf)#(lf)select distinct mp.id_number                                             \"\"F/S ID\"\",#(lf)       'Active'                                                          \"\"Status\"\",#(lf)       mp.id_number||to_char((select * from advur.vw_current_fiscal_year))  \"\"ComboIDKey\"\",#(lf)       e.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e.id_number)                         \"\"Record Types\"\",#(lf)       mp.job_title                                                      \"\"Job Title\"\",#(lf)       pow.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp.employer_unit                                                  \"\"Department\"\",#(lf)       pl.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year))             \"\"Year\"\",#(lf)       to_date(mp.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                              \"\"Stop Dt\"\",#(lf)       NULL                                                              \"\"Stop Yr\"\"#(lf) from advance.employment mp#(lf)inner join advance.entity e              ON mp.id_number = e.id_number#(lf) left join advance.tms_place_of_work pow ON mp.place_of_work_code = pow.place_of_work_code#(lf) left join advance.tms_position_level pl ON mp.position_level_code = pl.position_level_code#(lf)where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year))#(lf)UNION ALL#(lf)-- Current FY Inactive#(lf)select distinct mp2.id_number                                             \"\"F/S ID\"\",#(lf)       'Inactive'                                                         \"\"Status\"\",#(lf)       mp2.id_number||to_char((select * from advur.vw_current_fiscal_year))  \"\"ComboIDKey\"\",#(lf)       e2.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e2.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e2.id_number)                         \"\"Record Types\"\",#(lf)       mp2.job_title                                                      \"\"Job Title\"\",#(lf)       pow2.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp2.employer_unit                                                  \"\"Department\"\",#(lf)       pl2.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year))              \"\"Year\"\",#(lf)       to_date(mp2.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                               \"\"Stop Dt\"\",#(lf)       NULL                                                               \"\"Stop Yr\"\"#(lf) from advance.employment mp2#(lf)inner join advance.entity e2              ON mp2.id_number = e2.id_number#(lf) left join advance.tms_place_of_work pow2 ON mp2.place_of_work_code = pow2.place_of_work_code#(lf) left join advance.tms_position_level pl2 ON mp2.position_level_code = pl2.position_level_code#(lf)where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)and   substr(mp2.stop_dt,7,2) <> '00'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year))#(lf)and   (mp2.stop_dt = '00000000' OR #(lf)      EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)))#(lf)UNION ALL#(lf)-- Current FY - 1 Active#(lf)select distinct mp.id_number                                             \"\"F/S ID\"\",#(lf)       'Active'                                                          \"\"Status\"\",#(lf)       mp.id_number||to_char((select * from advur.vw_current_fiscal_year)-1)    \"\"ComboIDKey\"\",#(lf)       e.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e.id_number)                         \"\"Record Types\"\",#(lf)       mp.job_title                                                      \"\"Job Title\"\",#(lf)       pow.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp.employer_unit                                                  \"\"Department\"\",#(lf)       pl.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-1)           \"\"Year\"\",#(lf)       to_date(mp.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                              \"\"Stop Dt\"\",#(lf)       NULL                                                              \"\"Stop Yr\"\"#(lf) from advance.employment mp#(lf)inner join advance.entity e              ON mp.id_number = e.id_number#(lf) left join advance.tms_place_of_work pow ON mp.place_of_work_code = pow.place_of_work_code#(lf) left join advance.tms_position_level pl ON mp.position_level_code = pl.position_level_code#(lf)where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-1)#(lf)UNION ALL#(lf)-- Current FY - 1 Inactive#(lf)select distinct mp2.id_number                                             \"\"F/S ID\"\",#(lf)       'Inactive'                                                         \"\"Status\"\",#(lf)       mp2.id_number||to_char((select * from advur.vw_current_fiscal_year)-1)    \"\"ComboIDKey\"\",#(lf)       e2.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e2.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e2.id_number)                         \"\"Record Types\"\",#(lf)       mp2.job_title                                                      \"\"Job Title\"\",#(lf)       pow2.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp2.employer_unit                                                  \"\"Department\"\",#(lf)       pl2.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-1)            \"\"Year\"\",#(lf)       to_date(mp2.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                               \"\"Stop Dt\"\",#(lf)       NULL                                                               \"\"Stop Yr\"\"#(lf) from advance.employment mp2#(lf)inner join advance.entity e2              ON mp2.id_number = e2.id_number#(lf) left join advance.tms_place_of_work pow2 ON mp2.place_of_work_code = pow2.place_of_work_code#(lf) left join advance.tms_position_level pl2 ON mp2.position_level_code = pl2.position_level_code#(lf)where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)and   substr(mp2.stop_dt,7,2) <> '00'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-1)#(lf)and   (mp2.stop_dt = '00000000' OR #(lf)      EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)-1))#(lf)UNION ALL#(lf)-- Current FY - 2 Active#(lf)select distinct mp.id_number                                             \"\"F/S ID\"\",#(lf)       'Active'                                                          status,#(lf)       mp.id_number||to_char((select * from advur.vw_current_fiscal_year)-2)    \"\"ComboIDKey\"\",#(lf)       e.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e.id_number)                         \"\"Record Types\"\",#(lf)       mp.job_title                                                      \"\"Job Title\"\",#(lf)       pow.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp.employer_unit                                                  \"\"Department\"\",#(lf)       pl.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-2)           \"\"Year\"\",#(lf)       to_date(mp.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                              \"\"Stop Dt\"\",#(lf)       NULL                                                              \"\"Stop Yr\"\"#(lf) from advance.employment mp#(lf)inner join advance.entity e              ON mp.id_number = e.id_number#(lf) left join advance.tms_place_of_work pow ON mp.place_of_work_code = pow.place_of_work_code#(lf) left join advance.tms_position_level pl ON mp.position_level_code = pl.position_level_code#(lf)where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-2)#(lf)UNION ALL#(lf)-- Current FY - 2 Inactive#(lf)select distinct mp2.id_number                                             \"\"F/S ID\"\",#(lf)       'Inactive'                                                         \"\"Status\"\",#(lf)       mp2.id_number||to_char((select * from advur.vw_current_fiscal_year)-2)    \"\"ComboIDKey\"\",#(lf)       e2.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e2.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e2.id_number)                         \"\"Record Types\"\",#(lf)       mp2.job_title                                                      \"\"Job Title\"\",#(lf)       pow2.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp2.employer_unit                                                  \"\"Department\"\",#(lf)       pl2.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-2)            \"\"Year\"\",#(lf)       to_date(mp2.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                               \"\"Stop Dt\"\",#(lf)       NULL                                                               \"\"Stop Yr\"\"#(lf) from advance.employment mp2#(lf)inner join advance.entity e2              ON mp2.id_number = e2.id_number#(lf) left join advance.tms_place_of_work pow2 ON mp2.place_of_work_code = pow2.place_of_work_code#(lf) left join advance.tms_position_level pl2 ON mp2.position_level_code = pl2.position_level_code#(lf)where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)and   substr(mp2.stop_dt,7,2) <> '00'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-2)#(lf)and   (mp2.stop_dt = '00000000' OR #(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)-2))#(lf)UNION ALL#(lf)-- Current FY - 3 Active#(lf)select distinct mp.id_number                                             \"\"F/S ID\"\",#(lf)       'Active'                                                          status,#(lf)       mp.id_number||to_char((select * from advur.vw_current_fiscal_year)-3)    \"\"ComboIDKey\"\",#(lf)       e.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e.id_number)                         \"\"Record Types\"\",#(lf)       mp.job_title                                                      \"\"Job Title\"\",#(lf)       pow.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp.employer_unit                                                  \"\"Department\"\",#(lf)       pl.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-3)             \"\"Year\"\",#(lf)       to_date(mp.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                              \"\"Stop Dt\"\",#(lf)       NULL                                                              \"\"Stop Yr\"\"#(lf) from advance.employment mp#(lf)inner join advance.entity e              ON mp.id_number = e.id_number#(lf) left join advance.tms_place_of_work pow ON mp.place_of_work_code = pow.place_of_work_code#(lf) left join advance.tms_position_level pl ON mp.position_level_code = pl.position_level_code#(lf)where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-3)#(lf)UNION ALL#(lf)-- Current FY - 3 Inactive#(lf)select distinct mp2.id_number                                             \"\"F/S ID\"\",#(lf)       'Inactive'                                                         \"\"Status\"\",#(lf)       mp2.id_number||to_char((select * from advur.vw_current_fiscal_year)-3)    \"\"ComboIDKey\"\",#(lf)       e2.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e2.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e2.id_number)                         \"\"Record Types\"\",#(lf)       mp2.job_title                                                      \"\"Job Title\"\",#(lf)       pow2.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp2.employer_unit                                                  \"\"Department\"\",#(lf)       pl2.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-3)            \"\"Year\"\",#(lf)       to_date(mp2.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                               \"\"Stop Dt\"\",#(lf)       NULL                                                               \"\"Stop Yr\"\"#(lf) from advance.employment mp2#(lf)inner join advance.entity e2              ON mp2.id_number = e2.id_number#(lf) left join advance.tms_place_of_work pow2 ON mp2.place_of_work_code = pow2.place_of_work_code#(lf) left join advance.tms_position_level pl2 ON mp2.position_level_code = pl2.position_level_code#(lf)where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)and   substr(mp2.stop_dt,7,2) <> '00'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-3)#(lf)and   (mp2.stop_dt = '00000000' OR #(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)-3))#(lf)UNION ALL#(lf)-- Current FY - 4 Active#(lf)select distinct mp.id_number                                             \"\"F/S ID\"\",#(lf)       'Active'                                                          status,#(lf)       mp.id_number||to_char((select * from advur.vw_current_fiscal_year)-4)    \"\"ComboIDKey\"\",#(lf)       e.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e.id_number)                         \"\"Record Types\"\",#(lf)       mp.job_title                                                      \"\"Job Title\"\",#(lf)       pow.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp.employer_unit                                                  \"\"Department\"\",#(lf)       pl.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-4)           \"\"Year\"\",#(lf)       to_date(mp.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                              \"\"Stop Dt\"\",#(lf)       NULL                                                              \"\"Stop Yr\"\"#(lf) from advance.employment mp#(lf)inner join advance.entity e              ON mp.id_number = e.id_number#(lf) left join advance.tms_place_of_work pow ON mp.place_of_work_code = pow.place_of_work_code#(lf) left join advance.tms_position_level pl ON mp.position_level_code = pl.position_level_code#(lf)where mp.employer_id_number = '0000054952' and   mp.job_status_code IN ('A','C','T')#(lf)and   mp.job_title NOT LIKE 'Resident%'    and   mp.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp.start_dt,1,4) <> '0000'    and   substr(mp.start_dt,5,2) <> '00'#(lf)and   substr(mp.start_dt,7,2) <> '00'      and   mp.start_dt <> '00000000'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-4)#(lf)UNION ALL#(lf)-- Current FY - 4 Inactive#(lf)select distinct mp2.id_number                                             \"\"F/S ID\"\",#(lf)       'Inactive'                                                         \"\"Status\"\",#(lf)       mp2.id_number||to_char((select * from advur.vw_current_fiscal_year)-4)    \"\"ComboIDKey\"\",#(lf)       e2.pref_mail_name                                                  \"\"Fac-Staff Name\"\",#(lf)       e2.institutional_suffix                                            \"\"Inst Suffix\"\",#(lf)       advdeploy.fn_get_record_type(e2.id_number)                         \"\"Record Types\"\",#(lf)       mp2.job_title                                                      \"\"Job Title\"\",#(lf)       pow2.short_desc                                                    \"\"School/College/Unit\"\",#(lf)       mp2.employer_unit                                                  \"\"Department\"\",#(lf)       pl2.short_desc                                                     \"\"Pos Lvl\"\",#(lf)       to_char((select * from advur.vw_current_fiscal_year)-4)            \"\"Year\"\",#(lf)       to_date(mp2.start_dt, 'YYYYMMDD')                                  \"\"Start Dt\"\",#(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) \"\"Start Yr\"\",#(lf)       NULL                                                               \"\"Stop Dt\"\",#(lf)       NULL                                                               \"\"Stop Yr\"\"#(lf) from advance.employment mp2#(lf)inner join advance.entity e2              ON mp2.id_number = e2.id_number#(lf) left join advance.tms_place_of_work pow2 ON mp2.place_of_work_code = pow2.place_of_work_code#(lf) left join advance.tms_position_level pl2 ON mp2.position_level_code = pl2.position_level_code#(lf)where mp2.employer_id_number = '0000054952' and   mp2.job_status_code IN ('P','R')#(lf)and   mp2.job_title NOT LIKE 'Resident%'    and   mp2.job_title NOT LIKE 'Fellow%'#(lf)and   substr(mp2.start_dt,1,4) <> '0000'    and   substr(mp2.start_dt,5,2) <> '00'#(lf)and   substr(mp2.start_dt,7,2) <> '00'      and   mp2.start_dt <> '00000000'#(lf)and   substr(mp2.stop_dt,1,4) <> '0000'     and   substr(mp2.stop_dt,5,2) <> '00'#(lf)and   substr(mp2.stop_dt,7,2) <> '00'#(lf)and   EXTRACT(YEAR FROM add_months(to_date(mp2.start_dt, 'YYYYMMDD'),6)) <= to_char((select * from advur.vw_current_fiscal_year)-4)#(lf)and   (mp2.stop_dt = '00000000' OR #(lf)       EXTRACT(YEAR FROM add_months(to_date(mp2.stop_dt, 'YYYYMMDD'),6)) >= to_char((select * from advur.vw_current_fiscal_year)-4))#(lf)order by \"\"F/S ID\"\", \"\"Year\"\"\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Year\", type text}, {\"Start Dt\", type date}, {\"Start Yr\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PLC Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "67d3567b-621f-41c8-bae0-d8f31c3f7da3",
        "measures": [
          {
            "name": "FY PLC HH Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYPLCHHCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( 'Current Parents_5Yr'[HH Key] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[PLC Ind] > 0 )",
              "return",
              "IF(ISBLANK(_FYPLCHHCnt),0,_FYPLCHHCnt)"
            ],
            "formatString": "0",
            "lineageTag": "31f7cf36-4248-4c65-a17e-745da961b900"
          },
          {
            "name": "FY PLC Ind Rev Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYPLCIndCnt = CALCULATE(",
              "                            SUMX( 'PLC Members', 'PLC Members'[Parent Count] ),",
              "                            FILTER( Revenue_5Yrs, Revenue_5Yrs[Fiscal Yr] = _SelFY ),",
              "                            FILTER( 'Current Parents_5Yr', 'Current Parents_5Yr'[PLC Ind] > 0 ),",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                            )",
              "return",
              "IF(ISBLANK(_FYPLCIndCnt),0,_FYPLCIndCnt)"
            ],
            "formatString": "0",
            "lineageTag": "6c84a31d-681b-461d-bfbf-bdd18f870f74"
          },
          {
            "name": "FY PLC Production",
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYPLCProd = CALCULATE(",
              "                        SUMX( Production_5Yrs, Production_5Yrs[Trans Amt] ),",
              "                            Production_5Yrs[Fiscal Yr] = _SelYr,",
              "                            'Current Parents_5Yr'[PLC Ind] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYPLCProd),0,_FYPLCProd)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e543cd9e-af14-4f55-b744-5a2f72432e9d"
          },
          {
            "name": "FY PLC Revenue",
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYPLCRev = CALCULATE(",
              "                        SUMX( Revenue_5Yrs, Revenue_5Yrs[Trans Amt] ),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelYr,",
              "                            'Current Parents_5Yr'[PLC Ind] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYPLCRev),0,_FYPLCRev)"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "31ee1cc5-0da0-4a51-b3f4-1cc29046807d"
          },
          {
            "name": "FY PLC Prod HH Dnr Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYPLCProdDnrCnt = CALCULATE(",
              "                        DISTINCTCOUNTNOBLANK( Production_5Yrs[HH Key] ),",
              "                        FILTER( Production_5Yrs, Production_5Yrs[Fiscal Yr] = _SelFY),",
              "                        FILTER( 'Current Parents_5Yr', 'Current Parents_5Yr'[PLC Ind] > 0 ),",
              "                        USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                    )",
              "return",
              "IF(ISBLANK(_FYPLCProdDnrCnt),0,_FYPLCProdDnrCnt)"
            ],
            "formatString": "0",
            "lineageTag": "e99eac40-7b43-47a9-a16d-ffd5e1457916"
          },
          {
            "name": "FY PLC Prod Ind Dnr Cnt",
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYPLCProdIndDnr = CALCULATE(",
              "                        SUMX( 'PLC Members', 'PLC Members'[Parent Count] ),",
              "                        FILTER( Production_5Yrs, Production_5Yrs[Fiscal Yr] = _SelYr),",
              "                        FILTER( 'Current Parents_5Yr', 'Current Parents_5Yr'[PLC Ind] > 0),",
              "                        USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYPLCProdIndDnr),0,_FYPLCProdIndDnr)"
            ],
            "formatString": "0",
            "lineageTag": "a2c9b164-aec5-4b65-8047-bf2bfa7ca185"
          },
          {
            "name": "FY PLC Prod Trans Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYPLCProdTransCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( Production_5Yrs[Trans Nbr] ),",
              "                            Production_5Yrs[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[PLC Ind] > 0,",
              "                             USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                            )",
              "return",
              "IF(ISBLANK(_FYPLCProdTransCnt),0,_FYPLCProdTransCnt)"
            ],
            "formatString": "0",
            "lineageTag": "173ae0c2-5e0f-45dc-ba54-62e64e0f9147"
          },
          {
            "name": "Avg PLC HH Trans (Prod)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY PLC Production] / [FY PLC Prod HH Dnr Count]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c9ec85be-a160-4f21-a1dc-116fa53eacb2"
          },
          {
            "name": "Avg PLC Per Trans (Prod)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY PLC Production] / [FY PLC Prod Trans Count]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e30cbefd-d30c-4ec0-b2d0-fdaa9865d39b"
          },
          {
            "name": "HH PLC Prod Part Rate",
            "expression": [
              "",
              "    [FY PLC Prod HH Dnr Count] / [FY PLC HH Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "37e54877-69ca-4c96-a697-53b93b785afa"
          },
          {
            "name": "Ind PLC Prod Part Rate",
            "expression": [
              "",
              "    [FY PLC Prod Ind Dnr Cnt] / [FY PLC Ind Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5ba2007c-0b46-4a18-a52c-d573ee362f80"
          },
          {
            "name": "FY PLC Rev Gift Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYPLCRevGiftCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( Revenue_5Yrs[Trans Nbr]),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[PLC Ind] > 0,",
              "                             USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                             )",
              "return",
              "IF(ISBLANK(_FYPLCRevGiftCnt),0,_FYPLCRevGiftCnt)"
            ],
            "formatString": "0",
            "lineageTag": "3893e2ce-209f-4ec4-b360-b0d39e434a9c"
          },
          {
            "name": "FY PLC Rev HH Dnr Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYPLCRevDnrCnt = CALCULATE(",
              "                        DISTINCTCOUNTNOBLANK( Revenue_5Yrs[HH Key] ),",
              "                        FILTER( Revenue_5Yrs, Revenue_5Yrs[Fiscal Yr] = _SelFY),",
              "                        FILTER( 'Current Parents_5Yr', 'Current Parents_5Yr'[PLC Ind] > 0),",
              "                        USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                    )",
              "return",
              "IF(ISBLANK(_FYPLCRevDnrCnt),0,_FYPLCRevDnrCnt)"
            ],
            "formatString": "0",
            "lineageTag": "3a9fcb75-8e70-4d2b-b705-7c9bc4fd85c8"
          },
          {
            "name": "HH PLC Rev Part Rate",
            "expression": [
              "",
              "    [FY PLC Rev HH Dnr Count] / [FY PLC HH Cnt]"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c5be59ca-3eb3-4d42-bede-4c3ee6001794"
          },
          {
            "name": "FY PLC Rev Ind Dnr Cnt",
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYPLCRevIndDnr = CALCULATE(",
              "                            SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[Rev Donor Ind] ),",
              "                            'Calendar - FY13+'[FiscalYear] = _SelYr,",
              "                            'Current Parents_5Yr'[PLC Ind] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYPLCRevIndDnr),0,_FYPLCRevIndDnr)"
            ],
            "formatString": "0",
            "lineageTag": "654bf686-d8c1-4902-bc47-b5578a964fc8"
          },
          {
            "name": "Ind PLC Rev Part Rate",
            "expression": [
              "",
              "    [FY PLC Rev Ind Dnr Cnt] / [FY Parent Ind Cnt]"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "835c36c9-b93f-4325-8d1f-8ee70d25c6da"
          },
          {
            "name": "Avg PLC Per Trans (Rev)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY PLC Revenue] / [FY PLC Rev Gift Count]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e1b1b3cb-3972-44df-91f0-cb7147f53295"
          },
          {
            "name": "Avg PLC HH Trans (Rev)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY PLC Revenue] / [FY PLC Rev HH Dnr Count]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "18c5cd4a-b30e-4c8c-b52a-123d371defba"
          },
          {
            "name": "FY PLC Ind Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYPLCIndCnt = CALCULATE(",
              "                            SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[Parent Cnt] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[PLC Ind] > 0",
              "                            )",
              "return",
              "IF(ISBLANK(_FYPLCIndCnt),0,_FYPLCIndCnt)"
            ],
            "formatString": "0",
            "lineageTag": "83855adb-0439-46e0-b759-a03cf100c5c5"
          }
        ],
        "partitions": [
          {
            "name": "PLC Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Alumni Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "9cd80b30-374b-40ad-b5c9-6c4c6535c576",
        "measures": [
          {
            "name": "FY Alumni HH Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAlumHHCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( 'Current Parents_5Yr'[HH Key] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[Alumni Cnt] > 0",
              "                            )",
              "return",
              "IF(ISBLANK(_FYAlumHHCnt),0,_FYAlumHHCnt)"
            ],
            "formatString": "0",
            "lineageTag": "ac268142-5cf2-4c8b-b3c0-30fc475d3eaf"
          },
          {
            "name": "FY Alumni Ind Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAlumIndCnt = CALCULATE(",
              "                            SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[Alumni Cnt] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY",
              "                            )",
              "return",
              "IF(ISBLANK(_FYAlumIndCnt),0,_FYAlumIndCnt)"
            ],
            "formatString": "0",
            "lineageTag": "716953f2-538c-420d-afd9-d03c6c2db3b2"
          },
          {
            "name": "FY Alumni Prod HH Dnr Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAluProdDnrCnt = CALCULATE(",
              "                        DISTINCTCOUNT( Production_5Yrs[HH Key] ),",
              "                        FILTER( Production_5Yrs, Production_5Yrs[Fiscal Yr] = _SelFY),",
              "                        FILTER( 'Current Parents_5Yr', 'Current Parents_5Yr'[Alumni Cnt] > 0 ),",
              "                        USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                    )",
              "return",
              "IF(ISBLANK(_FYAluProdDnrCnt),0,_FYAluProdDnrCnt)"
            ],
            "formatString": "0",
            "lineageTag": "4a5f988b-e5a0-42f8-bcba-94fc3b1b93ce"
          },
          {
            "name": "FY Alumni Prod Ind Dnr Cnt",
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYAluIndDnr = CALCULATE(",
              "                        SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[Prod Donor Ind] ),",
              "                            'Calendar - FY13+'[FiscalYear] = _SelYr,",
              "                            'Current Parents_5Yr'[Alumni Cnt] > 0",
              "                        )",
              "return",
              "IF(ISBLANK(_FYAluIndDnr),0,_FYAluIndDnr)"
            ],
            "formatString": "0",
            "lineageTag": "28f39d00-d6f0-4513-ac1f-23c720f9fb7e"
          },
          {
            "name": "FY Alumni Prod Trans Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAluProdTransCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( Production_5Yrs[Trans Nbr] ),",
              "                            Production_5Yrs[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[Alumni Cnt] > 0,",
              "                             USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                            )",
              "return",
              "IF(ISBLANK(_FYAluProdTransCnt),0,_FYAluProdTransCnt)"
            ],
            "formatString": "0",
            "lineageTag": "98f797e4-7ae8-45cd-8f7c-660cd58b7404"
          },
          {
            "name": "FY Alumni Production",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYAluProd = CALCULATE(",
              "                        SUMX( Production_5Yrs, Production_5Yrs[Trans Amt] ),",
              "                            'Calendar - FY13+'[FiscalYear] = _SelYr,",
              "                            'Current Parents_5Yr'[Alumni Cnt] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYAluProd),0,_FYAluProd)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6d467314-35b6-4b8c-8608-9e97b846c962"
          },
          {
            "name": "FY Alumni Rev Gift Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAluRevGiftCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( Revenue_5Yrs[Trans Nbr]),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[Alumni Cnt] > 0,",
              "                             USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                             )",
              "return",
              "IF(ISBLANK(_FYAluRevGiftCnt),0,_FYAluRevGiftCnt)"
            ],
            "formatString": "0",
            "lineageTag": "42e38fc7-d1a9-4ee5-bdb0-42f606631117"
          },
          {
            "name": "FY Alumni Rev HH Dnr Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAluRevDnrCnt = CALCULATE(",
              "                        DISTINCTCOUNT( Revenue_5Yrs[HH Key] ),",
              "                        FILTER( Revenue_5Yrs, Revenue_5Yrs[Fiscal Yr] = _SelFY),",
              "                        FILTER( 'Current Parents_5Yr', 'Current Parents_5Yr'[Alumni Cnt] > 0),",
              "                        USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                    )",
              "return",
              "IF(ISBLANK(_FYAluRevDnrCnt),0,_FYAluRevDnrCnt)"
            ],
            "formatString": "0",
            "lineageTag": "0aac4f4a-a287-4a72-8dfb-d0211b31eb85"
          },
          {
            "name": "FY Alumni Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYAluRev = CALCULATE(",
              "                        SUMX( Revenue_5Yrs, Revenue_5Yrs[Trans Amt] ),",
              "                            'Calendar - FY13+'[FiscalYear] = _SelYr,",
              "                            'Current Parents_5Yr'[Alumni Cnt] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYAluRev),0,_FYAluRev)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e93de6d2-2000-43e3-a202-32ce79502db7"
          },
          {
            "name": "HH Alumni Prod Part Rate",
            "expression": [
              "",
              "    [FY Alumni Prod HH Dnr Count] / [FY Alumni HH Cnt]"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "e1771ea1-4e22-4a24-bc6b-eee8c217bc0a"
          },
          {
            "name": "Ind Alumni Prod Part Rate",
            "expression": [
              "",
              "    [FY Alumni Prod Ind Dnr Cnt] / [FY Alumni Ind Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d4f8635c-4a89-49dd-9b31-074ad0df1de6"
          },
          {
            "name": "Avg Alumni HH Trans (Rev)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY Alumni Revenue] / [FY Alumni Rev HH Dnr Count]"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a1901f50-fe67-44e4-99eb-43c758ef0a56"
          },
          {
            "name": "FY Alumni Ind Rev Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAluIndCnt = CALCULATE(",
              "                            SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[Rev Donor Ind] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[Alumni Cnt] > 0",
              "                            )",
              "return",
              "IF(ISBLANK(_FYAluIndCnt),0,_FYAluIndCnt)"
            ],
            "formatString": "0",
            "lineageTag": "01d270df-e47d-4e36-9313-1d204071eb34"
          },
          {
            "name": "FY Alumni Rev Ind Dnr Cnt",
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYAluRevIndDnr = CALCULATE(",
              "                        SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[Alumni Cnt] ),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelYr,",
              "                            'Current Parents_5Yr'[Alumni Cnt] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYAluRevIndDnr),0,_FYAluRevIndDnr)"
            ],
            "formatString": "0",
            "lineageTag": "0bd32055-201a-4302-89fe-ec62fcbaea8b"
          },
          {
            "name": "HH Alumni Rev Part Rate",
            "expression": [
              "",
              "    [FY Alumni Rev HH Dnr Count] / [FY Alumni HH Cnt]"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "82ac06d2-8c38-4418-bec5-13a56a4f5e9b"
          },
          {
            "name": "Ind Alumni Rev Part Rate",
            "expression": [
              "",
              "    [FY Alumni Rev Ind Dnr Cnt] / [FY Alumni Ind Cnt]"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "780dfc29-d930-49c7-848d-7fe3f6b643ad"
          },
          {
            "name": "Avg Alumni HH Trans (Prod)",
            "expression": [
              "",
              "    [FY Alumni Production] / [FY Alumni Prod HH Dnr Count]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6ca03275-01fe-4f5e-b09a-2b2b46372366"
          },
          {
            "name": "Avg Alumni Per Trans (Rev)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY Alumni Revenue] / [FY Alumni Rev Gift Count]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "26ac1ac5-ac1e-47a0-8423-fa7ae330c575"
          },
          {
            "name": "Avg Alumni Per Trans (Prod)",
            "expression": [
              "",
              "    [FY Alumni Production] / [FY Alumni Prod Trans Count]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "eed75fe9-2061-4198-9168-57b1979784dc"
          }
        ],
        "partitions": [
          {
            "name": "Alumni Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "F/S Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "bdfed2c4-6a83-477c-acf5-d77bc99daee6",
        "measures": [
          {
            "name": "FY F/S HH Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYFSHHCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( 'Current Parents_5Yr'[HH Key] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[F/S Cnt] > 0",
              "                            )",
              "return",
              "IF(ISBLANK(_FYFSHHCnt),0,_FYFSHHCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "1dc40c31-6965-4f94-abe8-37ca73066b28"
          },
          {
            "name": "FY F/S Ind Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYFSIndCnt = CALCULATE(",
              "                            SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[F/S Cnt] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[F/S Cnt] > 0",
              "                            )",
              "return",
              "IF(ISBLANK(_FYFSIndCnt),0,_FYFSIndCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "eb6f65b5-67ef-4435-82b6-0f0fcc3d19c9"
          },
          {
            "name": "FY F/S Ind Rev Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYFSIndCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( 'Fac-Staff (Primary)'[F/S ID] ) + DISTINCTCOUNTNOBLANK( 'Fac-Staff (Spouse)'[F/S ID] ),",
              "                            FILTER( Revenue_5Yrs, Revenue_5Yrs[Fiscal Yr] = _SelFY ),",
              "                            FILTER( 'Current Parents_5Yr', 'Current Parents_5Yr'[F/S Cnt] > 0 ),",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                            )",
              "return",
              "IF(ISBLANK(_FYFSIndCnt),0,_FYFSIndCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "19f5c574-219b-44c3-8d28-761b4babaa42"
          },
          {
            "name": "FY F/S Prod HH Dnr Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYFSProdDnrCnt = CALCULATE(",
              "                        DISTINCTCOUNTNOBLANK( Production_5Yrs[HH Key] ),",
              "                        FILTER( Production_5Yrs, Production_5Yrs[Fiscal Yr] = _SelFY),",
              "                        FILTER( 'Current Parents_5Yr', 'Current Parents_5Yr'[F/S Cnt] > 0 ),",
              "                        USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                    )",
              "return",
              "IF(ISBLANK(_FYFSProdDnrCnt),0,_FYFSProdDnrCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "94042148-765f-4495-a5f8-9e0c86679ede"
          },
          {
            "name": "FY F/S Prod Ind Dnr Cnt",
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYFSProdIndDnr = CALCULATE(",
              "                            SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[F/S Cnt] ),",
              "                            Production_5Yrs[Fiscal Yr] = _SelYr,",
              "                            'Current Parents_5Yr'[F/S Cnt] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYFSProdIndDnr),0,_FYFSProdIndDnr)"
            ],
            "formatString": "0",
            "lineageTag": "51128f94-ccbe-4c5a-b955-d19ca3dc27bb"
          },
          {
            "name": "FY F/S Prod Trans Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYFSProdTransCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( Production_5Yrs[Trans Nbr] ),",
              "                            Production_5Yrs[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[F/S Cnt] > 0,",
              "                             USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                            )",
              "return",
              "IF(ISBLANK(_FYFSProdTransCnt),0,_FYFSProdTransCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "6dfb0fde-d062-4976-807d-c5797d72fbf5"
          },
          {
            "name": "FY F/S Production",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYFSProd = CALCULATE(",
              "                        SUMX( Production_5Yrs, Production_5Yrs[Trans Amt] ),",
              "                            Production_5Yrs[Fiscal Yr] = _SelYr,",
              "                            'Current Parents_5Yr'[F/S Cnt] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYFSProd),0,_FYFSProd)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a0832f90-a333-4a57-bd25-a47e5e699a3a"
          },
          {
            "name": "FY F/S Rev Gift Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYFSRevGiftCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( Revenue_5Yrs[Trans Nbr]),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[F/S Cnt] > 0,",
              "                             USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                             )",
              "return",
              "IF(ISBLANK(_FYFSRevGiftCnt),0,_FYFSRevGiftCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "0ba4c2a5-44f8-4c49-bec1-b15837dde156"
          },
          {
            "name": "FY F/S Rev HH Dnr Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYFSRevDnrCnt = CALCULATE(",
              "                        DISTINCTCOUNTNOBLANK( Revenue_5Yrs[HH Key] ),",
              "                        FILTER( Revenue_5Yrs, Revenue_5Yrs[Fiscal Yr] = _SelFY),",
              "                        FILTER( 'Current Parents_5Yr', 'Current Parents_5Yr'[F/S Cnt] > 0),",
              "                        USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                    )",
              "return",
              "IF(ISBLANK(_FYFSRevDnrCnt),0,_FYFSRevDnrCnt)"
            ],
            "formatString": "#,0",
            "lineageTag": "e31a1827-064e-40fc-b64c-ed773ba792b8"
          },
          {
            "name": "FY F/S Rev Ind Dnr Cnt",
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYFSRevIndDnr = CALCULATE(",
              "                            SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[F/S Cnt] ),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelYr,",
              "                            'Current Parents_5Yr'[F/S Cnt] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYFSRevIndDnr),0,_FYFSRevIndDnr)"
            ],
            "formatString": "#,0",
            "lineageTag": "4769bca0-df9f-4dc2-aecf-31711537b602"
          },
          {
            "name": "FY F/S Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYFSRev = CALCULATE(",
              "                        SUMX( Revenue_5Yrs, Revenue_5Yrs[Trans Amt] ),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelYr,",
              "                            'Current Parents_5Yr'[F/S Cnt] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYFSRev),0,_FYFSRev)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "59c9d5ec-df90-4b27-a19e-63e6091652f4"
          },
          {
            "name": "HH F/S Prod Part Rate",
            "expression": [
              "",
              "    [FY F/S Prod HH Dnr Count] / [FY F/S HH Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "de33c6cc-026b-4614-a3a2-e15b3d6a8d4b"
          },
          {
            "name": "HH F/S Rev Part Rate",
            "expression": [
              "",
              "    [FY F/S Rev HH Dnr Count] / [FY F/S HH Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ff4310ac-1e71-44ab-9a65-efce003a2fcf"
          },
          {
            "name": "Ind F/S Prod Part Rate",
            "expression": [
              "",
              "    [FY F/S Prod Ind Dnr Cnt] / [FY F/S Ind Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "08b9c4a1-94b2-4286-b213-7cd977bc3f29"
          },
          {
            "name": "Ind F/S Rev Part Rate",
            "expression": [
              "",
              "    [FY F/S Rev Ind Dnr Cnt] / [FY F/S Ind Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "49a77444-e3a5-4bff-ba84-70713ce81092"
          },
          {
            "name": "Avg F/S HH Trans (Prod)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY F/S Production] / [FY F/S Prod HH Dnr Count]"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "22ee7d26-6a59-4189-87f1-d9a5d2e52cfa"
          },
          {
            "name": "Avg F/S HH Trans (Rev)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY F/S Revenue] / [FY F/S Rev HH Dnr Count]"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b3c8316a-2c96-46f0-9c87-a1e2845df4d2"
          },
          {
            "name": "Avg F/S Per Trans (Prod)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY F/S Production] / [FY F/S Prod Trans Count]"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "108d4df3-1317-46a4-8e58-ccadf0234abf"
          },
          {
            "name": "Avg F/S Per Trans (Rev)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY F/S Revenue] / [FY F/S Rev Gift Count]"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "87775b88-fd96-4fa2-a6bf-93a1110a6776"
          }
        ],
        "partitions": [
          {
            "name": "F/S Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Assigned Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "3f483e87-3548-48a7-84b3-20fcbc6a536b",
        "measures": [
          {
            "name": "FY Assgn HH Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAssgnHHCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( 'Current Parents_5Yr'[HH Key] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[Assigned Ind] > 0",
              "                            )",
              "return",
              "IF(ISBLANK(_FYAssgnHHCnt),0,_FYAssgnHHCnt)"
            ],
            "formatString": "0",
            "lineageTag": "6e06db4e-9b13-4911-9524-417b3d6a6398"
          },
          {
            "name": "FY Assgn Ind Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAssgnIndCnt = CALCULATE(",
              "                            SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[Parent Cnt] ),",
              "                            'Current Parents_5Yr'[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[Assigned Ind] > 0",
              "                            )",
              "return",
              "IF(ISBLANK(_FYAssgnIndCnt),0,_FYAssgnIndCnt)"
            ],
            "formatString": "0",
            "lineageTag": "00363f66-3dd1-4963-8790-deca2e3f9e92"
          },
          {
            "name": "FY Assgn Ind Rev Cnt",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAssgnIndCnt = CALCULATE(",
              "                            SUMX( 'Assigned Prim Managers', 'Assigned Prim Managers'[Par Count] ),",
              "                            FILTER( Revenue_5Yrs, Revenue_5Yrs[Fiscal Yr] = _SelFY ),",
              "                            FILTER( 'Current Parents_5Yr', 'Current Parents_5Yr'[Assigned Ind] > 0 ),",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                            )",
              "return",
              "IF(ISBLANK(_FYAssgnIndCnt),0,_FYAssgnIndCnt)"
            ],
            "formatString": "0",
            "lineageTag": "11c65de0-0eb9-4c9e-8a0a-9e6375e8a2ae"
          },
          {
            "name": "FY Assgn Prod HH Dnr Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAssgnProdDnrCnt = CALCULATE(",
              "                        DISTINCTCOUNTNOBLANK( Production_5Yrs[HH Key] ),",
              "                        FILTER( Production_5Yrs, Production_5Yrs[Fiscal Yr] = _SelFY),",
              "                        FILTER( 'Current Parents_5Yr', 'Current Parents_5Yr'[Assigned Ind] > 0 ),",
              "                        USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                    )",
              "return",
              "IF(ISBLANK(_FYAssgnProdDnrCnt),0,_FYAssgnProdDnrCnt)"
            ],
            "formatString": "0",
            "lineageTag": "e7de5c2a-b210-47ed-8f36-3273f21e9c85"
          },
          {
            "name": "FY Assgn Prod Ind Dnr Cnt",
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYAssgnProdIndDnr = CALCULATE(",
              "                        SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[Prod Donor Ind] ),",
              "                            Production_5Yrs[Fiscal Yr] = _SelYr,",
              "                            'Current Parents_5Yr'[Assigned Ind] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYAssgnProdIndDnr),0,_FYAssgnProdIndDnr)"
            ],
            "formatString": "0",
            "lineageTag": "fc0cfedf-4b9e-46cd-bc1f-b8a44e695324"
          },
          {
            "name": "FY Assgn Production",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYAssgnProd = CALCULATE(",
              "                        SUMX( Production_5Yrs, Production_5Yrs[Trans Amt] ),",
              "                            Production_5Yrs[Fiscal Yr] = _SelYr,",
              "                            'Current Parents_5Yr'[Assigned Ind] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYAssgnProd),0,_FYAssgnProd)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "db908436-8471-48f5-8340-ff86d08bee07"
          },
          {
            "name": "FY Assgn Prod Trans Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAssgnProdTransCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( Production_5Yrs[Trans Nbr] ),",
              "                            Production_5Yrs[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[Assigned Ind] > 0,",
              "                             USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Production_5Yrs[ComboKey] )",
              "                            )",
              "return",
              "IF(ISBLANK(_FYAssgnProdTransCnt),0,_FYAssgnProdTransCnt)"
            ],
            "formatString": "0",
            "lineageTag": "85f3f33a-32fb-40d3-acd7-9502d95a20b0"
          },
          {
            "name": "FY Assgn Rev Gift Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAssgnRevGiftCnt = CALCULATE(",
              "                            DISTINCTCOUNTNOBLANK( Revenue_5Yrs[Trans Nbr]),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelFY,",
              "                            'Current Parents_5Yr'[Assigned Ind] > 0,",
              "                             USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                             )",
              "return",
              "IF(ISBLANK(_FYAssgnRevGiftCnt),0,_FYAssgnRevGiftCnt)"
            ],
            "formatString": "0",
            "lineageTag": "6c20fc66-fd76-4089-8769-654d48d19daa"
          },
          {
            "name": "FY Assgn Rev HH Dnr Count",
            "expression": [
              "",
              "    var _SelFY = [Selected FY]",
              "    var _FYAssgnRevDnrCnt = CALCULATE(",
              "                        DISTINCTCOUNTNOBLANK( Revenue_5Yrs[HH Key] ),",
              "                        FILTER( Revenue_5Yrs, Revenue_5Yrs[Fiscal Yr] = _SelFY),",
              "                        FILTER( 'Current Parents_5Yr', 'Current Parents_5Yr'[Assigned Ind] > 0),",
              "                        USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                    )",
              "return",
              "IF(ISBLANK(_FYAssgnRevDnrCnt),0,_FYAssgnRevDnrCnt)"
            ],
            "formatString": "0",
            "lineageTag": "fec119af-4a25-4054-b22c-98e65804b81d"
          },
          {
            "name": "FY Assgn Rev Ind Dnr Cnt",
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYAssgnRevIndDnr = CALCULATE(",
              "                            SUMX( 'Current Parents_5Yr', 'Current Parents_5Yr'[Rev Donor Ind] ),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelYr,",
              "                            'Current Parents_5Yr'[Assigned Ind] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYAssgnRevIndDnr),0,_FYAssgnRevIndDnr)"
            ],
            "formatString": "0",
            "lineageTag": "ca1a4e30-ead3-4eb7-820c-947777291621"
          },
          {
            "name": "FY Assgn Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    var _SelYr = [Selected FY]",
              "    var _FYAssgnRev = CALCULATE(",
              "                        SUMX( Revenue_5Yrs, Revenue_5Yrs[Trans Amt] ),",
              "                            Revenue_5Yrs[Fiscal Yr] = _SelYr,",
              "                            'Current Parents_5Yr'[Assigned Ind] > 0,",
              "                            USERELATIONSHIP( 'Current Parents_5Yr'[ComboKey], Revenue_5Yrs[ComboKey] )",
              "                        )",
              "return",
              "IF(ISBLANK(_FYAssgnRev),0,_FYAssgnRev)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "32b7a136-de33-4449-a5d8-89e017941d93"
          },
          {
            "name": "HH Assgn Prod Part Rate",
            "expression": [
              "",
              "    [FY Assgn Prod HH Dnr Count] / [FY Assgn HH Cnt]"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bbfb7a47-756a-46c2-9b78-c9e30a2e3305"
          },
          {
            "name": "HH Assgn Rev Part Rate",
            "expression": [
              "",
              "    [FY Assgn Rev HH Dnr Count] / [FY Assgn HH Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "480b1303-27c9-474c-bbc5-94fd3ee18e71"
          },
          {
            "name": "Ind Assgn Prod Part Rate",
            "expression": [
              "",
              "    [FY Assgn Prod Ind Dnr Cnt] / [FY Assgn Ind Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "22be9640-1ccc-4e5a-b732-74a9e55900fa"
          },
          {
            "name": "Ind Assgn Rev Part Rate",
            "expression": [
              "",
              "    [FY Assgn Rev Ind Dnr Cnt] / [FY Assgn Ind Cnt]"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f9d0e005-9eb5-438c-a0d9-1835a2eebc31"
          },
          {
            "name": "Avg Assgn HH Trans (Prod)",
            "expression": [
              "",
              "    [FY Assgn Production] / [FY Assgn Prod HH Dnr Count]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ed91d0e0-0308-491e-bc99-4f9f9eb2382b"
          },
          {
            "name": "Avg Assgn HH Trans (Rev)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY Assgn Revenue] / [FY Assgn Rev HH Dnr Count]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f7e7cff6-3146-4a7a-9fa0-91a877f36a97"
          },
          {
            "name": "Avg Assgn Per Trans (Prod)",
            "expression": [
              "",
              "    [FY Assgn Production] / [FY Assgn Prod Trans Count]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "fe9e3ee6-da3f-4928-ad8f-02a1bc0c30ec"
          },
          {
            "name": "Avg Assgn Per Trans (Rev)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "    [FY Assgn Revenue] / [FY Assgn Rev Gift Count]"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "5856aeac-2dce-4c63-8c6f-0794de30b689"
          }
        ],
        "partitions": [
          {
            "name": "Assigned Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Ignatian Merit Indicator",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Indicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e36272b-082f-4907-ba03-c4dd13b90d60",
            "sourceColumn": "Indicator",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "55324aeb-09ac-4797-acf2-4c97e5e5fac7",
        "partitions": [
          {
            "name": "Ignatian Merit Indicator",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8kzPSyzJTMxT8E0tyixRCE7OyM9JLCrOyCxQitWJVvIvyUgtUoqNBQA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Indicator = _t])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "General Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "adc454ef-3dea-45c1-97e2-05f2c57bda66",
        "measures": [
          {
            "name": "FY Ending",
            "expression": [
              "",
              "    MAX( Revenue_5Yrs[Fiscal Yr] )"
            ],
            "lineageTag": "950e8f16-c982-45e7-94e5-9ed716feb188"
          },
          {
            "name": "FY Starting",
            "expression": [
              "",
              "    MIN( Revenue_5Yrs[Fiscal Yr] )"
            ],
            "lineageTag": "2cf43dc3-75a9-4534-81f9-88cd5b497b32"
          },
          {
            "name": "Page Title PLC Dash",
            "expression": [
              "",
              "    \"Current Parents' PLC Dashboard - FY\" & [Selected FY]"
            ],
            "lineageTag": "5a8f47fd-4d8e-4bbb-8c2e-eb583d7fe4b9"
          },
          {
            "name": "Page Title Stats",
            "expression": [
              "",
              "    \"Current Parents' Stats Dashboard - FY\" & [Selected FY]"
            ],
            "lineageTag": "0d2fd2bd-d019-484b-8114-647ae502367f"
          },
          {
            "name": "Page Title Scholarship Details",
            "expression": [
              "",
              "    \"Scholarship Production Details - \" & SELECTEDVALUE( 'Current Parents_5Yr'[Alumni], \"All Current Parents\")"
            ],
            "lineageTag": "a49a7c34-49dc-48fe-8543-9bd9bed89eb9"
          },
          {
            "name": "FY Current",
            "expression": [
              "",
              "    \"20\" &",
              "    MID( CALCULATE( MAX( 'Calendar - FY13+'[FiscalYear] ),",
              "           'Calendar - FY13+'[CurFiscalYearOffset] = 0",
              "            ), 3, 2 ",
              "            )"
            ],
            "lineageTag": "4c60dce1-56b3-47e2-a188-84b14c865f31"
          },
          {
            "name": "Page Title CFY",
            "expression": [
              "",
              "    \"FY\" & [FY Current] & \" Revenue & Production for Current Parents\""
            ],
            "lineageTag": "3b019ab2-b3b9-4d5e-981a-c1c6399d641a"
          },
          {
            "name": "Page Title CFY Students",
            "expression": [
              "",
              "    \"FY\" & [FY Current] & \" Current Students Linked to Parents\""
            ],
            "lineageTag": "da60fa31-ad72-45e8-a892-9e42e8ad06d5"
          },
          {
            "name": "Page Title Production",
            "expression": [
              "",
              "    \"Current Parents' Production - \" & [FY Starting] & \" to \" & [FY Ending]"
            ],
            "lineageTag": "52c5c21e-cdfc-4065-b3c0-dca5cc8833fe"
          },
          {
            "name": "Page Title Revenue",
            "expression": [
              "",
              "    \"Current Parents' Revenue - \" & [FY Starting] & \" to \" & [FY Ending]"
            ],
            "lineageTag": "30c1273f-8453-468c-b7c1-ef42f4ec4fbb"
          },
          {
            "name": "Five-Year Scope SubTitle",
            "expression": [
              "",
              "    \"This page shows totals for the Fiscal Years indicated, for the \" & [Selected FY] & \" Current Parent cohort\""
            ],
            "lineageTag": "cd2e8c85-22ea-4533-82e7-d934158f251a"
          },
          {
            "name": "Selected FY",
            "expression": [
              "",
              "    SELECTEDVALUE( 'Fiscal Yrs'[Fiscal Yr] )"
            ],
            "lineageTag": "b69e74c4-9b00-486a-8821-a83f53d94629"
          },
          {
            "name": "Page Title Scholarships",
            "expression": [
              "",
              "    \"Scholarship Revenue & Production for All Schools - FY\" & [Selected FY]"
            ],
            "lineageTag": "e6da83de-1328-4c05-b630-0ea549cb6a01"
          },
          {
            "name": "Page Title Alumni Dash",
            "expression": [
              "",
              "    \"Current Parents' Alumni Dashboard - FY\" & [Selected FY]"
            ],
            "lineageTag": "aaf19822-0144-4a6a-ba16-2869b06ac2a3"
          },
          {
            "name": "Page Title F/S Dash",
            "expression": [
              "",
              "    \"Current Parents' Faculty/Staff Dashboard - FY\" & [Selected FY]"
            ],
            "lineageTag": "d664169d-1d37-4139-b617-d2d0d6686d02"
          },
          {
            "name": "Page Title Assigned Dash",
            "expression": [
              "",
              "    \"Current Parents' Assigned Dashboard - FY\" & [Selected FY]"
            ],
            "lineageTag": "7313be4d-591d-4fe3-a978-01d334d3a536"
          },
          {
            "name": "Database",
            "expression": [
              "",
              "    \"Database: \" & SELECTEDVALUE( DataSource[DataSource] )"
            ],
            "lineageTag": "215eb6c8-b347-4e88-93b7-ed37ff5c333a"
          },
          {
            "name": "Last Proc Dt",
            "expression": [
              "",
              "    SWITCH(",
              "        TRUE(),",
              "        [Max Production Proc Dt] > [Max Revenue Proc Dt], [Max Production Proc Dt],",
              "        [Max Revenue Proc Dt] > [Max Production Proc Dt], [Max Revenue Proc Dt],",
              "        [Max Production Proc Dt]",
              ")"
            ],
            "formatString": "General Date",
            "lineageTag": "fc5378de-8fe7-4dd8-8f36-181aba5129f1"
          },
          {
            "name": "Max Production Proc Dt",
            "expression": [
              "",
              "    MAXA( Production_5Yrs[Orig Proc Dt] )"
            ],
            "formatString": "Short Date",
            "lineageTag": "d790afac-df23-4950-86cd-7636ba22da6c"
          },
          {
            "name": "Max Revenue Proc Dt",
            "expression": [
              "",
              "    MAXA( Revenue_5Yrs[Orig Proc Dt] )"
            ],
            "formatString": "Short Date",
            "lineageTag": "9d9340c2-2fbc-4af4-80e4-62bbd9e73f48"
          },
          {
            "name": "As of Date",
            "expression": [
              "",
              "    \"As of \" & 'General Measures'[Last Proc Dt]"
            ],
            "lineageTag": "41d5ad6e-5f28-4f76-8f89-c32cd9ce4c33"
          },
          {
            "name": "Page Title PLC Details",
            "expression": [
              "",
              "    \"Current Parents' PLC Details - FY\" & [Selected FY]"
            ],
            "lineageTag": "a655e9e8-bad0-4fa5-ba6d-acabf98b3027"
          },
          {
            "name": "Page Title Alumni Details",
            "expression": [
              "",
              "    \"Current Parents' Alumni Details - FY\" & [Selected FY]"
            ],
            "lineageTag": "6ed8d246-46ee-4527-a7e8-e10a1e298c8f"
          },
          {
            "name": "Page Title Assigned Details",
            "expression": [
              "",
              "    \"Current Parents' Assigned Parents Details - FY\" & [Selected FY]"
            ],
            "lineageTag": "f3989f34-9404-4f84-a966-82cb80f92661"
          },
          {
            "name": "Page Title Student Details",
            "expression": [
              "",
              "    \"Current Students Details - FY\" & [FY Current]"
            ],
            "lineageTag": "f8cbbb9d-9778-47e6-8daf-65e6dc9558a1"
          }
        ],
        "partitions": [
          {
            "name": "General Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Students",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SORT_PAR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "680d4913-fe68-4620-b4ec-ad9b9ceb3a03",
            "sourceColumn": "SORT_PAR",
            "summarizeBy": "none"
          },
          {
            "name": "HH Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be0de55a-78ea-47d8-89e7-99b6604cb463",
            "sourceColumn": "HH Key",
            "summarizeBy": "none"
          },
          {
            "name": "Parent 1 ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b655738-9341-42a2-a557-297049f75a4f",
            "sourceColumn": "Parent 1 ID",
            "summarizeBy": "none"
          },
          {
            "name": "Parent 1 Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a967465b-87de-48e1-8b97-ca5cab7eaf97",
            "sourceColumn": "Parent 1 Name",
            "summarizeBy": "none"
          },
          {
            "name": "Parent 2 ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "577e389c-53f9-4e20-b564-8a259a2122a9",
            "sourceColumn": "Parent 2 ID",
            "summarizeBy": "none"
          },
          {
            "name": "Parent 2 Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "944b4f05-21e7-45bf-a930-289845faa2f2",
            "sourceColumn": "Parent 2 Name",
            "summarizeBy": "none"
          },
          {
            "name": "Student ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "633b402b-0664-429f-a924-b49860aa551a",
            "sourceColumn": "Student ID",
            "summarizeBy": "none"
          },
          {
            "name": "Student Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2308c34-c832-492b-93af-83a54c15baec",
            "sourceColumn": "Student Name",
            "summarizeBy": "none"
          },
          {
            "name": "School",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "031c3c9a-7ae7-46a8-a16f-ccd73cbf7b51",
            "sourceColumn": "School",
            "summarizeBy": "none"
          },
          {
            "name": "Campus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05a2331a-27bf-4ca3-b3f9-13dfcb83169f",
            "sourceColumn": "Campus",
            "summarizeBy": "none"
          },
          {
            "name": "Ant Grad Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73949c86-478d-4680-9f99-d683208fba0a",
            "sourceColumn": "Ant Grad Year",
            "summarizeBy": "none"
          },
          {
            "name": "Student Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee5393e8-2bcd-4415-a1f0-1ce90b7a3b3f",
            "sourceColumn": "Student Status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3617a31b-24c4-4e8d-924c-2edd44faaa4c",
        "partitions": [
          {
            "name": "Students",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(#\"Data Source\", [HierarchicalNavigation=true, Query=\"-- Created to use in Current Parent reports just to pull in student names, their enrolled school and admission status by Parent Household. smk 9/11/2023#(lf)-- This only pulls those who are Current Students the day the logic is executed.#(lf)#(lf)select distinct par.household_key         \"\"HH Key\"\",#(lf)       pe.id_number                       \"\"Parent 1 ID\"\",#(lf)       pe.pref_mail_name                  \"\"Parent 1 Name\"\",#(lf)       se.id_number                       \"\"Parent 2 ID\"\",#(lf)       se.pref_mail_name                  \"\"Parent 2 Name\"\",#(lf)       stdnt.sid                          \"\"Student ID\"\",#(lf)       stdnt.nme                          \"\"Student Name\"\",#(lf)       stdnt.schl                         \"\"School\"\",#(lf)       stdnt.cmp                          \"\"Campus\"\",#(lf)       stdnt.yr                           \"\"Ant Grad Year\"\",#(lf)       stdnt.stat                         \"\"Student Status\"\",#(lf)       pe.pref_name_sort                  Sort_Par#(lf)from advance.relationship rel_1#(lf)inner join advance.entity e1              ON rel_1.id_number = e1.id_number#(lf)inner join advance.tms_relationships r    ON rel_1.relation_type_code = r.relation_type_code#(lf)inner join advur.mvw_hh_entities_gen par  ON (e1.id_number = par.primary_id_number OR e1.id_number = par.secondary_id_number)#(lf)inner join advance.entity pe              ON par.primary_id_number = pe.id_number#(lf) left join advance.entity se              ON par.secondary_id_number = se.id_number#(lf)inner join ( #(lf)            select st.id_number sid, st.pref_mail_name nme, ts.long_desc schl, #(lf)                   CASE WHEN d.school_code = 'AS' THEN 'Arts & Sciences'#(lf)                        WHEN d.school_code = 'CBA' THEN 'Heider CoB'#(lf)                        WHEN d.school_code = 'DEN' THEN 'Dentistry'#(lf)                        WHEN d.school_code = 'GRA' THEN 'Graduate'#(lf)                        WHEN d.school_code = 'LAW' THEN 'Law'#(lf)                        WHEN d.school_code = 'MED' THEN 'Medicine'#(lf)                        WHEN d.school_code = 'NUR' THEN 'Nursing'#(lf)                        WHEN d.school_code = 'PHA' THEN 'Pharmacy & HP'#(lf)                        WHEN d.school_code = 'UC' THEN 'CPCE'#(lf)                      ELSE 'Missing' END fschl, d.degree_year yr, #(lf)                   ads.short_desc stat, c.short_desc cmp, st.pref_name_sort srt#(lf)              from advance.entity st#(lf)             inner join advance.degrees d            ON st.id_number = d.id_number#(lf)             left join advance.tms_admiss_status ads ON d.admiss_status_code = ads.admiss_status_code#(lf)             inner join advance.tms_school ts        ON d.school_code = ts.school_code#(lf)             left join advance.tms_campus c          ON d.campus_code = c.campus_code#(lf)             where d.institution_code = '6121'#(lf)             and   d.degree_type = 'S'#(lf)             and   d.admiss_status_code NOT IN ('DSM','WTH')#(lf)             and   st.record_status_code = 'A'#(lf)             ) stdnt ON rel_1.relation_id_number = stdnt.sid#(lf)where rel_1.relation_type_code IN ('PC','SD','G7')#(lf)#(lf)order by Sort_Par\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Current Parents_Unique",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "HH Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43a64441-c9d5-4c3b-b390-21eff2abc390",
            "sourceColumn": "HH Key",
            "summarizeBy": "none"
          },
          {
            "name": "Prim Parent Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "410be98c-e0cd-465e-bf13-1355b7554ba6",
            "sortByColumn": "Sort Parent Name",
            "sourceColumn": "Prim Parent Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prim Inst Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5274ef3b-927a-4f28-aa90-a189dc528c7f",
            "sourceColumn": "Prim Inst Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Rec Types",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e945c4c-9f68-43a3-a9db-fceb0a8d668e",
            "sourceColumn": "Primary Rec Types",
            "summarizeBy": "none"
          },
          {
            "name": "Sec Parent ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75553869-57ca-4546-91f4-507189b2c9f6",
            "sourceColumn": "Sec Parent ID",
            "summarizeBy": "none"
          },
          {
            "name": "Sec Rec Types",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "668369d9-bb8f-4a5d-bbe4-5631ce0fcbf0",
            "sourceColumn": "Sec Rec Types",
            "summarizeBy": "none"
          },
          {
            "name": "Prim Parent ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34516494-bc81-427d-8ab5-73a50f703104",
            "sourceColumn": "Prim Parent ID",
            "summarizeBy": "none"
          },
          {
            "name": "Sec Parent Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d053e6c-cef8-40b9-98f7-6d674af285ef",
            "sourceColumn": "Sec Parent Name",
            "summarizeBy": "none"
          },
          {
            "name": "MG EVI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aa3c7941-c52d-4e63-afb2-8e244b394a31",
            "sourceColumn": "MG EVI",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Worth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23420d60-318e-4d30-b565-6eb07c3551d0",
            "sourceColumn": "Net Worth",
            "summarizeBy": "none"
          },
          {
            "name": "Six Square",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d503a3fb-b0b1-4e99-855d-13d851942a82",
            "sourceColumn": "Six Square",
            "summarizeBy": "none"
          },
          {
            "name": "Engagement Score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "486eebb2-cb14-43ac-99c5-4be79a579b57",
            "sourceColumn": "Engagement Score",
            "summarizeBy": "sum"
          },
          {
            "name": "Alumni",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c886700-f347-458a-983e-e0ba82eb917e",
            "sourceColumn": "Alumni",
            "summarizeBy": "none"
          },
          {
            "name": "PLC Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "59f67c03-f70f-4b3d-bc30-faaa12701c95",
            "sourceColumn": "PLC Ind",
            "summarizeBy": "sum"
          },
          {
            "name": "Assigned Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cdb99dc8-cc19-4df7-94b1-d7748f3c571b",
            "sourceColumn": "Assigned Ind",
            "summarizeBy": "sum"
          },
          {
            "name": "Rev Donor Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6e3ce292-0ff1-4e89-8ce7-6d9d55fa986c",
            "sourceColumn": "Rev Donor Ind",
            "summarizeBy": "sum"
          },
          {
            "name": "Prod Donor Ind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8c53ce21-3e76-440d-8d50-766129fba73c",
            "sourceColumn": "Prod Donor Ind",
            "summarizeBy": "sum"
          },
          {
            "name": "F/S Cnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "72f1b273-86da-4160-b53a-2b845561cba4",
            "sourceColumn": "F/S Cnt",
            "summarizeBy": "sum"
          },
          {
            "name": "Sec Inst Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0dad7875-755f-436f-8e23-08331f936636",
            "sourceColumn": "Sec Inst Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Parent Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9bb0a54a-1065-4c66-ab7f-3de783568bae",
            "sourceColumn": "Sort Parent Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "177cd80c-4a5c-47bb-8643-f5d72b79d798",
        "partitions": [
          {
            "name": "Current Parents_Unique",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Current Parents_5Yr\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"HH Key\", \"Prim Parent ID\", \"Prim Parent Name\", \"Prim Inst Suffix\", \"Primary Rec Types\", \"Sec Parent ID\", \"Sec Parent Name\", \"Sec Rec Types\", \"Sec Inst Suffix\", \"MG EVI\", \"Net Worth\", \"Six Square\", \"Engagement Score\", \"Alumni\", \"PLC Ind\", \"Assigned Ind\", \"F/S Cnt\", \"Rev Donor Ind\", \"Prod Donor Ind\", \"Sort Parent Name\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\", {\"HH Key\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DataSource",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "columns": [
          {
            "name": "DataSource",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "712a656f-7ed7-44e7-802f-95f855ead717",
            "sourceColumn": "DataSource",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8bca5cd9-c0f2-4413-8cd8-3a3c2c9ae1c8",
        "partitions": [
          {
            "name": "DataSource",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Data Source\"",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Max Rev Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "columns": [
          {
            "name": "Max Rev Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c92604bc-c422-4d94-b6ae-0310c4c3e052",
            "sourceColumn": "Max Rev Date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a745d2ac-384e-4f4e-87c8-116a91841523",
        "partitions": [
          {
            "name": "Max Rev Date",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = List.Max( Revenue_5Yrs[Trans Dt] )",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fiscal Yrs",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Fiscal Yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "700690b7-0fcb-44e8-9f11-c25ad42d0e0d",
            "sourceColumn": "Fiscal Yr",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "267f04b5-1377-410c-9a08-d2da9a586ec3",
        "partitions": [
          {
            "name": "Fiscal Yrs",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Revenue_5Yrs,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Fiscal Yr\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "F/S (Primary)_Unique",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "F/S ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28ef7dbc-fed6-4012-ac64-7aa98ac0b64f",
            "sourceColumn": "F/S ID",
            "summarizeBy": "none"
          },
          {
            "name": "Fac-Staff Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39668e15-054d-4b0a-98ab-484e21887da4",
            "sourceColumn": "Fac-Staff Name",
            "summarizeBy": "none"
          },
          {
            "name": "Inst Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d4c99a1-3b55-4419-837b-66b41345097f",
            "sourceColumn": "Inst Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "Record Types",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "302842be-a514-4c39-9c28-10953c0ed7bb",
            "sourceColumn": "Record Types",
            "summarizeBy": "none"
          },
          {
            "name": "Job Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66c5c489-9092-44b9-8132-f16ed1302eb9",
            "sourceColumn": "Job Title",
            "summarizeBy": "none"
          },
          {
            "name": "School/College/Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d651284-82a0-4bcf-b9c0-971172a6cc31",
            "sourceColumn": "School/College/Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3458991e-07c9-40b9-b486-094fa7cadba8",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Pos Lvl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0432705-718e-4210-abad-df04eb6ca43f",
            "sourceColumn": "Pos Lvl",
            "summarizeBy": "none"
          },
          {
            "name": "Start Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "0cea5fea-a02f-46df-82d2-43260e309ab1",
            "sourceColumn": "Start Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Stop Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01ccb462-e9c0-472b-a7b1-57fff2dcfba7",
            "sourceColumn": "Stop Dt",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a8c46045-1855-4bcd-98ed-13a6a44ba9cf",
        "partitions": [
          {
            "name": "F/S (Primary)_Unique",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Fac-Staff (Primary)\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"F/S ID\", \"Fac-Staff Name\", \"Inst Suffix\", \"Record Types\", \"Job Title\", \"School/College/Unit\", \"Department\", \"Pos Lvl\", \"Start Dt\", \"Stop Dt\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\", {\"F/S ID\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "F/S (Spouse)_Unique",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "F/S ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25812d5e-6137-45bb-9862-97a258e4e8c1",
            "sourceColumn": "F/S ID",
            "summarizeBy": "none"
          },
          {
            "name": "Fac-Staff Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fec6125a-dcbb-4c44-b24c-ee12f5244f39",
            "sourceColumn": "Fac-Staff Name",
            "summarizeBy": "none"
          },
          {
            "name": "Inst Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4beb4c3-0cb0-49b8-9cca-5a1e9a45db42",
            "sourceColumn": "Inst Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "Record Types",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be979429-b722-42e5-a4b0-acc4d6ec254d",
            "sourceColumn": "Record Types",
            "summarizeBy": "none"
          },
          {
            "name": "Job Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6347e5f-51f9-4d1e-a7de-9ae5c1128c84",
            "sourceColumn": "Job Title",
            "summarizeBy": "none"
          },
          {
            "name": "School/College/Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4b0e6f7-7a89-4a8d-b331-33c54a790ddb",
            "sourceColumn": "School/College/Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3a84f42-0be0-4025-95c3-4d71003da4c6",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Pos Lvl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85f916cf-94ea-426f-85b9-2a7b2bc21bb9",
            "sourceColumn": "Pos Lvl",
            "summarizeBy": "none"
          },
          {
            "name": "Start Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "27a70250-fb18-4e8f-bf16-6610ad9050c7",
            "sourceColumn": "Start Dt",
            "summarizeBy": "none"
          },
          {
            "name": "Stop Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af0cbf00-b32f-47a2-a830-4d77f24abeca",
            "sourceColumn": "Stop Dt",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ff44c3d9-e34c-42dd-a3b6-9d788032cdd5",
        "partitions": [
          {
            "name": "F/S (Spouse)_Unique",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Fac-Staff (Spouse)\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"F/S ID\", \"Fac-Staff Name\", \"Inst Suffix\", \"Record Types\", \"Job Title\", \"School/College/Unit\", \"Department\", \"Pos Lvl\", \"Start Dt\", \"Stop Dt\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\", {\"F/S ID\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}